### PR TITLE
[spirv] Error out if SV_InnerCoverage is not uint.

### LINKED ISSUE #2954: Silent crash or validation error when SV_InnerCoverage semantic is assigned to a float parameter instead of uint
### Title
Silent crash or validation error (DXIL and SPIR-V backends respectively) when SV_InnerCoverage semantic is assigned to a float parameter instead of uint

### Functional impact
Compiler crashes, no result gets printed to stdout for the DXIL backend. SPIR-V backend prints validation error and asks to report a bug.

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746311/repro_shader.txt) with `dxc.exe -E frag -T ps_6_1 repro_shader.txt`
```
float4 frag (uint viewID : SV_ViewID, float innerCoverage : SV_InnerCoverage) : SV_Target
{
  return float4(1, float(viewID), innerCoverage, 0);
}
```

### Expected result
The compiler prints out an informative error message.

### Actual result
Compiler crashes, no result gets printed to stdout for the DXIL backend.

### Further technical details
Running the snippet through the SPIR-V backend with `dxc.exe -E frag -T ps_6_1 repro_shader.txt -spirv` produces the following validation error:
`fatal error: generated SPIR-V is invalid: Expected Constituents to be scalars or vectors of the same type as Result Type components                                                %23 = OpCompositeConstruct %v4float %float_1 %22 %21 %float_0                                                                                                                                                                                                                                                                                                   note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible`
DXC bult from changeset 5ebc67c618d7061407cca039573108078f601ee6.

### PR DESCRIPTION
**Pull request by ehsannas**
Fixes #2954

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -2041,6 +2041,10 @@ bool DeclResultIdMapper::createStageVars(
                                                  clang::ArrayType::Normal, 0);
       break;
     case hlsl::Semantic::Kind::InnerCoverage:
+      if (!type->isSpecificBuiltinType(BuiltinType::UInt)) {
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2044]: I am curious why this is not reported by the front-end parser. Anyway, it looks good to me.

Comment (ehsannas) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2044]: You're right. Unfortunately this is also an issue when compiling to DXIL. So it's in fact better if the frontend performs the check. I'll merge this PR, and I'll check if I can modify the frontend in a separate PR. Thanks
