### PR TITLE
[spirv] Fix read/write to base struct member from derived struct

### LINKED ISSUE #3213: [SPIR-V] Reading or writing a struct's member from a derived struct's method causes SPIR-V codegen errors
### Title
 Reading or writing a struct's member from a derived struct's method causes SPIR-V codegen errors which ask to report a bug

### Functional impact
Compilation fails with the SPIR-V backend. Does not fail with the DXIL backend or FXC.

### Minimal repro steps

1.1. Compile [read_issue.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5414931/read_issue.txt)  (seen below) with `dxc.exe -T ps_6_0 -E PSMain -spirv read_issue.txt`:
```
struct A {
  float4 base;
};

struct B : A {
  float4 derived;
  float4 GetBase() {return base;}
  float4 GetDerived() {return derived;}
};

#define REPRODUCE_ISSUE 1

float4 PSMain() : SV_Target {
  B b;
  b.base = float4(1, 1, 0, 1);
  b.derived = float4(1, 0, 1, 1);
    
#if REPRODUCE_ISSUE
  return b.GetBase();
#else
  return b.GetDerived();
#endif
}
```
1.2. Observe compiler output:
```
fatal error: generated SPIR-V is invalid: Expected number of constituents to be at least 2
  %12 = OpCompositeConstruct %v4float %7

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```
2.1.  Compile [write_issue.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5414929/write_issue.txt)  (seen below) with `dxc.exe -T ps_6_0 -E PSMain -spirv write_issue.txt`:
```
struct A {
  float4 base;
};

struct B : A {
  float4 derived;
  void SetBase(float4 v) { base = v;}
  void SetDerived(float4 v) { derived = v; }
};

#define REPRODUCE_ISSUE 1

float4 PSMain() : SV_Target {
  B b;
    
#if REPRODUCE_ISSUE
  b.SetBase(float4(1, 0, 1, 1));    
  return b.base;
#else
  b.SetDerived(float4(1, 0, 1, 1));    
  return b.derived;
#endif
}

```
2.2. Observe compiler output:
```
fatal error: generated SPIR-V is invalid: Type Id 4 is not a scalar numeric type
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Expected result
Compilation succeeds when a base struct's member is read or written from a derived struct's method

### Actual result
The generated SPIR-V generates validation errors. Compilation fails and messages asking to report a bug are printed.

### Further technical details
The [read](http://shader-playground.timjones.io/0f04d9b0ca49abf96ffbd0989fdd9e89) and [write](http://shader-playground.timjones.io/391b05af7ecbb1429f826e1110c1f4f2) shaders on shader-playground for convenience.

### PR DESCRIPTION
**Pull request by ehsannas**
Fixes #3213

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -341,6 +341,34 @@ void getBaseClassIndices(const CastExpr *expr,
...
+  // In this example, the 'this' pointer (pointing to Derived) is used inside
+  // 'getBaseValue', which is then cast to a Base pointer:
+  //
+  // ImplicitCastExpr 'Base *' <UncheckedDerivedToBase (Base)>
+  // `-CXXThisExpr 'Derviced *' this
+  //
+  // Therefore in order to obtain the derivedDecl below, we must make sure that
+  // we handle the second case too by using the pointee type.
+  if (derivedType->isPointerType())
+    derivedType = derivedType->getPointeeType();
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:370]: Does this code work for the recursive case?
For example,
```
class grandparent { float value; };
class parent : grandparent {};
class child : parent { float4 getBaseValue() { return value; } };
```

Based the following HLSL code examples (the unit tests you added), I think this PR correctly handles the recursive cases but I just thought we might need a loop (instead of if-statement)?
Probably my intuition is wrong ..

**Review by jaebaek — APPROVED** [review]
LGTM with a nit

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 1 above)
Comment (ehsannas) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:370]: Your intuition is correct. This the initialization for the loop. The loop is below on line 376 and 382.
