### PR TITLE
Fix crash when using precise matrix with -Od

### LINKED ISSUE #2189: Test crash with Od
The test `test\CodeGenHLSL\batch\declarations\precise\matrix.hlsl` crashes the compiler when adding `/Od` flag:
```
// RUN: %dxc -E main -T vs_6_0 %s | FileCheck %s | XFail GitHub #2080

// Test that precise modifier on a matrix has an effect.

// CHECK-NOT: fmul fast float
// CHECK: fmul float
// CHECK-NOT: fmul fast float
// CHECK: fmul float
// CHECK-NOT: fmul fast float
// CHECK: fmul float
// CHECK-NOT: fmul fast float
// CHECK: fmul float
// CHECK-NOT: fmul fast float

float2x2 main(float2x2 m : IN) : OUT
{
  precise float2x2 result = m * m;
  return result;
}```

### PR DESCRIPTION
**Pull request by pow2clk**
To flag a variable as precise, a dx.attribute.precise call is inserted.
In the case of matrices, this becomes a problem if it persists too long
due to validation errors because the matrix is never lowered. When we
reach the HLMatrixLowerPass, the matrix can be lowered to vector. This
change detects when the precise call is applied to a matrix, lowers the
parameters and replaces the call with one taking a vector instead.
The call is necessary to keep the precise informaton across function
calls.

Adds variante of precise tests. precise/matrix.hlsl is modified by
matrix_od.hlsl to take the -Od parameter.
precise/propagate_to_producers_interproc.hlsl is modified to use
matrices since an earlier fix for this bug caused a regression when this
alteration was made.

Fixes #2189

### CODE REVIEW

File: lib/HLSL/HLMatrixLowerPass.cpp [hunk 1]
```diff
@@ -683,6 +684,19 @@ Value *HLMatrixLowerPass::lowerCall(CallInst *Call) {
...
 }
 
+// Special function to lower precise call applied to a matrix
+// The matrix should be lowered and the call regenerated with vector arg
+void HLMatrixLowerPass::lowerPreciseCall(CallInst *Call, IRBuilder<> Builder) {
+  DXASSERT(Call->getNumArgOperands() == 1, "Only one arg expected for precise matrix call");
+  Value *Arg = Call->getArgOperand(0);
+  Value *LoweredArg = getLoweredByValOperand(Arg, Builder);
+  for (Value *A : Call->arg_operands()) {
+    DXASSERT(A == Arg, "oops");
```
Comment (tex3d) [inline lib/HLSL/HLMatrixLowerPass.cpp]: How is this necessary?  There's already:
```
DXASSERT(Call->getNumArgOperands() == 1, ...
```
and
```
Value *Arg = Call->getArgOperand(0);
```
So how could A be different unless there's a fundamental problem with operand iteration or something?

Comment (pow2clk) [reply lib/HLSL/HLMatrixLowerPass.cpp]: Debug code I meant to remove. Hang on a sec.

File: include/dxc/HLSL/HLModule.h [hunk 2]
```diff
@@ -211,6 +211,9 @@ class HLModule {
   static bool HasPreciseAttributeWithMetadata(llvm::Instruction *I);
   static void MarkPreciseAttributeWithMetadata(llvm::Instruction *I);
   static void ClearPreciseAttributeWithMetadata(llvm::Instruction *I);
+  template<class BuilderTy>
+  static void MarkPreciseAttributeOnValWithFunctionCall(llvm::Value *V,
+							BuilderTy &Builder, llvm::Module &M);
```
Comment (tex3d) [inline include/dxc/HLSL/HLModule.h]: Tabs here.  Make sure your settings are to insert 2-space indents.

Comment (pow2clk) [reply include/dxc/HLSL/HLModule.h]: done!
