### PR TITLE
Fix matrix support in GS OutputStream

### LINKED ISSUE #1757: Crash when compiling geometry shader and using matrix type
Compiling the following geometry shader into DXIL using the following command ` dxc -Tgs_6_0 -E Main test.gs` causes a crash.

```hlsl
struct GSInOut {
    float4x4 Matrix : TEXCOORD0;
};

[maxvertexcount(3)]
void Main( triangle GSInOut In[3], inout TriangleStream<GSInOut> Output )
{
    GSInOut Out;
    for (uint i = 0; i < 3; ++i) {
		Out.Matrix			= In[i].Matrix;
		Output.Append(Out);
	}
}
```

Interestingly enough this compiles fine when targeting SPIR-V instead ` dxc -spirv -Tgs_6_0 -E Main test.gs`

### PR DESCRIPTION
**Pull request by MrTrillian**
A couple things were missing here:
- `SROA_Parameter` did not properly handle `DxilFieldAttribute`s when generating the flattened `OutputStream.Append` call, this would cause at least an assert to be hit.
- `SROA_Parameter` did not expect outputstream-qualified matrices and would replace all uses of such matrices with a local variable, with the result that we would never actually write to the outputstream value.
- `HLMatrixLowerPass` did not support lowering `OutputStream.Append(matrix)`

Also adds a test and includes a few cleanups.

Fixes #1757

### CODE REVIEW

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 1]
```diff
@@ -5956,13 +5961,11 @@ static void LegalizeDxilInputOutputs(Function *F,
       }
     } else if (qual == DxilParamInputQual::Inout) {
       // Only replace inout when (bLoad && bStore) == false.
-      bNeedTemp = true;
       bLoadOutputFromTemp = true;
       bStoreInputToTemp = true;
     }
 
     if (HLMatrixLower::IsMatrixType(Ty)) {
-      bNeedTemp = true;
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: The bug was this when `qual == DxilParamInputQual::OutStream`. I removed the variable since it is redundant with the other two.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 2]
```diff
@@ -6344,6 +6347,8 @@ void SROA_Parameter_HLSL::createFlattenedFunction(Function *F) {
       }
 
       flatArg->replaceAllUsesWith(Arg);
+      if (isa<Instruction>(flatArg))
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: This does not fix any bug, but there's no need to keep those temp alloca's around once replaced with the new function's argument. They probably got eliminated by dead code removal later on.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 3]
```diff
@@ -2365,44 +2365,55 @@ static void SplitCpy(Type *Ty, Value *Dest, Value *Src,
...
+// Given a pointer to a value, produces a list of pointers to
+// all scalar elements of that value and their field annotations, at any nesting level.
+static void SplitPtr(Value *Ptr, // The root value pointer
+  SmallVectorImpl<Value *> &IdxList, // GEP indices stack during recursion
+  Type *Ty, // Type at the current GEP indirection level
+  const DxilFieldAnnotation &Annotation, // Annotation at the current GEP indirection level
+  SmallVectorImpl<Value *> &EltPtrList, // Accumulates pointers to each element found
+  SmallVectorImpl<const DxilFieldAnnotation*> &EltAnnotationList, // Accumulates field annotations for each element found
+  DxilTypeSystem &TypeSys,
+  IRBuilder<> &Builder) {
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: I changed the style of this function to early return, since multiple branches ended up doing what is now at the end: appending the current element's pointer to the list.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 4]
```diff
@@ -2414,19 +2425,16 @@ static void SplitPtr(Type *Ty, Value *Ptr, SmallVector<Value *, 16> &idxList,
...
 
-    if (!ElTy->isStructTy() ||
-        HLMatrixLower::IsMatrixType(ElTy)) {
-      // Not split array of basic type.
-      Value *GEP = Builder.CreateInBoundsGEP(Ptr, idxList);
-      EltPtrList.emplace_back(GEP);
-    }
-    else {
+    if (ElTy->isStructTy() && !HLMatrixLower::IsMatrixType(ElTy)) {
       DXASSERT(0, "Not support array of struct when split pointers.");
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: I filed #1768 for this assert.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 5]
```diff
@@ -2293,31 +2293,31 @@ static void SplitCpy(Type *Ty, Value *Dest, Value *Src,
...
-          Builder, HLOpcodeGroup::HLMatLoadStore,
-          static_cast<unsigned>(HLMatLoadStoreOpcode::ColMatLoad), Ty, {SrcGEP},
-          *M);
 
-      // Generate Matrix Store.
-      HLModule::EmitHLOperationCall(
-          Builder, HLOpcodeGroup::HLMatLoadStore,
-          static_cast<unsigned>(HLMatLoadStoreOpcode::ColMatStore), Ty,
-          {DestGEP, Load}, *M);
+    Value *DestMatPtr;
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: This is not to fix any bug, but the code was generating useless GEP(ptr, {0}). I also consolidated the row-major vs column-major logic a bit.

File: tools/clang/test/CodeGenHLSL/quick-test/streamout_matrix_all_orientations.hlsl [hunk 6]
```diff
@@ -0,0 +1,45 @@
+// RUN: %dxc -E main -T gs_6_0 %s | FileCheck %s
+
+// CHECK: call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 0)
```
Comment (MrTrillian) [inline tools/clang/test/CodeGenHLSL/quick-test/streamout_matrix_all_orientations.hlsl]: Pay attention to the third and fourth args here, this is what shows that we're doing row or column-major loads and stores.
