### PR TITLE
Fix static global resource arrays.

### LINKED ISSUE #2061: Crash on static arrays of resources
Repro:
```
Buffer buf;
static Buffer bufs[1];
void main() { bufs[0] = buf; }
```
It looks like SROA for globals doesn't handle this case.

### PR DESCRIPTION
**Pull request by tex3d**
Fixes #2061 

Additional work needed to support unroll case since GEP not known to be constant there.  Either need simplification between unroll and DxilPromoteStaticResources (no good for /Od case though), or DxilValueCache access in LoadAndStorePromoter.  But not sure LoadAndStorePromoter should be used on static global uses in the first place.  Perhaps an another solution is needed.

### CODE REVIEW

File: lib/HLSL/DxilPromoteResourcePasses.cpp [hunk 1]
```diff
@@ -184,11 +185,18 @@ bool DxilPromoteStaticResources::PromoteStaticGlobalResources(
       GlobalVariable *GV = *(it++);
       // Build list of instructions to promote.
       for (User *U : GV->users()) {
-        Instruction *I = cast<Instruction>(U);
-        Insts.emplace_back(I);
+        if (isa<LoadInst>(U) || isa<StoreInst>(U)) {
+          Insts.emplace_back(cast<Instruction>(U));
+        } else if (GEPOperator *GEP = dyn_cast<GEPOperator>(U)) {
+          for (User *gepU : GEP->users()) {
+            DXASSERT_NOMSG(isa<LoadInst>(gepU) || isa<StoreInst>(gepU));
```
Comment (jpporto) [inline lib/HLSL/DxilPromoteResourcePasses.cpp]: this will silently be ignored in a NoAsserts build. Will breaking this assumption cause any other failures? If so, compiler users may se a runtime crash without any actionable error messages...

Comment (tex3d) [reply lib/HLSL/DxilPromoteResourcePasses.cpp]: Do you think it's better if we don't add it, so promotion fails with:
`error: local resource not guaranteed to map to unique global resource.`
It's difficult to think of an actionable error message if this assumption fails.

At least this will crash in fewer cases now than it did before.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 2]
```diff
@@ -6245,13 +6246,19 @@ class LowerStaticGlobalIntoAlloca : public ModulePass {
...
+      // only for non-constant static globals
+      if (!dxilutil::IsStaticGlobal(&GV) || GV.isConstant())
+        continue;
+      Type *EltTy = GV.getType()->getElementType();
+      if (!EltTy->isAggregateType()) {
         staticGVs.emplace_back(&GV);
+      } else {
+        // Lower static [array of] resources
+        while (EltTy->isArrayTy())
+          EltTy = EltTy->getArrayElementType();
```
Comment (python3kgae) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: dxilutil::GetArrayEltTy?
