### PR TITLE
Fix vec1/mat1x1 to aggregate type splats and a crash

### LINKED ISSUE #1863: DXC does not allow explicit splatting casts from vector/matrices to arrays/structs
Repro:
```
typedef int A[2];
struct S { int f0, f1; };
void main()
{
    (A)int1(1);
    (A)int1x1(1);
    (S)int1(1);
    (S)int1x1(1);
}
```

DXC output:
```
E:\Sandbox\playground.hlsl:5:5: error: cannot convert from 'int1' to 'A' (aka 'int [2]')
    (A)int1(1);
    ^
E:\Sandbox\playground.hlsl:6:5: error: cannot convert from 'int1x1' to 'A' (aka 'int [2]')
    (A)int1x1(1);
    ^
E:\Sandbox\playground.hlsl:7:5: error: cannot convert from 'int1' to 'S'
    (S)int1(1);
    ^
E:\Sandbox\playground.hlsl:8:5: error: cannot convert from 'int1x1' to 'S'
    (S)int1x1(1);
    ^
```

FXC output:
```
vs_5_0
dcl_globalFlags refactoringAllowed
ret
```

It's not visible in this example, but the semantics are that of splatting.

### PR DESCRIPTION
**Pull request by MrTrillian**
FXC treats scalars, vector1s and matrix1x1s the same, at least as far as conversions go. We allowed splats from scalars to aggregates, but not from vector1s or matrix1x1s.

Also fixes a bug where we would crash on conversions to aggregates where the result was ignored, because clang wouldn't allocate an `AggValueSlot` and we didn't handle the destination pointer being `nullptr`.

Fixes #1863 and #1978

### CODE REVIEW

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -8149,22 +8143,29 @@ bool HLSLExternalSource::CanConvert(
...
+        sourceSingleElementBuiltinType = hlsl::GetElementTypeOrType(source)->getAs<BuiltinType>();
+      }
+
+      if (sourceSingleElementBuiltinType != nullptr) {
+        BuiltinType::Kind kind = sourceSingleElementBuiltinType->getKind();
+        switch (kind) {
+        case BuiltinType::Kind::UInt:
+        case BuiltinType::Kind::Int:
+        case BuiltinType::Kind::Float:
+        case BuiltinType::Kind::LitFloat:
```
Comment (MrTrillian) [inline tools/clang/lib/Sema/SemaHLSL.cpp]: Note that this means that 16 or 64-bit types cannot be splat sources, which may be a bit inconsistent?

Comment (MrTrillian) [reply tools/clang/lib/Sema/SemaHLSL.cpp]: Filed #2047
