### PR TITLE
[spirv] handle sizeof using Clang's const folding

### LINKED ISSUE #3198: [SPIR-V] sizeof() gets wrong value when used in a non-entry function
The shader:
```
struct StructA
{
    float3 one;
    float3 two;
};

uint foo()
{
    return sizeof(StructA);
}

[numthreads(64, 1, 1)]
void main()
{
    uint a = foo();
    uint b = sizeof(StructA);
}
```

Using command: `dxc -spirv -E main -T cs_6_0 shader.hlsl -fcgl`

The result is:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 18
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 64 1 1
               OpSource HLSL 600
               OpName %main "main"
               OpName %src_main "src.main"
               OpName %bb_entry "bb.entry"
               OpName %a "a"
               OpName %b "b"
               OpName %foo "foo"
               OpName %bb_entry_0 "bb.entry"
       %uint = OpTypeInt 32 0
    %uint_24 = OpConstant %uint 24
    %uint_32 = OpConstant %uint 32
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
%_ptr_Function_uint = OpTypePointer Function %uint
         %16 = OpTypeFunction %uint
       %main = OpFunction %void None %6
          %7 = OpLabel
          %8 = OpFunctionCall %void %src_main
               OpReturn
               OpFunctionEnd
   %src_main = OpFunction %void None %6
   %bb_entry = OpLabel
          %a = OpVariable %_ptr_Function_uint Function
          %b = OpVariable %_ptr_Function_uint Function
         %14 = OpFunctionCall %uint %foo
               OpStore %a %14
               OpStore %b %uint_24
               OpReturn
               OpFunctionEnd
        %foo = OpFunction %uint None %16
 %bb_entry_0 = OpLabel
               OpReturnValue %uint_32
               OpFunctionEnd
```

You can see that in `main()`, `sizeof(StructA)` calculates to 24, but in `foo()`, it is 32.

### PR DESCRIPTION
**Pull request by jaebaek**
```
struct StructA
{
  float3 one;
  float3 two;
};
```

`sizeof(StructA)` must be 24 bytes. `AlignmentSizeCalculator` with a void
memory layout will return 32 bytes for it. We have to use the constant
folding provided by Clang.

Fixes #3198

### CODE REVIEW

**Comment by jaebaek** [comment]
@LLJJDD PTAL!

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -11984,6 +11984,11 @@ SpirvEmitter::doUnaryExprOrTypeTraitExpr(const UnaryExprOrTypeTraitExpr *expr) {
...
   }
 
+  if (auto *constExpr = tryToEvaluateAsConst(expr)) {
+    constExpr->setRValue();
+    return constExpr;
+  }
+
   AlignmentSizeCalculator alignmentCalc(astContext, spirvOptions);
   uint32_t size = 0, stride = 0;
   std::tie(std::ignore, size) = alignmentCalc.getAlignmentAndSize(
```
Comment (LLJJDD) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:11994]: @jaebaek Thanks for fixing my issue!

Just one more question: Can we just call `AlignmentSizeCalculator` with a `scalar` memory layout instead of `void` here?

Comment (ehsannas) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:11994]: yeah I think that's the more proper fix. Scalar memory layout allows non-scalar types to be aligned solely based on the size of their components (like C). Reference: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_scalar_block_layout.html#_description

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:11994]: Good question. I think the `AlignmentSizeCalculator` with a `scalar` memory layout would also work.

In the example code,

```
struct StructA
{
    float3 one;
    float3 two;
};

uint foo()
{
    return sizeof(StructA);   // First case
}

[numthreads(64, 1, 1)]
void main()
{
    uint a = foo();
    uint b = sizeof(StructA);   // Second case
}
```

I just wanted to make the same result for `First case` and `Second case`.

[This code](https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L1395) is for the `Second case` and I wanted to reuse it.

In my opinion, even though both `tryToEvaluateAsConst()` and `AlignmentSizeCalculator` with a `scalar` memory layout will work, `tryToEvaluateAsConst()` would be a better option for this case.
We want to use what DXIL backend uses (as I mentioned `sizeof(some type)` does not rely on the Vulkan spec and we should mimic what the DXIL backend does) and `tryToEvaluateAsConst()` is what DXIL backend uses.

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:11994]: Oh sorry. I misunderstood. Yeah, I agree that we have to change `void` to `scalar` memory layout in the line 11995 in addition to this change.

**Review by ehsannas — APPROVED** [review]
