### PR TITLE
[DXIL generation] Merge GepUse last to avoid crash in EmitGetNodeRecordPtrAndUpdateUsers

### LINKED ISSUE #6223: DXC crashes when reading arrays inside work graph record
**Description**
If a work graph record contains an array (e.g. `float2 data[8]`) and thread accesses the array using a local variable (e.g. thread id or counter in a for loop) then DXC crashes with an internal exception.

**Steps to Reproduce**
Minimal example with thread id:
[https://godbolt.org/z/bMo7Mobvd](https://godbolt.org/z/bMo7Mobvd)
Minimal example with for-loop:
[https://godbolt.org/z/3jojY6o64](https://godbolt.org/z/3jojY6o64)

**Actual Behavior**
`dxcompiler.dll` crashes with `Access violation reading location 0x0000000000000048`
Call stack:
```
dxcompiler.dll!llvm::iplist<llvm::Instruction,llvm::ilist_traits<llvm::Instruction>>::remove(llvm::ilist_iterator<llvm::Instruction> &)	
dxcompiler.dll!llvm::iplist<llvm::Instruction,llvm::ilist_traits<llvm::Instruction>>::erase(llvm::ilist_iterator<llvm::Instruction>)	
dxcompiler.dll!llvm::Instruction::eraseFromParent()	
dxcompiler.dll!`anonymous namespace'::TryMegeWithNestedGEP(llvm::GEPOperator * GEP)	
dxcompiler.dll!hlsl::dxilutil::MergeGepUse(llvm::Value * V)	
dxcompiler.dll!hlsl::ReplaceUsesForLoweredUDT(llvm::Value * V, llvm::Value * NewV)	
dxcompiler.dll!hlsl::ReplaceUsesForLoweredUDT(llvm::Value * V, llvm::Value * NewV)	
dxcompiler.dll!hlsl::EmitGetNodeRecordPtrAndUpdateUsers(HLOperationLowerHelper & helper, llvm::CallInst * CI, llvm::Value * ArrayIndex)	
dxcompiler.dll!hlsl::LowerRecordAccessToGetNodeRecordPtr(hlsl::HLModule & HLM)	
dxcompiler.dll!`anonymous namespace'::DxilGenerationPass::runOnModule(llvm::Module & M)	
dxcompiler.dll!`anonymous namespace'::MPPassManager::runOnModule(llvm::Module & M)	
dxcompiler.dll!llvm::legacy::PassManagerImpl::run(llvm::Module &)	
dxcompiler.dll!llvm::legacy::PassManager::run(llvm::Module & M)	
dxcompiler.dll!`anonymous namespace'::EmitAssemblyHelper::EmitAssembly(clang::BackendAction Action, llvm::raw_pwrite_stream * OS)	
dxcompiler.dll!clang::EmitBackendOutput(clang::DiagnosticsEngine & Diags, const clang::CodeGenOptions & CGOpts, const clang::TargetOptions & TOpts, const clang::LangOptions & LOpts, llvm::StringRef TDesc, llvm::Module * M, clang::BackendAction Action, llvm::raw_pwrite_stream * OS)	
dxcompiler.dll!clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext & C)	
dxcompiler.dll!clang::ParseAST(clang::Sema & S, bool PrintStats, bool SkipFunctionBodies)	
dxcompiler.dll!clang::ASTFrontendAction::ExecuteAction()	
dxcompiler.dll!clang::CodeGenAction::ExecuteAction()	
dxcompiler.dll!clang::FrontendAction::Execute()	
```

**Environment**
- DXC version `1.7.2308.417`
- Host Operating System: Windows 11

### PR DESCRIPTION
**Pull request by python3kgae**
In EmitGetNodeRecordPtrAndUpdateUsers, the type will be mutated. And the GEP user of the RecordPtr will be merged at same time. This make things complex because the GEP index need to be updated since type is mutated.

To make things easier, merge the GepUse after mutate type.

Fixes #6223

### CODE REVIEW

**Review by tex3d — COMMENTED** [review]
This looks good, but I also think the call to `MergeGepUse` inside of `ReplaceUsesForLoweredUDT` should be removed if possible.  If not it should be called on `NewV` instead of `NewGEP`.  Otherwise, I fear this change might hide a still possible subtle bug there.

See my comment on this issue [here](https://github.com/microsoft/DirectXShaderCompiler/issues/6038#issuecomment-1947580888).

File: lib/HLSL/HLLowerUDT.cpp [hunk 1]
```diff
@@ -179,6 +179,9 @@ hlsl::TranslateInitForLoweredUDT(Constant *Init, Type *NewTy,
 }
 
 void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
+  // Merge GepUse first to avoid mutate type and merge gep use at same time.
+  dxilutil::MergeGepUse(V);
```
Comment (tex3d) [inline lib/HLSL/HLLowerUDT.cpp:183]: I don't think it's ok to add this here.  This function is recursed into, and `V` may be referenced after the call, but MergeGepUse might replace `V` if it's a GEP when merging into another GEP.

File: lib/HLSL/HLLowerUDT.cpp [hunk 2]
```diff
@@ -255,7 +255,7 @@ void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
       IRBuilder<> Builder(GEP);
       SmallVector<Value *, 4> idxList(GEP->idx_begin(), GEP->idx_end());
       Value *NewGEP = Builder.CreateGEP(NewV, idxList);
-      ReplaceUsesForLoweredUDT(GEP, NewGEP);
+      ReplaceUsesForLoweredUDTImpl(GEP, NewGEP);
       dxilutil::MergeGepUse(NewGEP);
```
Comment (tex3d) [inline lib/HLSL/HLLowerUDT.cpp:259]:
```suggestion
```

I think we need to get rid of this call if we can.  If it's required for some reason, it would be interesting to understand why.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl [hunk 3]
```diff
@@ -14,9 +14,9 @@
 // CHECK-DAG: [[ORH:%[0-9]+]] = call %dx.types.NodeRecordHandle @dx.op.allocateNodeOutputRecords(i32 238, %dx.types.NodeHandle [[ANOH]], i32 1, i1 false)
 // CHECK-DAG: [[AORH:%[0-9]+]] = call %dx.types.NodeRecordHandle @dx.op.annotateNodeRecordHandle(i32 251, %dx.types.NodeRecordHandle [[ORH]], %dx.types.NodeRecordInfo { i32 70, i32 32768 })
 // CHECK-DAG: [[IRP:%[0-9]+]] = call %[[RECORD:struct\.MyRecord[^ ]*]] addrspace(6)* @dx.op.getNodeRecordPtr.[[RECORD]](i32 239, %dx.types.NodeRecordHandle [[AIRH]], i32 0)
-// CHECK-DAG: getelementptr {{(inbounds )?}}%[[RECORD]], %[[RECORD]] addrspace(6)* [[IRP]], i32 0, i32 0, i32 [[TID]], i32 0
+// CHECK-DAG: getelementptr {{(inbounds )?}}%[[RECORD]], %[[RECORD]] addrspace(6)* [[IRP]], i32 0, i32 0, i32 [[TID]]
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl:17]: Looks like this might have become a multi-level GEP?  I think this test change might violate the purpose of this test.
```
// Ensure multi-dim array produced by lowering record struct with array of
// vector has GEP instructions merged to prevent invalid GEP with array type.
```

We might have to do `MergeGepUse` after the call to `ReplaceUsesForLoweredUDTImpl` in `ReplaceUsesForLoweredUDT`.

Comment (python3kgae) [reply tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl]: Updated.

File: lib/HLSL/HLLowerUDT.cpp [hunk 4]
```diff
@@ -475,3 +474,13 @@ void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
       CV->removeDeadConstantUsers();
   }
 }
+
+void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
+  // Merge GepUse first to avoid mutate type and merge gep use at same time.
+  dxilutil::MergeGepUse(V);
+
```
Comment (tex3d) [inline lib/HLSL/HLLowerUDT.cpp:481]: This now appears unnecessary, and we don't need the `inbounds` changes anymore.
```suggestion
```

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/called_function_arg_record_object.hlsl [hunk 5]
```diff
@@ -13,7 +13,7 @@ void loadStressWorker(
     inout DispatchNodeInputRecord<loadStressRecord> inputData,
     GroupNodeOutputRecords<loadStressRecord> outRec)
 {
-    // CHECK: getelementptr inbounds %struct.loadStressRecord.0, %struct.loadStressRecord.0
+    // CHECK: getelementptr %struct.loadStressRecord.0, %struct.loadStressRecord.0
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/called_function_arg_record_object.hlsl:16]: Pretty sure this change is unnecessary if you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters.hlsl [hunk 6]
```diff
@@ -20,25 +20,25 @@
 
 
 // CHECK:  %[[node_ptr:.+]] = call %struct.RECORD.0 addrspace(6)* @dx.op.getNodeRecordPtr.struct.RECORD.0(i32 239, %dx.types.NodeRecordHandle %[[annotHdl]], i32 0)  ; GetNodeRecordPtr(recordhandle,arrayIndex)
-// CHECK:  %[[ptr:.+]] = getelementptr inbounds %struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 0, i32 0
+// CHECK:  %[[ptr:.+]] = getelementptr {{(inbounds )?}}%struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 0, i32 0
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters.hlsl:23]: Pretty sure changes in this file are unnecessary if you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters_01.hlsl [hunk 7]
```diff
@@ -20,25 +20,25 @@
 
 
 // CHECK:  %[[node_ptr:.+]] = call %struct.RECORD.0 addrspace(6)* @dx.op.getNodeRecordPtr.struct.RECORD.0(i32 239, %dx.types.NodeRecordHandle %[[annotHdl]], i32 0)  ; GetNodeRecordPtr(recordhandle,arrayIndex)
-// CHECK:  %[[ptr:.+]] = getelementptr inbounds %struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 0, i32 0
+// CHECK:  %[[ptr:.+]] = getelementptr {{(inbounds )?}}%struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 0, i32 0
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters_01.hlsl:23]: Pretty sure changes in this file are unnecessary if you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters_02.hlsl [hunk 8]
```diff
@@ -18,11 +18,11 @@
 
 // CHECK:  %[[ptr:.+]] = getelementptr %struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 0
 // CHECK:  store i32 0, i32 addrspace(6)* %[[ptr]], align 4
-// CHECK:  %[[ptr:.+]] = getelementptr inbounds %struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 1, i32 0
+// CHECK:  %[[ptr:.+]] = getelementptr {{(inbounds )?}}%struct.RECORD.0, %struct.RECORD.0 addrspace(6)* %[[node_ptr]], i32 0, i32 1, i32 0
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/common_input_parameters_02.hlsl:21]: Pretty sure changes in this file are unnecessary if you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl [hunk 9]
```diff
@@ -14,9 +14,9 @@
 // CHECK-DAG: [[ORH:%[0-9]+]] = call %dx.types.NodeRecordHandle @dx.op.allocateNodeOutputRecords(i32 238, %dx.types.NodeHandle [[ANOH]], i32 1, i1 false)
 // CHECK-DAG: [[AORH:%[0-9]+]] = call %dx.types.NodeRecordHandle @dx.op.annotateNodeRecordHandle(i32 251, %dx.types.NodeRecordHandle [[ORH]], %dx.types.NodeRecordInfo { i32 70, i32 32768 })
 // CHECK-DAG: [[IRP:%[0-9]+]] = call %[[RECORD:struct\.MyRecord[^ ]*]] addrspace(6)* @dx.op.getNodeRecordPtr.[[RECORD]](i32 239, %dx.types.NodeRecordHandle [[AIRH]], i32 0)
-// CHECK-DAG: getelementptr inbounds %[[RECORD]], %[[RECORD]] addrspace(6)* [[IRP]], i32 0, i32 0, i32 [[TID]], i32 0
+// CHECK-DAG: getelementptr {{(inbounds )?}}%[[RECORD]], %[[RECORD]] addrspace(6)* [[IRP]], i32 0, i32 0, i32 [[TID]], i32 0
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl:17]: Pretty sure changes in this file are unnecessary if you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before.

**Review by tex3d — COMMENTED** [review]
If you only do `MergeGepUse` after `ReplaceUsesForLoweredUDTImpl` instead of before, It appears that the test changes are unnecessary.

File: tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl (hunk 9 above)
Comment (python3kgae) [reply tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl:17]: Failed after only do MergeGepUse after ReplaceUsesForLoweredUDTImpl  and revert the change in inbounds.

File: lib/HLSL/HLLowerUDT.cpp [hunk 10]
```diff
@@ -475,3 +474,9 @@ void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
       CV->removeDeadConstantUsers();
   }
 }
+
+void hlsl::ReplaceUsesForLoweredUDT(Value *V, Value *NewV) {
+  ReplaceUsesForLoweredUDTImpl(V, NewV);
+  // Merge GepUse later to avoid mutate type and merge gep use at same time.
+  dxilutil::MergeGepUse(V);
```
Comment (tex3d) [inline lib/HLSL/HLLowerUDT.cpp:481]: This is wrong.  It should be merging `NewV`.
```suggestion
  dxilutil::MergeGepUse(NewV);
```

**Review by tex3d — APPROVED** [review]
LGTM!

**Review by pow2clk — COMMENTED** [review]
I don't think the description is accurate anymore as it is actually merging gepuse as the last thing in EmitGetNOdeRecordPtrAndUpdateUsers.

**Comment by python3kgae** [comment]
> I don't think the description is accurate anymore as it is actually merging gepuse as the last thing in EmitGetNOdeRecordPtrAndUpdateUsers.

Fixed.

**Review by pow2clk — APPROVED** [review]
Thanks for addressing the comment!
