### PR TITLE
[SPIR-V] Fix invalid isnan codegen

### LINKED ISSUE #6712: [SPIR-V] Invalid SPIR-V operand with isnan()
**Description**
DXC generates an invalid SPIR-V

**Steps to Reproduce**

`dxc -T cs_6_0 -spirv path/to/file.hlsl`

HLSL code:

```
RWStructuredBuffer<float> Out;
[numthreads(1, 1, 1)]
void main(uint id : SV_DispatchThreadID)
{
        bool bar = isnan(Out[id]);
        Out[id] = (float)bar;
}
```

If we change the code as follows, the issue is not occurred.

```
        float baz = Out[id];
        Out[id] = (float)isnan(baz);
```

**Actual Behavior**

> fatal error: generated SPIR-V is invalid: Expected bool scalar or vector type as Result Type: IsNan
  %23 = OpIsNan %uint %22
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

**Environment**
- DXC version: libdxcompiler.dylib: 1.8(dev;4640-45018c75)
- Host Operating System: Windows 11 23H2 and macOS 14.5

### PR DESCRIPTION
**Pull request by Keenuts**
IsNan returns a boolean, even is the input-type is a float. This was working in most cases except:
 - if the layout was not Void
 - if the input type was not a matrix

The first bug is because a bool memory layout/representation is not specified, and shall never be exposed to externaly-accessible memory. Hence, if we saw a layout rule != Void, we converted it to a UINT. When calling isnan, the layout rule should not be propagated as we loose any layout info.

The second is because our codegen assumed matrix operations returned a matrix with the same type as the input parameters. In the case of isnan, this was just wrong.

Fixes #6712

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -9042,6 +9056,15 @@ SpirvEmitter::processIntrinsicCallExpr(const CallExpr *callExpr) {
   case hlsl::IntrinsicOp::IOP_firstbitlow: {
     retVal = processIntrinsicFirstbit(callExpr, GLSLstd450::GLSLstd450FindILsb);
     break;
+  }
+  case hlsl::IntrinsicOp::IOP_isnan: {
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:9060]: Should this be done for `isinf` as well?

Comment (s-perron) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9060]: Yes, `isinf` is a problem as well. Please open a new issues for `isinf`, no need to hold up this PR.

https://godbolt.org/z/fKfzaxE6E

**Review by s-perron — APPROVED** [review]
Looks good. We will need to follow up with other similar bugs.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 1 above)
Comment (s-perron) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9060]: I opened the follow up issue. https://github.com/microsoft/DirectXShaderCompiler/issues/6783

Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9060]: Oh right, thanks. Yes we might want to refactorize a bit this, several intrinsics might be impacted.

**Comment by Keenuts** [comment]
@cassiebeckley in case you missed it.

**Review by sudonatalie — APPROVED** [review]
LGTM!
