### PR TITLE
Correctly handle comma operator w/matrices

### LINKED ISSUE #3916: Internal compiler error with DXC version 1.6.2106.3
Hello,
when compiling the attached HLSL shader with **DXC version 1.6.2106.3**, I get an internal compiler error.

```
OVERVIEW: HLSL Compiler for Windows
Version: dxcompiler.dll: 1.6 - 1.6.2106.3 (dad1cfc30); dxil.dll: 1.6(101.6.2106.2)

Command line: dxc.exe -T ps_6_0 bugShader.hlsl.txt
Output:
  Internal Compiler error: Invalid OpCode!
  UNREACHABLE executed at D:\agent\_work\8\s\lib\HLSL\HLOperations.cpp:222!
```

**DXC version 1.6.2104.52** also produces a similar error: `"Internal compiler error: LLVM Unreachable"`
But with **DXC version 1.5.2010.6 (b640fa4ba)**, no error was generated, and a valid binary output was produced.

FYI, the attached HLSL shader is the outcome of `spirv_cross` compilation (SPV -> HLSL), which is working fine on
our huge set of shaders, except for this compiler issue. The shader has been manually edited to reduce its length, to ease debugging.

According to my tests, the issue in `bugShader.hlsl.txt` is related to the `float2x2` variable _13331 at line 357.
For example, removing the "_13331 = _13524;"  copy at line 365 avoids the "internal compiler error".

[bugShader.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/7057058/bugShader.hlsl.txt)

### PR DESCRIPTION
**Pull request by pow2clk**
The special HLSL matrix codegen didn't handle the comma operator. Since
the operation is simple enough, skip special handling and fallback to
the default behavior

Fixed #3916

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGExprScalar.cpp [hunk 1]
```diff
@@ -204,17 +204,16 @@ class ScalarExprEmitter
...
-              llvm::Value *RHS = CGF.EmitScalarExpr(BinOp->getRHS());
-              return CGF.CGM.getHLSLRuntime().EmitHLSLMatrixOperationCall(
-                  CGF, E, ConvertType(E->getType()), { LHS, RHS });
-          }
-          else {
+          if (BinOp->getOpcode() == BO_Assign) {
               LValue LHS = CGF.EmitLValue(BinOp->getLHS());
               llvm::Value *RHS = CGF.EmitScalarExpr(BinOp->getRHS());
               CGF.CGM.getHLSLRuntime().EmitHLSLMatrixStore(CGF, RHS, LHS.getAddress(), BinOp->getLHS()->getType());
               return RHS;
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprScalar.cpp:211]: Moving the handling of the assign operator just made the logic easier to follow since I'm adding another special case depending on the opcode

**Review by tex3d — APPROVED** [review]
LGTM!
