### PR TITLE
[SPIR-V] Fix invalid codegen for empty cbuffers

### LINKED ISSUE #7681: [SPIR-V] Invalid codegen for empty cbuffer resources
When building an empty `cbuffer`, a variable with the `UniformConstant` storage class is created, but no `DescripotorSet` or `Binding` decoration is attached.
This is not legal SPIR-V [VUID 06677](https://registry.khronos.org/vulkan/specs/latest/man/html/StandaloneSpirv.html#VUID-StandaloneSpirv-UniformConstant-06677)

Building with `-O3` removed the unused variable, but building with `-O0` will cause a validation issue.

repro:
```hlsl
// RUN: %dxc -T ps_6_0 -E main -O0 %s -spirv | FileCheck %s

cbuffer empty {
};

float4 main(float2 uv : TEXCOORD) : SV_TARGET {
  return uv.xyxy;
}
```

### PR DESCRIPTION
**Pull request by Keenuts**
Each variable in the Uniform/Uniform Constant storage class must be decorated with DescriptorSet + Binding.
-> VUID-StandaloneSpirv-UniformConstant-06677

When a cbuffer was empty (or only contained resources), an empty struct and variable in the uniform storage class was created. Because the cbuffer was empty, no binding/descriptor set was assigned, hence no decoration was emitted.

This was fine as long as we compiled with optimizations on, as DCE would get rid of this unused cbuffer. But compiling with -O0 would yield a validation error.

Fixes #7681

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -1486,26 +1513,13 @@ SpirvVariable *DeclResultIdMapper::createCTBuffer(const HLSLBufferDecl *decl) {
...
-    registerVariableForDecl(varDecl, createDeclSpirvInfo(bufferVar, index++));
-  }
-  // If it does not contains a member with non-resource type, we do not want to
-  // set a dedicated binding number.
-  if (index != 0) {
-    resourceVars.emplace_back(
-        bufferVar, decl, decl->getLocation(), getResourceBinding(decl),
-        decl->getAttr<VKBindingAttr>(), decl->getAttr<VKCounterBindingAttr>());
-  }
+  resourceVars.emplace_back(
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1513]: Having two different variables `resourceVars` and `ResourceVars` is confusing. Can you rename one to something else?

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 2]
```diff
@@ -1474,6 +1474,33 @@ void DeclResultIdMapper::createEnumConstant(const EnumConstantDecl *decl) {
...
+
+    VariablesToDeclare.push_back(varDecl);
+  }
+
+  // If the cbuffer is empty or only contains resources, skip the variable
+  // creation.
+  if (VariablesToDeclare.size() == 0) {
+    // But don't forget to lower the contained resources, if any.
+    for (const VarDecl *VD : ResourceVars)
+      createExternVar(VD);
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: Why do we not have to do this if the buffer is not otherwise empty? This could get confusing if we now have two different places where we create the external variables for the resources in cbuffers.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 1 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1513]: Ah missed the other one, will change the names.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 2 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: Alternative is I could lift the existing `createExternVar` from the other function, it will slightly change the order of resources in the SPIR-V module, but shouldn't be much of an issue.

Comment (s-perron) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: Let's try to bring the together somehow. Thanks.

**Comment by Keenuts** [comment]
The 2 failures in the CI are due to apt-get failing to get some dependencies. Not related to this PR.

**Review by s-perron — APPROVED** [review]
