### PR TITLE
[SPIR-V] Allow literal selectors in switch stmts

### LINKED ISSUE #4338: [SPIR-V] Error with switch statement with constant input
If I try to create a switch statement with a literal value as the input, I get an error like the following when compiling with spirv:
```
file.hlsl:5:7: error: non-32bit integer case value in switch statement unimplemented
        case 0:
             ^
```

This link should reproduce the issue: https://shader-playground.timjones.io/6fd31f9898afb861d22de36c0f989a85

Shader code, in case that link goes stale:
```
float PSMain() : SV_TARGET
{
    switch (0)
	{
	case 0:
        return 1;
    }
	return 0;
}
```

(Obviously you generally would not hand-write code like that, but in our case the code is generated).

The issue can be worked-around by assigning the value to a dummy variable, or introducing an (identity) cast, e.g. `switch ((int)0)`

### PR DESCRIPTION
**Pull request by sudonatalie**
Adds support for literal ints as selectors in switch statements.

Fixes #4338

### CODE REVIEW

File: tools/clang/include/clang/SPIRV/SpirvInstruction.h [hunk 1]
```diff
@@ -837,7 +837,7 @@ class SpirvSwitch : public SpirvBranching {
 
   SpirvInstruction *getSelector() const { return selector; }
   SpirvBasicBlock *getDefaultLabel() const { return defaultLabel; }
-  llvm::ArrayRef<std::pair<llvm::APInt, SpirvBasicBlock *>> getTargets() const {
+  std::vector<std::pair<llvm::APInt, SpirvBasicBlock *>> &getTargets() {
```
Comment (Keenuts) [inline tools/clang/include/clang/SPIRV/SpirvInstruction.h:840]: You can revert all the `std::vector` changes if you change the `llvm::ArrayRef` here by a `llvm::MutableArrayRef`.

**Review by Keenuts — APPROVED** [review]

File: tools/clang/include/clang/SPIRV/SpirvInstruction.h (hunk 1 above)
Comment (sudonatalie) [reply tools/clang/include/clang/SPIRV/SpirvInstruction.h]: Good call, thanks!

File: tools/clang/include/clang/SPIRV/SpirvInstruction.h [hunk 2]
```diff
@@ -837,7 +837,8 @@ class SpirvSwitch : public SpirvBranching {
 
   SpirvInstruction *getSelector() const { return selector; }
   SpirvBasicBlock *getDefaultLabel() const { return defaultLabel; }
-  llvm::ArrayRef<std::pair<llvm::APInt, SpirvBasicBlock *>> getTargets() const {
+  llvm::MutableArrayRef<std::pair<llvm::APInt, SpirvBasicBlock *>>
```
[the remark this answers is not in the document]
Comment (sudonatalie) [reply tools/clang/include/clang/SPIRV/SpirvInstruction.h:840]: Good point, done.

**Review by Keenuts — APPROVED** [review]

**Review by cassiebeckley — APPROVED** [review]
