### PR TITLE
De-duplicate numerical conversions code

### LINKED ISSUE #1878: DXC doesn't respect signedness when converting in constant initializer lists
Repro:
```
float main() : OUT
{
    static float a[1] = {uint1(0xFFFFFFFF)};
    return a[0];
}
```
DXC output: `call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float -1.000000e+00)`
FXC output: `mov o0.x, l(4294967296.000000)`
The issue is in `CGHLSLMS.cpp`'s `BuildConstInitializer`. The way the `QualType` of the conversion source is lost due to the way the code is written, and so it bogusly uses the destination type:
```
Instruction::CastOps castOp =
          static_cast<Instruction::CastOps>(HLModule::FindCastOp(
              IsUnsigned(Type), IsUnsigned(Type), Val->getType(), Ty));
```

### LINKED ISSUE #1880: DXC crashes when bools indirectly appear in static initializers
Repro:
```
bool2 main() : OUT
{
    static bool2 a = bool2(false, true);
    return a;
}
```
or:
```
bool2 main() : OUT
{
    static bool2 a[1] = { bool2(false, true) };
    return a[0];
}
```

Apparently, constants are expected to be in their memory representation (ie bools as i32s, see `CodeGenModule::EmitConstantExpr`), and the HLSL constant initializer emitting logic in `CGHLSLMS.cpp` doesn't fully respect this, leading to mismatches between the global variable type and that of its constant valued initializer.

### PR DESCRIPTION
**Pull request by MrTrillian**
Lots of different code in `CGHLSLMS.cpp` did numerical conversions in slightly different ways, most of them forgetting to take into account bools. This change introduces a single `ConvertScalarOrVector` function which handles both and updates code to use it. This implied a partial rewrite of const init list handling code because they lost the `QualType` information necessary to properly cast. They were also not handling register/memory representations properly so I fixed it at the same time.

Fixes #1880 
Fixes #1878 
Adds a test for #1875

### CODE REVIEW

File: lib/HLSL/HLMatrixLowerPass.cpp [hunk 1]
```diff
@@ -411,29 +411,29 @@ INITIALIZE_PASS(HLMatrixLowerPass, "hlmatrixlower", "HLSL High-Level Matrix Lowe
 
 static Instruction *CreateTypeCast(HLCastOpcode castOp, Type *toTy, Value *src,
```
Comment (MrTrillian) [inline lib/HLSL/HLMatrixLowerPass.cpp]: This is a minor duplication of ConvertScalarOrVector in CGHLSLMS.cpp, unfortunately. But because of the different IRBuilder template specializations, I can't move it to HLModule.h

File: lib/HLSL/HLModule.cpp [hunk 2]
```diff
@@ -984,54 +991,40 @@ CallInst *HLModule::EmitHLOperationCall(BuilderTy &Builder,
...
-                                           Type *RetType,
-                                           ArrayRef<Value *> paramList,
-                                           llvm::Module &M);
-
-unsigned HLModule::FindCastOp(bool fromUnsigned, bool toUnsigned,
-                              llvm::Type *SrcTy, llvm::Type *DstTy) {
-  Instruction::CastOps castOp = llvm::Instruction::CastOps::BitCast;
-
-  if (SrcTy->isAggregateType() || DstTy->isAggregateType())
-    return llvm::Instruction::CastOps::BitCast;
```
Comment (MrTrillian) [inline lib/HLSL/HLModule.cpp]: I got rid of this from the original implementation and made it invalid to pass in non-scalar or vector types. It seemed like it's not this method's job to decide that everything else can be casted using bitcasts.

File: tools/clang/include/clang/AST/HlslTypes.h [hunk 3]
```diff
@@ -372,6 +372,8 @@ bool IsHLSLVecType(clang::QualType type);
 bool IsHLSLMatType(clang::QualType type);
 clang::QualType GetElementTypeOrType(clang::QualType type);
 bool HasHLSLMatOrientation(clang::QualType type, bool *pIsRowMajor = nullptr);
+bool IsHLSLMatRowMajor(clang::QualType type, bool defaultValue);
+bool IsHLSLUnsigned(clang::QualType type);
```
Comment (MrTrillian) [inline tools/clang/include/clang/AST/HlslTypes.h]: Moved here from CGHLSLRuntime.

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 4]
```diff
@@ -1232,7 +1232,7 @@ llvm::Constant *CodeGenModule::EmitConstantInit(const VarDecl &D,
   assert(E && "No initializer to emit");
 
   llvm::Constant* C = ConstExprEmitter(*this, CGF).Visit(const_cast<Expr*>(E));
-  if (C && C->getType()->isIntegerTy(1)) {
+  if (C && C->getType()->getScalarType()->isIntegerTy(1)) { // HLSL Change
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp]: To handle bool vectors

File: tools/clang/lib/CodeGen/CGHLSLRuntime.cpp [hunk 5]
```diff
@@ -21,23 +21,3 @@ using namespace clang;
 using namespace CodeGen;
 
 CGHLSLRuntime::~CGHLSLRuntime() {}
-
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLRuntime.cpp]: Moved to HlslTypes.h

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 6]
```diff
@@ -5773,106 +5756,128 @@ Value *CGMSHLSLRuntime::EmitHLSLInitListExpr(CodeGenFunction &CGF, InitListExpr
   }
 }
 
-static void FlatConstToList(Constant *C, SmallVector<Constant *, 4> &EltValList,
-                            QualType Type, CodeGenTypes &Types,
-                            bool bDefaultRowMajor) {
+static void FlatConstToList(CodeGenTypes &Types, bool bDefaultRowMajor,
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: This method is partially rewritten to make it output the QualTypes of the constant elements, though I also took the opportunity to clean things up a bit.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 7]
```diff
@@ -5883,163 +5888,164 @@ static bool ScanConstInitList(CodeGenModule &CGM, InitListExpr *E,
...
-
-static Constant *BuildConstMatrix(llvm::Type *Ty, unsigned &offset,
-                                  SmallVector<Constant *, 4> &EltValList,
-                                  QualType Type, CodeGenTypes &Types,
-                                  bool bDefaultRowMajor) {
-  QualType EltTy = hlsl::GetHLSLMatElementType(Type);
-  unsigned col, row;
-  HLMatrixLower::GetMatrixInfo(Ty, col, row);
-  llvm::ArrayType *AT = cast<llvm::ArrayType>(Ty->getStructElementType(0));
+static Constant *BuildConstInitializer(CodeGenTypes &Types, bool bDefaultRowMajor,
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: This and accompanying method are also partially rewritten to consume the QualTypes and deal with register/memory representations, plus the usual cleanups.

File: tools/clang/lib/AST/HlslTypes.cpp [hunk 8]
```diff
@@ -160,6 +161,26 @@ bool HasHLSLMatOrientation(clang::QualType type, bool *pIsRowMajor) {
...
+
+bool IsHLSLUnsigned(clang::QualType type) {
+  if (type->getAs<clang::BuiltinType>() == nullptr) {
+    type = type.getCanonicalType().getNonReferenceType();
+
+    if (IsHLSLVecMatType(type))
+      type = GetElementTypeOrType(type);
+
+    if (type->isExtVectorType())
+      type = type->getAs<clang::ExtVectorType>()->getElementType();
```
Comment (tex3d) [inline tools/clang/lib/AST/HlslTypes.cpp]: I don't think we should ever see clang::ExtVectorType in HLSL, right?  Though I can understand including this for completeness I guess.

File: tools/clang/lib/CodeGen/CGExprConstant.cpp (hunk 4 above)
Comment (tex3d) [reply tools/clang/lib/CodeGen/CGExprConstant.cpp]: Shouldn't this also handle matrix here?

Comment (tex3d) [reply tools/clang/lib/CodeGen/CGExprConstant.cpp]: Or will that insert an implicit cast that gets handled elsewhere?  If so, does that not happen for vector as well?  What scenario hits this case?

Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGExprConstant.cpp]: This case happens when a static initializer is of type bool or bool vector: `static bool foo = { true };` or `static bool2 foo = { true, false };` Emitting the initializer will result in a register-representation i1 or <2 x i1>, which should be converted to its memory representation before storage to match the storage type of the variable and later support loads from it.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 9]
```diff
@@ -7127,16 +7116,15 @@ void CGMSHLSLRuntime::EmitHLSLOutParamConversionInit(
...
-            static_cast<Instruction::CastOps>(HLModule::FindCastOp(
-                IsUnsigned(argLV.getType()), IsUnsigned(tmpLV.getType()),
-                outVal->getType(), ToTy));
-
-        Value *castVal = CGF.Builder.CreateCast(castOp, outVal, ToTy);
-        if (!HLMatrixLower::IsMatrixType(ToTy))
-          CGF.Builder.CreateStore(castVal, tmpArgAddr);
-        else
+        if (HLMatrixLower::IsMatrixType(ToTy)) {
+          Value *castVal = CGF.Builder.CreateBitCast(outVal, ToTy);
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I'm not clear on the scenario for which this bitcast is used, though I see that it was doing the same thing by other means before.

Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I agree and also noted it as being highly suspicious. I have on my backlog to write tests for inout conversions.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 10]
```diff
@@ -5773,106 +5756,128 @@ Value *CGMSHLSLRuntime::EmitHLSLInitListExpr(CodeGenFunction &CGF, InitListExpr
...
-    }
-  } else if (dyn_cast<llvm::StructType>(Ty)) {
-    RecordDecl *RD = Type->getAsStructureType()->getDecl();
-    const CGRecordLayout &RL = Types.getCGRecordLayout(RD);
+
+    // Return the elements in the order respecting the orientation.
+    bool IsRowMajor = hlsl::IsHLSLMatRowMajor(QualTy, bDefaultRowMajor);
+    for (unsigned r = 0; r < RowCount; ++r) {
+      for (unsigned c = 0; c < ColCount; ++c) {
+        unsigned Idx = IsRowMajor ? (r * ColCount + c) : (c * RowCount + r);
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I'm not sure why we are transposing constant matrix based on row/col major.  Since the logical layout is always row major, it should not make any difference for constant initializer, should it?

File: tools/clang/lib/AST/HlslTypes.cpp (hunk 8 above)
Comment (tex3d) [reply tools/clang/lib/AST/HlslTypes.cpp]: Ok, I say leave it for now.  I'm just not sure I fully understand what scenarios hit certain cases in some of this code.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 10 above)
Comment (tex3d) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I would feel more comfortable if there was a test that exercised this a couple different ways and made sure the components came out in the right order.

**Comment by ehsannas** [comment]
@MrTrillian Thanks for the heads up. I'll take a look at why we're calling that API for non-matrices. I'll fix our code and then reintroduce the assert 👍

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 9 above)
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: (btw, filed #1890 to remember testing this)

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 11]
```diff
@@ -5773,106 +5756,128 @@ Value *CGMSHLSLRuntime::EmitHLSLInitListExpr(CodeGenFunction &CGF, InitListExpr
...
+    // Get all the elements from the array of row vectors.
+    // Matrices are never in memory representation so convert as needed.
+    SmallVector<Constant *, 16> MatElts;
+    for (unsigned r = 0; r < RowCount; ++r) {
+      Constant *RowVec = RowArrayVal->getAggregateElement(r);
+      for (unsigned c = 0; c < ColCount; ++c) {
+        Constant *MatElt = RowVec->getAggregateElement(c);
+        if (MatEltQualTy->isBooleanType()) {
+          DXASSERT(MatElt->getType()->isIntegerTy(1),
+            "Matrix elements should be in their register representation.");
```
[the remark this answers is not in the document]
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: True, but I'd rather not do so because it would lead to a really ugly assert condition like `!MatEltQualTy->isBooleanType() || RowArrayVal->getAggregateElement(0)->getAggregateElement(0)->getType()->isIntegerType(1)`.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 10 above)
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I was confused about this too, but the reason it matters is that the constant initializer has to produce a value that will live in memory (where the static variable lives), so it must have its bools as i32s and its matrices in memory packing order such that the loads then properly reconvert to the register representation. Let's see if I can add a test.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 12]
```diff
@@ -5773,106 +5756,128 @@ Value *CGMSHLSLRuntime::EmitHLSLInitListExpr(CodeGenFunction &CGF, InitListExpr
...
   llvm::Type *Ty = C->getType();
-  if (llvm::VectorType *VT = dyn_cast<llvm::VectorType>(Ty)) {
-    // Type is only for matrix. Keep use Type to next level.
-    for (unsigned i = 0; i < VT->getNumElements(); i++) {
-      FlatConstToList(C->getAggregateElement(i), EltValList, Type, Types,
-                      bDefaultRowMajor);
+  if (llvm::VectorType *VecTy = dyn_cast<llvm::VectorType>(Ty)) {
+    DXASSERT(hlsl::IsHLSLVecType(QualTy), "QualType/Type mismatch!");
+    for (unsigned i = 0; i < VecTy->getNumElements(); i++) {
+      FlatConstToList(Types, bDefaultRowMajor,
```
[the remark this answers is not in the document]
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: Sure

**Comment by MrTrillian** [comment]
Sorry for the churn, I rebased because I didn't trust github's merge-based conflict resolution to be squashable.

**Comment by ehsannas** [comment]
@MrTrillian , one interesting instance that I found is array of matrices. e.g.
```hlsl
column_major float2x3 matrixArray[4];
```
In these cases, the `attr_hlsl_row_major` or `attr_hlsl_column_major` attribute is applied to the array type, not the matrix type.

So, sometimes we pass an array type (array of matrices) to `hlsl::HasHLSLMatOrientation` . I guess there might be other cases too, but this is the one I've found so far.

**Comment by ehsannas** [comment]
We actually have a pretty ugly bookkeeping code that tries to figure out the matrix majorness of a QualType. The reason we had to write that code was that the majorness attribute was not always applied to the matrix QualType (e.g. the array of matrix case shown above). It would be really nice if the attribute is always properly applied to the matrix QualType. It would allow us to remove that bookkeeping code.

**Comment by MrTrillian** [comment]
@ehsannas I'm unable to repro seeing the attribute be applied to the array rather than the matrix. With your snippet as a local variable, I see the expected QualType below. If you have a repro for the attribute being on the array, I'd run it by Tex but it sounds like a bad bug to me and I'd file it as such.

```
Ty.dump()
ConstantArrayType 0x223d93993b0 'column_major float2x3 [4]' 4 
`-AttributedType 0x223d9399280 'column_major float2x3' sugar
  |-TypedefType 0x223d9399230 'float2x3' sugar
```

**Comment by ehsannas** [comment]
Sorry. My comment above was incorrect. The reason we needed the bookkeeping was because we do a recursive visit to translate QualTypes to spirv types. When we reach the leaf node
```
  |-TypedefType 0x223d9399230 'float2x3' sugar
```
we have lost the information about majorness.

So I'll take a closer look at our usages of `HasHLSLMatOrientation`.
I'll stop hijacking this PR thread :P and open a separate issue or PR. Thanks!

**Comment by MrTrillian** [comment]
Yet another rebase to fix merge conflicts. Will merge PR as soon as appveyor/travis are happy.
