### PR TITLE
[SPIR-V] Fix crash with out-of-line template decl

### LINKED ISSUE #5823: [SPIR-V] Out-of-line initialization of `static const` member arrays of templated types SIGSEGVs
**Description**
When compiling with `-HV 202x -T ps_6_7 -E PSMain` it works and produces DXIL, when adding `-spirv` it SIGSEGVs the compiler.

**Steps to Reproduce**
https://godbolt.org/z/WasWzsq4E

If you strip all my C++ compat code then you have
https://godbolt.org/z/dWMfjxza1

**Actual Behavior**
SIGSEGV of the compiler.

I think this is because `static` outside of the class makes no sense in C++ (and for LLVM), but I cannot use `const` on its own because I get a different problem.

**Environment**
- DXC version Latest trunk according to Godbolt
- Host Operating System Linux I guess

### PR DESCRIPTION
**Pull request by Keenuts**
The SPIR-V backend made no differentence between VarDecl from template declaration and VarDecl from template instantiation. Fixing this by not creating a SPIR-V variable for template declaration (and waiting for the final instantiation).

Fixes #5823

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -2034,6 +2034,26 @@ void SpirvEmitter::doVarDecl(const VarDecl *decl) {
     return;
   }
 
+  // Considering the following example:
+  //
+  // ```cpp
+  //  template<typename T> static const T MyClass<T>::myVar = 1;
+  //  [...]
+  //  int use = MyClass<int>::myVar;
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp]: This looks different than the test that you added.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 2]
```diff
@@ -2034,6 +2034,26 @@ void SpirvEmitter::doVarDecl(const VarDecl *decl) {
...
+  // ```
+  //
+  // The AST will contain 2 variable declarations:
+  //  - VarDecl for the template declaration
+  //  - VarDecl for the tempalte instantiation
+  // The difference lies in the InitExpr:
+  //  - declaration will have the type `void` because the template is
+  //    not resolve yet.
+  //  - the second will have the proper type (`int` here).
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp]: I'm not sure that is true, and could be fragile:

```
|-ClassTemplateDecl 0x55de8ce4a908 <t.hlsl:1:1, line:4:1> line:2:8 MyClass
| |-TemplateTypeParmDecl 0x55de8ce4a7b8 <line:1:10, col:19> col:19 referenced typename T
| |-CXXRecordDecl 0x55de8ce4a850 <line:2:1, line:4:1> line:2:8 struct MyClass definition
| | |-CXXRecordDecl 0x55de8ce4aba8 <col:1, col:8> col:8 implicit struct MyClass
| | `-VarDecl 0x55de8ce4ad18 <line:3:3, col:25> col:18 array 'const T [2]' static

VarDecl 0x55de8ce4b0c8 parent 0x55de8ce4a850 prev 0x55de8ce4ad18 <line:9:1, col:67> col:49 array 'const T [2]' static cinit
```

The template varDecl, contains a pointer to the orginal var decl that is a member of the ClassTemplateDecl. That is definitive. I think the void is a side effect that may not be robust.

Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp]: Looks like there is indeed a better way to detect this (as long as a comment explain some bits).
Changed the method to look at the declaration context. Since this only happens on static variable in templated classes, seems like what I did is enough.
