### PR TITLE
[spirv] Add null check to binary op processing

### LINKED ISSUE #2953: [SPIR-V] Crash when result of dot4add_u8packed or dot4add_i8packed is operated on by a literal
### Title
 Compiler crash when the result of dot4add_u8packed or dot4add_i8packed is operated on by a literal e.g when performing multiplication/division/addition/subtraction.

### Functional impact
Compiler crashes, no result gets printed to stdout.

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746158/repro_shader.txt) with `dxc.exe -E frag -T ps_6_4 repro_shader.txt -spirv -fspv-target-env=vulkan1.1`
```
uint frag(float4 vertex : SV_POSITION) : SV_Target
{
    uint acc = 0;
    
	acc += 1+dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
        acc += 2+dot4add_i8packed(vertex.z, vertex.w, int(vertex.x));
	
	//The following does not cause a crash
	
	//uint tempVar = 2;
	//acc += tempVar*dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
        //acc += tempVar*dot4add_i8packed(vertex.z, vertex.w, int(vertex.x));
    
	return acc;
}
```

### Expected result
The compiler outputs correct SPIR-V or prints an informative error message.

### Actual result
DXC crashes on assertion `assert(Val && "isa<> used on a null pointer");` (see
[call_stack.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746146/call_stack.txt))

### Further technical details
DXC bult from changeset 5ebc67c618d7061407cca039573108078f601ee6

### PR DESCRIPTION
**Pull request by sudonatalie**
The repro shader from issue #2953 now fails with a useful error message
and has been added as a unit test.

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -5795,17 +5795,17 @@ SpirvInstruction *SpirvEmitter::processBinaryOp(
...
-        if (isAcceptedSpecConstantBinaryOp(spvOp)) {
-          if (lhsValConstant->isSpecConstant() ||
-              rhsValConstant->isSpecConstant()) {
-            auto *val = spvBuilder.createSpecConstantBinaryOp(
-                spvOp, resultType, lhsVal, rhsVal, loc);
-            val->setRValue();
-            return val;
-          }
-        }
+    if (lhsVal && rhsVal) {
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:5798]: See the line 5812 ~ 2824. It uses `lhsVal` and `rhsVal` without null check.

Why don't we add `if (lhsVal == nullptr || rhsVal == nullptr) return nullptr;` just before this line?

File: tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// Run: %dxc -E frag -T ps_6_4 -fspv-target-env=vulkan1.1
+
+uint frag(float4 vertex
+          : SV_POSITION) : SV_Target {
+  uint acc = 0;
+
+  // CHECK: 8:14: error: dot4add_u8packed intrinsic function unimplemented
+  acc += 1 + dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
```
Comment (jaebaek) [inline tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl:8]: Could you please add
```
acc += dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y)) + 1;
acc = 1 + dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
acc = dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y)) + 1;
```
?

Since the main issue is the `lhs` and `rhs` and the type of binary operator, I want to know what happens when `lhs` has the issue and it is not compound assignment op.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 1 above)
Comment (sudonatalie) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp]: Done, thanks!

File: tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl (hunk 2 above)
Comment (sudonatalie) [reply tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl:8]: Done

**Review by jaebaek — APPROVED** [review]
