### PR TITLE
[SM6.9] Enable trivial native vector Dxil Operations plus a few

### LINKED ISSUE #7297: vectors longer than 254 are truncated to 1 when passed to intrinsics
**Description**

```c++
template<int N>
int VectorLength(vector<float, N>) { return N; }

export int Test1(vector<float, 254> Input) {
    return VectorLength(mul(Input, 1));
    // ret i32 254
}

export int Test2(vector<float, 255> Input) {
    return VectorLength(mul(Input, 1));
    // EXPECTED: ret i32 255
    // ACTUAL  : ret i32 1
}
```

**Steps to Reproduce**

Compile the above shader with -Tlib_6_9 to see the repro.

### PR DESCRIPTION
**Pull request by llvm-beanz**
This enables the generation of native vector DXIL Operations
that are "trivial", meaning they take only a single DXOp Call
instruction to implement as well as a few others that either only took
such a call and some llvm operations or were of particular interest for
other reasons.

This involves allowing the overloads by adding the vector indication in
hctdb, altering the lowering to maintain the vectors instead of
scalarizing them, and a few sundry changes to fix issues along the way.

The "trivial" dxil operations that return a different value from the
overload type had to be moved out of the way and given their own
lowering function so that the main function could generate vectors
conditional on the version and vector type. These will be added in a
later change.

While the long vector supporting intrinsics that weren't given this
treatment will continue to generate scalarized operations, some of them
needed some work as well. The dot product for float vectors longer than
4 had to take the integer fallback path, which required some small
modificaitons and a rename.
Additionally, a heuristic for pow that malfunctioned with too many
elements had to have a limit placed on it.

Since the or()/and()/select() intrinsics translate directly to LLVM ops,
they can have their lowering scalarization removed and what future
scalarization might be needed by the current version can be done by
later passes as with other LLVM operators.

An issue with a special value used to represent unassined dimensions had
to be addressed since new dimensions can exceed that value. It's now
MAX_INT.

Contributes to #7120, but I'd prefer to leave it open until all
intrinsics are covered

Primary work by @pow2clk

Fixes #7297 & #7120

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -459,12 +467,40 @@ Value *TrivialDxilOperation(Function *dxilFunc, OP::OpCode opcode,
...
+// type `Ty`.
+// Utility objects `HlslOp` and `Builder` are used to create a call to the given
+// `DxilFunc` with `RefArgs` arguments.
+Value *TrivialDxilVectorOperation(Function *Func, OP::OpCode Opcode,
+                                  ArrayRef<Value *> Args, Type *Ty, OP *OP,
+                                  IRBuilder<> &Builder) {
+  if (!Ty->isVoidTy())
+    return Builder.CreateCall(Func, Args, OP->GetOpCodeName(Opcode));
+  else
+    return Builder.CreateCall(Func, Args); // Cannot add name to void.
```
Comment (llvm-beanz) [inline lib/HLSL/HLOperationLower.cpp:482]: see: https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return

```suggestion
  return Builder.CreateCall(Func, Args); // Cannot add name to void.
```

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 2]
```diff
@@ -6606,7 +6606,7 @@ bool HLSLExternalSource::MatchArguments(
   argTypes.clear();
   const bool isVariadic = IsVariadicIntrinsicFunction(pIntrinsic);
 
-  static const UINT UnusedSize = 0xFF;
+  static const UINT UnusedSize = UINT_MAX;
```
Comment (damyanp) [inline tools/clang/lib/Sema/SemaHLSL.cpp:6609]: Is this a fix for #7297?

File: tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+  vec1 = dot(vec1, vec2);
+
+  vector<bool, 8> bvec = b;
+  // CHECK: or i1
+  // CHECK: or i1
+  // CHECK: or i1
+  // CHECK: or i1
+  // CHECK: or i1
+  // CHECK: or i1
+  // CHECK: or i1
```
Comment (damyanp) [inline tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl:125]:
```suggestion
  // CHECK-COUNT-7: or i1
```

Which does make me wonder why it isn't 8 though.

File: tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+#define CALLARGS(x,y,z) x, i
+// ARITY 5 is used for 1 vec + uint4 mask for wavemultiprefix*
+#elif ARITY == 5
+#define CALLARGS(x,y,z) x, m
+#endif
+
+StructuredBuffer< vector<TYPE, 8> > buf;
+ByteAddressBuffer rbuf;
+
+float4 main(uint i : SV_PrimitiveID, uint4 m : M) : SV_Target {
```
Comment (damyanp) [inline tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl:65]: @alsepkow - the approach used in this file might be interesting to think about for the HLKs you're working on

File: lib/HLSL/HLOperationLower.cpp [hunk 5]
```diff
@@ -484,55 +519,81 @@ Value *TrivialDxilOperation(OP::OpCode opcode, ArrayRef<Value *> refArgs,
...
 }
 
-Value *TrivialDxilUnaryOperation(OP::OpCode opcode, Value *src,
-                                 hlsl::OP *hlslOP, IRBuilder<> &Builder) {
-  return TrivialDxilUnaryOperationRet(opcode, src, src->getType(), hlslOP,
-                                      Builder);
+Value *TrivialDxilUnaryOperation(OP::OpCode OpCode, Value *Src, hlsl::OP *Op,
+                                 IRBuilder<> &Builder,
+                                 bool SupportsVectors = false) {
+  Type *Ty = src->getType();
```
Comment (damyanp) [inline lib/HLSL/HLOperationLower.cpp:545]:
```suggestion
  Type *Ty = Src->getType();
```

File: tools/clang/lib/Sema/SemaHLSL.cpp (hunk 2 above)
Comment (llvm-beanz) [reply tools/clang/lib/Sema/SemaHLSL.cpp:6609]: I believe so. I have a small update to this line coming to not use the Windows typedefs and use C++ limits.

File: lib/HLSL/HLOperationLower.cpp (hunk 5 above)
Comment (llvm-beanz) [reply lib/HLSL/HLOperationLower.cpp]: This is in my latest change.

File: tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl (hunk 3 above)
Comment (llvm-beanz) [reply tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl:125]: Sadly DXC's FileCheck doesn't support `CHECK-COUNT`, that's a newer feature:
https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/CommandGuide/FileCheck.rst

`CHECK-COUNT` was added in 2018 with this patch: https://reviews.llvm.org/D54336

Comment (llvm-beanz) [reply tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl:125]: As to why this is 7. The IR is basically:
```
vec[0] & vec[1] & vec[2] & vec[3] & vec[4] & vec[5] & vec[6] & vec[7]
```
Eight elements, 7 operations.

File: tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl [hunk 6]
```diff
@@ -0,0 +1,391 @@
+// RUN: %dxc -T cs_6_9 -enable-16bit-types -DNUM=7   %s | FileCheck %s
+// RUN: %dxc -T cs_6_9 -enable-16bit-types -DNUM=125 %s | FileCheck %s
```
[the remark this answers is not in the document]
Comment (llvm-beanz) [reply tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl:2]: Yea, I'm also going to throw 2 into the mix, because the short vectors should also be vectorizing now too.

File: lib/HLSL/HLOperationLower.cpp [hunk 7]
```diff
@@ -459,12 +467,39 @@ Value *TrivialDxilOperation(Function *dxilFunc, OP::OpCode opcode,
...
+// of `SupportsVectors`, which is deteremined by version and opcode support.
 Value *TrivialDxilOperation(OP::OpCode opcode, ArrayRef<Value *> refArgs,
                             Type *Ty, Type *RetTy, OP *hlslOP,
-                            IRBuilder<> &Builder) {
+                            IRBuilder<> &Builder,
+                            bool SupportsVectors = false) {
+
+  // If supported and the overload type is a vector with more than 1 element,
+  // create a native vector operation.
+  if (SupportsVectors && Ty->isVectorTy() && Ty->getVectorNumElements() > 1) {
```
[the remark this answers is not in the document]
Comment (llvm-beanz) [reply lib/HLSL/HLOperationLower.cpp:496]: Great catch @tex3d!

Fixing this actually corrects at least some of the missing intrinsics you cited in your comment above. I'll roll this change through and do a pass at removing spurious diffs too. I think this is a fantastic simplification of the change.

**Comment by llvm-beanz** [comment]
After adapting to @tex3d's feedback this really simplified and cleaned up a lot. Please let me know if there are other changes I should make, but I think I got everything that has been suggested.

**Review by damyanp — APPROVED** [review]
FWIW, LGTM.

**Review by damyanp — APPROVED** [review]

File: tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl
Comment (tex3d) [inline tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl:1]: Nit: Given that only `WaveMatch` is truly "scalarized", the name of the test isn't great.  Perhaps "expanded" instead.  But I don't think this justifies an update on its own.  This can be cleaned up later.

**Review by tex3d — APPROVED** [review]
Looks good!
