### PR TITLE
Fixed offset being lost when lowering Buffer<Struct>[i].Field

### LINKED ISSUE #2258: Field offset is lost when lowering Buffer<Struct>[i].Field
Repro:
```
struct S { int x; int y; };
Buffer<S> buf;
int main() : OUT { return buf[0].y; }
```
Result:
```
define void @main() {
entry:
  %buf_texture_buf = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 0, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %0 = call %dx.types.ResRet.i32 @dx.op.bufferLoad.i32(i32 68, %dx.types.Handle %buf_texture_buf, i32 0, i32 undef)  ; BufferLoad(srv,index,wot)
  %1 = extractvalue %dx.types.ResRet.i32 %0, 0
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 0, i32 %1)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```
Note that only the "x" field is read instead of "y".

### PR DESCRIPTION
**Pull request by MrTrillian**
`Buffer<Struct>[i].Field` was handled by the structuredbuffer code, which emitted a `rawBufferLoad` intrinsic. However, typed buffers cannot use `rawBufferLoad`, so some further code patched it back into a `bufferLoad`. The problem is that `bufferLoad` cannot take a byte offset into the element to be loaded, it has to load the entire thing, so we always ended up loading the first struct field.

This fix makes us emit a `bufferLoad` directly, and use the offset to determine which `ResRet` components to return, falling back to using a temporary array for dynamic indexing if needed.

Fixes #2258

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -6485,7 +6553,8 @@ void TranslateStructBufSubscriptUser(Instruction *user, Value *handle,
       TranslateStructBufMatLdSt(userCall, handle, OP, status, bufIdx,
                                 baseOffset, DL);
     else if (group == HLOpcodeGroup::HLSubscript) {
-      TranslateStructBufMatSubscript(userCall, handle, OP, bufIdx, baseOffset, status, DL);
+      TranslateStructBufMatSubscript(userCall,
+        handle, ResKind, bufIdx, baseOffset, status, OP, DL);
```
Comment (vcsharma) [inline lib/HLSL/HLOperationLower.cpp]: `OP`'s position changed to second last, whereas in other places (such as `TranslateStructBufMatLdSt`), it appears immediately after `handle`. was this intentional?

File: lib/HLSL/HLOperationLower.cpp [hunk 2]
```diff
@@ -6067,6 +6068,74 @@ Value *GEPIdxToOffset(GetElementPtrInst *GEP, IRBuilder<> &Builder,
...
+    Value* ArrayAlloca = SpillValuesToArrayAlloca(
+      ArrayRef<Value*>(ResRet.data(), ResRet.size()), Builder);
+
+    // Get all elements to be returned through dynamic indices
+    Value *FirstElemIdx = Builder.CreateUDiv(Offset, Builder.getInt32(ElemSizeInBytes));
+    for (unsigned i = 0; i < ElemCount; ++i) {
+      Value *ElemIdx = Builder.CreateAdd(FirstElemIdx, Builder.getInt32(i));
+      Value* ElemPtr = Builder.CreateGEP(ArrayAlloca, { Builder.getInt32(0), ElemIdx });
+      Elems.emplace_back(Builder.CreateLoad(ElemPtr));
+    }
```
Comment (vcsharma) [inline lib/HLSL/HLOperationLower.cpp]: do we have test for dynamic indexing scenario?

File: lib/HLSL/HLOperationLower.cpp (hunk 1 above)
Comment (MrTrillian) [reply lib/HLSL/HLOperationLower.cpp]: I actually made it consistent with `TranslateStructBufSubscriptUser`, but the whole file is a mess. I guess the new state isn't worse than the old one?

Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: hmm, yes, this could cleaned up later. Not a high-pri for now, imo..

File: lib/HLSL/HLOperationLower.cpp (hunk 2 above)
Comment (MrTrillian) [reply lib/HLSL/HLOperationLower.cpp]: Now we do!
