### PR TITLE
Fix constexpr cast involving matrix type

### LINKED ISSUE #3041: half3x3 to float3x3 is causing DXC to crash due to stack overflow
Hi!

The shader code below is crashing DXC due to stack overflow 

Same behaviour with XBox dxc compiler and latest version from Github.
Compiled using following command line _dxc -E main -T ps_6_0 test.hlsl_

It could be ill-formed code, but compiler should at least point to the error and no just silently crash.

PS. Same behaviour if using dxcompiler.dll  and IDxcCompiler3.

```c++
static const float sFoo = 1.5;

static const float3x3 sBar = half3x3
(
    sFoo,  0.0f,   -sFoo * 0.5f,
    0.0f,   sFoo,  -sFoo * 0.5f,
    0.0f,   0.0f,   1.0f
);

half4 main() : SV_Target
{
    half3 result = half3(0.0, 0.0, 0.0);
    return(float4(result, 0));
}
```

### LINKED ISSUE #3590: constexpr cast involving matrix type causes compiler crash
**Scenario 1: Matrix to Scalar truncation cast**

```
void main() {
	const float foo = float1x1(1);
}
```

**Scenario 2: Matrix to Matrix truncation with zero initializer**

Note: If the initialized value is non-zero, then it works.

```
void main() {
	const float1x1 foo = float2x2(0, 0, 0, 0);
}
```

### PR DESCRIPTION
**Pull request by vcsharma**
Fix a bunch of issues (described below) related to constexpr cast involving matrix types. Also refactor redundant code into a separate function `ExtractConstantValueElems` for better clarity.

**Issue 1:**
We were not handling below component conversion cast for matrix type:
```
    CK_HLSLCC_FloatingCast:
    CK_HLSLCC_IntegralCast:
    CK_HLSLCC_IntegralToBoolean:
    CK_HLSLCC_IntegralToFloating:
    CK_HLSLCC_FloatingToIntegral:
    CK_HLSLCC_FloatingToBoolean:
```

**Issue 2:**
We were not handling cast of kind `CK_HLSLMatrixToScalarCast`:

**Issue 3:**
We were not handling `ConstantAggregateZero` type for `CK_HLSLMatrixTruncationCast` cast kind.

All of the above issues were causing compiler crashes.

Fixes #3041 
Fixes #3590

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 1]
```diff
@@ -840,10 +840,6 @@ class ConstExprEmitter :
           return SubExprResult;
         }
 
-        if (llvm::ConstantAggregateZero *CAZ = dyn_cast<llvm::ConstantAggregateZero>(SubExprResult)) {
```
Comment (vcsharma) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp]: I have already moved this logic under else block below. So this is no longer needed.

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 2]
```diff
@@ -749,9 +812,62 @@ class ConstExprEmitter :
     case CK_HLSLCC_IntegralToFloating:
     case CK_HLSLCC_FloatingToIntegral:
     case CK_HLSLCC_FloatingToBoolean:
-      // Since these cast kinds have already been handled in ExprConstant.cpp,
-      // we can reuse the logic there.
-      return CGM.EmitConstantExpr(E, E->getType(), CGF);
+      if (hlsl::IsHLSLMatType(E->getType()) && hlsl::IsHLSLMatType(E->getSubExpr()->getType()) && C) {
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp:815]: I don't think C can be null here because of the ` if (!C) return nullptr;` line above

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 3]
```diff
@@ -749,9 +812,62 @@ class ConstExprEmitter :
     case CK_HLSLCC_IntegralToFloating:
     case CK_HLSLCC_FloatingToIntegral:
     case CK_HLSLCC_FloatingToBoolean:
-      // Since these cast kinds have already been handled in ExprConstant.cpp,
-      // we can reuse the logic there.
-      return CGM.EmitConstantExpr(E, E->getType(), CGF);
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp:754]: It's minor, but given how long the special case for matrices is, I think the code is more readable if it detects the common cast and returns at the top before delving into the matrix variant. instead of making readers scroll down to find the else

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 4]
```diff
@@ -749,9 +812,62 @@ class ConstExprEmitter :
...
+
+        // If the dest type is same as the src type, then trivially
+        // return the result of the subexpression evaluation.
+        llvm::Type *srcEltLLVMTy = CGM.getTypes().ConvertType(srcEltType->getCanonicalTypeInternal());
+        llvm::Type *destEltLLVMTy = CGM.getTypes().ConvertType(destEltType->getCanonicalTypeInternal());
+        // Use desugared llvm type for comparison as half and float could both mean float type
+        // when -enable-16bit-types flag is not used.
+        if (srcEltLLVMTy == destEltLLVMTy) {
+          return SubExprResult;
+        }
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp:841]: Since this involves a potential early return and doesn't care about row/col counts, you might move it above that code, closer to where the eltTypes are retrieved and bringing the row/col counts closer to where they are used

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 5]
```diff
@@ -636,6 +636,69 @@ class ConstExprEmitter :
...
+        Elems[c] = CAZ->getElementValue(c);
+      }
+    }
+  }
+
+  static llvm::Constant* ConvertToMatchDestType (const clang::Type *srcTy, const clang::Type *destTy,
+    llvm::Type *srcLLVMTy, llvm::Type *destLLVMTy, llvm::Constant *C, CodeGenModule &CGM) {
+
+    assert(srcTy->isFloatingType() || srcTy->isIntegerType());
+    assert(destTy->isFloatingType() || destTy->isIntegerType());
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp:663]: if you like, you could make use of dxilutil::IsIntegerOrFloatingPointType(), but if it requires a new header, it's probably not worth it

File: tools/clang/lib/CodeGen/CGExprConstant.cpp [hunk 6]
```diff
@@ -636,6 +636,69 @@ class ConstExprEmitter :
...
+        castOp = llvm::Instruction::FPExt;
+      }
+    }
+    else if (srcLLVMTy->isFloatingPointTy() && destLLVMTy->isIntegerTy()) {
+      castOp = destTy->isSignedIntegerType() ? llvm::Instruction::FPToSI : llvm::Instruction::FPToUI;
+    }
+    else if (srcLLVMTy->isIntegerTy() && destLLVMTy->isFloatingPointTy()) {
+      castOp = srcTy->isSignedIntegerType() ? llvm::Instruction::SIToFP : llvm::Instruction::UIToFP;
+    }
+    else {
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprConstant.cpp:687]: A comment saying the else is both integers might be helpful

**Review by pow2clk — APPROVED** [review]
Looks good. I have various suggestions that you might consider for readability's sake, but it's already pretty clear

File: tools/clang/lib/CodeGen/CGExprConstant.cpp (hunk 4 above)
Comment (vcsharma) [reply tools/clang/lib/CodeGen/CGExprConstant.cpp:841]: Fixed.

File: tools/clang/lib/CodeGen/CGExprConstant.cpp (hunk 6 above)
Comment (vcsharma) [reply tools/clang/lib/CodeGen/CGExprConstant.cpp:687]: Done, also added an assert.

**Review by tex3d — APPROVED** [review]
LGTM.
