### PR TITLE
Fix broken ternary on matrix return type (#4434)

### LINKED ISSUE #4434: Internal Compiler Error with ternary operations on matrices
December 2021 DXC crashes when compiling this shader:

```
float2x2 crashingFunction( bool b )
{
    float2x2 x = { 0.0, 0.0, 0.0, 0.0 };
    float2x2 y = { 0.0, 0.0, 0.0, 0.0 };
    return b ? x : y; // <-- this is the issue
}

float2x2 workingFunction( bool b )
{
    float2x2 x = { 0.0, 0.0, 0.0, 0.0 };
    float2x2 y = { 0.0, 0.0, 0.0, 0.0 };
    if( b ) { return x; } else { return y; }
}

[numthreads( 1, 1, 1 )]
void CSMain()
{
    if( crashingFunction(true)[0][0] > 0 )
        return;
    if( workingFunction(true)[0][0] > 0 )
        return;
} 
```
Compile command:
`dxc.exe /Ges -HV 2021 /T cs_6_0 /Fo repro.obj /E CSMain repro.hlsl`

Output:
`Internal compiler error: access violation. Attempted to read from address 0x0000000000000018`

### PR DESCRIPTION
**Pull request by llvm-beanz**
HLSL ternary operators that result in vector or matrix types need
special handling even if the condition is not a vector. This change
allows vector and matrix result types for ternary operators even if
matrix and vector conditions are not allowed.

Preventing matrix and vector conditions is done in Sema, so we should
never be able to reach this code path with a matrix or vector condition
unless the HLSL language version is < 2021.

Fixes #4434

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGExprScalar.cpp [hunk 1]
```diff
@@ -3700,7 +3700,13 @@ VisitAbstractConditionalOperator(const AbstractConditionalOperator *E) {
     return tmp5;
   }
   // HLSL Change Starts
-  if (CGF.getLangOpts().HLSL && !CGF.getLangOpts().EnableShortCircuit) {
+  // This code generates ternary results for vector and matrix types, and needs
+  // to execute if the result of the expression is a vector or matrix type even
+  // if the condition is not. Conditions are not allowed to be vector or matrix
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGExprScalar.cpp:3705]: But don't we still want to avoid emitting these outside the conditional when short-circuiting?
```cpp
      llvm::Value *LHS = Visit(lhsExpr);
      llvm::Value *RHS = Visit(rhsExpr);
```
I'm not sure the fix is this simple, or I'm missing something here.

Comment (tex3d) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp:3705]: In fact, I suspect we are missing tests for short-circuiting to ensure side-effects from dead branches are not seen for functions that return matrix and vector.

Comment (llvm-beanz) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp:3705]: Nope, you're right. We need to generate that under a branch instead of outside the branch.

**Comment by tex3d** [comment]
Test failures are due to our preservation of value names in debug builds.

File: tools/clang/lib/CodeGen/CGExprScalar.cpp [hunk 2]
```diff
@@ -3729,6 +3730,13 @@ VisitAbstractConditionalOperator(const AbstractConditionalOperator *E) {
           CGF, E, LHS->getType(), {Cond, LHS, RHS});
     }
   }
+
+  llvm::Value *ResultAlloca = nullptr;
+  if (CGF.getLangOpts().HLSL && CGF.getLangOpts().EnableShortCircuit &&
+      hlsl::IsHLSLMatType(E->getType())) {
+    llvm::Type *MatTy = CGF.ConvertType(E->getType());
+    ResultAlloca = Builder.CreateAlloca(MatTy);
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGExprScalar.cpp:3738]: We previously, perhaps superstitiously, tried to push all the allocas at the top of the code block. Is this going to maintain that? Need it?

elsewhere, we've used `dxilutil::FindAllocaInsertionPoint(F)`, which would also allow this operation to be done below where the alloca is used

Comment (tex3d) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp:3738]: At the very least, allocas must be inserted in the entry block.  You should use `CGF.CreateTempAlloca` instead, that will place it correctly.

Comment (tex3d) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp:3738]: Alsok, shouldn't we do this after the `isCheapEnoughToEvaluateUnconditionally` part when we know we'll use it?

**Review by pow2clk — APPROVED** [review]
All comments addressed. Let's get it in!
