### PR TITLE
[Linux] WinAdapter: Remove virtual dtors from IUnknown to fix vtable ABI

### LINKED ISSUE #3783: [Linux] WinAdapter: `IUnknown` vtable includes destructors resulting in ABI mismatch
The vtable for `IUnknown` from `WinAdapter.h` contains five instead of three function pointers, shifting vtable entries for every subclass. Two pointers following the three virutal functions in `IUnknown` are reserved for a complete object and deleting destructor:

```cpp
vtable for 'DxcLibrary' @ 0x7ffff7cbc5f8 (subobject @ 0x5555556bb9e0):
[0]: 0x7ffff6a56d40 <DxcLibrary::QueryInterface(_GUID const&, void**)>
[1]: 0x7ffff6a56d20 <DxcLibrary::AddRef()>
[2]: 0x7ffff6a56d30 <DxcLibrary::Release()>
[3]: 0x7ffff6b36bc0 <IUnknown::~IUnknown()> // Complete object destructor
[4]: 0x7ffff6a57130 <DxcLibrary::~DxcLibrary()> // Deleting destructor
[5]: 0x7ffff6a56d50 <DxcLibrary::SetMalloc(IMalloc*)>
[6]: 0x7ffff6a56d60 <DxcLibrary::CreateBlobFromBlob(IDxcBlob*, unsigned int, unsigned int, IDxcBlob**)>
[7]: 0x7ffff6a56d70 <DxcLibrary::CreateBlobFromFile(wchar_t const*, unsigned int*, IDxcBlobEncoding**)>
[8]: 0x7ffff6a56d80 <DxcLibrary::CreateBlobWithEncodingFromPinned(void const*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[9]: 0x7ffff6a56d90 <DxcLibrary::CreateBlobWithEncodingOnHeapCopy(void const*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[10]: 0x7ffff6a56da0 <DxcLibrary::CreateBlobWithEncodingOnMalloc(void const*, IMalloc*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[11]: 0x7ffff6a56db0 <DxcLibrary::CreateIncludeHandler(IDxcIncludeHandler**)>
[12]: 0x7ffff6a56dc0 <DxcLibrary::CreateStreamFromBlobReadOnly(IDxcBlob*, IStream**)>
[13]: 0x7ffff6a56dd0 <DxcLibrary::GetBlobAsUtf8(IDxcBlob*, IDxcBlobEncoding**)>
[14]: 0x7ffff6a56e90 <DxcLibrary::GetBlobAsUtf16(IDxcBlob*, IDxcBlobEncoding**)>
```

This makes it [annoying](https://github.com/Traverse-Research/hassle-rs/blob/1e624792fc3a252ac7788e3c1c5feda52887272f/src/unknown.rs) or [impossible](https://github.com/microsoft/windows-rs/pull/802#discussion_r631784635) to interact with the interfaces from Linux and Windows in a generic way.

Simply removing it results in compiler warnings from both Clang and GCC:

```cpp
../include/dxc/Support/WinAdapter.h:628:8: warning: 'IUnknown' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]
struct IUnknown {
       ^
```

No idea if ignoring them locally (`#pragma clang/GCC diagnostic ignored "-Wnon-virtual-dtor"`) or globally is the right way forward though. Members owned by subclasses of `IUnknown` should be cleaned up through the `Release()` function anyway otherwise this would leak memory and other resources on Windows where no virtual destructors are used.

I recall reading something about `operator delete` (called as `delete this` in `IUnknown::Release`) requiring object size to call the appropriate memory deallocation function which could be facilitated through this destructor. The deleting destructor could possibly pass a size to one of the [`operator delete`](https://en.cppreference.com/w/cpp/memory/new/operator_delete) variants.

@pow2clk Hope you have some suggestions since you've been working on Linux compatibility - apart this issue everything runs flawlessly on Linux on-par with our Windows builds and that's simply awesome!

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes #3783

The vtable for `IUnknown` and its subclasses contain two deletion pointers when compiled on non-Windows systems with `IUnknown` from `WinAdapter.h`:

```cpp
vtable for 'DxcLibrary' @ 0x7ffff7cbc5f8 (subobject @ 0x5555556bb9e0):
[0]: 0x7ffff6a56d40 <DxcLibrary::QueryInterface(_GUID const&, void**)>
[1]: 0x7ffff6a56d20 <DxcLibrary::AddRef()>
[2]: 0x7ffff6a56d30 <DxcLibrary::Release()>
[3]: 0x7ffff6b36bc0 <IUnknown::~IUnknown()> // Complete object destructor
[4]: 0x7ffff6a57130 <DxcLibrary::~DxcLibrary()> // Deleting destructor
[5]: 0x7ffff6a56d50 <DxcLibrary::SetMalloc(IMalloc*)>
[6]: 0x7ffff6a56d60 <DxcLibrary::CreateBlobFromBlob(IDxcBlob*, unsigned int, unsigned int, IDxcBlob**)>
... More DxcLibrary virtual functions
```

This shifts the the pointers for functions for all subclasses, and is [annoying] to deal with in otherwise cross-platform applications using DirectXShaderCompiler as library.  `dxcompiler.dll` compiled on/for
Windows without `WinAdapter.h` does not suffer this problem, and only has three function pointers for `IUnknown`.

Fortunately it is easily solved by removing the virtual destructor from `IUnknown`.  LLVM enables `-Wnon-virtual-dtor` that warns against classes with virtual methods but no virtual destructor, though this
warning is best not enabled akin to Windows builds where `IUnknown` from `windows.h` (`unknwn.h`) results in the same warning on MSVC ([1]/[2]).

[annoying]: https://github.com/Traverse-Research/hassle-rs/blob/1e624792fc3a252ac7788e3c1c5feda52887272f/src/unknown.rs
[1]: https://github.com/microsoft/DirectXShaderCompiler/issues/3783#issuecomment-844189358
[2]: https://godbolt.org/z/hKPT6ThEf

---

Tested on Clang `11.1.0` and GCC `11.1.0`. Unfortunately GCC fails compiling on an irrelevant `-Werror=stringop-truncation` in `SPIRV-Tools`, irrespective of this PR.

On Clang this PR still results in quite a few warnings of the sort:

```cpp
[605/1293] Building CXX object lib/DxcSupport/CMakeFiles/LLVMDxcSupport.dir/WinAdapter.cpp.o
../lib/DxcSupport/WinAdapter.cpp:24:5: warning: delete called on 'IUnknown' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
    delete this;
    ^
1 warning generated.
```
And it seems the same warning is named `-Wdelete-non-virtual-dtor` on GCC - but unfortunately surrounded by hundreds upon hundreds of [these warnings](https://github.com/microsoft/DirectXShaderCompiler/commit/913868b184b0234e0db72a60d308a888deee3393).

---

CC @jenatali; thanks for checking this with me and pointing out the warning on MSVC too!

### CODE REVIEW

**Comment by jenatali** [comment]
Huh. The `IUnknown` implementation should be pure virtual and shouldn't have the `m_count` member. I missed that last time I looked at it. I guess you could theoretically rely on that to implement a Linux-only `IUnknown`-derived class, but anything cross platform would need to define its own count and implement `Release()` on a more-derived class, since Windows defines `IUnknown` as pure-virtual with no virtual destructor.

Removing the implementation of `AddRef` and `Release` from `WinAdapter.cpp` will resolve the `-Wdelete-non-virtual-dtor` error/warning.

**Comment by MarijnS95** [comment]
@jenatali thanks for the insight!

> The `IUnknown` implementation should be pure virtual and shouldn't have the `m_count` member. I missed that last time I looked at it. I guess you could theoretically rely on that to implement a Linux-only `IUnknown`-derived class, but anything cross platform would need to define its own count and implement `Release()` on a more-derived class, since Windows defines `IUnknown` as pure-virtual with no virtual destructor.

I wonder if that's done on purpose, to have an easier time implementing other wrapper structs. Though it seems only `IMalloc` is affected:

```cpp
../lib/DxcSupport/WinFunctions.cpp:158:19: error: allocating an object of abstract class type 'IMalloc'
  *ppMalloc = new IMalloc;
                  ^
../include/dxc/Support/WinAdapter.h:626:17: note: unimplemented pure virtual method 'AddRef' in 'IMalloc'
  virtual ULONG AddRef() = 0;
                ^
../include/dxc/Support/WinAdapter.h:627:17: note: unimplemented pure virtual method 'Release' in 'IMalloc'
  virtual ULONG Release() = 0;
                ^
```

That's simply solved by moving `m_count` to `IMalloc`, see the last commit.

> Removing the implementation of `AddRef` and `Release` from `WinAdapter.cpp` will resolve the `-Wdelete-non-virtual-dtor` error/warning.

<details>
<summary>For completeness this error occurs on all other subclasses that contain virtual methods themselves. Expand this block to see all the errors.</summary>

```cpp
[62/1040] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Process.cpp.o
In file included from ../lib/Support/Process.cpp:78:
../lib/Support/Unix/Process.inc:98:10: warning: 'mallinfo' is deprecated [-Wdeprecated-declarations]
  mi = ::mallinfo();
         ^
/usr/include/malloc.h:118:48: note: 'mallinfo' has been explicitly marked deprecated here
extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
                                               ^
/usr/include/malloc.h:31:30: note: expanded from macro '__MALLOC_DEPRECATED'
# define __MALLOC_DEPRECATED __attribute_deprecated__
                             ^
/usr/include/sys/cdefs.h:261:51: note: expanded from macro '__attribute_deprecated__'
# define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                  ^
1 warning generated.
[530/1040] Building CXX object lib/DxcSupport/CMakeFiles/LLVMDxcSupport.dir/dxcmem.cpp.o
../lib/DxcSupport/dxcmem.cpp:46:55: warning: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [-Wdtor-name]
    g_ThreadMallocTls->llvm::sys::ThreadLocal<IMalloc>::~ThreadLocal();
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                      ::ThreadLocal
1 warning generated.
[532/1040] Building CXX object lib/DxcSupport/CMakeFiles/LLVMDxcSupport.dir/WinAdapter.cpp.o
../lib/DxcSupport/WinAdapter.cpp:31:5: warning: delete called on non-final 'IMalloc' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    delete this;
    ^
1 warning generated.
[602/1040] Building CXX object lib/HLSL/CMakeFiles/LLVMHLSL.dir/HLMatrixLowerPass.cpp.o
../lib/HLSL/HLMatrixLowerPass.cpp:1582:18: warning: unused variable 'ValMatTy' [-Wunused-variable]
    HLMatrixType ValMatTy = HLMatrixType::cast(TrueMat->getType());
                 ^
1 warning generated.
[861/1040] Building CXX object tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGHLSLMSFinishCodeGen.cpp.o
../tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp:164:6: warning: unused function 'IsHLSLBufferViewType' [-Wunused-function]
bool IsHLSLBufferViewType(llvm::Type *Ty) {
     ^
1 warning generated.
[972/1040] Building CXX object tools/clang/tools/libclang/CMakeFiles/libclang.dir/dxcisenseimpl.cpp.o
../tools/clang/tools/libclang/dxcisenseimpl.cpp:584:5: warning: delete called on non-final 'DxcBasicUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    delete newValue;
    ^
1 warning generated.
[991/1040] Building CXX object tools/clang/tools/dxclib/CMakeFiles/dxclib.dir/dxc.cpp.o
../tools/clang/tools/dxclib/dxc.cpp:591:3: warning: delete called on non-final 'DxcIncludeHandlerForInjectedSources' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
  DXC_MICROCOM_ADDREF_RELEASE_IMPL(m_dwRef)
  ^
../include/dxc/Support/microcom.h:90:7: note: expanded from macro 'DXC_MICROCOM_ADDREF_RELEASE_IMPL'
      delete this;                                                             \
      ^
1 warning generated.
[994/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/Objects.cpp.o
In file included from ../tools/clang/unittests/HLSL/Objects.cpp:11:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[995/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/VerifierTest.cpp.o
In file included from ../tools/clang/unittests/HLSL/VerifierTest.cpp:14:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[1003/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/FunctionTest.cpp.o
In file included from ../tools/clang/unittests/HLSL/FunctionTest.cpp:16:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[1006/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/ExtensionTest.cpp.o
In file included from ../tools/clang/unittests/HLSL/ExtensionTest.cpp:10:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
../tools/clang/unittests/HLSL/ExtensionTest.cpp:306:3: warning: delete called on non-final 'TestIntrinsicTable' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
  DXC_MICROCOM_ADDREF_RELEASE_IMPL(m_dwRef)
  ^
../include/dxc/Support/microcom.h:90:7: note: expanded from macro 'DXC_MICROCOM_ADDREF_RELEASE_IMPL'
      delete this;                                                             \
      ^
../tools/clang/unittests/HLSL/ExtensionTest.cpp:406:3: warning: delete called on non-final 'TestSemanticDefineValidator' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
  DXC_MICROCOM_ADDREF_RELEASE_IMPL(m_dwRef)
  ^
../include/dxc/Support/microcom.h:90:7: note: expanded from macro 'DXC_MICROCOM_ADDREF_RELEASE_IMPL'
      delete this;                                                             \
      ^
3 warnings generated.
[1007/1040] Building CXX object tools/clang/unittests/HLSLTestLib/CMakeFiles/HLSLTestLib.dir/DxcTestUtils.cpp.o
In file included from ../tools/clang/unittests/HLSLTestLib/DxcTestUtils.cpp:12:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[1010/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/DXIsenseTest.cpp.o
In file included from ../tools/clang/unittests/HLSL/DXIsenseTest.cpp:12:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[1013/1040] Building CXX object tools/clang/unittests/HLSL/CMakeFiles/clang-hlsl-tests.dir/DxilModuleTest.cpp.o
In file included from ../tools/clang/unittests/HLSL/DxilModuleTest.cpp:10:
../include/dxc/Test/CompilationResult.h:74:22: warning: delete called on non-final 'TrivialDxcUnsavedFile' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    if (result == 0) delete this;
                     ^
1 warning generated.
[1040/1040] Linking CXX executable bin/clang-spirv-tests
```
</details>

**Comment by jenatali** [comment]
> That's simply solved by moving m_count to IMalloc, see the last commit.
Note that `IMalloc` is supposed to be a pure-virtual class as well, since that's also an interface in the SDK: https://docs.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-imalloc

So you'd run into the same problem if you tried to have cross-platform usage of IMalloc. The solution is to make anything which implements `IMalloc` use the same `DXC_MICROCOM_ADDREF_RELEASE_IMPL` as everything else which inherits from `IUnknown` instead of trying to bake this behavior into the interface definition itself.

> all other subclasses
Nah, looks like these are all in tests. I suspect core code suppresses this warning already. There's plenty of classes which inherit from `IUnknown` which don't produce this warning.

**Comment by MarijnS95** [comment]
> Note that `IMalloc` is supposed to be a pure-virtual class as well, since that's also an interface in the SDK: https://docs.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-imalloc

Ah I could have figured :)

> 
> So you'd run into the same problem if you tried to have cross-platform usage of IMalloc. The solution is to make anything which implements `IMalloc` use the same `DXC_MICROCOM_ADDREF_RELEASE_IMPL` as everything else which inherits from `IUnknown` instead of trying to bake this behavior into the interface definition itself.

This is again a default implementation that's only used from `CoGetMalloc`. The `IMalloc` interface has now been converted to pure-virtual, with the default implementation in a local class. Couple observations:

- `DXC_MICROCOM_ADDREF_RELEASE_IMPL` is pretty much providing `m_count` in much the same way, cleaner to use that indeed;
- The implementation still gives off the warning:
  ```cpp
  [546/1039] Building CXX object lib/DxcSupport/CMakeFiles/LLVMDxcSupport.dir/WinFunctions.cpp.o
  ../lib/DxcSupport/WinFunctions.cpp:162:3: warning: delete called on non-final 'CoMalloc' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
  DXC_MICROCOM_ADDREF_RELEASE_IMPL(m_dwRef)
  ^
  ../include/dxc/Support/microcom.h:90:7: note: expanded from macro 'DXC_MICROCOM_ADDREF_RELEASE_IMPL'
      delete this;                                                             \
      ^
  1 warning generated.
  ```
- Should perhaps use a single, static instance just like `struct HeapMalloc`? (`static HeapMalloc g_HeapMalloc;`, `AddRef` and `Release` return `1`). This struct doesn't store anything but passes through to system allocation functions, and could just as well be a static global.
  However, statics don't initialize vtables properly:
  ```cpp
  Program received signal SIGSEGV, Segmentation fault.
  0x00007ffff68b47f5 in DxcInitThreadMalloc () at ../lib/DxcSupport/dxcmem.cpp:32
  32	  g_ThreadMallocTls = (llvm::sys::ThreadLocal<IMalloc>*)g_pDefaultMalloc->Alloc(sizeof(llvm::sys::ThreadLocal<IMalloc>));
  (gdb) bt
  #0  0x00007ffff68b47f5 in DxcInitThreadMalloc () at ../lib/DxcSupport/dxcmem.cpp:32
  #1  0x00007ffff67d2597 in DllMain() () from ./libdxcompiler.so
  ...
  (gdb) p g_pDefaultMalloc
  $1 = (IMalloc *) 0x7ffff7d76c80 <g_CoMalloc>
  (gdb) info vtbl g_pDefaultMalloc
  vtable for 'IMalloc' @ 0x0 (subobject @ 0x7ffff7d76c80):
  [0]: <error: Cannot access memory at address 0x0>
  [1]: <error: Cannot access memory at address 0x8>
  [2]: <error: Cannot access memory at address 0x10>
  [3]: <error: Cannot access memory at address 0x18>
  [4]: <error: Cannot access memory at address 0x20>
  [5]: <error: Cannot access memory at address 0x28>
  [6]: <error: Cannot access memory at address 0x30>
  [7]: <error: Cannot access memory at address 0x38>
  [8]: <error: Cannot access memory at address 0x40>
  ```
  Same applies to `GetGlobalHeapMalloc()` - I guess that codepath is never called?

By the way that documentation shows more functions are available, and that was never caught because implementations like `struct HeapMalloc : public IMalloc` lack the `override` keyword. Fixed that now too just so that our vtables are in-check again.

> > all other subclasses
> 
> Nah, looks like these are all in tests. I suspect core code suppresses this warning already. There's plenty of classes which inherit from `IUnknown` which don't produce this warning.

Not sure why I wrote `all`... Seems there's only one, for `DxcIncludeHandlerForInjectedSources` outside of tests.

Final nit, looks like the API in WinAdapter isn't using `STDMETHODCALLTYPE`/`STDMETHODIMP` like the rest. The former is defined to nothing so it doesn't make a difference, but might be more consistent to use.

**Comment by jaebaek** [comment]
Thank you for this change!
I am excited this will fix the virtual table issue.
I tried to fix the build failure on Linux with the clang++. Please let me know if the change I made is wrong!

File: lib/DxcSupport/dxcmem.cpp [hunk 1]
```diff
@@ -43,7 +43,7 @@ HRESULT DxcInitThreadMalloc() throw() {
 void DxcCleanupThreadMalloc() throw() {
   if (g_ThreadMallocTls) {
     DXASSERT(g_pDefaultMalloc, "else DxcInitThreadMalloc didn't work/fail atomically");
-    g_ThreadMallocTls->llvm::sys::ThreadLocal<IMalloc>::~ThreadLocal();
+    g_ThreadMallocTls->llvm::sys::ThreadLocal<IMalloc>::~ThreadLocal<IMalloc>();
```
Comment (MarijnS95) [inline lib/DxcSupport/dxcmem.cpp:46]: @jaebaek This warning shows up on master regardless, and has been fixed by removing the `ThreadLocal` classification entirely in https://github.com/microsoft/DirectXShaderCompiler/pull/3794/commits/43d09822e571b8d8d56c8d0ed20f8906f63268bf. Inclined to remove it from this PR, do you think that PR should use the full `llvm::sys::ThreadLocal<IMalloc>::~ThreadLocal<IMalloc>` name instead?

**Comment by MarijnS95** [comment]
> Thank you for this change!
> I am excited this will fix the virtual table issue.

Yes it's going to be awesome and we can finally drop our hacks! Unfortunately this means the applications we're using `libdxcompiler.so` in are not backwards- nor forwards-compatible (on Linux), but that's a problem of our own creation for [allowing said hack](https://github.com/Traverse-Research/hassle-rs/blob/1e624792fc3a252ac7788e3c1c5feda52887272f/src/unknown.rs) in the first place instead of fixing it in here straight away :grinning: 

> I tried to fix the build failure on Linux with the clang++. Please let me know if the change I made is wrong!

Thanks! Yes `final` was the next stop to fix this issue, including the removal of `final`. I've adopted your change and fixed the `CComPtr<DxcIncludeHandlerForInjectedSources>` -> `CComPtr<IDxcIncludeHandler>` so that the windows build should succeed now too. The empty destructors have been removed, those should not be necessary (and had inconsistent formatting).

Finally, `HeapMalloc` has been marked as `final` as well, even though it doesn't show up in the warnings (there might be more such classes?).
Any comment on the VTable issue though? `GetGlobalHeapMalloc()` returns garbage, but it might be fine because this is never called? See https://github.com/MarijnS95/DirectXShaderCompiler/compare/static-global for turning `CoMalloc` into a `const static` like `HeapMalloc` and showing the `vtable` issue on both.

File: lib/DxcSupport/dxcmem.cpp (hunk 1 above)
Comment (jaebaek) [reply lib/DxcSupport/dxcmem.cpp]: Oh, I did not know you prepared another commit for it. With clang on Linux, `g_ThreadMallocTls->~ThreadLocal()` also works fine.

**Comment by MarijnS95** [comment]
> called? See [MarijnS95/DirectXShaderCompiler@winadapter-iunknown-no-virtual-dtor...static-global](https://github.com/MarijnS95/DirectXShaderCompiler/compare/winadapter-iunknown-no-virtual-dtor...static-global) for turning `CoMalloc` into a `static` global like `HeapMalloc` and showing the `vtable` issue on both.

I've hack-fixed this by running placement-new (which is fine to run unconditionally because the classes don't contain any other data) but now we're crashing elsewhere. To be continued :)

**Comment by jaebaek** [comment]
Nice :) I do not have any specific comment for now. I just thought using `final` might be not a good solution because of `CComPtr`. I prepared another commit to avoid the error with `virtual` dtor but I am not sure it is a good solution either :sweat_smile: (and it seems you already fixed the issue about `CComPtr`)

I attach the one with `virtual` dtor: [diff.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6537501/diff.txt). I will just follow your decision about it.

I want to check my other projects with this change. I am just curious previous issues I met was this issue or not.

Thanks! :+1:

**Comment by MarijnS95** [comment]
> Nice :) I do not have any specific comment for now.

Not sure if you noticed the ninja-edit, but it's "fixed" now with placement-new, let me know if that's an acceptable change (I'll add a comment on the placement-new). It's more concise to keep these stateless instances as `static` globals, but for that they have to work in the first place. Any idea if `HeapMalloc` through `GetGlobalHeapMalloc` is used anywhere, because `Alloc` crashes on it (after fixing the vtable)?

> I just thought using `final` might be not a good solution because of `CComPtr`. I prepared another commit to avoid the error with `virtual` dtor but I am not sure it is a good solution either  (and it seems you already fixed the issue about `CComPtr`)
> 
> I attach the one with `virtual` dtor: [diff.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6537501/diff.txt). I will just follow your decision about it.

Oh yeah, it looks like this was one odd case where the class type instead of the (pure virtual) interface was used in `CComPtr<>` - I don't see that anywhere else in the code, everything uses `CComPtr<I...>`. The CI should succeed now, awaiting in suspense (someone please put a ThreadRipper in AppVeyor :joy:). Looks like we can keep it simple without extra virtual dtors :+1:

**Comment by MarijnS95** [comment]
Oh yikes, the explicit type was used on purpose to access `DxcIncludeHandlerForInjectedSources::insertIncludeFile`. Not sure what the best fix is, I don't want to add virtual dtors and remove `final` just to satisfy some weird `CComPtr`/`ATL` behaviour that I have yet to fully understand. Added an extra unmanaged pointer with the right type for now, alternatively we can cast in the call too.

**Comment by jaebaek** [comment]
I am not versed on the code base of this change in terms of the purpose of classes. I am afraid that I am not a right person to make a decision for the direction of changes here. If there are no other issues, fixing the vtable issue with working code looks good to me.

Let's wait @jenatali 's code review

**Comment by MarijnS95** [comment]
@jaebaek Thanks for the review and suggestions thus far anyway! If anything I'll submit the conversion to a `static` global (singleton) in a separate PR together with the vtable-pointer fix (for `HeapMalloc`) so that we can have a better discussion there; let's first get the dtor here out of the way :grin: 

(Assuming it is okay to have `CoMalloc` as a refcounted but stateless object for the time being - it already was before, anyway)

**Comment by MarijnS95** [comment]
@pow2clk thanks for self-requesting a review; is this something you can look at? It'd be nice to get this finalized before I completely forget all the implementation details, and it'll take a few coordinated downstream changes, too.

**Comment by MarijnS95** [comment]
@pow2clk Is this something you can review? I understand this is not of highest priority but it's been almost three months since you self-requested a review. I'd like to get this in so that we don't have to spread Linux-specific hacks around any longer; it's only making the migration back worse over time.

@jenatali Do you have any more comments that could further this PR?

**Comment by MarijnS95** [comment]
@pow2clk Would it help review if this PR is split up? That is, remove everything _but_ the first commit that actually addresses #3783, and submit the other patches separately for improved definitions of pure-virtual interfaces?

**Review by pow2clk — COMMENTED** [review]
First of all, mea culpa.

Because of miscommunication and missed communication, this change languished to an extent that embarrasses me greatly. I hope that this mistake won't discourage future contributions as it is far from how we want to treat outside contributions.

I tested this change against #3888, which added a lot of new (or revived) Linux testing. Unfortunately, it also reintroduces a file that needs attention to work with this change. CompilerTest.cpp contains `TestIncludeHandler`, which will need to be marked `final`.

**Comment by MarijnS95** [comment]
@pow2clk Thanks a lot for tackling more Linux issues and extended testing! I'll get right to rebasing this on top of #3888 / `main` and resolving the remaining issue :+1:!

**Comment by MarijnS95** [comment]
@pow2clk Things got a bit mixed up and lost in the comments above, but as a followup do you think looking into these are useful:

- Convert `CoMalloc` to a static singleton just like `HeapMalloc` - requires placement new to initialize the vtable?
- `GetGlobalHeapMalloc` currently returns such a static singleton that has an uninitialized vtable;
- Calling `GetGlobalHeapMalloc()->Alloc` for testing (it doesn't appear to be used otherwise) segfaults deep in `std::map<...>::operator[]`.

**Comment by MarijnS95** [comment]
https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=895&view=logs&j=24c9fe99-3b1b-58cc-6a06-beff22cc45c7&t=21badf4d-2659-5245-8ca3-8874367569d5&l=1852 it looks like we need to come up with the same pointer duplication as https://github.com/microsoft/DirectXShaderCompiler/pull/3793/files#diff-ff426fac7f90d369f6c137698730989cf30ad094c6b1c37e5978563cf82f06ebR710-R711 so that the pure-virtual interface can be used inside `CComPtr`, to fix https://github.com/microsoft/DirectXShaderCompiler/pull/3793#issuecomment-847679213 :(

Is there something better we can do here to fix this?

File: include/dxc/Test/CompilationResult.h [hunk 2]
```diff
@@ -49,7 +49,7 @@ inline HRESULT GetFirstChildFromCursor(IDxcCursor *cursor,
   return hr;
 }
 
-class TrivialDxcUnsavedFile : IDxcUnsavedFile
+class TrivialDxcUnsavedFile final : IDxcUnsavedFile
```
Comment (pow2clk) [inline include/dxc/Test/CompilationResult.h:52]: We'd like these final keywords removed since they aren't necessary with the explicit destructor calls.

File: tools/clang/tools/dxclib/dxc.cpp [hunk 3]
```diff
@@ -707,15 +707,16 @@ void DxcContext::Recompile(IDxcBlob *pSource, IDxcLibrary *pLibrary,
   IFT(pPdbUtils->GetEntryPoint(&pEntryPoint));
 
   CComPtr<IDxcBlobEncoding> pCompileSource;
-  CComPtr<DxcIncludeHandlerForInjectedSources> pIncludeHandler = new DxcIncludeHandlerForInjectedSources();
+  DxcIncludeHandlerForInjectedSources *pIncludeHandlerForInjectedSources = new DxcIncludeHandlerForInjectedSources();
+  CComPtr<IDxcIncludeHandler> pIncludeHandler = pIncludeHandlerForInjectedSources;
```
Comment (pow2clk) [inline tools/clang/tools/dxclib/dxc.cpp:711]: With the removal of the "final" keyword, this shouldn't be needed anymore, but as an aside, this is the solution I came up with for the TestIncludeHandler CComPtr problem as well.

**Review by pow2clk — COMMENTED** [review]
We discussed this internally and I thought about it some more and came up with basically two options:
* Effectively disable the warnings about the possibility of bad destructor calls due to not being virtual
* Make every final descendent from IUnknown final.

The first is simple to implement and maintain, but does carry some risk of undetected programmer mistakes.

The second is probably "right". In that it forces people to either make final classes or add virtual destructors. However, it is cumbersome and represents a retraction of capabilities as there are users out there who have created descendants from our classes and would have to change how they use them. Incidentally, you are only supposed to create CComPtrs with interface types, but DXC, D3D and pretty much every else seems to violate this rampantly 😅

As such, I'm asking that the additions of finals to leaf node classes be removed along with the workarounds that they necessitated and that the Release() implementation in DXC_MICROCOM_ADDREF_RELEASE_IMPL be modified to be more in line with the "TM" variant. This has the effect of disabling the warnings only where we want exceptions with IUnknown descended classes.

Since it's a bit hard to communicate all this in the abstract, I created a commit that includes my suggestions plus a few other additions that you can draw from or incorporate directly if you choose: https://github.com/pow2clk/DirectXShaderCompiler/commit/ea34d7095419b97e69049b95b77657507df71ef2

edit: corrected commit

File: cmake/modules/HandleLLVMOptions.cmake [hunk 4]
```diff
@@ -395,19 +395,31 @@ elseif( LLVM_COMPILER_IS_GCC_COMPATIBLE )
...
+    # set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} -std=c++11 -Werror=non-virtual-dtor")
+    # CHECK_CXX_SOURCE_COMPILES("class base {public: virtual void anchor();protected: ~base();};
+    #                            class derived final : public base { public: ~derived();};
+    #                            int main() { return 0; }"
+    #                           CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR)
+    # set(CMAKE_REQUIRED_FLAGS ${OLD_CMAKE_REQUIRED_FLAGS})
+    # append_if(CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
+    #           "-Wnon-virtual-dtor" CMAKE_CXX_FLAGS)
+
+    # HLSL Change Ends
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply cmake/modules/HandleLLVMOptions.cmake:422]: We'd effectively have to inline-disable the warning every time a pure virtual interface is defined it seems. I guess the main point for this was because MSVC doesn't warn on this either.

File: include/dxc/Support/microcom.h [hunk 5]
```diff
@@ -101,7 +101,7 @@ inline T *CreateOnMalloc(IMalloc * pMalloc, Args&&... args) {
 
 template<typename T>
 void DxcCallDestructor(T *obj) {
-  obj->~T();
+  obj->T::~T();
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/microcom.h:104]: Disabling that warning in this way would have been fine with the `final` notion, but theoretically it should be possible to have subclasses of subclasses with virtual destructors beyond that [^1]? This would then call the wrong destructor, though it wasn't removed in your commit?

For my understanding, as this has all been long ago and I don't write a lot of C++: calling `operator delete(this)` directly is different in that it doesn't perform a virtual dispatch to any of the destructor operators (since that's done already by `DxcCallDestructor`) but merely frees the memory allocated by `new`?

[^1]: As long as it isn't intermixed with the pure-virtual interfaces that would otherwise get a skewed vtable.

[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/microcom.h:104]: Perhaps this is fine after all, given that:

- COM objects should only be freed through the `Release` virtual function;
- Hence, every descendant should override it;
- Which will call the "lowest" destructor through `DxcCallDestructor`: it's known statically here as `T`, hence doesn't need to be virtual.

File: tools/clang/tools/libclang/dxcisenseimpl.cpp [hunk 6]
```diff
@@ -581,7 +581,9 @@ HRESULT DxcBasicUnsavedFile::Create(
   HRESULT hr = newValue->Initialize(fileName, contents, contentLength);
   if (FAILED(hr))
   {
-    delete newValue;
+    CComPtr<IMalloc> pTmp(newValue->m_pMalloc);
+    newValue->DxcBasicUnsavedFile::~DxcBasicUnsavedFile();
+    pTmp->Free(newValue);
```
Comment (MarijnS95) [inline tools/clang/tools/libclang/dxcisenseimpl.cpp:586]: @pow2clck what'd happen if we just call `newValue->Release()` here? Same for `InternalDxcBlobEncoding_Impl`/`MemoryStream` above that had to get the `->T::~T` "fix" to get rid of the warning.

Comment (MarijnS95) [reply tools/clang/tools/libclang/dxcisenseimpl.cpp:586]: Oh that's not entirely correct: Those two types have their code located in `Release()` already, and the code here also uses `IMalloc`. The only thing all three have in common: they use `IMalloc` (ie. not suitable for `DXC_MICROCOM_ADDREF_RELEASE_IMPL`) yet don't use `DxcThreadMalloc` (ie. not suitable for `DXC_MICROCOM_TM_ADDREF_RELEASE_IMPL` either).

**Comment by MarijnS95** [comment]
@pow2clk This is once again rebased on `master` and tested to work as intended. Your recommended/requested changes have been pulled in directly, anything else that needs to be done? I don't want this to sit yet another ~8 months :sweat_smile:

**Comment by MarijnS95** [comment]
@pow2clk It seems the CI still succeeds after a merge with master... 2 months later :slightly_smiling_face:

**Review by pow2clk — APPROVED** [review]
A much-delayed approval. Sorry again :(

**Comment by MarijnS95** [comment]
@pow2clk thank you so much, after 1.5 years this is finally allowing me to drop some hacks in downstream wrapper projects :+1:
