### PR TITLE
[SPIRV] Handle bit fields with initializer lists

### LINKED ISSUE #5688: [SPIR-V] Crash on brace initialization of struct with bitfields
**Description**
dxc allows uniform initialization syntax for structs containing bitfields but crashes when invoked with -spirv.

**Steps to Reproduce**

https://godbolt.org/z/9vPeM38a3
```hlsl
// dxc -spirv -T cs_6_4 -HV 2021 -E main

struct ColorRGBA {
  uint R:8;
  uint G:8;
  uint B:8;
  uint A:8;
};

RWStructuredBuffer<uint> buf : r0;

[numthreads(1,1,1)]
void main()
{
    
    ColorRGBA c = {127, 127, 127, 0};
    buf[0] = c.A;
}
```
**Actual Behavior**
Internal compiler error: LLVM Assert

**Environment**
- DXC version 1.7 - 1.7.0.14081 (main, 9cb80b6cc)
- Windows 10 Pro (21H2)

### PR DESCRIPTION
**Pull request by s-perron**
The spir-v backend currently treats each bitfield as a separate member
in the spir-v type when processing an initializer list. This commit
changes that so that it matches the behaviour of the DXIL backend.

In particular, if `{bf1, bf2}` is used to initialize a struct with two
bitfield, then `bf1` and bf2` will be merged into a single field when
constructing the struct.

Fixes #5688

### CODE REVIEW

**Review by sudonatalie — APPROVED** [review]

File: tools/clang/lib/SPIRV/InitListHandler.cpp [hunk 1]
```diff
@@ -399,39 +400,52 @@ InitListHandler::createInitForStructType(QualType type, SourceLocation srcLoc,
...
-  }
+  LowerTypeVisitor lowerTypeVisitor(astContext, theEmitter.getSpirvContext(),
+                                    theEmitter.getSpirvOptions());
+  const SpirvType *spirvType =
+      lowerTypeVisitor.lowerType(type, SpirvLayoutRule::Void, false, srcLoc);
 
-  // TODO: use OpConstantComposite when all components are constants
+  llvm::SmallVector<SpirvInstruction *, 4> fields;
+  forEachSpirvField(
+      recordType, dyn_cast<StructType>(spirvType),
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/InitListHandler.cpp:413]: Should you assert that this dyn_cast is not nullptr?

**Review by cassiebeckley — APPROVED** [review]

File: tools/clang/lib/SPIRV/InitListHandler.cpp (hunk 1 above)
Comment (s-perron) [reply tools/clang/lib/SPIRV/InitListHandler.cpp]: done
