### PR TITLE
Require complete types in some missing places

### LINKED ISSUE #7510: Segfault when calling `sizeof()` on templated type
**Description**

We just upgraded to the [latest May 2025 release](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.8.2505), from a previous [self-compiled build](https://github.com/Traverse-Research/dxc-build/commit/555c603cb7c2680493d144dac111740bc921ec33) at 47e11af022d4ed41ac87348f822ea8804b55523a. One of our shaders triggers a `SIGSEGV` right inside DXC. This seems to be caused by calling `sizeof()` on a templated type, regardless of what the struct contains. It doesn't seem to need to use `T` in any capacity for this to trigger.

**Steps to Reproduce**

https://godbolt.org/z/hnfd5EEGY (DXC on `trunk`, this doesn't have an explicit tagged `1.8.2505` release just yet)

```hlsl
template<typename T> struct Encoded{
    // uint x;
    // T y;
};

[numthreads(8, 8, 1)]
void main(uint2 tid : SV_DispatchThreadID) {
    uint s = sizeof(Encoded<int>);
}
```

It doesn't matter if we compile to DXIL or SPIR-V.

**Environment**
- DXC version: `v1.8.2505` (using the library)
- Host Operating System: Windows, MacOS (Linux untested, but likely to fail as well)

Given that we have a known-working commit, bisection should only contain these 51 commits:

https://github.com/microsoft/DirectXShaderCompiler/compare/47e11af022d4ed41ac87348f822ea8804b55523a...v1.8.2505

### PR DESCRIPTION
**Pull request by llvm-beanz**
This change adds two additional calls to Sema::RequireCompleteType, one when evaluating unary `sizeof`, which fixes a reported issue with templates. The second is in the DXR diagnostics where complete type should be required but not diagnosed because ordering in the compiler is a bit wonky when diagnosing DXR entry points.

Fixes #7510

### CODE REVIEW

**Review by tex3d — APPROVED** [review]
Thanks Chris!

File: tools/clang/lib/Sema/SemaDXR.cpp [hunk 1]
```diff
@@ -1232,6 +1232,11 @@ void DiagnoseMissOrAnyHitEntry(Sema &S, FunctionDecl *FD,
 
     QualType Ty = Param->getType().getNonReferenceType();
 
+    // Don't diagnose here, just continue if this fails. Function parameters are
+    // checked in Sema::CheckParmsForFunctionDef.
+    if (S.RequireCompleteType(Param->getLocation(), Ty, 0))
```
Comment (tex3d) [inline tools/clang/lib/Sema/SemaDXR.cpp:1240]: Oh, I think we also need this inside `DiagnoseClosestHitEntry` and `DiagnoseCallableEntry` as well.

Ultimately, I think we are calling `DiagnoseEntry` too early - I think it should be called during `DiagnoseTranslationUnit` instead.  If we did that, we wouldn't get here if these parameters couldn't be completed, since `CheckParmsForFunctionDef` would happen earlier during parsing, and any error during parse would prevent `DiagnoseTranslationUnit`.  That change would be more disruptive to tests though.

Comment (tex3d) [reply tools/clang/lib/Sema/SemaDXR.cpp:1240]: I added more checks and tests that I found were missing to this branch.

File: tools/clang/test/SemaHLSL/sizeof-requires-complete-type.hlsl [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  // It may be incomplete because there is only a forward declaration, which
+  // should produce an error since we can't materialize a definition.
+  s = sizeof(Incomplete); // expected-error{{invalid application of 'sizeof' to an incomplete type 'Incomplete'}}
+
+  // It may be incomplete because it is an un-instantiated template, which
+  // should work because we can just instantiate it.
+  s = sizeof(CompleteTemplate<int>); // This works!
+
+  // It may be incomplete because it is a lazy-initialized type from HLSL, which
+  // should work because we can just complete it.
```
Comment (tex3d) [inline tools/clang/test/SemaHLSL/sizeof-requires-complete-type.hlsl]: By the way, RayDesc is already a complete type.  If you use `Buffer` instead, you have a lazy-initialized type that can be completed, then correctly reports the error for non-numeric type.

Comment (tex3d) [reply tools/clang/test/SemaHLSL/sizeof-requires-complete-type.hlsl]: I pushed a change to use Buffer instead.

**Comment by llvm-beanz** [comment]
@tex3d's additions look good to me. I can't approve since I'm the original author.

**Comment by tex3d** [comment]
> It looks sensible to me. The overall question I have is how do we determine where this is needed? Is it anywhere we check a type in Sema? Is there not somewhere we can insert this once and for all? I added a lot of these as part of the longvector diagnostics

Yeah, it's a bit more complicated than that.  While it would seem convenient to call `RequireCompleteType` from `IsHLSLCopyableAnnotatableRecord`, the code that's calling this may need to handle an incomplete type scenario differently than a failing `IsHLSLCopyableAnnotatableRecord` call.  Plus, some code paths should be able to assume the type is completed already, otherwise something else is wrong.  For instance, there's a code path that uses `IsHLSLCopyableAnnotatableRecord` for a call argument type (payload) during `DiagnoseTranslationUnit`, where there should definitely not be an incomplete type, and if there was, this is not the right time to complete it, so it will hit the assert instead of blindly trying to complete the type now.
