### PR TITLE
[SPIR-V] Emulate OpBitFieldExtract for type != i32

### LINKED ISSUE #6327: [SPIR-V] Fatal error with validation on using bitfield uint64_t
**Description**

When using a shader with bitfield structs and uint64_t, getting invalid SPIR-V and failing.

**Steps to Reproduce**

For example, when using the following struct:
```hlsl
struct TransferRequest
{
    // This represents a transfer command/request
    uint64_t srcAddr;
    uint64_t dstAddr;
    uint64_t srcIndexAddr; // IOTA default
    uint64_t dstIndexAddr; // IOTA default
    uint64_t elementCount : 35; // allow up to 64GB IGPUBuffers
    uint64_t propertySize : 24; // all the leftover bits (just use bytes now)
    uint64_t fill;
    // 0=uint8, 1=uint16, 2=uint32, 3=uint64
    uint64_t srcIndexSizeLog2 : 2;
    uint64_t dstIndexSizeLog2 : 2;
};
```
And trying to set values to it.

(Error happens on this shader code: https://github.com/Devsh-Graphics-Programming/Nabla/tree/adc4d576d034b3e1fb31356645c0a0915beee817/include/nbl/builtin/hlsl/property_pool)

**Actual Behavior**
Invalid SPIR-V causing fatal error on validation.
```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-Base-04781] Expected 32-bit int type for Base operand: BitFieldInsert
%58 = OpBitFieldInsert %ulong %42 %57 %uint_0 %uint_35
```

**Environment**
- DXC version: From commit 7d2f9c74d53dcbb9de4e148b68c99e5986875be6 
- Host Operating System: Windows 11 version 22H2 build 22621.3155

### PR DESCRIPTION
**Pull request by Keenuts**
This is a follow up to #6491 which adds emulation for OpBitField*Extract
This is required because Vulkan requires OpBitField*Extract operands to
be 32-bit integers.

Fixes #6327

### CODE REVIEW

**Comment by Keenuts** [comment]
Applied the same feedback as the related PR, and also fixed an issue with signed bitfields.
Ready for review!

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp [hunk 1]
```diff
@@ -980,12 +974,70 @@ SpirvBuilder::createBitFieldInsert(QualType resultType, SpirvInstruction *base,
...
+    auto baseType = dyn_cast<IntegerType>(base->getResultType());
+    leftShift->setResultType(baseType);
+    rightShift->setResultType(baseType);
+  }
+
+  return rightShift;
+}
+
+SpirvInstruction *SpirvBuilder::createBitFieldExtract(
+    QualType resultType, SpirvInstruction *Src, unsigned bitOffset,
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvBuilder.cpp:1018]: nit: s/Src/base

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp [hunk 2]
```diff
@@ -980,12 +974,70 @@ SpirvBuilder::createBitFieldInsert(QualType resultType, SpirvInstruction *base,
   return inst;
 }
 
-SpirvBitFieldExtract *SpirvBuilder::createBitFieldExtract(
-    QualType resultType, SpirvInstruction *base, SpirvInstruction *offset,
-    SpirvInstruction *count, bool isSigned, SourceLocation loc) {
+SpirvInstruction *SpirvBuilder::createEmulatedBitFieldExtract(
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvBuilder.cpp:977]: Do we need to emulate `OpBitFieldUExtract` differently when `isSigned = false`?

**Review by sudonatalie — COMMENTED** [review]
Can you update the PR description for OpBitFieldExtract?

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp (hunk 1 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:1018]: ah yes, thanks

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp (hunk 2 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:977]: I don't think so:
If the type was unsigned, we wouldn't have to do sign extension, to masking could be enough. But this requires also 2 instructions (shift + masking).
Since using 2 shifts should yield the same result, I think both can use this method.

(Changed the instruction from ShiftRightLogical to ShiftRightArithmetic, as the second does sign-extension when required vs the first)

Comment (sudonatalie) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:977]: Sorry, I wasn't very clear. I meant that the `createBitFieldExtract` function has a distinct `isSigned` parameter, and for non-emulated versions, we determine whether or not to do sign extension based on its value, but for the emulated version, it's now based on the signedness of `base`.

If we know those are equivalent for all the existing usages, we should remove the `isSigned` param because it's now a misleading interface. If we're not certain, then we should pass `isSigned` onto `createEmulatedBitFieldExtract` and use it there too.

Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:975]: Right, got it.
I checked, and it is invalid to have the resultType != baseType on OpBitFieldExtract instructions. This means we can use the AST result type to get the `isSigned`, and there is no risk of mismatch.
Cleanup those.

**Review by sudonatalie — APPROVED** [review]
Thanks for the updates, LGTM!

**Review by cassiebeckley — APPROVED** [review]
