### PR TITLE
[Sema] Check FunctionDecl has identifier before getName.

### LINKED ISSUE #6426: Regression, SIGSEGV instead of diagnostics when encountering bool operator==(const T&, const T&)
Description
SIGSEGV instead of diagnostics when encountering `bool operator==(const T&, const T&)`

Steps to reproduce:
Godbolt link: https://godbolt.org/z/5hsxeK5aE

### PR DESCRIPTION
**Pull request by python3kgae**
Use identifier name without check the identifier exists will cause crash.

Fixes #6426

### CODE REVIEW

**Comment by bob80905** [comment]
For your test case, I would think only one function declaration is needed. Is it possible to get rid of the rest of them?

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -15690,7 +15690,7 @@ void TryAddShaderAttrFromTargetProfile(Sema &S, FunctionDecl *FD,
 
   // if this FD isn't the entry point, then we shouldn't add
   // a shader attribute to this decl, so just return
-  if (EntryPointName != FD->getIdentifier()->getName()) {
+  if (FD->getIdentifier() && EntryPointName != FD->getIdentifier()->getName()) {
```
Comment (tex3d) [inline tools/clang/lib/Sema/SemaHLSL.cpp:15693]: I don't think this is right.  We should return if there is no identifier as well, since it can't be an entry point.

```suggestion
    if (!FD->getIdentifier() || EntryPointName != FD->getIdentifier()->getName()) {
```

**Review by llvm-beanz — APPROVED** [review]

**Review by tex3d — APPROVED** [review]
LGTM.
