### PR TITLE
Fix HLMatrixLowerPass leaving call to dangling FunctionVal

### LINKED ISSUE #6423: ASAN heap-use-after-free during GlobalDCE due to HLMatrixLowerPass leaving a dangling FunctionVal in the Module
We hit an asan failure with a very simple compute shader:

```cpp
float4x2 foo() {
  while (true) {
  }
  return float4x2((0.0f).xx, (0.0f).xx, (0.0f).xx, (0.0f).xx);
}

[numthreads(1, 1, 1)]
void main() {
  float4x2 _e1 = foo();
}
```
Compiler Explorer link: https://godbolt.org/z/bK3EEs8bn

Note that we have an infinite loop in `foo`, followed by the return of a matrix.

ASAN fails with this error:

```
=================================================================
==66244==ERROR: AddressSanitizer: heap-use-after-free on address 0x11a0c24a4a30 at pc 0x7ffbf02fa225 bp 0x0040525ce2e0 sp 0x0040525ce328
READ of size 1 at 0x11a0c24a4a30 thread T0
    #0 0x7ffbf02fa224 in llvm::Value::getValueID C:\src\dawn\third_party\dxc\include\llvm\IR\Value.h:374
    #1 0x7ffbf02fa224 in llvm::isa_impl<llvm::GlobalVariable,llvm::Value,void>::doit C:\src\dawn\third_party\dxc\include\llvm\IR\Value.h:692
    #2 0x7ffbf02fa224 in llvm::isa_impl_cl<llvm::GlobalVariable,const llvm::Value>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:76
    #3 0x7ffbf02fa224 in llvm::isa_impl_wrap<llvm::GlobalVariable,const llvm::Value,const llvm::Value>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:123
    #4 0x7ffbf02fa224 in llvm::isa C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:134
    #5 0x7ffbf02fa224 in llvm::isa_impl<llvm::GlobalObject,llvm::Value,void>::doit C:\src\dawn\third_party\dxc\include\llvm\IR\Value.h:710
    #6 0x7ffbf02fa224 in llvm::isa_impl_cl<llvm::GlobalObject,const llvm::Value>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:76
    #7 0x7ffbf02fa224 in llvm::isa_impl_wrap<llvm::GlobalObject,const llvm::Value,const llvm::Value>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:123
    #8 0x7ffbf02fa224 in llvm::isa C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:134
    #9 0x7ffbf02fa224 in llvm::isa_impl<llvm::GlobalValue,llvm::Value,void>::doit C:\src\dawn\third_party\dxc\include\llvm\IR\Value.h:704
    #10 0x7ffbf02fa224 in llvm::isa_impl_cl<llvm::GlobalValue,llvm::Value *>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:83
    #11 0x7ffbf02fa224 in llvm::isa_impl_wrap<llvm::GlobalValue,llvm::Value *,llvm::Value *>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:123
    #12 0x7ffbf02fa224 in llvm::isa_impl_wrap<llvm::GlobalValue,const llvm::Use,llvm::Value *>::doit C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:113
    #13 0x7ffbf02fa224 in llvm::isa C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:134
    #14 0x7ffbf02fa224 in llvm::dyn_cast C:\src\dawn\third_party\dxc\include\llvm\Support\Casting.h:294
    #15 0x7ffbf02fa224 in `anonymous namespace'::GlobalDCE::GlobalIsNeeded C:\src\dawn\third_party\dxc\lib\Transforms\IPO\GlobalDCE.cpp:244:33
    #16 0x7ffbf02f8ff0 in `anonymous namespace'::GlobalDCE::runOnModule C:\src\dawn\third_party\dxc\lib\Transforms\IPO\GlobalDCE.cpp:100:9
    #17 0x7ffbef6fd64d in `anonymous namespace'::MPPassManager::runOnModule C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1669
    #18 0x7ffbef6fd64d in llvm::legacy::PassManagerImpl::run(class llvm::Module &) C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1771:44
    #19 0x7ffbef704e3b in `anonymous namespace'::EmitAssemblyHelper::EmitAssembly C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:756
    #20 0x7ffbef704e3b in clang::EmitBackendOutput(class clang::DiagnosticsEngine &, class clang::CodeGenOptions const &, class clang::TargetOptions const &, class clang::LangOptions const &, class llvm::StringRef, class llvm::Module *, enum clang::BackendAction, class llvm::raw_pwrite_stream *) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:779:15
    #21 0x7ffbef282a1e in clang::BackendConsumer::HandleTranslationUnit(class clang::ASTContext &) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:191:7
    #22 0x7ffbef7e1c39 in clang::ParseAST(class clang::Sema &, bool, bool) C:\src\dawn\third_party\dxc\tools\clang\lib\Parse\ParseAST.cpp:164:13
    #23 0x7ffbef27cb8b in clang::CodeGenAction::ExecuteAction(void) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:807:28
    #24 0x7ffbef28b083 in clang::FrontendAction::Execute(void) C:\src\dawn\third_party\dxc\tools\clang\lib\Frontend\FrontendAction.cpp:455:8
    #25 0x7ffbef1b8bfb in DxcCompiler::Compile(struct DxcBuffer const *, wchar_t const **, unsigned int, struct IDxcIncludeHandler *, struct _GUID const &, void **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:982:18
    #26 0x7ffbef1aea2e in hlsl::DxcCompilerAdapter::WrapCompile(int, struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1845:5
    #27 0x7ffbef1b17c9 in hlsl::DxcCompilerAdapter::CompileWithDebug(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1748:10
    #28 0x7ffbef1c2f7b in hlsl::DxcCompilerAdapter::Compile(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompileradapter.h:75:12
    #29 0x7ff7a7a2f321 in DxcContext::Compile(void) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:873:9
    #30 0x7ff7a7a39aa6 in dxc::main(int, wchar_t const **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:1501:24
    #31 0x7ff7a7b00adb in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
    #32 0x7ff7a7b00adb in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #33 0x7ffc7b777343  (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #34 0x7ffc7c1026b0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

0x11a0c24a4a30 is located 48 bytes inside of 200-byte region [0x11a0c24a4a00,0x11a0c24a4ac8)
freed by thread T0 here:
    #0 0x7ff7a7ab6c6d in free C:\b\s\w\ir\cache\builder\src\third_party\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:82
    #1 0x7ffbf00b02cf in llvm::Function::`scalar deleting dtor'(unsigned int) C:\src\dawn\third_party\dxc\lib\IR\Function.cpp:275:23
    #2 0x7ffbef4ca5f1 in llvm::ilist_node_traits<llvm::Function>::deleteNode C:\src\dawn\third_party\dxc\include\llvm\ADT\ilist.h:113
    #3 0x7ffbef4ca5f1 in llvm::iplist<class llvm::Function, struct llvm::ilist_traits<class llvm::Function>>::erase(class llvm::ilist_iterator<class llvm::Function>) C:\src\dawn\third_party\dxc\include\llvm\ADT\ilist.h:479:5
    #4 0x7ffbf00a7f33 in llvm::Function::eraseFromParent(void) C:\src\dawn\third_party\dxc\lib\IR\Function.cpp:244:34
    #5 0x7ffbf03f44ac in `anonymous namespace'::TempOverloadPool::clear C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:102
    #6 0x7ffbf03f44ac in `anonymous namespace'::TempOverloadPool::~TempOverloadPool C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:63:25
    #7 0x7ffbf03f3951 in `anonymous namespace'::HLMatrixLowerPass::runOnModule C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:258:1
    #8 0x7ffbef6fd64d in `anonymous namespace'::MPPassManager::runOnModule C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1669
    #9 0x7ffbef6fd64d in llvm::legacy::PassManagerImpl::run(class llvm::Module &) C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1771:44
    #10 0x7ffbef704e3b in `anonymous namespace'::EmitAssemblyHelper::EmitAssembly C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:756
    #11 0x7ffbef704e3b in clang::EmitBackendOutput(class clang::DiagnosticsEngine &, class clang::CodeGenOptions const &, class clang::TargetOptions const &, class clang::LangOptions const &, class llvm::StringRef, class llvm::Module *, enum clang::BackendAction, class llvm::raw_pwrite_stream *) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:779:15
    #12 0x7ffbef282a1e in clang::BackendConsumer::HandleTranslationUnit(class clang::ASTContext &) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:191:7
    #13 0x7ffbef7e1c39 in clang::ParseAST(class clang::Sema &, bool, bool) C:\src\dawn\third_party\dxc\tools\clang\lib\Parse\ParseAST.cpp:164:13
    #14 0x7ffbef27cb8b in clang::CodeGenAction::ExecuteAction(void) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:807:28
    #15 0x7ffbef28b083 in clang::FrontendAction::Execute(void) C:\src\dawn\third_party\dxc\tools\clang\lib\Frontend\FrontendAction.cpp:455:8
    #16 0x7ffbef1b8bfb in DxcCompiler::Compile(struct DxcBuffer const *, wchar_t const **, unsigned int, struct IDxcIncludeHandler *, struct _GUID const &, void **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:982:18
    #17 0x7ffbef1aea2e in hlsl::DxcCompilerAdapter::WrapCompile(int, struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1845:5
    #18 0x7ffbef1b17c9 in hlsl::DxcCompilerAdapter::CompileWithDebug(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1748:10
    #19 0x7ffbef1c2f7b in hlsl::DxcCompilerAdapter::Compile(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompileradapter.h:75:12
    #20 0x7ff7a7a2f321 in DxcContext::Compile(void) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:873:9
    #21 0x7ff7a7a39aa6 in dxc::main(int, wchar_t const **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:1501:24
    #22 0x7ff7a7b00adb in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
    #23 0x7ff7a7b00adb in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #24 0x7ffc7b777343  (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #25 0x7ffc7c1026b0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

previously allocated by thread T0 here:
    #0 0x7ff7a7ab6d6d in malloc C:\b\s\w\ir\cache\builder\src\third_party\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:98
    #1 0x7ffbf1125ee6 in operator new(unsigned __int64) D:\a\_work\1\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp:35
    #2 0x7ffbf017cde3 in llvm::User::operator new(unsigned __int64, unsigned int) C:\src\dawn\third_party\dxc\lib\IR\User.cpp:96:19
    #3 0x7ffbef4808e6 in llvm::Function::Create(class llvm::FunctionType *, enum llvm::GlobalValue::LinkageTypes, class llvm::Twine const &, class llvm::Module *) C:\src\dawn\third_party\dxc\include\llvm\IR\Function.h:123:12
    #4 0x7ffbef4c5a05 in llvm::Module::getOrInsertFunction(class llvm::StringRef, class llvm::FunctionType *, class llvm::AttributeSet) C:\src\dawn\third_party\dxc\lib\IR\Module.cpp:129:21
    #5 0x7ffbef4c5bdf in llvm::Module::getOrInsertFunction(class llvm::StringRef, class llvm::FunctionType *) C:\src\dawn\third_party\dxc\lib\IR\Module.cpp:147:10
    #6 0x7ffbf03f69a9 in `anonymous namespace'::TempOverloadPool::get C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:88:42
    #7 0x7ffbf03feb2a in `anonymous namespace'::HLMatrixLowerPass::getLoweredByValOperand C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:427:48
    #8 0x7ffbf03f99a5 in `anonymous namespace'::HLMatrixLowerPass::lowerHLCast C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:1519
    #9 0x7ffbf03f99a5 in `anonymous namespace'::HLMatrixLowerPass::lowerHLOperation C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:903:12
    #10 0x7ffbf03f2a34 in `anonymous namespace'::HLMatrixLowerPass::lowerCall C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:786
    #11 0x7ffbf03f2a34 in `anonymous namespace'::HLMatrixLowerPass::lowerInstruction C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:749
    #12 0x7ffbf03f2a34 in `anonymous namespace'::HLMatrixLowerPass::runOnFunction C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:281
    #13 0x7ffbf03f2a34 in `anonymous namespace'::HLMatrixLowerPass::runOnModule C:\src\dawn\third_party\dxc\lib\HLSL\HLMatrixLowerPass.cpp:243:5
    #14 0x7ffbef6fd64d in `anonymous namespace'::MPPassManager::runOnModule C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1669
    #15 0x7ffbef6fd64d in llvm::legacy::PassManagerImpl::run(class llvm::Module &) C:\src\dawn\third_party\dxc\lib\IR\LegacyPassManager.cpp:1771:44
    #16 0x7ffbef704e3b in `anonymous namespace'::EmitAssemblyHelper::EmitAssembly C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:756
    #17 0x7ffbef704e3b in clang::EmitBackendOutput(class clang::DiagnosticsEngine &, class clang::CodeGenOptions const &, class clang::TargetOptions const &, class clang::LangOptions const &, class llvm::StringRef, class llvm::Module *, enum clang::BackendAction, class llvm::raw_pwrite_stream *) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\BackendUtil.cpp:779:15
    #18 0x7ffbef282a1e in clang::BackendConsumer::HandleTranslationUnit(class clang::ASTContext &) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:191:7
    #19 0x7ffbef7e1c39 in clang::ParseAST(class clang::Sema &, bool, bool) C:\src\dawn\third_party\dxc\tools\clang\lib\Parse\ParseAST.cpp:164:13
    #20 0x7ffbef27cb8b in clang::CodeGenAction::ExecuteAction(void) C:\src\dawn\third_party\dxc\tools\clang\lib\CodeGen\CodeGenAction.cpp:807:28
    #21 0x7ffbef28b083 in clang::FrontendAction::Execute(void) C:\src\dawn\third_party\dxc\tools\clang\lib\Frontend\FrontendAction.cpp:455:8
    #22 0x7ffbef1b8bfb in DxcCompiler::Compile(struct DxcBuffer const *, wchar_t const **, unsigned int, struct IDxcIncludeHandler *, struct _GUID const &, void **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:982:18
    #23 0x7ffbef1aea2e in hlsl::DxcCompilerAdapter::WrapCompile(int, struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1845:5
    #24 0x7ffbef1b17c9 in hlsl::DxcCompilerAdapter::CompileWithDebug(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **, wchar_t **, struct IDxcBlob **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompilerobj.cpp:1748:10
    #25 0x7ffbef1c2f7b in hlsl::DxcCompilerAdapter::Compile(struct IDxcBlob *, wchar_t const *, wchar_t const *, wchar_t const *, wchar_t const **, unsigned int, struct DxcDefine const *, unsigned int, struct IDxcIncludeHandler *, struct IDxcOperationResult **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxcompiler\dxcompileradapter.h:75:12
    #26 0x7ff7a7a2f321 in DxcContext::Compile(void) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:873:9
    #27 0x7ff7a7a39aa6 in dxc::main(int, wchar_t const **) C:\src\dawn\third_party\dxc\tools\clang\tools\dxclib\dxc.cpp:1501:24
    #28 0x7ff7a7b00adb in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
    #29 0x7ff7a7b00adb in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #30 0x7ffc7b777343  (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #31 0x7ffc7c1026b0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

SUMMARY: AddressSanitizer: heap-use-after-free C:\src\dawn\third_party\dxc\include\llvm\IR\Value.h:374 in llvm::Value::getValueID
Shadow bytes around the buggy address:
  0x11a0c24a4780: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x11a0c24a4800: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa
  0x11a0c24a4880: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x11a0c24a4900: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x11a0c24a4980: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x11a0c24a4a00: fd fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd fd
  0x11a0c24a4a80: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa
  0x11a0c24a4b00: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x11a0c24a4b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x11a0c24a4c00: 00 04 fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x11a0c24a4c80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==66244==ABORTING
```

I've spent a good day debugging this, and will share my findings in a new comment below.

### PR DESCRIPTION
**Pull request by llvm-beanz**
When lowering an hl.cast, when the operand was an undef matrix, the pass would insert a call to a mat2vec stub, but since the undef value is not an alloca, it never gets handled, and the call to the temporary stub remains. Since the stub FunctionVal gets deleted, when the instruction is accessed in a future pass, it reads a dangling pointer.

The fix is to handle undef similarly to how constant 0 is handled, and to return an undef vector from lowerHLCast.

Fixes #6423

### CODE REVIEW

File: lib/HLSL/HLMatrixLowerPass.cpp [hunk 1]
```diff
@@ -421,6 +421,11 @@ Value *HLMatrixLowerPass::getLoweredByValOperand(Value *Val,
   if (isa<ConstantAggregateZero>(Val))
     return ConstantAggregateZero::get(LoweredTy);
 
+  // Lower undef mat as undef vec
+  if (isa<UndefValue>(Val)) {
+    return UndefValue::get(LoweredTy);
+  }
```
Comment (llvm-beanz) [inline lib/HLSL/HLMatrixLowerPass.cpp:427]:
```suggestion
  if (isa<UndefValue>(Val))
    return UndefValue::get(LoweredTy);
```

**Comment by damyanp** [comment]
Does ASAN catch this in regular runs?  (trying to figure out if we need to think about crafting a test for this)?

**Comment by llvm-beanz** [comment]
> Does ASAN catch this in regular runs? (trying to figure out if we need to think about crafting a test for this)?

The test case that I just pushed triggers the asan failure.

**Review by tex3d — APPROVED** [review]
Looks good.

**Review by bogner — APPROVED** [review]

**Review by damyanp — APPROVED** [review]
