### PR TITLE
[SPIRV] Add warning for initialized globals

### LINKED ISSUE #3950: [SPIR-V] assigning default value to an external global silently fails without warning
The following compiles successfully when generating spirv, but `groupshared uint testing = 0;` will NOT be always initialized to zero. If I switch the compile mode to DXIL, I will get the warning: `Initializer of external global will be ignored`

http://shader-playground.timjones.io/46e4c2aa215eef693bea5e82cc6c3f8a

```
groupshared uint testing = 0;

[numthreads(1, 1, 1)]
void cs_main(uint local_thread_id_flat : SV_GroupIndex) {
    if (testing > 0) {
        printf("aaa");
    }
}
```

### PR DESCRIPTION
**Pull request by s-perron**
To be consistent with DXIL, we will start emitting a warning for
extenally visible variables that have an initializer. Until now, there
were silently ignored.

Fixes #3950

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -2021,6 +2021,11 @@ void SpirvEmitter::doVarDecl(const VarDecl *decl) {
   // variables) belongs to the Function storage class.
   if (isExternalVar(decl)) {
     var = declIdMapper.createExternVar(decl);
+
```
Comment (amaiorano) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:2024]: nit: unnecessary newline

**Review by cassiebeckley — APPROVED** [review]

**Review by cassiebeckley — APPROVED** [review]
