### PR TITLE
spirv: validates parameters for InterlockedAddExch

### LINKED ISSUE #5647: [SPIR-V] InterlockedCompareExchange parameters are not validated
**Description**

DXC doesn't validates `InterlockedCompareExchange` params, and fails to report when an immediate is passed as an out param.
Instead we show a fatal error and ask to report the issue. We should produce a normal error.

**Steps to Reproduce**

```hlsl
groupshared uint value;

[numthreads(1, 1, 1)]
void main() {
  InterlockedCompareExchange(value, 1, 2, 3);
}
```

`dxc -T cs_6_6 -E main -spirv ~/repro.hlsl`

**Actual Behavior**

```
$ dxc -T cs_6_6 -E main -spirv ~/repro.hlsl
fatal error: generated SPIR-V is invalid: OpStore Pointer <id> '7[%uint_3]' is not a logical pointer.
  OpStore %uint_3 %12

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Environment**

- DXC version: HEAD (0f282ccabaf21c88e7dbfe0c866422842b639bc3)
- Host: linux

### PR DESCRIPTION
**Pull request by Keenuts**
This function takes a reference as 4th parameter. This was not validated by the backend, meaning we'd generate invalid SPIR-V and fail validation.

This PR adds a check to emit a fatal error if an immediate is used.

Fixes #5647

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -8874,6 +8874,11 @@ SpirvEmitter::processIntrinsicInterlockedMethod(const CallExpr *expr,
                                        const CallExpr *callExpr,
                                        uint32_t outputArgIndex) {
     const auto outputArg = callExpr->getArg(outputArgIndex);
+    if (dyn_cast<DeclRefExpr>(outputArg) == nullptr) {
+      emitError("InterlockedCompareExchange requires a reference as output parameter.", outputArg->getExprLoc());
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:8878]: nit: I think most of our error messages don't end in a period

**Review by sudonatalie — APPROVED** [review]

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 2]
```diff
@@ -8874,6 +8874,11 @@ SpirvEmitter::processIntrinsicInterlockedMethod(const CallExpr *expr,
...
+      return;
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:8879]: Also return nullptr here

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 1 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:8878]: fixed, removed the period.
