### PR TITLE
Fix handling of [RW]ByteAddressBuffer load involving matrix type

### LINKED ISSUE #3371: DXIL ByteAddressBuffer doesn't support float4x4 in templated load
```
struct PSInput
{
	float4 color : COLOR;
};

ByteAddressBuffer g_stuff;

float4 PSMain(PSInput input) : SV_TARGET
{
	return mul(g_stuff.Load<float4x4>(0), input.color);
}
```

Output:
```
C:\Users\Jasper\>dxc -Tps_6_5 -EPSMain test.hlsl

C:\Users\Jasper\>echo %ERRORLEVEL%
-1073741819
```

However,
```
struct PSInput
{
	float4 color : COLOR;
};

ByteAddressBuffer g_stuff;

struct Mat4x4Wrapper {
    float4x4 internal;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return mul(g_stuff.Load<Mat4x4Wrapper>(0).internal, input.color);
}
```

Run the same way, does result in correct DXIL output.

### PR DESCRIPTION
**Pull request by vcsharma**
Given that load operation for both `StructuredBuffer` and `ByteAddressBuffer` is lowered to `rawBufferLoad` dxil op, this PR refactors lowering code to ensure that we use common code for both `StructuredBuffer` and `ByteAddressBuffer` while preserving a couple of restrictions (listed below) that only applies to `ByteAddressBuffer`.  The common code path also helps fix a crash with the handling of the matrix type in the case of `ByteAddressBuffer` as it was already handled correctly for `StructuredBuffer`.

- If alignment > 4, then it is set to 4 for `ByteAddressBuffer`
- Validator expects index-based `rawBufferLoad` operation for `ByteAddressBuffer`. In other words, the offset should be set to `undef`.

Fixes #3371

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -3703,14 +3700,7 @@ void TranslateLoad(ResLoadHelper &helper, HLResource::Kind RK,
...
 
   // Offset 1
-  if (RK == DxilResource::Kind::RawBuffer) {
-    // elementOffset, mask, alignment
-    loadArgs.emplace_back(undefI);
-    Type *rtnTy = helper.retVal->getType();
-    loadArgs.emplace_back(GetRawBufferMaskForETy(rtnTy, numComponents, OP));
-    loadArgs.emplace_back(Alignment);
-  }
-  else if (RK == DxilResource::Kind::TypedBuffer) {
```
Comment (vcsharma) [inline lib/HLSL/HLOperationLower.cpp:3713]: Removed this because `RawBuffer` and `StructuredBuffer` are handled in a common way.

File: lib/HLSL/HLOperationLower.cpp [hunk 2]
```diff
@@ -6815,7 +6805,7 @@ static Value* ExtractFromTypedBufferLoad(const ResRetValueArray& ResRet,
   return ScalarizeElements(ResultTy, Elems, Builder);
 }
 
-Value *GenerateStructBufLd(Value *handle, Value *bufIdx, Value *offset,
+Value *GenerateRawBufLd(Value *handle, Value *bufIdx, Value *offset,
```
Comment (vcsharma) [inline lib/HLSL/HLOperationLower.cpp:6808]: This was really generating `rawBufferLoad` dxil op so changed the function name.

File: lib/HLSL/HLOperationLower.cpp [hunk 3]
```diff
@@ -3599,26 +3600,22 @@ void TranslateLoad(ResLoadHelper &helper, HLResource::Kind RK,
...
-  if (RK == HLResource::Kind::RawBuffer && alignValue > 4)
-    alignValue = 4;
-  Constant *Alignment = OP->GetI32Const(alignValue);
   unsigned numComponents = 1;
   if (Ty->isVectorTy()) {
     numComponents = Ty->getVectorNumElements();
   }
 
-  if (DXIL::IsStructuredBuffer(RK)) {
+  if (DXIL::IsStructuredBuffer(RK) || DXIL::IsRawBuffer(RK)) {
```
Comment (vcsharma) [inline lib/HLSL/HLOperationLower.cpp:3608]: Both `StructuredBuffer` and `RawBuffer` are now handled in a common code path here.

File: lib/HLSL/HLOperationLower.cpp [hunk 4]
```diff
@@ -6871,34 +6861,57 @@ void GenerateStructBufSt(Value *handle, Value *bufIdx, Value *offset,
...
+  std::vector<Value*> &bufLds, DXIL::ResourceKind kind, bool isScalarTy) {
+
+  DXASSERT_NOMSG(kind == DXIL::ResourceKind::StructuredBuffer ||
+    kind == DXIL::ResourceKind::RawBuffer);
+
   unsigned  EltSize = DL.getTypeAllocSize(VecEltTy);
+  // If RawBuffer load of 64-bit value, don't set alignment to 8,
+  // since buffer alignment isn't known to be anything over 4.
+  if (kind == HLResource::Kind::RawBuffer && EltSize > 4) {
+    EltSize = 4;
```
Comment (tex3d) [inline lib/HLSL/HLOperationLower.cpp:6876]: I don't like that we are changing EltSize here, this doesn't seem right.  We need to keep track of alignment separately.  In the future, we should be adding something to allow a base alignment promise in HLSL for the buffer declaration.  This would allow higher alignment for these cases.

File: lib/HLSL/HLOperationLower.cpp [hunk 5]
```diff
@@ -6871,34 +6861,57 @@ void GenerateStructBufSt(Value *handle, Value *bufIdx, Value *offset,
...
 
-    // Update offset by 4*4bytes.
-    offset = Builder.CreateAdd(offset, OP->GetU32Const(4 * EltSize));
+    if (kind == DXIL::ResourceKind::RawBuffer) {
+      // For rawbuffer, the validator expects offset to be undef.
+      // Therefore leave the offset as-is and increment the index instead.
+      index = Builder.CreateAdd(index, OP->GetU32Const(1));
+    }
+    else {
+      offset = Builder.CreateAdd(offset, OP->GetU32Const(4 * EltSize));
```
Comment (tex3d) [inline lib/HLSL/HLOperationLower.cpp:6908]: Here's a place where EltSize is assumed to be the actual element size, but if it was changed above from 8 to 4, this will generate incorrect offsets for 64-bit types.

File: tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/bab_mat_load_method.hlsl [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=float1x1 %s | FileCheck %s -check-prefix=CHK_MAT1x1
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=bool1x2 %s | FileCheck %s -check-prefix=CHK_MAT1x2
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=int2x1 %s | FileCheck %s -check-prefix=CHK_MAT2x1
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint2x2 %s | FileCheck %s -check-prefix=CHK_MAT2x2
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=float16_t2x3 %s | FileCheck %s -check-prefix=CHK_MAT2x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint16_t3x2 %s | FileCheck %s -check-prefix=CHK_MAT3x2
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=float3x3 %s | FileCheck %s -check-prefix=CHK_MAT3x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=int3x4 %s | FileCheck %s -check-prefix=CHK_MAT3x4
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=bool4x3 %s | FileCheck %s -check-prefix=CHK_MAT4x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint4x4 %s | FileCheck %s -check-prefix=CHK_MAT4x4
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/bab_mat_load_method.hlsl:12]: No 64-bit types tested here.  Need to test SM 6.3+ as well, since that introduces 64-bit RawBufferLoad/Store.  Also need to test min-precision case.

**Review by tex3d — CHANGES_REQUESTED** [review]

**Comment by Jasper-Bekkers** [comment]
Could it be that this PR also fixes this: https://github.com/microsoft/DirectXShaderCompiler/issues/3370

**Review by tex3d — APPROVED** [review]
Looks good.

**Comment by MarijnS95** [comment]
> Could it be that this PR also fixes this: #3370

Unfortunately that issue persists. Both when using `.Load<column_major float4x4>(...)` versus `.Load<row_major float4x4>(...)`, or loading a struct with `column/row_major` annotation generated SPIR-V remains identical.

@vcsharma is this something you could look into, given recent bumps on matrix-related issues?

**Comment by vcsharma** [comment]
> > Could it be that this PR also fixes this: #3370
> 
> Unfortunately that issue persists. Both when using `.Load<column_major float4x4>(...)` versus `.Load<row_major float4x4>(...)`, or loading a struct with `column/row_major` annotation generated SPIR-V remains identical.
> 
> @vcsharma is this something you could look into, given recent bumps on matrix-related issues?

@Jasper-Bekkers and @MarijnS95 Thanks for reaching out and raising the orientation related bug here. This PR is not intended to fix the issue related to matrix orientation. Note that we have another open bug #1803 that you might want to track.
