### PR TITLE
Fix cast construction in template instantiation for Constant and Texture buffers

### LINKED ISSUE #3972: Reading from a ConstantBuffer within a template fails compilation in a non-library profile
Reading from a ConstantBuffer within a template causes `error: External function used in non-library profile: : \01??$Fn@N@@YANN@Z`. Making the read within a separate function seems to be a workaround. This could be tied to #3731, but the error is quite different.

Minimal example, reproduces with dndxc.exe from de6a8ed4's AppVeyor build
Fails: `-enable-templates -DFAILURE_CASE`
Compiles: `-enable-templates`
```
struct ConstantsStruct
{
    float Val : Val;
};
ConstantBuffer<ConstantsStruct> Constants;

#ifdef FAILURE_CASE
template<typename T>
T Fn(T input)
{
    // Also tried to explicitly cast into T here without luck
    T ret = input - Constants.Val;

    return ret;
}

#else

float ReadConstant()
{
    return Constants.Val;
}
template<typename T>
T Fn(T input)
{
    // Need explicit cast here, type coercion fails with internal compiler error
    // Separate issue for this
    T ret = input - (T)ReadConstant();

    return ret;
}

#endif

void main()
{
    Fn(1.0);
}
```

### PR DESCRIPTION
**Pull request by llvm-beanz**
ConstantBuffers and TextureBuffers need to behave at the source and AST levels as if they implicitly convert to the underlying buffer data type.

When generating the AST we generate FlatConversion casts, but we don't have the proper overrides in place in `Sema::PerformObjectMemberConversion` to generate the same conversions on AST transformations that occur during template instantiation.

This is the root cause of issue #3327, so this change also includes reverting 2903170ac.

This change resolves #3972.

### CODE REVIEW

File: tools/clang/unittests/HLSL/OptionsTest.cpp [hunk 1]
```diff
@@ -198,7 +198,7 @@ TEST_F(OptionsTest, ReadOptionsWhenInvalidThenFail) {
   const wchar_t *ArgsNoArg[] = {L"exe.exe", L"hlsl.hlsl", L"/E", L"main",
                                 L"/T"};
   const wchar_t *ArgsUnknown[] = { L"exe.exe", L"hlsl.hlsl", L"/E", L"main",
-    L"/T" L"ps_6_0", L"--unknown"};
+    (L"/T" L"ps_6_0"), L"--unknown"};
```
Comment (pow2clk) [inline tools/clang/unittests/HLSL/OptionsTest.cpp:201]: Looks like your other change got mixed in here. Might want to rebase to avoid confusion

Comment (llvm-beanz) [reply tools/clang/unittests/HLSL/OptionsTest.cpp]: Should be fixed now :)

**Comment by llvm-beanz** [comment]
This also resolves #3973

**Comment by llvm-beanz** [comment]
> This also resolves #3973

Or not... there a different error being surfaced in that case with this patch applied. Will address that in a separate PR.
