### PR TITLE
Fix conversions between aggregate and numerical types

### LINKED ISSUE #1795: Array/struct to vector casts have incorrect semantics
Repro:

```
int2 main() : OUT
{
    int array[] = { 1, 2 };
    return (int2)array;
}
```

DXC output (outputs twice the first array element): 

```
define void @main() {
entry:
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 0, i32 1)
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 1, i32 1)
  ret void
}
```

FXC output (outputs each array element as the corresponding vector element):

```
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_output o0.xy
mov o0.xy, l(1,2,0,0)
ret
```

### PR DESCRIPTION
**Pull request by MrTrillian**
Conversions from aggregates to numerical types were improperly implemented. They're tricky because they involve struct/array rvalues, which cannot happen in normal clang. We can't load structs/arrays in llvm registers because it breaks a ton of assumptions and doesn't make sense due to bool having a different stack representation and so on. The solution to preserve LValue-to-RValue semantics is to memcpy the LValue to a temporary and return a pointer to the temporary as the RValue.

Also includes various smaller fixes found along the way.

Fixes #1795
Fixes an unfiled issue with clang crashing while trying to evaluate a struct-to-int flat conversion.
Fixes without closing #1875 (must still write tests)
Fixes without closing #1873 (must still write tests)

### CODE REVIEW

File: lib/HLSL/HLModule.cpp [hunk 1]
```diff
@@ -1003,7 +1003,11 @@ unsigned HLModule::FindCastOp(bool fromUnsigned, bool toUnsigned,
   if (SrcTy->isIntOrIntVectorTy() && DstTy->isIntOrIntVectorTy()) {
     if (SrcBitSize > DstBitSize)
       return Instruction::Trunc;
-    if (toUnsigned)
+    // unsigned to unsigned: zext
+    // unsigned to signed: zext (fully representable)
+    // signed to signed: sext
+    // signed to unsigned: sext (like C++)
+    if (fromUnsigned)
```
Comment (MrTrillian) [inline lib/HLSL/HLModule.cpp]: This is the fix for #1875

File: tools/clang/lib/AST/ExprConstant.cpp [hunk 2]
```diff
@@ -7670,6 +7670,7 @@ bool IntExprEvaluator::VisitCastExpr(const CastExpr *E) {
   case CK_CopyAndAutoreleaseBlockObject:
   case CK_HLSLVectorToScalarCast:   // HLSL Change
   case CK_HLSLMatrixToScalarCast:   // HLSL Change
+  case CK_FlatConversion: // HLSL Change
```
Comment (MrTrillian) [inline tools/clang/lib/AST/ExprConstant.cpp]: Fixes a crash with `return (int)myStruct;` because clang attempts evaluating casts to integral types.

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 3]
```diff
@@ -9937,7 +9937,8 @@ FlattenedTypeIterator::FlattenedTypeIterator(SourceLocation loc, QualType type,
   m_source(source), m_draining(false), m_springLoaded(false), m_incompleteCount(0), m_typeDepth(0), m_loc(loc)
 {
   if (pushTrackerForType(type, nullptr)) {
-    considerLeaf();
+    while (!m_typeTrackers.empty() && !considerLeaf())
```
Comment (MrTrillian) [inline tools/clang/lib/Sema/SemaHLSL.cpp]: The code here was assuming that one can recursively step into a struct to find its first (numerical) data member, but this didn't cover cases where the first member was an empty struct. In that case, we may need to step out and in the next field again.

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 4]
```diff
@@ -10055,17 +10056,11 @@ bool FlattenedTypeIterator::considerLeaf()
   case FlattenedIterKind::FK_Fields:
     if (pushTrackerForType(tracker.CurrentField->getType(), nullptr)) {
       result = considerLeaf();
-    } else {
-      // Pop empty struct.
-      m_typeTrackers.pop_back();
```
Comment (MrTrillian) [inline tools/clang/lib/Sema/SemaHLSL.cpp]: This would cause an empty struct field to act as an end marker for its containing struct. We should not pop now but rather keep iterating to the next field. This is a fix for #1873

File: tools/clang/lib/AST/HlslTypes.cpp [hunk 5]
```diff
@@ -125,6 +125,15 @@ bool IsHLSLNumericUserDefinedType(clang::QualType type) {
   return false;
 }
 
+bool IsHLSLCompoundType(clang::ASTContext& context, clang::QualType type) {
+  // Compound types are arrays and user-defined structs
```
[the remark this answers is not in the document]
Comment (MrTrillian) [reply tools/clang/lib/AST/HlslTypes.cpp]: "aggregate" is a better term indeed. I thought I had seen compound used elsewhere but now that I checked it meant struct/class. It is the case that the function works where I use it but might not in general. However, I don't know how to do a more exhaustive test, either as an assert or as the implementation. The only super hack I can think of is checking whether the struct has a source location.

File: tools/clang/lib/CodeGen/CGExprScalar.cpp [hunk 6]
```diff
@@ -1817,9 +1818,36 @@ Value *ScalarExprEmitter::VisitCastExpr(CastExpr *CE) {
     return Builder.CreateExtractElement(Visit(E), (uint64_t)0);
   }
   case CK_FlatConversion: {
-      llvm::Value *val = Visit(E);
-      llvm::Value *elem = Builder.CreateExtractValue(val, (uint64_t)0);
-      return EmitScalarConversion(elem, E->getType(), DestTy);
+    llvm::Value *Src = Visit(E);
+
+    // We should have a compound type (struct or array) on one side,
+    // and a numeric type (scalar, vector or matrix) on the other.
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGExprScalar.cpp]: Does this mean aggregate to aggregate (or compound) cast is handled elsewhere?

File: tools/clang/lib/CodeGen/CGExprScalar.cpp [hunk 7]
```diff
@@ -1817,9 +1818,36 @@ Value *ScalarExprEmitter::VisitCastExpr(CastExpr *CE) {
...
+    // If the compound type is the cast source, it should be a pointer.
+    auto areCompoundAndNumeric = [this](QualType lhs, QualType rhs) {
+      return hlsl::IsHLSLCompoundType(CGF.getContext(), lhs)
+        && (dyn_cast<clang::BuiltinType>(rhs) != nullptr || hlsl::IsHLSLVecMatType(rhs));
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGExprScalar.cpp]: Is `isBuiltinType()` equivalent here?

File: tools/clang/lib/CodeGen/CGExprScalar.cpp (hunk 6 above)
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp]: Yes, in `CGExprAgg`

File: tools/clang/lib/CodeGen/CGExprScalar.cpp (hunk 7 above)
Comment (MrTrillian) [reply tools/clang/lib/CodeGen/CGExprScalar.cpp]: probably, good catch

File: tools/clang/lib/AST/HlslTypes.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/lib/AST/HlslTypes.cpp]: Also, perhaps a better proxy than source location with the same problem is getting the decl and calling isImplicit(), which should be true for built-in struct/class types.

[the remark this answers is not in the document]
Comment (MrTrillian) [reply tools/clang/lib/AST/HlslTypes.cpp]: Ooh good call!

[the remark this answers is not in the document]
Comment (MrTrillian) [reply tools/clang/lib/AST/HlslTypes.cpp]: Wait, how is `isImplicit` going to work with raytracing structs? They are implicit but otherwise behave as regular structs?
