### PR TITLE
Merge separate refleciton and validator 1.4 compatibility fixes

### LINKED ISSUE #2288: bool values in the output signature trigger a validation error
This is a minimal code snippet to repro the problem, the workaround for the moment is simply to use `uint` instead of `bool`. 

It is worth noting that it was use in front of a geometry shader, so we did not try to interpolate the `bool` in a pixel shader, i wonder what should be the behavior. and `nointerpolate` is of no use anyhow because it is vertex/geometry stage anyhow.

## Shader
```
struct IN
{
  float4 p : P;
  uint v : V ;
};

struct OUT
{
  float4 pos : SV_Position;
  bool boom : BOOM;
};
[RootSignature("")]
OUT main( IN i)
{
  OUT o;
  o. pos = i.p;
  o.boom = i.v > 10;
  return o;
}
```

## Output:
```
Container part 'Program Output Signature' does not match expected for module.
Container part 'Pipeline State Validation' does not match expected for module.
```

### PR DESCRIPTION
**Pull request by tex3d**
This change moves reflection into a new STAT container part.  Since this breaks a lot of tests that rely on module disassembly->assembly between testing phases, there are temporary options test may use to preserve reflection in DXIL.

Also:
Recent bug fixes broke IL compatibility with the DXIL.dll validator released in the last SDK.  This will fix cases that might have still worked when passing the validator.  Fixes #2288 by generating what the 1.4 validator expects - the fix for the bool component type in the signature will not apply when using this validator.

Add -validator-version <major,minor> option for compilation path.  Still needs linker support.  See issue #1906.  Note: used comma instead of period for major/minor separator.

More Fixes:
- Recent feature work did not necessarily set appropriate feature requirements.
- Remove (broken) prerelease RDAT loader
- Certain options were meant to be accepted by the Compilation API, but were not categorized for this.
- Metadata load for template type parameter wasn't right, leading to llvm_assert after store, load, store, then load again.
- Change validator to no longer require function annotations.
- Fix missing calls to global removal hook
- Fix issues with global init function, libraries, validation, linking
- Fix reflection/usage issues with 16-bit types
- Allow removal of reflection part in IDxcContainerBuilder

### CODE REVIEW

File: lib/DxcSupport/HLSLOptions.cpp [hunk 1]
```diff
@@ -642,18 +645,65 @@ int ReadDxcOpts(const OptTable *optionTable, unsigned flagsToInclude,
...
+  llvm::StringRef valVersionStr = Args.getLastArgValue(OPT_validator_version);
+  if (!valVersionStr.empty()) {
+    // Parse "major,minor" version string
+    auto verPair = valVersionStr.split(",");
+    llvm::APInt major, minor;
+    if (verPair.first.getAsInteger(0, major) || verPair.second.getAsInteger(0, minor)) {
+      errors << "Format of validator version is \"<major>,<minor>\" (ex: \"1,4\").";
+      return 1;
+    }
+    uint16_t major64 = major.getLimitedValue();
```
Comment (jpporto) [inline lib/DxcSupport/HLSLOptions.cpp]: major64, but type is uint16_t?

Comment (tex3d) [reply lib/DxcSupport/HLSLOptions.cpp]: Typo fixed.  Also, while I was at it, I completed the option by adding support to the linker, with a test.  I also switched the option to use period instead of comma to separate major from minor for consistency.
