### PR TITLE
Change scope nested CFG passes to use a stack instead of recursion

### LINKED ISSUE #8224: ScopeNestedCFG pass stack overflow in large shaders with debug builds
**Description**
Running some relatively simple shaders with GPU-based validation enabled, with debug builds of WARP, I see stack overflows in the ScopeNestedCFG pass in the `SanitizeBranchesRec` recursive stack, with 2000+ recursive frames.

This recursion call stack should be changed to a loop with a heap-allocated stack data structure as necessary.

**Steps to Reproduce**
Microsoft-internal reproduction environment available.

**Actual Behavior**
Crashes in the recursive stack, or crashes due to corruption after returning from the recursive stack.

### PR DESCRIPTION
**Pull request by jenatali**
Fixes #8224

### CODE REVIEW

**Review by llvm-beanz — CHANGES_REQUESTED** [review]
This does not conform to our coding standards some obvious violations include:
* [Do not use `using namespace std`](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/CodingStandards.rst#do-not-use-using-namespace-std)
* [Pick the right data structures](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/ProgrammersManual.rst#picking-the-right-data-structure-for-a-task)

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 1]
```diff
@@ -429,90 +425,92 @@ void ScopeNestedCFG::Clear() {
...
-      unsigned CaseIdx = 0;
-      for (const SwitchCaseGroup &G : SwitchCaseGroups) {
-        for (ConstantInt *pCaseValue : G.CaseValue) {
-          SwitchInst::CaseIt itCase(I, CaseIdx++);
-          itCase.setSuccessor(G.pSuccBB);
-          itCase.setValue(pCaseValue);
+        auto itGroup = BB2GroupIdMap.insert({pSuccBB, SwitchCaseGroups.size()});
+        if (itGroup.second) {
+          SwitchCaseGroups.emplace_back(SwitchCaseGroup{});
         }
```
Comment (llvm-beanz) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]:
```suggestion
        if (itGroup.second)
          SwitchCaseGroups.emplace_back(SwitchCaseGroup{});
```

There's numerous cases of this rule being violated too:
https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 2]
```diff
@@ -428,91 +424,90 @@ void ScopeNestedCFG::Clear() {
...
+            SwitchInst::CaseIt itCase(I, CaseIdx++);
+            itCase.setSuccessor(G.pSuccBB);
+            itCase.setValue(pCaseValue);
+          }
+        }
+        // Remove unused case labels.
+        for (unsigned NumCases = I->getNumCases(); CaseIdx < NumCases;
+             NumCases--) {
+          I->removeCase(SwitchInst::CaseIt{I, NumCases - 1});
         }
```
Comment (jenatali) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]:
```suggestion
        for (unsigned NumCases = I->getNumCases(); CaseIdx < NumCases;
             NumCases--)
          I->removeCase(SwitchInst::CaseIt{I, NumCases - 1});
```

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 3]
```diff
@@ -537,14 +532,24 @@ void ScopeNestedCFG::CollectUniqueSuccessors(
...
+  SmallVector<Loop *, 16> Stack;
+  SmallVector<Loop *, 16> ReversePostOrder;
+  Stack.push_back(pLoop);
+
+  while (!Stack.empty()) {
+    Loop *pCurrent = Stack.pop_back_val();
+    ReversePostOrder.push_back(pCurrent);
+    for (auto it = pCurrent->begin(), end = pCurrent->end(); it != end; ++it) {
+      Stack.push_back(*it);
+    }
```
Comment (jenatali) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]:
```suggestion
    for (auto it = pCurrent->begin(), end = pCurrent->end(); it != end; ++it)
      Stack.push_back(*it);
```

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 4]
```diff
@@ -537,14 +532,24 @@ void ScopeNestedCFG::CollectUniqueSuccessors(
...
   }
 
-  m_Loops.emplace_back(pLoop);
+  for (auto it = ReversePostOrder.rbegin(), end = ReversePostOrder.rend();
+       it != end; ++it) {
+    m_Loops.emplace_back(*it);
+  }
```
Comment (jenatali) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]:
```suggestion
  for (auto it = ReversePostOrder.rbegin(), end = ReversePostOrder.rend();
       it != end; ++it)
    m_Loops.emplace_back(*it);
```

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 5]
```diff
@@ -428,91 +424,89 @@ void ScopeNestedCFG::Clear() {
...
+          }
         }
-      }
-      // Remove unused case labels.
-      for (unsigned NumCases = I->getNumCases(); CaseIdx < NumCases;
-           NumCases--) {
-        I->removeCase(SwitchInst::CaseIt{I, NumCases - 1});
+        // Remove unused case labels.
+        for (unsigned NumCases = I->getNumCases(); CaseIdx < NumCases;
+             NumCases--)
```
Comment (llvm-beanz) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]: nit: https://llvm.org/docs/CodingStandards.html#prefer-preincrement
```suggestion
             --NumCases)
```

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 6]
```diff
@@ -988,60 +990,102 @@ void ScopeNestedCFG::BlockTopologicalOrderAndReachability::dump(
...
-    // Union reachable BBs.
-    (*ReachableBBs) |= (*BTO.GetReachableBBs(pSuccBB));
-  }
+    if (PushedChild)
+      continue;
 
-  Marks[pNode] = 2; // late watermark
+    // All successors processed.
+    BasicBlock *pNode = Frame.pNode;
+    auto ReachableBBs = std::move(Frame.ReachableBBs);
```
Comment (llvm-beanz) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp]: nit: https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable
```suggestion
    unique_ptr<BitVector> ReachableBBs = std::move(Frame.ReachableBBs);
```

File: projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp [hunk 7]
```diff
@@ -988,60 +990,102 @@ void ScopeNestedCFG::BlockTopologicalOrderAndReachability::dump(
...
+        break;
+      }
+    }
 
-    ComputeBlockTopologicalOrderAndReachabilityRec(pSuccBB, BTO, Marks);
-    // Union reachable BBs.
-    (*ReachableBBs) |= (*BTO.GetReachableBBs(pSuccBB));
-  }
+    if (PushedChild)
+      continue;
```
Comment (bob80905) [inline projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp:1074]: I can't wrap my mind around how this is logically equivalent to the previous code, this looks like a behavioral change. Lines 1054-1074 here are the only lines I can't see the equivalent iterative translation for. Can you explain why we continue here? Maybe that would help explain the previous lines to me also. Other than those lines, this change looks good to me.

Comment (jenatali) [reply projects/dxilconv/lib/DxilConvPasses/ScopeNestedCFG.cpp:1074]: The previous logic would:
* Check for work to do for the target block
* For each successor:
  * Recurse
  * After recursion for a specific block, update the reachable blocks
* After all recursion, update the late watermark and append to BTO

The new logic will:
* In an iteration, check if this is the "before recursion" phase (based on the initialized flag), and if so, do the pre-recursion work.
* Process one successor: For the current successor, if we haven't processed it, then push a stack frame, break out of the successor loop, and immediately proceed back to the top of the iteration loop (i.e. begin processing that new frame). If we've already processed the successor, then iterate until we find one we haven't processed, or until we've checked all of them.
* If we didn't push a recursive stack frame, then process the post-recursion work.
