### PR TITLE
RDAT: Check flags and WaveSize for min SM; fix flag detection and merging

### LINKED ISSUE #6218: Per-function feature flags and min target in RDAT are incorrect
**Description**
RDAT has per-function feature requirement flags, compatible shader stage flags, and a minimum shader target that should take into account internal function calls and should adjust the minimum shader targets and legal shader stages based on optional feature usage.

Several issues were preventing these from correctly representing the requirements for the function:
- per-function DXIL Shader Flag collection has bugs:
  - missing some feature usage scenarios
  - using global resources to indicate flags that may not be applicable to the function.
  - can't account for stage-specific flags (`DerivativesInMeshAndAmplificationShaders`)
- Features used in internally called functions were not accounted for in the caller.
- Min shader model wasn't adjusted by any feature usage flags introduced since SM 6.2.
- Min shader model didn't take into account newer shader stages (ms/as introduced in SM 6.5).
- Min shader model couldn't account for stage-specific feature availability differences (derivatives used in CS, MS, or AS).
- WaveSize and WaveSizeRange fail to impact minimum shader target.

This also impacts module-level flags, since they are just the union of flags computed for each function, plus a few module-scope checks.

Fixing these issues can cause differences in the `DFCC_RuntimeData` (`RDAT`) part as well as DxilModule ShaderFlags (in metadata) and the DFCC_FeatureInfo (`SFI0`) parts.  This would be considered a validator-breaking change, since the validator uses the same code to compute these details, then makes sure the container matches these expectations.

**Steps to Reproduce**
The following reflection test demonstrates some of these bugs based on the difference between expected result from 1.7 and fixed 1.8 validator:
```hlsl
// RUN: %dxilver 1.8 | %dxc -T lib_6_8 %s | %D3DReflect %s | %FileCheck %s -check-prefixes=RDAT,RDAT18
// RUN: %dxilver 1.7 | %dxc -T lib_6_7 -validator-version 1.7 %s | %D3DReflect %s | FileCheck %s -check-prefixes=RDAT,RDAT17

// Ensure min shader target incorporates optional features used

// RDAT: FunctionTable[{{.*}}] = {

// SM 6.7+

///////////////////////////////////////////////////////////////////////////////
// ShaderFeatureInfo_WriteableMSAATextures (0x40000000) = 1073741824

// RDAT-LABEL: UnmangledName: "rwmsaa"
// ShaderFeatureInfo_WriteableMSAATextures (0x40000000) = 1073741824
// RDAT:   FeatureInfo1: 1073741824
// RDAT:   FeatureInfo2: 0
// MinShaderTarget: (Library(6) << 16) + (SM 6.7 ((6 << 4) + 7)) = 0x60067 = 393319
// RDAT18: MinShaderTarget: 393319
// Old: 6.0
// RDAT17: MinShaderTarget: 393312

RWByteAddressBuffer BAB : register(u1, space0);
RWTexture2DMS<float, 1> T2DMS : register(u2, space0);

[noinline] export
void rwmsaa() {
  // Use dynamic resource to avoid MSAA flag on all functions issue in 1.7
  // RWTexture2DMS<float, 1> T2DMS = ResourceDescriptorHeap[0];
  BAB.Store(0, T2DMS.sample[1][uint2(1, 2)]);
}

// RDAT-LABEL: UnmangledName: "no_rwmsaa"
// RDAT18: FeatureInfo1: 0
// 1.7 Incorrectly reports feature use for function
// RDAT17: FeatureInfo1: 1073741824
// RDAT:   FeatureInfo2: 0
// MinShaderTarget: (Library(6) << 16) + (SM 6.0 ((6 << 4) + 0)) = 0x60060 = 393312
// RDAT: MinShaderTarget: 393312

export void no_rwmsaa() {
  BAB.Store(0, 0);
}

// RDAT-LABEL: UnmangledName: "rwmsaa_in_raygen"
// ShaderFeatureInfo_WriteableMSAATextures (0x40000000) = 1073741824
// Old: set because of global
// RDAT: FeatureInfo1: 1073741824
// RDAT:   FeatureInfo2: 0
// MinShaderTarget: (RayGeneration(7) << 16) + (SM 6.7 ((6 << 4) + 7)) = 0x70067 = 458855
// RDAT18: MinShaderTarget: 458855
// Old: 6.0
// RDAT17: MinShaderTarget: 458848

[shader("raygeneration")]
void rwmsaa_in_raygen() {
  rwmsaa();
}

// RDAT-LABEL: UnmangledName: "rwmsaa_not_used_in_raygen"
// ShaderFeatureInfo_WriteableMSAATextures (0x40000000) = 1073741824
// RDAT18: FeatureInfo1: 0
// Old: set because of global
// RDAT17: FeatureInfo1: 1073741824
// RDAT:   FeatureInfo2: 0
// MinShaderTarget: (RayGeneration(7) << 16) + (SM 6.3 ((6 << 4) + 3)) = 0x70063 = 458851
// RDAT18: MinShaderTarget: 458851
// Old: 6.0
// RDAT17: MinShaderTarget: 458848

[shader("raygeneration")]
void rwmsaa_not_used_in_raygen() {
  no_rwmsaa();
}
```

**Expected Behavior**
Optional feature use and potential optional feature use is always captured into flags.  Min shader model is correct when combining all called functions and any special-case logic required for a final entry point function of a particular kind.
For the example above, when expected is different than actual, expected values are shown in the RDAT18 checks.

**Actual Behavior**
See above description of cases not captured correctly, as well as the RDAT17 sections of the example test case above.

**Environment**
- DXC version: recent `main` branch (`dcb618a2f1b7f4265fc2b77c12291f76eb334ae3`).
- Host Operating System: any

### PR DESCRIPTION
**Pull request by tex3d**
Add ShaderKind::Last_1_8 for shader mask
Add shader model comments before flag groupings in DxilConstants.h and DxilShaderFlags.

Add missing flag checks for min shader model in RDAT function info. Move ShaderCompatInfo computation into DxilModule, propagate callee info.

Move computation of shader model requirements based on flags into DxilModule. Finalize requirements for entry functions in AdjustMinimumShaderModelAndFlags.

Fixes for function level flag tracking:
- DerivativesInMeshAndAmpShaders: use flag to track deriv use, then adjust for entry functions.
- hasUAVs: based on resource use in function instead of global resources.
- WriteableMSAATextures: based on use in function instead of global resources.
  - Also catch cases for dynamic res from any use by looking at create/annotate handle, not just the TextureStoreSample op.
- RaytracingTier1_1: move module-level detection to CollectShaderFlagsForModule
- Marked deriv and quad ops as being supported in node.
- Fixed SampleCmpBias to be considered gradient op.
- Update RDAT definitions to dump more useful info for testing

Fixes #6218.

### CODE REVIEW

**Comment by tex3d** [comment]
If you start [here](https://github.com/microsoft/DirectXShaderCompiler/pull/6207/commits/7f7f2af0c9c0746c23cc2337b72485a96246cf51), then step through commits with [Next], it's a lot more digestible.

File: include/dxc/DXIL/DxilConstants.h [hunk 1]
```diff
@@ -60,6 +60,22 @@ inline int CompareVersions(unsigned Major1, unsigned Minor1, unsigned Major2,
   return 0;
 }
 
+// Utility for updating major,minor to max of current and new.
+inline bool MaxOfShaderModels(unsigned &major, unsigned &minor,
```
Comment (python3kgae) [inline include/dxc/DXIL/DxilConstants.h:64]: Maybe move this to DxilShaderModel.h?

File: include/dxc/DXIL/DxilModule.h [hunk 2]
```diff
@@ -404,6 +404,31 @@ class DxilModule {
...
+  void ComputeShaderCompatInfo();
+
+  // Clear previous ShaderCompatInfo for recomputation.
+  void ClearShaderCompatInfo();
+
+  // ShaderCompatInfo tracks requirements per-function, subsequently merged into
+  // final entry function requirements.
+  struct ShaderCompatInfo {
+    unsigned minMajor = 6, minMinor = 0;
+    unsigned mask = ((unsigned)1 << (unsigned)DXIL::ShaderKind::Invalid) - 1;
```
Comment (python3kgae) [inline include/dxc/DXIL/DxilModule.h:419]: Comment for what the mask is would be nice.

File: include/dxc/DXIL/DxilConstants.h [hunk 3]
```diff
@@ -1882,12 +1892,13 @@ const uint64_t ShaderFeatureInfo_AdvancedTextureOps = 0x20000000;
...
 
 // SM 6.8+
-// WaveMMA slots in between two SM 6.6 feature bits.
-const uint64_t ShaderFeatureInfo_WaveMMA = 0x8000000;
-
 const uint64_t ShaderFeatureInfo_SampleCmpGradientOrBias = 0x80000000;
 const uint64_t ShaderFeatureInfo_ExtendedCommandInfo = 0x100000000;
 
+// Experimental SM 6.9+ - Reserved, not yet supported.
+// WaveMMA slots in between two SM 6.6 feature bits.
```
Comment (coopp) [inline include/dxc/DXIL/DxilConstants.h:1915]: Is this comment necessary?  Do developers need to know where feature bits are taken from?

Comment (coopp) [reply include/dxc/DXIL/DxilConstants.h:1915]: Oh.. I see that this was an existing code comment, not a new one.

File: lib/DXIL/DxilOperations.cpp [hunk 4]
```diff
@@ -3249,23 +3249,24 @@ void OP::GetMinShaderModelAndMask(const llvm::CallInst *CI,
...
-    unsigned mode = barrier.get_barrierMode_val();
-    if (mode != (unsigned)DXIL::BarrierMode::UAVFenceGlobal) {
-      mask =
-          SFLAG(Library) | SFLAG(Compute) | SFLAG(Amplification) | SFLAG(Mesh);
+    // Barrier mode should be a constant, but be robust to non-constants here.
+    if (isa<ConstantInt>(CI->getArgOperand(DxilInst_Barrier::arg_barrierMode))) {
+      DxilInst_Barrier barrier(const_cast<CallInst *>(CI));
+      unsigned mode = barrier.get_barrierMode_val();
+      if (mode != (unsigned)DXIL::BarrierMode::UAVFenceGlobal) {
+        mask &= SFLAG(Library) | SFLAG(Compute) | SFLAG(Amplification) |
```
Comment (coopp) [inline lib/DXIL/DxilOperations.cpp:3268]: Just double checking here.  The original code just assigned an OR'd set of flags directly 'mask = flag | flag | flag'.  This new logic is ANDing this set of bits now. 'mask &= flag | flag | flag'.  Is this expected?

File: include/dxc/DXIL/DxilConstants.h (hunk 1 above)
Comment (coopp) [inline include/dxc/DXIL/DxilConstants.h:64]: MaxOfShaderModels( ) returns a bool, but it looks like the code below never checks that return.  Could this just be void or is there really something the code below needs to be aware of if 'false' is returned?

Comment (coopp) [reply include/dxc/DXIL/DxilConstants.h:64]: I see in other areas that use this helper, they do in fact check the bool which means that values have changed.

File: include/dxc/DXIL/DxilModule.h [hunk 5]
```diff
@@ -404,6 +404,31 @@ class DxilModule {
...
+    ShaderFlags shaderFlags;
+    bool Merge(ShaderCompatInfo &other);
+  };
+
+  const ShaderCompatInfo *
+  GetCompatInfoForFunction(const llvm::Function *F) const;
+
+private:
+  typedef std::unordered_map<const llvm::Function *, ShaderCompatInfo>
```
Comment (coopp) [inline include/dxc/DXIL/DxilModule.h:428]: Consider using llvm::DenseMap instead of std::unordered_map?  ( I have been reading coding guidelines for the llvm project and it suggests that replacement for map usage.. I see other llvm:: objects are being used in this code, so I wanted to make this suggestion.

File: include/dxc/DXIL/DxilConstants.h (hunk 1 above)
Comment (tex3d) [reply include/dxc/DXIL/DxilConstants.h:64]: Maybe I should consider a rename instead.  It really isn't specific to DxilShaderModel, it's just trying to do an in-place max for a major/minor version pair.

How about `UpdateToMaxOfVersions`?

Comment (tex3d) [reply include/dxc/DXIL/DxilConstants.h:64]: Yeah, the way I tried to separate different changes made it so the first one didn't need the return value, but other later uses did.

File: include/dxc/DXIL/DxilModule.h (hunk 5 above)
Comment (tex3d) [reply include/dxc/DXIL/DxilModule.h:428]: I can do this, but there are several other pre-existing collections used in DxilModule for which the same argument stands.  This code uses a template already used elsewhere in DxilModule, and this was a move of existing code that used this map type, so perhaps a decision to change the collection types in DxilModule could be made separately?  What do you think?

File: lib/DXIL/DxilOperations.cpp (hunk 4 above)
Comment (tex3d) [reply lib/DXIL/DxilOperations.cpp:3268]: I believe the `&=` is a safer pattern to use whenever further restricting the mask based on any special case following the `GetMinShaderModelAndMask` call, which initializes the mask and should set it based on specific instruction requirements.

Special cases like this need to restrict the mask, not accidentally expand it.  The generated code for the DXIL op should have set the maximally permissive mask for the operation, which we might need to restrict with some special cases here.

Assignment would have been equivalent in this case, but it's not a pattern this code should use unless we are trying to match a prior validator in a special case for compatibility, like the earlier code does for wave ops.

However, this comment made take a second look at another case in this function, and I realized it needed updating, so thanks for that!  I'll update that in a little while after I can craft and verify a test that hits that case.

**Review by coopp — APPROVED** [review]

File: lib/DXIL/DxilModule.cpp [hunk 6]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+  if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 5) < 0) {
+    ValidShaderMask = (1 << ((unsigned)DXIL::ShaderKind::Last_1_4 + 1)) - 1;
+  } else if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) < 0) {
+    ValidShaderMask = (1 << ((unsigned)DXIL::ShaderKind::Last_1_7 + 1)) - 1;
+  } else if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) >= 0) {
+    ValidShaderMask = (1 << ((unsigned)DXIL::ShaderKind::Last_1_8 + 1)) - 1;
+  }
+
+  for (auto &function : GetModule()->getFunctionList()) {
+    if (!function.isDeclaration()) {
```
Comment (pow2clk) [inline lib/DXIL/DxilModule.cpp:2190]: Nit: It would be a bit easier to follow the indentation if this were accomplished using something like ` if (function.isDeclaration()) continue;`

File: lib/DXIL/DxilModule.cpp [hunk 7]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+      }
+
+      if (shaderKind == DXIL::ShaderKind::Library)
+        info.mask &= ValidShaderMask;
+      else
+        info.mask &= (1U << static_cast<unsigned>(shaderKind));
+
+      // Increase min target based on features used:
+      ShaderFlags &flags = info.shaderFlags;
+      if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) >= 0) {
```
Comment (pow2clk) [inline lib/DXIL/DxilModule.cpp:2206]: There are a few of these checks for greater than 1.8 sprinkled in this function. I can't tell quickly if this function has any effect with a version less than 1.8. Regardless, can any be consolidated for maintainability and legibility?

File: include/dxc/DXIL/DxilConstants.h [hunk 8]
```diff
@@ -1881,14 +1908,30 @@ const uint64_t ShaderFeatureInfo_AdvancedTextureOps = 0x20000000;
...
+const uint64_t ShaderFeatureInfo_WaveMMA = 0x8000000;
+
+// Maximum count without rolling over into another 64-bit field is 40,
+// so the last flag we can use for a feature requirement is: 0x8000000000
+// This is because of the following set of flags, considered optional
+// and ignored by the runtime if not recognized:
+// D3D11_OPTIONAL_FEATURE_FLAGS 0x7FFFFF0000000000
 const unsigned ShaderFeatureInfoCount = 33;
```
[the remark this answers is not in the document]
Comment (tex3d) [reply include/dxc/DXIL/DxilConstants.h:1923]: I don't know how we can get an assert for this.  The comment is here where we define these flags so when a new flag is defined, hopefully this will let us know.  I'm open to suggestions for a static assert if you have any ideas, of course.

[the remark this answers is not in the document]
Comment (tex3d) [reply include/dxc/DXIL/DxilConstants.h:1923]: Oh, sorry, I realize you're talking about `ShaderFeatureInfoCount`, duh.  I can static_assert that.  I also have to double-check that it's ok to have the optional flag outside this set.

File: lib/DXIL/DxilModule.cpp [hunk 9]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+    changed = true;
+  }
+  uint64_t rawBefore = shaderFlags.GetShaderFlagsRaw();
+  shaderFlags.CombineShaderFlags(other.shaderFlags);
+  if (rawBefore != shaderFlags.GetShaderFlagsRaw())
+    changed = true;
+  return changed;
+}
+
+void DxilModule::ClearShaderCompatInfo() { m_FuncToShaderCompat.clear(); }
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2128]: Yeah, it was intended to be used after changes are made to the functions in the module that might require recomputation, such as after a PIX pass or something like that, but I'll call it at the beginning of `CollectShaderFlagsForModule`, since that will also guarantee it's fresh when computing the overall module flags.

File: lib/DXIL/DxilModule.cpp [hunk 10]
```diff
@@ -342,6 +349,29 @@ void DxilModule::CollectShaderFlagsForModule(ShaderFlags &Flags) {
...
+      for (const auto &it : pSubobjects->GetSubobjects()) {
+        switch (it.second->GetKind()) {
+        case DXIL::SubobjectKind::RaytracingPipelineConfig1:
+          Flags.SetRaytracingTier1_1(true);
+          break;
+        case DXIL::SubobjectKind::StateObjectConfig: {
+          uint32_t configFlags;
+          if (it.second->GetStateObjectConfig(configFlags) &&
+              ((configFlags &
+                ~(unsigned)DXIL::StateObjectFlags::ValidMask_1_4) != 0))
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:364]: I moved this code unchanged, but I can update it.  I'll add a new mask that include the 1.1 flags I think.

File: lib/DXIL/DxilModule.cpp [hunk 11]
```diff
@@ -342,6 +349,29 @@ void DxilModule::CollectShaderFlagsForModule(ShaderFlags &Flags) {
...
+            Flags.SetRaytracingTier1_1(true);
+        } break;
+        default:
+          break;
+        }
+        if (Flags.GetRaytracingTier1_1())
+          break;
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:371]: Again, I moved this code unchanged.  I'll move it into a separate static function.

File: lib/DXIL/DxilModule.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:364]: Or maybe I'll just test for the one 1.1 flag.

File: lib/DXIL/DxilModule.cpp [hunk 12]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+  shaderFlags.CombineShaderFlags(other.shaderFlags);
+  if (rawBefore != shaderFlags.GetShaderFlagsRaw())
+    changed = true;
+  return changed;
+}
+
+void DxilModule::ClearShaderCompatInfo() { m_FuncToShaderCompat.clear(); }
+
+void DxilModule::ComputeShaderCompatInfo() {
+  // Initialize worklist with functions with callers
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2131]: ok

File: lib/DXIL/DxilModule.cpp [hunk 13]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+  SmallSetVector<llvm::Function *, 8> worklist;
+
+  for (auto &function : GetModule()->getFunctionList()) {
+    if (function.isDeclaration() && !function.isIntrinsic() &&
+        function.getLinkage() ==
+            llvm::GlobalValue::LinkageTypes::ExternalLinkage &&
+        OP::IsDxilOpFunc(&function)) {
+      // update min shader model and shader stage mask per function
+      UpdateFunctionToShaderCompat(&function);
+    } else if (!function.isDeclaration()) {
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2141]: ok

File: lib/DXIL/DxilModule.cpp [hunk 14]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+      // Initialize worklist with functions with callers.
+      // only used for validator version 1.8+
+      if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) >= 0 &&
+          !function.user_empty())
+        worklist.insert(&function);
+
+      // Skip functions with shader flags already set
+      if (m_FuncToShaderCompat.count(&function) != 0)
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2149]: Yes, we still want to add it to the worklist, as another function that doesn't have flags set may call this one.  We go from callee to caller when combining flags.

File: lib/DXIL/DxilModule.cpp [hunk 15]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+        continue;
+
+      // Collect shader flags for function
+      ShaderCompatInfo &info = m_FuncToShaderCompat[&function];
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2153]: We do this quite a bit elsewhere, but I'll add a comment.

File: lib/DXIL/DxilModule.cpp (hunk 6 above)
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2190]: ok

File: lib/DXIL/DxilModule.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2149]: I'm removing this because I realize it could cause functions to skip flag collection, if an intrinsic used in the function was iterated first.  That also means I'm not bothering with retaining results from a prior run, so I'll clear the map each time this is called and get rid of the `ClearShaderCompatInfo` function as well.

File: lib/DXIL/DxilModule.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2153]: Actually, this *may* add info, or the info may already be added when traversing an intrinsic users first.

File: lib/DXIL/DxilModule.cpp (hunk 7 above)
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2206]: It does have an effect for < 1.8.  The 1.8 checks are to make sure we generate the same result in validator 1.7 and below.

The effects when < 1.8 are:
- CollectShaderFlags for each function
- Updates each functions min target and valid shader stage flags based on intrinsic usage via UpdateFunctionToShaderCompat on intrinsics to update users.
- Masks shader stage flags based on ShaderKind for a shader entry function, or based on stages that exist in the shader model for a library function.
- Updates min target based on use of a few optional feature flags (6.2 for native low precision, 6.1 for barycentrics or ViewID)

With >= 1.8, we also:
- propagate flags from internal calees to callers
- use AdjustMinimumShaderModelAndFlags to account for all feature flags, shader stages, WaveSize use, and handle the special case for derivative use.

File: lib/DXIL/DxilModule.cpp [hunk 16]
```diff
@@ -2081,4 +2111,157 @@ bool DxilModule::IsPrecise(const Instruction *inst) const {
...
+        if (flags.GetUseNativeLowPrecision() && flags.GetLowPrecisionPresent())
+          DXIL::UpdateToMaxOfVersions(info.minMajor, info.minMinor, 6, 2);
+        else if (flags.GetBarycentrics() || flags.GetViewID())
+          DXIL::UpdateToMaxOfVersions(info.minMajor, info.minMinor, 6, 1);
+      }
+    }
+  }
+}
+
+void DxilModule::UpdateFunctionToShaderCompat(const llvm::Function *dxilFunc) {
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilModule.cpp:2221]: Yeah, good point for next time.  For this one, I believe I just added ` | SFLAG(Node)`, which was missing before, and encapsulated the version update in `DXIL::UpdateToMaxOfVersions`.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm67_writeablemsaa.hlsl [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+// ShaderFeatureInfo_WriteableMSAATextures (0x40000000) = 1073741824
+// ResourceDescriptorHeapIndexing (0x2000000) = 33554432
+// 0x40000000 + 0x2000000 = 0x42000000 = 1107296256
+// RDAT18:   FeatureInfo1: 1107296256
+// Old: missed use of WriteableMSAATextures
+// RDAT17:   FeatureInfo1: 33554432
+// RDAT:   FeatureInfo2: 0
+// MinShaderTarget: (Library(6) << 16) + (SM 6.7 ((6 << 4) + 7)) = 0x60067 = 393319
+// RDAT18: MinShaderTarget: 393319
+// Old: 6.6
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm67_writeablemsaa.hlsl:23]:
```suggestion
// Old: 6.6 (Because of dynamic resources)
```

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm67_writeablemsaa_global.hlsl [hunk 18]
```diff
@@ -0,0 +1,74 @@
...
+// Old: 6.0
+// RDAT17: MinShaderTarget: 393312
+
+RWByteAddressBuffer BAB : register(u1, space0);
+RWTexture2DMS<float, 1> T2DMS : register(u2, space0);
+
+[noinline] export
+void rwmsaa() {
+  // Use dynamic resource to avoid MSAA flag on all functions issue in 1.7
+  // RWTexture2DMS<float, 1> T2DMS = ResourceDescriptorHeap[0];
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm67_writeablemsaa_global.hlsl:29]: These seem irrelevant here. 
```suggestion
```

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_barrier.hlsl [hunk 19]
```diff
@@ -0,0 +1,52 @@
+// RUN: %dxilver 1.8 | %dxc -T lib_6_8 %s | %D3DReflect %s | %FileCheck %s -check-prefixes=RDAT
+
+// Ensure that barrier is allowed for node shaders.
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_barrier.hlsl:3]: I guess it has that side effect, but the checks seem to be, like the other tests to determine that RDAT data correctly sets the version due to node shaders.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_deriv.hlsl [hunk 20]
```diff
@@ -0,0 +1,222 @@
+// RUN: %dxilver 1.8 | %dxc -T lib_6_8 %s | %D3DReflect %s | %FileCheck %s -check-prefixes=RDAT
+
+// Ensure that categories of deriv ops are allowed for node shaders.
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_deriv.hlsl:3]: As with the previous, this at least seems to check that and that the OptFeatureInfo_UsesDerivatives  flag gets set. 
```suggestion
// Ensure that the OptFeatureInfo_UsesDerivatives flag gets set
// for different categories of deriv ops in node shaders.
```

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm6x_wavemma.hlsl [hunk 21]
```diff
@@ -0,0 +1,53 @@
...
+// + WaveOps (0x4000) = 0x8004000 = 134234112
+// RDAT:   FeatureInfo1: 134234112
+// RDAT:   FeatureInfo2: 0
+// MinShaderTarget: (Library(6) << 16) + (SM 6.9 ((6 << 4) + 9)) = 0x60069 = 393321
+// RDAT: MinShaderTarget: 393321
+
+[noinline] export
+void call_use_wavematrix() {
+  use_wavematrix();
+}
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm6x_wavemma.hlsl:39]: I'm curious why a second level of indirection was useful here and nowhere else.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/uavs_at_every_stage.hlsl
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/uavs_at_every_stage.hlsl:1]: This looks to be an exact copy of sm67_advancedtextureops.hlsl. I think you meant to modify it.

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp [hunk 22]
```diff
@@ -783,8 +783,15 @@ FileRunCommandPart::RunD3DReflect(dxc::DxcDllSupport &DllSupport,
   IFT(DllSupport.CreateInstance(CLSID_DxcLibrary, &pLibrary));
   IFT(DllSupport.CreateInstance(CLSID_DxcAssembler, &pAssembler));
 
-  IFT(pLibrary->CreateBlobWithEncodingFromPinned(
-      (LPCVOID)Prior->StdOut.c_str(), Prior->StdOut.size(), CP_UTF8, &pSource));
+  // It would be better to properly honour %s for input, but for now, if prior
+  // output is empty, use the file as input.
```
Comment (pow2clk) [inline tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:787]: I'd like to understand why this was necessary

File: lib/DXIL/DxilShaderFlags.cpp [hunk 23]
```diff
@@ -420,16 +438,22 @@ ShaderFlags ShaderFlags::CollectShaderFlags(const Function *F,
...
 
   bool hasAdvancedTextureOps = false;
-  bool hasWriteableMSAATextures = false;
+  bool hasWriteableMSAATexturesGlobal = false;
   bool hasSampleCmpGradientOrBias = false;
 
   bool hasWaveMMA = false;
   bool hasExtendedCommandInfo = false;
 
+  // UsesDerivatives is used to indicate any derivative use per-function, before
```
Comment (pow2clk) [inline lib/DXIL/DxilShaderFlags.cpp:450]: Typo I think
```suggestion
  // hasDerivatives is used to indicate any derivative use per-function, before
```

File: lib/DXIL/DxilShaderFlags.cpp [hunk 24]
```diff
@@ -778,17 +840,86 @@ ShaderFlags ShaderFlags::CollectShaderFlags(const Function *F,
   flag.SetSamplerDescriptorHeapIndexing(hasSamplerDescriptorHeapIndexing);
   flag.SetAtomicInt64OnHeapResource(hasAtomicInt64OnHeapResource);
   flag.SetAdvancedTextureOps(hasAdvancedTextureOps);
-  flag.SetWriteableMSAATextures(hasWriteableMSAATextures);
+  flag.SetWriteableMSAATextures(setWriteableMSAATexturesBasedOnGlobal
+                                    ? hasWriteableMSAATexturesGlobal
+                                    : hasWriteableMSAATextures);
```
Comment (pow2clk) [inline lib/DXIL/DxilShaderFlags.cpp:845]: This check seems unnecessary and inconsistent as there's already a place above that will set `hasWriteableMSAATextures` to true if `setWiteableMSAATexturesBasedOnGlobal` is true and there are any RWMS textures in the module. 

Is there a case where there aren't RWMS textures in the module and yet there are somehow handle creation calls for a RWMS texture? That seems the only case where `hasWriteableMSAATexturesGlobal` would be false, but somehow `hasWriteableMSAATextures` would be true and we want the false because `setWiteableMSAATexturesBasedOnGlobal` is set. 

Said another way, I thinkt hat if `hasWriteableMSAATextures` is true, then `hasWriteableMSAATexturesGlobal` _must_ be true, so I don't know why you wouldn't just use `hasWriteableMSAATextures` here without any contidional. 
```suggestion
  flag.SetWriteableMSAATextures(hasWriteableMSAATextures);
```

File: lib/DXIL/DxilShaderFlags.cpp [hunk 25]
```diff
@@ -778,17 +840,86 @@ ShaderFlags ShaderFlags::CollectShaderFlags(const Function *F,
...
+  flag.SetUsesDerivatives(hasDerivatives);
 
   return flag;
 }
 
 void ShaderFlags::CombineShaderFlags(const ShaderFlags &other) {
   SetShaderFlagsRaw(GetShaderFlagsRaw() | other.GetShaderFlagsRaw());
 }
+
+ShaderFlags
```
Comment (pow2clk) [inline lib/DXIL/DxilShaderFlags.cpp:861]: As many times as I've cursed when I came to a called function without any description above it, I would like a description above this function. 
```suggestion
// Use the function properties `props` to determine the minimum shader model and
// flag requirements based on shader stage and feature usage.
// Compare that minimum required version to the values passed in with
// `minMajor` and `minMinor` and pass the maximum of those back through those
// same variables.
// Return a copy of the `ShaderFlags` object with any additional flags required
// by `props` set.
ShaderFlags
```
Note that if the returned value of this changes because of my comment below, the last line will have to change too.

File: lib/DxilContainer/DxilContainerAssembler.cpp [hunk 26]
```diff
@@ -1829,50 +1768,26 @@ class DxilRDATWriter : public DxilPartWriter {
                                              TGSMInFunc[&function]);
             } else if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) >
                        0) {
```
Comment (pow2clk) [inline lib/DxilContainer/DxilContainerAssembler.cpp:1770]: Is this right or should it be `>=`? Maybe it's part of an experimental feature? 
```suggestion
            } else if (DXIL::CompareVersions(m_ValMajor, m_ValMinor, 1, 8) >=
                       0) {
```

**Review by pow2clk — COMMENTED** [review]
I think with a long change like this, my comments tend toward complaining about how hard it is to read and review. Sorry about that. 

I tried to make suggested changes where possible. Overall, this improves more than I expected to fix this bug. Now that it's done, that's great!

I don't think much needs to change, I just have a couple concerns and many readability suggestions.

File: lib/DxilContainer/DxilContainerAssembler.cpp (hunk 26 above)
Comment (tex3d) [reply lib/DxilContainer/DxilContainerAssembler.cpp:1770]: It's not included for 1.8, it's part of the experimental/potential next version.

File: lib/DXIL/DxilOperations.cpp [hunk 27]
```diff
@@ -3230,42 +3225,42 @@ void OP::GetMinShaderModelAndMask(const llvm::CallInst *CI,
...
+    }
   }
 
   if (DXIL::CompareVersions(valMajor, valMinor, 1, 5) < 0) {
     // validator 1.4 didn't exclude wave ops in mask
     if (IsDxilOpWave(opcode))
-      mask = ((unsigned)1 << (unsigned)DXIL::ShaderKind::Invalid) - 1;
-    // These shader models don't exist before 1.5
-    mask &= ~(SFLAG(Amplification) | SFLAG(Mesh));
+      mask = ((unsigned)1 << (unsigned)DXIL::ShaderKind::Mesh) - 1;
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilOperations.cpp:3245]: This is merely to maintain compatibility with validator version < 1.4.  It had a bug where it said wave ops were available to all shader stages.  However, the previous workaround using `((unsigned)1 << (unsigned)DXIL::ShaderKind::Invalid) - 1` would produce flags that included mesh and amp shaders when we added them.  That was incorrect, since in 1.4, mesh and amp shaders didn't exist.  So instead of including all stages, I'm including only the ones that existed at the time.

File: lib/DXIL/DxilShaderFlags.cpp (hunk 23 above)
Comment (tex3d) [reply lib/DXIL/DxilShaderFlags.cpp:450]: `UsesDerivatives` is the name of the flag, and intentional.  `hasDerivatives` is the name of the bool variable that we use locally to keep track of whether we found derivative usage, but may or may not result in the UsesDerivatives flag being set.

File: lib/DXIL/DxilShaderFlags.cpp (hunk 24 above)
Comment (tex3d) [reply lib/DXIL/DxilShaderFlags.cpp:845]: It *is* possible to use a dynamic resource so `hasWriteableMSAATextures` can be true with `hasWriteableMSAATexturesGlobal` being false.

However, revisiting this, I think the compatibility code won't quite get it right either.  Before, the flag would be set if either there was a global resource, or if [TextureStoreSample was used](https://github.com/microsoft/DirectXShaderCompiler/pull/6207/files#diff-d35f0d00e33e546a948baeacb7cbd7b6e5d3ebf0650bf93bd354e0f47821c20aR710).  But there are more potential uses of the resource than `TextureStoreSample`, so I added code to catch any other use.  However, since the `TextureStoreSample` isn't counted separately now, neither flag captures the exact behavior of 1.7.

I think I'm going to rename `hasWriteableMSAATexturesGlobal` to `hasWriteableMSAATextures_1_7`, then set this based on global, and set it when `TextureStoreSample` is encountered, then switch between the flags based on that.  Looks like another subtle test case is needed, ugh..

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_atomicint64.hlsl [hunk 28]
```diff
@@ -0,0 +1,96 @@
...
+  GroupMemoryBarrierWithGroupSync();
+  uint64_t original;
+  InterlockedExchange(gs, tidx, original);
+  BAB.Store(tidx * 4, original);
+}
+
+///////////////////////////////////////////////////////////////////////////////
+// ShaderFeatureInfo_AtomicInt64OnHeapResource (0x10000000) = 268435456
+
+// TBD: should it be set on bound heap resource?
```
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_atomicint64.hlsl:59]: Oh yeah, we only set this if a dynamic heap resource is used with AtomicInt64.  I remember that was necessary, and was wondering why it wasn't set when you used a bound heap resource instead.  But we set a flag on the resource itself indicating this usage when it's a bound resource, and this flag makes it into PSV0 and RDAT resource flags, so I guess it wasn't necessary.  It was just a bit confusing because the feature can be used without incurring the feature flag requirement here.  I think it's by-design, but it made me go hmmm?

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives.hlsl [hunk 29]
```diff
@@ -0,0 +1,131 @@
...
+
+// Ensure min shader target incorporates optional features used
+
+// RDAT: FunctionTable[{{.*}}] = {
+
+// SM 6.6+
+
+///////////////////////////////////////////////////////////////////////////////
+// ShaderFeatureInfo_DerivativesInMeshAndAmpShaders (0x1000000) = 16777216
+// OptFeatureInfo_UsesDerivatives (0x0000010000000000) = FeatureInfo2: 256
```
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives.hlsl:39]: No, not to reflection API actually.  This is an RDAT dump which is part of our D3DReflect dump for testing purposes, but is not exposed through our reflection API.  The flag is explicitly masked off for the reflection API, so there is no API surface impacted.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives_lib_6_6.ll [hunk 30]
```diff
@@ -0,0 +1,218 @@
...
+; RDAT18: ShaderStageFlag: 57441
+; Old would not report Compute, Mesh, Amplification, or Node compatibility.
+; Pixel(0), Library(6) = 0x41 = 65
+; RDAT16: ShaderStageFlag: 65
+; RDAT17: ShaderStageFlag: 65
+; MinShaderTarget: (Library(6) << 16) + (SM 6.0 ((6 << 4) + 0)) = 0x60060 = 393312
+; RDAT17: MinShaderTarget: 393312
+; RDAT18: MinShaderTarget: 393312
+; Old: Didn't set min target properly for lib function
+; RDAT16: MinShaderTarget: 393318
```
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives_lib_6_6.ll:43]: The issue is that I had to split these into three files for different versions, and they needed the identical checks that the HLSL file had.  I wanted to preserve the checks as-is so copy-paste between would work.  If I tailor each to each version, it would be a lot harder to edit and maintain.  I wish there was a way to do multiple RUN lines with preprocessing and ifdef/macro expansion on the source for .ll tests.  Then I could use an include file for common checks and/or code.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives_lib_6_8_decl_intrin_first.ll [hunk 31]
```diff
@@ -0,0 +1,223 @@
...
+; RDAT18: ShaderStageFlag: 57441
+; Old would not report Compute, Mesh, Amplification, or Node compatibility.
+; Pixel(0), Library(6) = 0x41 = 65
+; RDAT16: ShaderStageFlag: 65
+; RDAT17: ShaderStageFlag: 65
+; MinShaderTarget: (Library(6) << 16) + (SM 6.0 ((6 << 4) + 0)) = 0x60060 = 393312
+; RDAT17: MinShaderTarget: 393312
+; RDAT18: MinShaderTarget: 393312
+; Old: Didn't set min target properly for lib function
+; RDAT16: MinShaderTarget: 393318
```
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_derivatives_lib_6_8_decl_intrin_first.ll:146]: See earlier comment regarding the ability to copy-paste between these that have different versions.  It's much easier to maintain if they have the same checks, and it's much easier to see the expected version differences side-by-side.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_barrier.hlsl (hunk 19 above)
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_barrier.hlsl:3]: This one is to test the bug where node wasn't added to the mask of allowed shader stages for this barrier operation.  This test ensures the function is still considered compatible with node shader when the barrier is used.

In fact, this is the fix that's being waited on so that Amar can enable the RDAT validation in the runtime, which currently breaks node shader tests due to this bug.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_deriv.hlsl (hunk 20 above)
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_node_deriv.hlsl:3]: I can add that it checks that the `OptFeatureInfo_UsesDerivatives` flag gets set as well, but this is also to explicitly regression test that node shaders are considered compatible with different categories of derivative ops, since that was another bug fixed (some deriv op categories didn't say that they were supported in node shaders, see update in hctdb.py).

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/uavs_at_every_stage.hlsl
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/uavs_at_every_stage.hlsl:1]: I didn't mean to add it.  I was going to use it to test the change to that flag, but it turns out putting the metadata check in the sm66_derivatives.hlsl test did double duty checking this and making sure the UsesDerivatives flag was masked away from the global flags.  I have an update deleting this file incoming soon.

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp (hunk 22 above)
Comment (tex3d) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:787]: It was necessary to input raw IR.  Normally, `%D3DReflect` follows a compilation (`%dxc`) or link (`%dxl`) where the resulting IR is dumped to the `Prior->StdOut`.  But if I want to start with IR, there is no prior stage dumping this IR to `Prior->StdOut`.  Ideally, I might do `%dxa` but that doesn't exist here, so I did this as a workaround for the problem.  The right fix would be to use the file if `%s` was specified, otherwise use the `Prior->StdOut`.  But to make that change, I'd have to change a whole lot more tests to remove the `%s` from `%D3DReflect %s` in their RUN lines.  I was thinking of doing that in a follow-up change.

File: lib/DXIL/DxilShaderFlags.cpp [hunk 32]
```diff
@@ -778,17 +840,86 @@ ShaderFlags ShaderFlags::CollectShaderFlags(const Function *F,
...
+    DXIL::UpdateToMaxOfVersions(minMajor, minMinor, 6, 7);
+  else if (GetAtomicInt64OnTypedResource() || GetAtomicInt64OnGroupShared() ||
+           GetAtomicInt64OnHeapResource() ||
+           GetResourceDescriptorHeapIndexing() ||
+           GetSamplerDescriptorHeapIndexing())
+    DXIL::UpdateToMaxOfVersions(minMajor, minMinor, 6, 6);
+  else if (GetRaytracingTier1_1() || GetSamplerFeedback())
+    DXIL::UpdateToMaxOfVersions(minMajor, minMinor, 6, 5);
+  else if (GetShadingRate())
+    DXIL::UpdateToMaxOfVersions(minMajor, minMinor, 6, 4);
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilShaderFlags.cpp:918]: I'm not sure what you mean.

File: lib/DXIL/DxilShaderFlags.cpp [hunk 33]
```diff
@@ -778,17 +840,86 @@ ShaderFlags ShaderFlags::CollectShaderFlags(const Function *F,
...
+    // entry point we have. Then, we may need to clear the flag, when it doesn't
+    // apply.
+
+    if (GetUsesDerivatives()) {
+      if (props->IsCS()) {
+        // Always supported if SM 6.6+.
+        DXIL::UpdateToMaxOfVersions(minMajor, minMinor, 6, 6);
+      } else if (props->IsMS() || props->IsAS()) {
+        // Requires flag for support on SM 6.6+.
+        flags.SetDerivativesInMeshAndAmpShaders(true);
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilShaderFlags.cpp:887]: I suppose it could be elsewhere, but where?  Perhaps DxilModule?

File: lib/HLSL/DxilContainerReflection.cpp [hunk 34]
```diff
@@ -2837,59 +2847,66 @@ HRESULT CFunctionReflection::GetDesc(D3D12_FUNCTION_DESC *pDesc) {
...
+  // Unset: UINT MacroInstructionCount; // Number of macro instructions used
+  // Unset: UINT ArrayInstructionCount; // Number of array instructions used
+  // Unset: UINT MovInstructionCount; // Number of mov instructions used
+  // Unset: UINT MovcInstructionCount; // Number of movc instructions used
+  // Unset: UINT ConversionInstructionCount; // Number of type conversion
+  //                                            instructions used
+  // Unset: UINT BitwiseInstructionCount; // Number of bitwise arithmetic
+  //                                         instructions used
+  // Unset: D3D_FEATURE_LEVEL MinFeatureLevel; // Min target of the function
+  //                                              byte code
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/HLSL/DxilContainerReflection.cpp:2891]: Yeah, I thought that at the time, but I saw it and felt I needed to fix it while I was here.  I could try to extract into another PR, if you'd like.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm6x_wavemma.hlsl (hunk 21 above)
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm6x_wavemma.hlsl:35]: I honestly don't recall at the moment.  I think I wanted to make sure the exported function picked up the called function as well in this case, but I don't really remember now.  It seems useful to have at least one test here that does two levels of indirection though, so I'm inclined to leave it.

File: tools/clang/test/HLSLFileCheck/d3dreflect/empty_broadcasting_nodes.hlsl [hunk 35]
```diff
@@ -16,7 +16,7 @@
 // CHECK:      FeatureInfo1: 0
 // CHECK:      FeatureInfo2: 0
 // CHECK:      ShaderStageFlag: 32768
-// CHECK:      MinShaderTarget: 983136
+// CHECK:      MinShaderTarget: 983144
```
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/empty_broadcasting_nodes.hlsl]: I changed the dump output to make this much easier to check.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_atomicint64.hlsl (hunk 28 above)
[the remark this answers is not in the document]
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm66_atomicint64.hlsl]: I removed this comment.

File: lib/DXIL/DxilShaderFlags.cpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (pow2clk) [reply lib/DXIL/DxilShaderFlags.cpp:924]: We missed the minimum version required in a lot of cases. Will any full shaders require later versions as a result of this or is it just functions showing up in RDAT?

File: lib/DXIL/DxilShaderFlags.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (pow2clk) [reply lib/DXIL/DxilShaderFlags.cpp:887]: I don't have something in mind. It's probably not worth it. I was just thinking out loud.

File: lib/DXIL/DxilModule.cpp [hunk 36]
```diff
@@ -288,11 +288,39 @@ unsigned DxilModule::GetGlobalFlags() const {
...
-  };
+  ComputeShaderCompatInfo();
+  for (auto &itInfo : m_FuncToShaderCompat)
+    Flags.CombineShaderFlags(itInfo.second.shaderFlags);
+
+  // Clear UsesDerivatives flag for module, making sure
+  // DerivativesInMeshAndAmpShaders is set for MS/AS.
+  if (Flags.GetUsesDerivatives()) {
+    Flags.SetUsesDerivatives(false);
+    if (m_pSM->IsMS() || m_pSM->IsAS())
```
Comment (python3kgae) [inline lib/DXIL/DxilModule.cpp:321]: Why compute is not here?

Comment (pow2clk) [reply lib/DXIL/DxilModule.cpp:321]: Advanced Texture Ops made derivatives in mesh and amplification shaders a separate feature bit. This is to check if that bit is needed.

**Review by pow2clk — APPROVED** [review]
Love the pretty printing! Thanks for all the responses!

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp [hunk 37]
```diff
@@ -783,8 +783,15 @@ FileRunCommandPart::RunD3DReflect(dxc::DxcDllSupport &DllSupport,
   IFT(DllSupport.CreateInstance(CLSID_DxcLibrary, &pLibrary));
   IFT(DllSupport.CreateInstance(CLSID_DxcAssembler, &pAssembler));
 
-  IFT(pLibrary->CreateBlobWithEncodingFromPinned(
-      (LPCVOID)Prior->StdOut.c_str(), Prior->StdOut.size(), CP_UTF8, &pSource));
+  // It would be better to properly honour %s for input, but for now, if prior
```
Comment (python3kgae) [inline tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: Why we need this?

File: lib/HLSL/DxilContainerReflection.cpp [hunk 38]
```diff
@@ -2837,59 +2847,66 @@ HRESULT CFunctionReflection::GetDesc(D3D12_FUNCTION_DESC *pDesc) {
...
 
   pDesc->RequiredFeatureFlags =
       m_FeatureFlags & ~(UINT64)D3D_SHADER_REQUIRES_EARLY_DEPTH_STENCIL;
+  // Also Mask off function-level derivatives flag.
```
Comment (python3kgae) [inline lib/HLSL/DxilContainerReflection.cpp:2895]: Why mask off function-level flag?

Comment (pow2clk) [reply lib/HLSL/DxilContainerReflection.cpp:2895]: It's a temporary flag that isn't meant to make it to the final feature flags as runtime has no need of it. It's used to determine derivative usage for the sake of cs/as/ms shaders. Once it has been used to determine what the entry points use, it can and should be discarded.

File: lib/DXIL/DxilShaderFlags.cpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (pow2clk) [reply lib/DXIL/DxilShaderFlags.cpp]: I'll incorporate what I mean in my release notes and ask that Tex look them over.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm65_ms_as.hlsl [hunk 39]
```diff
@@ -0,0 +1,67 @@
...
+// works.  If that requirement were to be enforced, we would have to declare
+// these outputs.  However, if we do, there should also be a requirement that
+// mesh shader vertex output has SV_Position (not enforced currently either).
+// If that were to be enforced, and added to the struct, then the validator
+// will fail unless you write to all components of SV_Position.  This should
+// probably only be the case if OutputCounts are set to anything other than 0.
+// In any case, all this means that if some rules start to be enforced, we
+// will be forced to use things which will produce intrinsic calls in the mesh
+// shader which will cause the min target to be set to SM 6.5+ even for
+// validator version 1.7 and below.
```
[the remark this answers is not in the document]
Comment (pow2clk) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm65_ms_as.hlsl:26]: I filed a bug: https://github.com/microsoft/DirectXShaderCompiler/issues/6267

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp (hunk 37 above)
Comment (tex3d) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: I'll give the response I gave @pow2clk [here](https://github.com/microsoft/DirectXShaderCompiler/pull/6207#discussion_r1483829104):

> It was necessary to input raw IR.  Normally, `%D3DReflect` follows a compilation (`%dxc`) or link (`%dxl`) where the resulting IR is dumped to the `Prior->StdOut`.  But if I want to start with IR, there is no prior stage dumping this IR to `Prior->StdOut`.  Ideally, I might do `%dxa` but that doesn't exist here, so I did this as a workaround for the problem.  The right fix would be to use the file if `%s` was specified, otherwise use the `Prior->StdOut`.  But to make that change, I'd have to change a whole lot more tests to remove the `%s` from `%D3DReflect %s` in their RUN lines.  I was thinking of doing that in a follow-up change.

Comment (python3kgae) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: You mean for the ll tests?
You can do it in lit with
// RUN: %dxa %s -o %t
// RUN: %dxa %t -dumpreflection | FileCheck %s

Comment (python3kgae) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: Or -dumpreflection does not dump what we need here?

Comment (python3kgae) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: maybe -dumprdat?

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp (hunk 22 above)
Comment (tex3d) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:787]: Filed #6271 to track.

File: tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp (hunk 37 above)
Comment (tex3d) [reply tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp:786]: Filed #6271 to track.
