### PR TITLE
Fix two issues with DXR -remove-unused-globals

### LINKED ISSUE #1907: DXR rewrites invalid HLSL with anonymous global structs and -remove-unused-globals
Repro:
```
struct {} foo;
void main() {}
```
CMD: `dxr -remove-unused-globals repro.hlsl -Emain`
Output: 
```
// Rewrite unused globals result:
struct {
};
void main() {
}
```
CMD: `dxc -T vs_6_0 rewritten.hlsl`
```
E:\Sandbox\playground.hlsl:2:1: error: anonymous structs and classes must be class members
struct {
```

### PR DESCRIPTION
**Pull request by MrTrillian**
1. Constant buffer globals could get removed, causing the layout of the implicit constant buffer to change.
2. For cases like `static struct { int x; } s;` (which happen in some commercial shaders), we would be left with `struct { int x; };` at the global scope, which is illegal. This change cleans up anonymous records if we remove their last declared variable.

There's no testing infrastructure for this and I'm unconvinced it's worth adding.

Fixes #1907

### CODE REVIEW

File: tools/clang/tools/libclang/dxcrewriteunused.cpp [hunk 1]
```diff
@@ -65,32 +65,28 @@ class RewriteUnusedASTConsumer : public SemaConsumer {
 
 class VarReferenceVisitor : public RecursiveASTVisitor<VarReferenceVisitor> {
 private:
-  SmallPtrSet<VarDecl*, 128>& m_unusedGlobals;
-  SmallPtrSet<FunctionDecl*, 128>& m_visitedFunctions;
-  SmallVector<FunctionDecl*, 32>& m_pendingFunctions;
+  SmallPtrSetImpl<VarDecl*>& m_unusedGlobals;
+  SmallPtrSetImpl<FunctionDecl*>& m_visitedFunctions;
+  SmallVectorImpl<FunctionDecl*>& m_pendingFunctions;
```
Comment (MrTrillian) [inline tools/clang/tools/libclang/dxcrewriteunused.cpp]: I thought I had to modify this class. In the end, no, but I can leave the few cleanups.
