### PR TITLE
Fix ternary operator for enum result type

### LINKED ISSUE #4826: ternary `?` degrades enumerator types to `int`
```
enum Composite
{
    Spec,
    Diff,
};
static const Composite g_c = true ? Spec : Diff; 
```

result

> error: cannot initialize a variable of type 'const Composite' with an rvalue of type 'int'

excepted: successful build. (verified in clang, gcc and msvc on C++)

### PR DESCRIPTION
**Pull request by tex3d**
Note: existing path that limits operator to basic numeric types still allowed enum due to it being AR_TOBJ_BASIC, rather than using a new ArTypeObjectKind. It's questionable whether this was intentional, but changing it would require another special case to allow enums, like exists for object types, and it might have other side effects as well.

Fixes #4826

### CODE REVIEW

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -9855,8 +9855,15 @@ clang::QualType HLSLExternalSource::CheckVectorConditional(
     return QualType();
   }
 
-  // Here, element kind is combined with dimensions for result type.
-  ResultTy = NewSimpleAggregateType(AR_TOBJ_INVALID, resultElementKind, 0, rowCount, colCount)->getCanonicalTypeInternal();
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:9859]: Troubling how long this has been here 😣

File: tools/clang/test/HLSLFileCheck/hlsl/operators/ternary-enum.hlsl [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+#endif
+MyEnum {
+    One,
+    Two,
+};
+
+#ifdef CLASS
+static const MyEnum g_c = true ? MyEnum::One : MyEnum::Two;
+#else
+static const MyEnum g_c = true ? One : Two;
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/hlsl/operators/ternary-enum.hlsl:31]: Does it have to be static const? Does it have to be the initialization? Just wondering how narrow this is. Clearly we aren't testing the different things we can plug into the ternary operator (or select()) as well as we should. What do you think about expanding this to include a number of other types? Maybe not in this change, but I think it's a test we need.

**Review by pow2clk — APPROVED** [review]
Everything here looks good. I'm just wondering about futher testing.
