### PR TITLE
Prevent texture of structs/matrices/arrays, and don't crash

### LINKED ISSUE #1695: Add error for non-vector arguments of Texture2D
The following code crashes the compiler. Expected behavior is an error that Struct cannot be used as Texture2D template argument.

```
struct PSInput
{
    float2 uv : TEXCOORD0;
};

struct Struct
{
    float x;
};

Texture2D<Struct> t;
SamplerState s;

float4 PSMain(PSInput input) : SV_TARGET
{
    return float4(t.GatherRed( s, input.uv), 0, 0, 0);
}
```
`dxc -T ps_6_0 -E PSMain test.hlsl`.

### PR DESCRIPTION
**Pull request by MrTrillian**
For structs and arrays, this matches FXC's behavior. For matrices, FXC accepts it if the number of elements is <= 4 and reports an error otherwise. DXC also accepted it but would crash if the number of elements was > 4. After this change, DXC will reject textures of matrices, regardless of the number of elements.

Fixes #1695

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 1]
```diff
@@ -2624,13 +2624,27 @@ bool CGMSHLSLRuntime::SetUAVSRV(SourceLocation loc,
...
+        cast<ClassTemplateSpecializationDecl>(RD);
     const clang::TemplateArgument &sampleCountArg =
         templateDecl->getTemplateArgs()[1];
     uint32_t sampleCount = sampleCountArg.getAsIntegral().getLimitedValue();
     hlslRes->SetSampleCount(sampleCount);
   }
 
+  if (hlsl::DxilResource::IsAnyTexture(kind)) {
+    const ClassTemplateSpecializationDecl *templateDecl = cast<ClassTemplateSpecializationDecl>(RD);
+    const clang::TemplateArgument &retTyArg = templateDecl->getTemplateArgs()[0];
```
Comment (hekota) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I'm just wondering why the name is retTyArg - since it's not a return type. Or did I miss something?
