### PR TITLE
[spirv] Add support for RValues with OpaqueArrayType

### LINKED ISSUE #3677: fatal error: generated SPIR-V is invalid: The Base <id> '35[%35]' in OpAccessChain instruction must be a pointer
Hello

Have an error when compiling into SPIR-V:

dxc.exe ps.hlsl  -spirv  -T ps_6_6  -E ps_main  -fvk-use-dx-layout -fspv-target-env=vulkan1.1 -Fo ps.out

fatal error: generated SPIR-V is invalid: The Base <id> '35[%35]' in OpAccessChain instruction must be a pointer.
  %36 = OpAccessChain %_ptr_Function_type_2d_image %35 %int_0

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Repro Code:

```
SamplerState SS_OVERLAY;

Texture2D<float4> g_albedo0;
Texture2D<float4> g_albedo1;
Texture2D<float4> g_albedo2;
Texture2D<float4> g_albedo3;


float4 ps_main() : SV_Target
{
  Texture2D<float4> amTextures[4] = { g_albedo0, g_albedo1, g_albedo2, g_albedo3 };

  float4 result = 0;
  [unroll] for (int layerId = 0; layerId < 4; ++layerId)
  {
    result +=  amTextures[layerId].Sample(SS_OVERLAY, float2(0.0, 0.0));
  }

  return result;
}
```

Thank you

### PR DESCRIPTION
**Pull request by sudonatalie**
RValues with OpaqueArrayType can now be legalized with spirv-opt.

Fixes #3677

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -5525,21 +5525,20 @@ void SpirvEmitter::storeValue(SpirvInstruction *lhsPtr,
...
     // represented differently as struct T.
   } else if (isOpaqueArrayType(lhsValType)) {
+    // SPIRV-Tools can handle legalization of the store in these cases.
+    if (!lhsValType->isConstantArrayType() || rhsVal->isRValue()) {
+      spvBuilder.createStore(lhsPtr, rhsVal, loc);
+      needsLegalization = true;
+      return;
+    }
+
     // For opaque array types, we cannot perform OpLoad on the whole array and
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:5535]: @jaebaek I know we talked about removing this comment as well, but as far as I can tell it looks to still be correct, but it applied to the later block, so I moved it down for clarity. Let me know if that still doesn't seem right!

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:5535]: Makes sense. Thanks.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 2]
```diff
@@ -5525,21 +5525,20 @@ void SpirvEmitter::storeValue(SpirvInstruction *lhsPtr,
...
     // then write out as a whole; instead, we need to OpLoad each element
     // using access chains. This is to influence later SPIR-V transformations
     // to use access chains to access each opaque object; if we do array
     // wholesale handling here, they will be in the final transformed code.
     // Drivers don't like that.
     // TODO: consider moving this hack into SPIRV-Tools as a transformation.
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:5541]: Could you please just remove the last line `// TODO: consider moving this hack into SPIRV-Tools as a transformation.`?

**Review by jaebaek — COMMENTED** [review]
It seems the test failure is caused by some cmake updates. Please make sure you rebase your change with the upstream. If it still fails after that, we can ask Microsoft about it.

**Review by jaebaek — APPROVED** [review]

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 2 above)
Comment (sudonatalie) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:5541]: Done

Comment (sudonatalie) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp]: Done
