### PR TITLE
Fix crash when casting structs with identical layout

### LINKED ISSUE #1560: Crash when using structurally equivalent structs
The following program crashes on dxc but works on fxc.

```
// dxc /Tgs_6_0 t.hlsl
struct VSOutGSIn
{
    float4  clr : COLOR0;
    float4  pos : SV_Position;
};

struct GSOutPSIn
{
    float4  clr : COLOR0;
    float4  pos : SV_Position;
};

[maxvertexcount(3)]
void main(triangle VSOutGSIn tri[3], inout TriangleStream<GSOutPSIn> stream)
{
//#define WORKAROUND
#if !defined(WORKAROUND)
    stream.Append(tri[0]);
    stream.Append(tri[1]);
    stream.Append(tri[2]);
#else
    GSOutPSIn t0;
        t0.clr = tri[0].clr;
        t0.pos = tri[0].pos;
    GSOutPSIn t1;
        t1.clr = tri[1].clr;
        t1.pos = tri[1].pos;
    GSOutPSIn t2;
        t2.clr = tri[2].clr;
        t2.pos = tri[2].pos;

    stream.Append(t0);
    stream.Append(t1);
    stream.Append(t2);
#endif
}
```
If I copy the fields manually it works correctly on dxc. Seems to be some issue with casting between structurally equivalent types.

### PR DESCRIPTION
**Pull request by vcsharma**
Fixes #1560 , #1684 and a similar bug reported internally.

### CODE REVIEW

**Comment by MrTrillian** [comment]
Comment for all tests: you're committing the exact failing tests given by the customer, which is good for validating that their specific instance of the bug is fixed, but it makes it more difficult to understand what is the exact case that is being tested. Shouldn't we prefer having tests that are as reduced as possible? Of course at the time of checking in we should verify that the original shader works, but it seems more valuable to have succinct regression tests.

**Comment by vcsharma** [comment]
> Comment for all tests: you're committing the exact failing tests given by the customer, which is good for validating that their specific instance of the bug is fixed, but it makes it more difficult to understand what is the exact case that is being tested. Shouldn't we prefer having tests that are as reduced as possible? Of course at the time of checking in we should verify that the original shader works, but it seems more valuable to have succinct regression tests.

Usually I do prefer smallest possible example which could repro the bug. I also noticed that you had smaller examples posted for these bugs which still repro this bugs. However, given that we had related issues reported from multiple sources, I just wanted to keep them as-is to ensure we are exactly fixing the reported scenarios. That said, I would possibly get rid of a couple of them before merging..

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 1]
```diff
@@ -4427,6 +4432,84 @@ INITIALIZE_PASS(SROA_Parameter_HLSL, "scalarrepl-param-hlsl",
...
+  std::vector<Value *> idxConstList;
+  for (unsigned idx : idxlist) {
+    idxConstList.push_back(ConstantInt::get(builder.getInt32Ty(), idx));
+  }
+  return idxConstList;
+}
+
+void SROA_Parameter_HLSL::CopyElementsOfStructsWithIdenticalLayout(
+    IRBuilder<> &builder, Value *destPtr, Value *srcPtr, Type *ty,
+    std::vector<unsigned> idxlist) {
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: Instead of taking the vector by value, can't you take it by ref, and pop_back after recursing? Your push/pops should be perfectly balanced.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 2]
```diff
@@ -4427,6 +4432,84 @@ INITIALIZE_PASS(SROA_Parameter_HLSL, "scalarrepl-param-hlsl",
...
+      Type *SrcTy = BCI->getSrcTy();
+      if (!SrcTy->isPointerTy() || !DstTy->isPointerTy())
+        continue;
+      DstTy = DstTy->getPointerElementType();
+      SrcTy = SrcTy->getPointerElementType();
+      if (!SrcTy->isStructTy() || !DstTy->isStructTy())
+        continue;
+      StructType *DstST = cast<StructType>(DstTy);
+      StructType *SrcST = cast<StructType>(SrcTy);
+      if (!SrcST->isLayoutIdentical(DstST))
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: For the record, as we discussed, this won't catch all the cases FXC supports (whether that's desirable or not). For FXC, struct { float2, float2} == struct { float, float2, float }. The DXC semantic layer actually also accepts this, I believe, so it will still crash here.

File: tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test02.hlsl [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+   input.f2[3][1] = 12;
+   input.f3[0] = float2(13, 14);
+   input.f3[1] = float2(15, 16);
+   input.f3[2] = float2(17, 18);
+   input.f3[3] = float2(19, 20);   
+   input.f4 = uint3(21, 22, 23);
+   input.s.f5 = float4(24, 25, 26, 27);
+   input.s.f6 = float3(28, 29, 30);
+   input.f7 = true;
+   o1 = input;
```
Comment (MrTrillian) [inline tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test02.hlsl]: Related to my other comment, the whole test is really just for this line and the below, right? That's far from obvious.

File: tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test01.hlsl [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    tri[0].clr = float4(1, 2, 3, 4);
+    tri[0].pos = float4(5, 6, 7, 8);
+
+    tri[1].clr = float4(9, 10, 11, 12);
+    tri[1].pos = float4(13, 14, 15, 16);
+
+    tri[2].clr = float4(17, 18, 19, 20);
+    tri[2].pos = float4(21, 22, 23, 24);
+    
+//#define WORKAROUND
```
Comment (MrTrillian) [inline tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test01.hlsl]: here too I don't see value in keeping the workaround

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 5]
```diff
@@ -4427,6 +4432,84 @@ INITIALIZE_PASS(SROA_Parameter_HLSL, "scalarrepl-param-hlsl",
...
+          builder, destPtr, srcPtr, ty->getStructElementType(i), idxlist);
+    }
+  } else if (ty->isArrayTy()) {
+    for (unsigned i = 0; i < ty->getArrayNumElements(); i++) {
+      idxlist.push_back(i);
+      CopyElementsOfStructsWithIdenticalLayout(
+          builder, destPtr, srcPtr, ty->getArrayElementType(), idxlist);
+    }
+  } else if (ty->isIntegerTy() || ty->isFloatTy() || ty->isDoubleTy() ||
+             ty->isHalfTy() || ty->isVectorTy()) {
```
Comment (MrTrillian) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: That looks brittle, is there no test for being a primitive numeric type? And aren't there bools in hlsl?

Comment (MrTrillian) [reply lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: Oh that's true. And you can GetElementPointer to an i1 even though the target platforms have byte granularity for pointers?

File: tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test02.hlsl (hunk 3 above)
Comment (MrTrillian) [reply tools/clang/test/CodeGenHLSL/casting_identical_layout_structs_test02.hlsl]: Ah actually never mind. I see that you're testing the codegen for copying all possible struct members.

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp (hunk 2 above)
Comment (vcsharma) [reply lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp]: Yes, FXC is far more flexible with casting not only with struct casting but in other cases too. This change would enable the scenario where the layout matches exactly. In future, we could look to extend cases like you mentioned above.
