### PR TITLE
Make external sema source handle type completion

### LINKED ISSUE #4315: Template instantiation fails to populate object methods
DXC lazy-initializes the member methods for built-in objects. This triggers during parsing when objects of an HLSL type are provided, and fails to trigger during template instantiation as shown in the example below. This test case was reduced from the test provided in #4263, but is a separate issue from the "partial specialization" error.

```cpp
template <typename T> struct MyTex2D {
  uint heapId;

  template <typename Arg0> T Load(Arg0 arg0) { return Get().Load(arg0); }

  Texture2D<T> Get() { return (Texture2D<T>)ResourceDescriptorHeap[heapId]; }
};

cbuffer constantBuffer : register(b0) {
  MyTex2D<float4> tex;
};

float4 main() : SV_Target {
  float4 output = tex.Load(float3(0, 0, 0));
  return output;
}
```

### PR DESCRIPTION
**Pull request by llvm-beanz**
Prior to this change the HLSL built in types are inserted into the AST
during initialization as complete types missing their methods. The
method implementations are then inserted during parsing when handling
declarators and parameter declarations of the built in types.

This method of lazy expansion does not work with HLSL templates because
template declarators in dependent contexts are not handled by the
parser, so they bypass the code path that generates method definitions
(see #4315).

This change alters how we lazy initialize types. Instead of
lazy-initializing in parsing, this change lazy initializes when the
type is required to be complete. This is accomplished by creating the
built in type objects as incomplete decls, and adding an override for
`CompleteType` to the `HLSLExternalSource`.

This change simplifies our code because we can use the type's
`IsCompleteDefinition` flag to track types that have been completed
instead of our own bitmask system.

Fixes #4315

### CODE REVIEW

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -5117,20 +5113,21 @@ class HLSLExternalSource : public ExternalSemaSource {
...
+    if(Tag->isCompleteDefinition() || !isa<CXXRecordDecl>(Tag))
       return;
-    CXXRecordDecl *recordDecl = const_cast<CXXRecordDecl *>(GetRecordDeclForBuiltInOrStruct(qt->getAsCXXRecordDecl()));
+
+    CXXRecordDecl *recordDecl = cast<CXXRecordDecl>(Tag);
+    if (auto TDecl = dyn_cast<ClassTemplateSpecializationDecl>(recordDecl))
+      recordDecl = TDecl->getSpecializedTemplate()->getTemplatedDecl();
+
+    if (recordDecl->isCompleteDefinition())
+      return;
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:5125]: Is this necessary? I think there's only one implementation of `isCompleteDefinition()`. So if it didn't bail above, it won't bail here.

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 2]
```diff
@@ -12688,16 +12684,12 @@ bool Sema::DiagnoseHLSLDecl(Declarator &D, DeclContext *DC, Expr *BitWidth,
...
-    // Add methods if not ready.
-    hlslSource->AddHLSLObjectMethodsIfNotReady(qt);
   } else if (qt->isArrayType()) {
     QualType eltQt(qt->getArrayElementTypeNoTypeQual(), 0);
     while (eltQt->isArrayType())
       eltQt = QualType(eltQt->getArrayElementTypeNoTypeQual(), 0);
 
     if (hlsl::IsObjectType(this, eltQt, &bDeprecatedEffectObject)) {
-      // Add methods if not ready.
-      hlslSource->AddHLSLObjectMethodsIfNotReady(eltQt);
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:12700]: Where do these get "completed" now? Looks like RequireCompleteType is called all over the place?

**Review by pow2clk — APPROVED** [review]
Looks good, just a small suggestion and an ignorant question

File: tools/clang/lib/Sema/SemaHLSL.cpp (hunk 1 above)
Comment (llvm-beanz) [reply tools/clang/lib/Sema/SemaHLSL.cpp:5125]: It’s a different Decl. The first call might be safe to omit because we shouldn’t get there without it being incomplete. The second call is on the template decl rather than the specialization decl. Because of the way clang recursively resolves templates the two don’t always agree.

File: tools/clang/lib/Sema/SemaHLSL.cpp (hunk 2 above)
Comment (llvm-beanz) [reply tools/clang/lib/Sema/SemaHLSL.cpp:12700]: This is the best part. Clang enforces C rules for requiring completeness. Any use of a type that requires completeness in C also requires it in HLSL. Whenever a type is required to be complete, but is not, clang calls out to the External AST source (if available) to complete the type. This preserves our laziness, but through clang’s built in methods.

**Comment by pow2clk** [comment]
sounds good!

**Comment by llvm-beanz** [comment]
It occurred to me that I could nest the second `isCompleteDefinition` check under the if statement that gates the `recordDecl` being different. In the most common cases that if block is executed, but it isn't always.
