### PR TITLE
New barrier DXIL Op fixes for Validation and RDAT function compatibility info

### LINKED ISSUE #6266: Barrier ops: fix legal models and stages for RDAT
`OP::GetMinShaderModelAndMask`: account for new barrier ops for legal shader stages and minimum shader model, including potential for translation.  Add D3DReflect RDAT tests for scenarios.  This impacts the validated RDAT blob, so it's a DXIL container breaking change and should be prioritized first.

### PR DESCRIPTION
**Pull request by tex3d**
Fix barrier allowed ops and flags by shader kind

New barrier operations lacked validation and for RDAT info: had incorrect min target and shader stage flags.

- Identify barrier DXIL operations with new `is_barrier` in `hctdb.py` and generated `OP::IsDxilOpBarrier`.
- Identify when a barrier op requires shader stage with group (compute-like stage), or when it requires node memory.
- Add new `OptFeatureInfo_RequiresGroup` to identify function only compatible with a shader stage with a visible group for access to groupshared memory or use of group sync.
- Translate to original `BarrierMode` when compatible; adds `BarrierMode::Invalid` to identify invalid cases.
- Account for `DXIL::MemoryTypeFlags::AllMemory` being allowed and auto-masked by driver.
- Properly set min shader model and compatible shader stage flags.
- Validate barrier for shader stage.
- Added new barriers to counters which were missing.

Adressing parts of: #6256 and #6292
Fixes #6266

### CODE REVIEW

File: lib/DXIL/DxilOperations.cpp [hunk 1]
```diff
@@ -2876,6 +2876,128 @@ bool OP::IsDxilOpFeedback(OpCode C) {
...
+    if (isa<ConstantInt>(barrier.get_MemoryTypeFlags())) {
+      memoryTypeFlags = barrier.get_MemoryTypeFlags_val();
+    }
+    if (isa<ConstantInt>(barrier.get_SemanticFlags())) {
+      semanticFlags = barrier.get_SemanticFlags_val();
+    }
+    // If the memory type is AllMemory, masking inapplicable flags is allowed.
+    if (memoryTypeFlags != (unsigned)DXIL::MemoryTypeFlag::AllMemory) {
+      if (memoryTypeFlags & ((unsigned)DXIL::MemoryTypeFlag::NodeInputMemory |
+                             (unsigned)DXIL::MemoryTypeFlag::NodeOutputMemory))
```
Comment (pow2clk) [inline lib/DXIL/DxilOperations.cpp:2978]: Nit: Having this exception in multiple places makes me a little nervous. It might be safer to have a utility function that does this for you.

File: lib/DXIL/DxilOperations.cpp [hunk 2]
```diff
@@ -3249,20 +3381,23 @@ void OP::GetMinShaderModelAndMask(const llvm::CallInst *CI,
...
-  if (opcode == DXIL::OpCode::Barrier) {
-    // Barrier mode should be a constant, but be robust to non-constants here.
-    if (isa<ConstantInt>(
-            CI->getArgOperand(DxilInst_Barrier::arg_barrierMode))) {
-      DxilInst_Barrier barrier(const_cast<CallInst *>(CI));
-      unsigned mode = barrier.get_barrierMode_val();
-      if (mode != (unsigned)DXIL::BarrierMode::UAVFenceGlobal) {
-        mask &= SFLAG(Library) | SFLAG(Compute) | SFLAG(Amplification) |
-                SFLAG(Mesh) | SFLAG(Node);
+  // Barrier requiring node or group limit shdaer kinds.
```
Comment (pow2clk) [inline lib/DXIL/DxilOperations.cpp:3384]: typo: shdaer -> shader

File: lib/DXIL/DxilOperations.cpp [hunk 3]
```diff
@@ -3249,20 +3381,23 @@ void OP::GetMinShaderModelAndMask(const llvm::CallInst *CI,
...
+  if (IsDxilOpBarrier(opcode)) {
+    // TODO: if BarrierByMemoryType, check if translatable, or set min to 6.8.
```
Comment (pow2clk) [inline lib/DXIL/DxilOperations.cpp:3386]: Looks like that's what the code does? Is something still missing here?

File: tools/clang/test/HLSLFileCheck/d3dreflect/amp-groupshared.hlsl [hunk 4]
```diff
@@ -38,7 +38,7 @@
 // CHECK:      PayloadSizeInBytes: 0
 // CHECK:      AttributeSizeInBytes: 0
 // CHECK:      FeatureInfo1: 0
-// CHECK:      FeatureInfo2: 0
+// CHECK:      FeatureInfo2: (Opt_RequiresGroup)
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/amp-groupshared.hlsl:41]: Reaping the benefits of pretty printing! 😄

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_samplecmpgradbias.hlsl [hunk 5]
```diff
@@ -60,7 +60,7 @@ void samplecmpbias() {
 // RDAT:   MinShaderTarget: 0x50068
 
 [shader("compute")]
-[numthreads(1,1,1)]
+[numthreads(4,1,1)]
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_samplecmpgradbias.hlsl:63]: I see why this is required. I'm not sure what about this change enforced that requirement.

File: tools/clang/tools/dxcompiler/dxcdisassembler.cpp [hunk 6]
```diff
@@ -355,6 +355,7 @@ static_assert(_countof(g_pFeatureInfoNames) == ShaderFeatureInfoCount,
 
 PCSTR g_pOptFeatureInfoNames[] = {
     "Function uses derivatives",
+    "Function requires group",
```
Comment (pow2clk) [inline tools/clang/tools/dxcompiler/dxcdisassembler.cpp:358]: nit: more bikeshedding, but maybe "visible group"?

**Review by pow2clk — APPROVED** [review]
Looks good. I have some very minor nits you might choose to address or not.

File: include/dxc/DXIL/DxilInstructions.h [hunk 7]
```diff
@@ -8856,6 +8856,15 @@ struct DxilInst_BarrierByNodeRecordHandle {
   void set_object(llvm::Value *val) { Instr->setOperand(1, val); }
   llvm::Value *get_SemanticFlags() const { return Instr->getOperand(2); }
   void set_SemanticFlags(llvm::Value *val) { Instr->setOperand(2, val); }
```
[the remark this answers is not in the document]
Comment (tex3d) [reply include/dxc/DXIL/DxilInstructions.h:8858]: `is_const - True` in `hctdb.py` doesn't mean you can't set the argument `llvm::Value`, it means the value must be an immediate `llvm::Constant` value  We don't do additional validation upon setting the value to make sure it's `llvm::Constant` though.  More validation in these generated helpers could be useful, but I don't think it's within the scope of this change.

File: utils/hct/hctdb.py [hunk 8]
```diff
@@ -685,12 +692,20 @@ def populate_categories_and_models(self):
...
+            self.name_idx[i].is_barrier = True
+            self.name_idx[i].shader_model = 6, 8
+            self.name_idx[i].shader_model_translated = 6, 0
+        for i in "BarrierByMemoryHandle".split(","):
+            # included in Synchronization category
+            self.name_idx[i].is_barrier = True
+            self.name_idx[i].shader_model = 6, 8
+        for i in "BarrierByNodeRecordHandle".split(","):
+            # included in Synchronization category
+            self.name_idx[i].is_barrier = True
```
[the remark this answers is not in the document]
Comment (tex3d) [reply utils/hct/hctdb.py:706]: True for these, the prior one was to capture the flag for all barrier ops, including the pre-existing one.  We could remove it here if you want.  The reason the earlier addition is where it is was due to where `Barrier` was placed in the `Synchronization` category.  That could be moved, but it wouldn't make any difference of course.

File: tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_samplecmpgradbias.hlsl (hunk 5 above)
Comment (tex3d) [reply tools/clang/test/HLSLFileCheck/d3dreflect/rdat_mintarget/sm68_samplecmpgradbias.hlsl:63]: Ah, the change that enforces this requirement was separated into another branch for independent PR, but forgot to move this change I guess.  Should I remove it or leave it (it is correct).

File: lib/DXIL/DxilModule.cpp [hunk 9]
```diff
@@ -314,15 +314,15 @@ void DxilModule::CollectShaderFlagsForModule(ShaderFlags &Flags) {
   for (auto &itInfo : m_FuncToShaderCompat)
     Flags.CombineShaderFlags(itInfo.second.shaderFlags);
 
-  // Clear UsesDerivatives flag for module, making sure
-  // DerivativesInMeshAndAmpShaders is set for MS/AS.
+  const ShaderModel *SM = GetShaderModel();
```
Comment (bob80905) [inline lib/DXIL/DxilModule.cpp:317]: Why not throw out this variable entirely and use m_pSM?

File: utils/hct/hctdb.py (hunk 8 above)
[the remark this answers is not in the document]
Comment (bob80905) [reply utils/hct/hctdb.py:700]: I also don't like this assignment method, the for loop isn't really being used. Personally I would just say b = "Barrier" and sub in b for the name_idx index, so that the for loops can all be removed. Different variables for the different strings too.
