### PR TITLE
[spirv] Handle invalid arg for residency code.

### LINKED ISSUE #3045: [SPIRV] Invalid shader crashes compiler
Repro:

```
struct Jasper {
    float4 asdf;
};

StructuredBuffer<uint> g_input : register(t0, space0);
RWStructuredBuffer<uint> g_output : register(u1, space0);
ConstantBuffer<Jasper> g_constant : register(b2, space0);
StructuredBuffer<uint> g_bindlessInput[] : register(t0, space1);
Texture2D<uint> g_texture2d : register(t0, space2);
RWTexture2D<uint> g_rwtexture2d : register(u1, space3);


[numthreads(64, 1, 1)]
void main(int threadId: SV_DispatchThreadID)
{
    g_output[threadId] = g_input[threadId] + g_constant.asdf + g_bindlessInput[threadId][threadId] + g_texture2d.Load(0, 0) + g_rwtexture2d.Load(0, 0);
}
```

Invoking the compiler with like this outputs an error:
```
> dxc -Tcs_6_3 repro.hlsl
repro.hlsl:16:24: warning: implicit truncation of vector type [-Wconversion]
    g_output[threadId] = g_input[threadId] + g_constant.asdf + g_bindlessInput[threadId][threadId] + g_texture2d.Load(0, 0) + g_rwtexture2d.Load(0, 0);
                       ^
repro.hlsl:16:149: error: cannot compile this unexpected cast lvalue yet
    g_output[threadId] = g_input[threadId] + g_constant.asdf + g_bindlessInput[threadId][threadId] + g_texture2d.Load(0, 0) + g_rwtexture2d.Load(0, 0);
```

However, adding -spirv crashes the compiler; instead yielding no output:
```
> dxc -Tcs_6_3 -spirv repro.hlsl

```

Relevant callstack:

```
>	[Inline Frame] dxcompiler.dll!spvtools::opt::Instruction::opcode() Line 219	C++
 	dxcompiler.dll!spvtools::opt::Instruction::GetBaseAddress() Line 228	C++
 	[Inline Frame] dxcompiler.dll!spvtools::opt::MemPass::GetPtr(unsigned int) Line 108	C++
 	dxcompiler.dll!spvtools::opt::MemPass::GetPtr(spvtools::opt::Instruction * ip, unsigned int * varId) Line 132	C++
 	dxcompiler.dll!spvtools::opt::AggressiveDCEPass::AggressiveDCE(spvtools::opt::Function * func) Line 364	C++
 	[Inline Frame] dxcompiler.dll!std::_Func_class<bool,spvtools::opt::Function *>::operator()(spvtools::opt::Function * <_Args_0>) Line 899	C++
 	dxcompiler.dll!spvtools::opt::IRContext::ProcessCallTreeFromRoots(std::function<bool __cdecl(spvtools::opt::Function *)> & pfn, std::queue<unsigned int,std::deque<unsigned int,std::allocator<unsigned int>>> * roots) Line 899	C++
 	dxcompiler.dll!spvtools::opt::IRContext::ProcessEntryPointCallTree(std::function<bool __cdecl(spvtools::opt::Function *)> & pfn) Line 854	C++
 	dxcompiler.dll!spvtools::opt::AggressiveDCEPass::ProcessImpl() Line 655	C++
 	dxcompiler.dll!spvtools::opt::Pass::Run(spvtools::opt::IRContext * ctx) Line 41	C++
 	dxcompiler.dll!spvtools::opt::PassManager::Run(spvtools::opt::IRContext * context) Line 51	C++
 	dxcompiler.dll!spvtools::Optimizer::Run(const unsigned int * original_binary, const unsigned __int64 original_binary_size, std::vector<unsigned int,std::allocator<unsigned int>> * optimized_binary, spv_optimizer_options_t * const opt_options) Line 576	C++
 	dxcompiler.dll!clang::spirv::SpirvEmitter::spirvToolsOptimize(std::vector<unsigned int,std::allocator<unsigned int>> * mod, std::string * messages) Line 11661	C++
 	dxcompiler.dll!clang::spirv::SpirvEmitter::HandleTranslationUnit(clang::ASTContext & context) Line 603	C++
 	dxcompiler.dll!clang::ParseAST(clang::Sema & S, bool PrintStats, bool SkipFunctionBodies) Line 162	C++
 	dxcompiler.dll!clang::ASTFrontendAction::ExecuteAction() Line 554	C++
 	dxcompiler.dll!clang::FrontendAction::Execute() Line 469	C++
 	dxcompiler.dll!DxcCompiler::Compile(const DxcBuffer * pSource, const wchar_t * * pArguments, unsigned int argCount, IDxcIncludeHandler * pIncludeHandler, const _GUID & riid, void * * ppResult) Line 736	C++
 	dxcompiler.dll!hlsl::DxcCompilerAdapter::WrapCompile(int bPreprocess, IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult, wchar_t * * ppDebugBlobName, IDxcBlob * * ppDebugBlob) Line 1376	C++
 	dxcompiler.dll!hlsl::DxcCompilerAdapter::CompileWithDebug(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult, wchar_t * * ppDebugBlobName, IDxcBlob * * ppDebugBlob) Line 1282	C++
 	dxcompiler.dll!hlsl::DxcCompilerAdapter::Compile(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult) Line 72	C++
 	dxc.exe!DxcContext::Compile() Line 810	C++
 	dxc.exe!dxc::main(int argc, const wchar_t * * argv_) Line 1264	C++
 	[Inline Frame] dxc.exe!invoke_main() Line 90	C++
 	dxc.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ffb002d7bd4()	Unknown
 	ntdll.dll!00007ffb00a2ce51()	Unknown
```

### PR DESCRIPTION
**Pull request by ehsannas**
Fixes #3045

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -3216,6 +3216,13 @@ SpirvInstruction *SpirvEmitter::processBufferTextureLoad(
     return nullptr;
   }
 
+  if (residencyCode && residencyCode->isRValue()) {
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:3219]: What happens if `residencyCode` is `nullptr`?
Why don't we change this condition to `if (residencyCode == nullptr || residencyCode->isRValue()) {`?

Comment (ehsannas) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:3219]: this function (`SpirvEmitter::processBufferTextureLoad`) handles the Load methods. There are 2 Load methods that are defined for textures and buffer: one method that just does the load, and one method that does the load and also returns the status of the operation.

For example, for Texture2D we have these 2 methods: ([spec](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2d-load))
```
Load(int,int) : Reads texture data.
Load(int,int,uint) : Reads texture data and returns status of the operation.
```
In the first method, `residencyCode` is in fact `nullptr` and it should not be an error.

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:3219]: Got it. It would be better to add a comment to briefly explain it.
