### PR TITLE
Handles SpirvIntrinsicInstruction barriers in CapabilityVisitor.

### LINKED ISSUE #7671: [SPIR-V] Internal Compiler error: llvm::cast<X>() argument of incompatible type!
I have a shader that was working on commit [71f2766](https://github.com/Devsh-Graphics-Programming/DirectXShaderCompiler/tree/71f2766da918d33d34fefac270fdee983a06dd20) which would be DXC commit [0beaa76](https://github.com/Devsh-Graphics-Programming/DirectXShaderCompiler/commit/0beaa767f7712f0ed0ab72e1e17cb94c25f84c34)

It's no longer working after merging DXC [d64d34c](https://github.com/Devsh-Graphics-Programming/DirectXShaderCompiler/commit/d64d34ced89e2ac407d151b8f04516684fc41ed0). It now throws the error in the title when trying to compile, so whatever broke it is somewhere inbetween.

Here's the Godbolt with a repro: https://godbolt.org/z/7jGfzW6TK

### PR DESCRIPTION
**Pull request by danbrown-amd**
Fixes #7671.

### CODE REVIEW

File: tools/clang/lib/SPIRV/CapabilityVisitor.cpp [hunk 1]
```diff
@@ -615,9 +615,10 @@ bool CapabilityVisitor::visitInstruction(SpirvInstruction *instr) {
   }
   case spv::Op::OpControlBarrier:
   case spv::Op::OpMemoryBarrier: {
-    auto barrier = cast<SpirvBarrier>(instr);
-    if ((bool)(barrier->getMemorySemantics() &
-               spv::MemorySemanticsMask::OutputMemoryKHR)) {
+    auto barrier = dyn_cast<SpirvBarrier>(instr);
+    if (!barrier || (barrier->getMemorySemantics() &
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/CapabilityVisitor.cpp]: If I understand the test correctly, there is in inline spir-v instruction to generate a barrier. This instruction will have one of the Barrier opcodes, but will not be a SpirvBarrier isntructions.

In this case, I don't think we should be "blindly" requesting the vulkan version and capability because it may not be needed.

For inline spir-v it is the responsibility of the user to pick the correct vulkan version and annotate with the correct capabilities to generate valid code, so I would change this to:

```suggestion
   // barrier will be null if the instruction was generated from inline spir-v. In that case, it is the user's responsibility to
   // to ensure the correct capabilities are added.
    if (barrier && (barrier->getMemorySemantics() &
```

Comment (danbrown-amd) [reply tools/clang/lib/SPIRV/CapabilityVisitor.cpp]: Done.
