### PR TITLE
[SM6.10] Make DxilStructAnnotation aware of target types

### LINKED ISSUE #8279: [SM6.10] Invalid codegen when LinAlgMatrix type is used in a class
**Description**
The compiler fails to generate correct IR when a struct or class contains a LinAlgMatrix attributed type.

**Steps to Reproduce**

```hlsl
class MyMatrix {
  using MyHandleT = __builtin_LinAlgMatrix [[__LinAlgMatrix_Attributes(9, 4, 4, 0, 1)]];
  MyHandleT handle;

  static MyMatrix Splat(float Val) {
    MyMatrix Result;
    __builtin_LinAlg_FillMatrix(Result.handle, Val);
    return Result;
  }
};

[numthreads(4, 4, 4)]
void main() {
  MyMatrix MatA = MyMatrix::Splat(1.0f);
}
```
https://godbolt.org/z/KKnfKzsc5

**Actual Behavior**
```
define void @main() {
  call void @llvm.dbg.value(metadata float 1.000000e+00, i64 0, metadata !32, metadata !33), !dbg !34 ; var:"Val" !DIExpression() func:"Splat"
  %1 = call %dx.types.LinAlgMatrixC9M4N4U0S1 @dx.op.linAlgFillMatrix.mC9M4N4U0S1.f32(i32 -2147483636, float 1.000000e+00), !dbg !36 ; line:8 col:5  ; LinAlgFillMatrix(value)
  call void @llvm.trap(), !dbg !36 ; line:8 col:5
  unreachable
}
```
**Environment**
- DXC version main as of 3/19/26

### PR DESCRIPTION
**Pull request by hekota**
Update `DxilStructAnnotation` to be aware of target types. Otherwise the annotation would declare a struct with a single LinAlg Matrix type as empty, leading to invalid codegen.

Declaration names match the style of the surrounding code. 

Fixes #8279

### CODE REVIEW

File: include/dxc/DXIL/DxilTypeSystem.h [hunk 1]
```diff
@@ -148,10 +148,12 @@ class DxilStructAnnotation {
   void SetCBufferSize(unsigned size);
   void MarkEmptyStruct();
   bool IsEmptyStruct();
-  // Since resources don't take real space, IsEmptyBesidesResources
-  // determines if the structure is empty or contains only resources.
-  bool IsEmptyBesidesResources();
+  // Since resources and target types don't take real space,
+  // IsEmptyBesidesResourcesAndTargetTypes() determines if the structure is
+  // empty or contains only resources or target types.
+  bool IsEmptyBesidesResourcesAndTargetTypes();
```
Comment (damyanp) [inline include/dxc/DXIL/DxilTypeSystem.h]: Any reason this isn't const, other than the original one wasn't const?

File: include/dxc/DXIL/DxilTypeSystem.h [hunk 2]
```diff
@@ -174,6 +176,15 @@ class DxilStructAnnotation {
...
   } m_ResourcesContained = HasResources::False;
+
+  void SetContainsTargetTypes();
+  // HasTargetTypes::Only will be set on MarkEmptyStruct() when
+  // HasTargetTypes::True
+  enum class HasTargetTypes {
+    True,
+    False,
+    Only
+  } m_TargetTypesContained = HasTargetTypes::False;
```
Comment (damyanp) [inline include/dxc/DXIL/DxilTypeSystem.h:187]: Nit: I think this would be easier to read with some more spacing.


```suggestion

  // HasTargetTypes::Only will be set on MarkEmptyStruct() when
  // HasTargetTypes::True
  enum class HasTargetTypes {
    True,
    False,
    Only
  };
  
  HasTargetTypes m_TargetTypesContained = HasTargetTypes::False;
```

But I can see this is following a pre-existing pattern so maybe we can ignore this.

File: include/dxc/DXIL/DxilTypeSystem.h [hunk 3]
```diff
@@ -343,6 +354,9 @@ class DxilTypeSystem {
   // Determines whether type is a resource or contains a resource
   bool IsResourceContained(llvm::Type *Ty);
 
+  // Determines whether type is a target type or contains a target type
+  bool IsTargetTypeContained(llvm::Type *Ty);
```
Comment (damyanp) [inline include/dxc/DXIL/DxilTypeSystem.h]: Should this be const?

File: lib/DXIL/DxilTypeSystem.cpp [hunk 4]
```diff
@@ -872,6 +890,24 @@ bool DxilTypeSystem::IsResourceContained(llvm::Type *Ty) {
...
+    Ty = Ty->getArrayElementType();
+
+  if (auto ST = dyn_cast<StructType>(Ty)) {
+    if (dxilutil::IsHLSLKnownTargetType(Ty)) {
+      return true;
+    } else if (auto SA = GetStructAnnotation(ST)) {
+      if (SA->ContainsTargetTypes())
+        return true;
+    }
+  }
```
Comment (damyanp) [inline lib/DXIL/DxilTypeSystem.cpp]:
```suggestion
  if (auto *ST = dyn_cast<StructType>(Ty)) {
    if (dxilutil::IsHLSLKnownTargetType(Ty)) {
      return true;
    } else if (auto *SA = GetStructAnnotation(ST)) {
      if (SA->ContainsTargetTypes())
        return true;
    }
  }
```

File: lib/DXIL/DxilTypeSystem.cpp [hunk 5]
```diff
@@ -854,24 +872,42 @@ void DxilTypeSystem::SetMinPrecision(bool bMinPrecision) {
...
   }
   return false;
 }
 
+bool DxilTypeSystem::IsTargetTypeContained(llvm::Type *Ty) const {
+  // strip pointer/array
+  if (Ty->isPointerTy())
+    Ty = Ty->getPointerElementType();
+  if (Ty->isArrayTy())
+    Ty = Ty->getArrayElementType();
```
Comment (bogner) [inline lib/DXIL/DxilTypeSystem.cpp:897]: Is it deliberate that this only handles pointers to arrays, and not arrays of pointers or other more complicated nestings?

File: tools/clang/test/CodeGenDXIL/hlsl/linalg/matrix-target-type-in-struct.hlsl [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+    return Result;
+  }
+};
+
+[numthreads(4, 4, 4)]
+void main() {
+  MyMatrix MatA = MyMatrix::Splat(1.0f);
+}
+
+// CHECK:  %1 = call %dx.types.LinAlgMatrixC9M4N4U0S1 @dx.op.linAlgFillMatrix.mC9M4N4U0S1.f32(i32 -2147483636, float 1.000000e+00)  ; LinAlgFillMatrix(value)
```
Comment (bogner) [inline tools/clang/test/CodeGenDXIL/hlsl/linalg/matrix-target-type-in-struct.hlsl]: Usually better to avoid relying on the exact value names. We can do that by capturing the variable or, since we don't use it again, just omitting it.
```suggestion
// CHECK: call %dx.types.LinAlgMatrixC9M4N4U0S1 @dx.op.linAlgFillMatrix.mC9M4N4U0S1.f32(i32 -2147483636, float 1.000000e+00)  ; LinAlgFillMatrix(value)
```

File: lib/DXIL/DxilTypeSystem.cpp [hunk 7]
```diff
@@ -854,24 +872,42 @@ void DxilTypeSystem::SetMinPrecision(bool bMinPrecision) {
...
+
+  if (auto *ST = dyn_cast<StructType>(Ty)) {
+    if (dxilutil::IsHLSLKnownTargetType(Ty)) {
+      return true;
+    } else if (auto *SA = GetStructAnnotation(ST)) {
+      if (SA->ContainsTargetTypes())
+        return true;
+    }
```
Comment (V-FEXrt) [inline lib/DXIL/DxilTypeSystem.cpp]: nit:
```suggestion
    if (dxilutil::IsHLSLKnownTargetType(Ty))
      return true;
    if (auto *SA = GetStructAnnotation(ST) && SA->ContainsTargetTypes())
      return true;
```

File: tools/clang/test/CodeGenDXIL/hlsl/linalg/matrix-target-type-in-struct.hlsl [hunk 8]
```diff
@@ -0,0 +1,22 @@
+// REQUIRES: dxil-1-10
+// RUN: %dxc -I %hlsl_headers -T cs_6_10 -enable-16bit-types %s | FileCheck %s
```
Comment (V-FEXrt) [inline tools/clang/test/CodeGenDXIL/hlsl/linalg/matrix-target-type-in-struct.hlsl]: nit: I don't think you are actually using the headers here 
```suggestion
// RUN: %dxc -T cs_6_10 -enable-16bit-types %s | FileCheck %s
```

File: lib/DXIL/DxilTypeSystem.cpp (hunk 7 above)
Comment (hekota) [reply lib/DXIL/DxilTypeSystem.cpp]: I don't think you can do that when SA is declared in the same if statement.

File: lib/DXIL/DxilTypeSystem.cpp (hunk 5 above)
Comment (hekota) [reply lib/DXIL/DxilTypeSystem.cpp:897]: I think so. We don't support array of pointers to resources or target types.

File: lib/DXIL/DxilTypeSystem.cpp (hunk 7 above)
Comment (V-FEXrt) [reply lib/DXIL/DxilTypeSystem.cpp]: in that case, this should still work
```suggestion
    if (dxilutil::IsHLSLKnownTargetType(Ty))
      return true;
    if (auto *SA = GetStructAnnotation(ST))
      if (SA->ContainsTargetTypes())
        return true;
```

File: lib/DXIL/DxilTypeSystem.cpp [hunk 9]
```diff
@@ -899,10 +899,10 @@ bool DxilTypeSystem::IsTargetTypeContained(llvm::Type *Ty) const {
   if (auto *ST = dyn_cast<StructType>(Ty)) {
     if (dxilutil::IsHLSLKnownTargetType(Ty))
       return true;
-    else if (auto *SA = GetStructAnnotation(ST)) {
+    else if (auto *SA = GetStructAnnotation(ST))
       if (SA->ContainsTargetTypes())
         return true;
-    }
+  }
```
Comment (V-FEXrt) [inline lib/DXIL/DxilTypeSystem.cpp:905]: Is this diff right? It look like you only deleted one curly bracket, was there an extra one somewhere?

Comment (hekota) [reply lib/DXIL/DxilTypeSystem.cpp:905]: This is fixing a build break. There was a curly bracket missing and the ones around `if else` are not needed.
