### PR TITLE
[SPIRV] Update spir-v submodules and handle multi-dim array

### LINKED ISSUE #7922: [SPIR-V] Arrays of arrays of resources are unsupported
**Description**
Using `RWTexture2D<float4>[16][32]` for example produces invalid SPIRV. Annotating this resource with `[[vk::image_format("unknown")]]` produces a validation error. It seems like this feature is unsupported, while with DXIL this works okay (though it flattens it to a 1D array).

**Steps to Reproduce**
```cpp
//dxc -spirv -E mainCompute -T cs_6_5
RWTexture2D<float4> _test[16][32];

[numthreads(8, 8, 1)]
void mainCompute(uint2 id : SV_DispatchThreadID) {
    _test[0][0][id] = float4(id, 0, 1);
}
```
```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-UniformConstant-04655] UniformConstant OpVariable <id> '4[%_test]' has illegal type.
Variables identified with the UniformConstant storage class are used only as handles to refer to opaque resources. Such variables must be typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, OpTypeAccelerationStructureKHR, or an array of one of these types.
  %_test = OpVariable %_ptr_UniformConstantarrarr_type_2d_image_uint_32_uint_16 UniformConstant

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

And
```cpp
[[vk::image_format("unknown")]] RWTexture2D<float4> _test[16][32];

[numthreads(8, 8, 1)]
void mainCompute(uint2 id : SV_DispatchThreadID) {
    _test[0][0][id] = float4(id, 0, 1);
}
```
```
C:\local\Temp\ea8c1737-a2f4-421d-a3b7-88e1c5278ee6.hlsl:2:3: error: 'image_format' attribute only applies to RWTextures, Buffers and RWBuffers
[[vk::image_format("unknown")]] RWTexture2D<float4> _test[16][32];
  ^
```

**Actual Behavior**
Spirv to support this with arrays of arrays (if possible by spec), otherwise flattening the array or throwing an error that's clearer about lack of multi dimensional descriptor array support.

**Environment**
- DXC version: latest
- Host Operating System: N/A

### PR DESCRIPTION
**Pull request by s-perron**
We are updating the spir-v submodules. They contain a new pass that will linearize multi-dimensional resource arrays, and call the combine access chain pass.

This means we need to fix up some tests, and we want to make sure that we can properly handle multi-dimensional resource array in DXC.

Fixes #7922

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -1263,6 +1263,21 @@ SpirvVariable *DeclResultIdMapper::createExternVar(const VarDecl *var,
...
+  if (const auto *arrayType = astContext.getAsConstantArrayType(type)) {
+    if (astContext.getAsConstantArrayType(arrayType->getElementType())) {
+      QualType elemType = arrayType->getElementType();
+      while (const auto *innerArrayType =
+                 astContext.getAsConstantArrayType(elemType)) {
+        elemType = innerArrayType->getElementType();
+      }
+      if (hlsl::IsHLSLResourceType(elemType))
+        needsLegalization = true;
+    }
```
Comment (Keenuts) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1278]:
```suggestion
    QualType elemType = arrayType->getElementType();
    while (const auto *innerArrayType =
                 astContext.getAsConstantArrayType(elemType)) {
      elemType = innerArrayType->getElementType();
    }
    if (hlsl::IsHLSLResourceType(elemType))
      needsLegalization = true;
```

Comment (Keenuts) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1278]: ahh nevermind, missed the negative case.
