### PR TITLE
[spirv] use rvalue for array index

### LINKED ISSUE #3553: [SPIR-V] HLSL 2021 Template support
I just noticed that #3533 got merged into the hlsl-2021 branch so I had to give it a go since this is something we're very much looking forward to. In SPIR-V mode it looks like there's still some invalid SPIR-V being generated for the following code:

```
[[vk::binding(0, 0)]] ByteAddressBuffer g_stuff[]: register(t0, space0);
[[vk::binding(0, 0)]] RWByteAddressBuffer g_rwStuff[]: register(u0, space0);

struct BindlessBuffer {
    uint handle;

    template<typename T>
    T Load(uint offset) {
        return g_stuff[this.handle].Load<T>(offset * sizeof(T));
    }

    template<typename T>
    void Store(uint offset, T value) {
        return g_rwStuff[this.handle].Store<T>(offset * sizeof(T), value);
    }
};

struct BindingsOffset {
    BindlessBuffer bindingsOffset;
    uint userData0;
    uint userData1;
    uint userData2;
};

struct Bindings {
    uint data;
};

[[vk::push_constant]] ConstantBuffer<BindingsOffset> g_bindingsOffset;

[numthreads(1, 1, 1)]
void main(uint tidx : SV_DispatchThreadId) {
    Bindings b = g_bindingsOffset.bindingsOffset.Load<Bindings>(0);
    b.data = 12;
    g_bindingsOffset.bindingsOffset.Store<Bindings>(0, b);
}
```

This works and outputs some DXIL that seems to do the right thing:
```cmd
dxc /Tcs_6_6 /Emain -enable-templates test.hlsl
```

This doesn't work, giving the validation error below:
```cmd
dxc /Tcs_6_6 /Emain -enable-templates -spirv test.hlsl
```

Error message:
```
fatal error: generated SPIR-V is invalid: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
  %25 = OpAccessChain %_ptr_PushConstant_type_RWByteAddressBuffer %g_rwStuff %24

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### PR DESCRIPTION
**Pull request by jaebaek**
The newly introduced template support generates a template instance
of a struct method that has a slightly different AST from the one
with hard-coded type. The template instance misses LValueToRValue
cast for an array index. This PR lets SPIR-V backend uses rvalue for
an array index. If the array index expression is not rvalue, it reports
an error.

Fixes #3553

### CODE REVIEW

**Comment by jaebaek** [comment]
@pow2clk Hi, #3553 reported an issue of SPIR-V backend when we enable the template support. This PR fixes the issue. I want to send this PR to `hlsl-2021` branch. Is it ok?

**Comment by pow2clk** [comment]
@jaebaek, you are welcome to submit fixes to hlsl-2021. Its purpose is to work out bugs in the template implementation  and even though this isn't directly related to the new template code, it would block further testing along these lines. 

This branch will be merge into the main one when we are satisfied with the quality and this change will be part of that.

**Comment by jaebaek** [comment]
Thanks!

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -6839,7 +6839,12 @@ const Expr *SpirvEmitter::collectArrayStructIndices(
     // The index into an array must be an integer number.
     const auto *idxExpr = indexing->getIdx();
     const auto idxExprType = idxExpr->getType();
-    SpirvInstruction *thisIndex = doExpr(idxExpr);
+    if (idxExpr->isLValue()) {
+      emitError("Index of ArraySubscriptExpr must be rvalue",
+                idxExpr->getExprLoc());
+      return nullptr;
+    }
+    SpirvInstruction *thisIndex = loadIfGLValue(idxExpr);
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:6847]: I'm a bit confused here. If `idxExpr` is LValue, then the code errors out above, right? so does this `loadIfGLValue` get executed if `idxExpr` is an LValue?

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:6854]: Good question. I believe `idxExpr` should never be LValue. If it is LValue, it means the given HLSL code or the AST parser has a bug, because we do not use LValue for the index of an array.

The reason why we use `loadIfGLValue` instead of `doExpr` is because we have some cases that `doExpr` returns SPIR-V instruction with LValue for `idxExpr` with RValue e.g., missing `ImplicitCast<LValueToRValue>` #3620 

I added comments to explain it.

**Review by ehsannas — APPROVED** [review]
