### PR TITLE
Make the location map run per entry point

### LINKED ISSUE #5213: [Spir-V] Vertex shader locations are offset by 1 when compiled with the `lib_6_6` profile
Feel free to close if this is a duplicate. The following shader:

```hlsl
struct V2P
{
    float4 Pos : SV_Position;
    float2 Uv : COLOR0;
};

#define PI (3.14159f)

[shader("vertex")]
V2P VSMain(uint vId : SV_VertexID)
{
    float2 uv = float2((vId << 1) & 2, vId & 2);
    V2P vsOut;
    vsOut.Uv = float2(uv.x, 1.0 - uv.y);
    vsOut.Pos = float4((2.0 * uv) - 1.0, 0.0, 1.0);
    return vsOut;
}

[[vk::binding(0)]] Texture2D<float3> source_tex;
[[vk::binding(1)]] SamplerState samp;

[shader("pixel")]
float4 PSMain(V2P psIn) : SV_Target0
{
    return float4(source_tex.Sample(samp, psIn.Uv), 1.0);
}
```
when compiled with `dxc shaders/blit.hlsl -spirv -T lib_6_6` has the following decorations:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 56
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %VSMain "VSMain" %gl_VertexIndex %gl_Position %out_var_COLOR0
               OpEntryPoint Fragment %PSMain "PSMain" %in_var_COLOR0 %out_var_SV_Target0
               OpExecutionMode %PSMain OriginUpperLeft
               OpSource HLSL 660
               OpName %type_2d_image "type.2d.image"
               OpName %source_tex "source_tex"
               OpName %type_sampler "type.sampler"
               OpName %samp "samp"
               OpName %out_var_COLOR0 "out.var.COLOR0"
               OpName %in_var_COLOR0 "in.var.COLOR0"
               OpName %out_var_SV_Target0 "out.var.SV_Target0"
               OpName %VSMain "VSMain"
               OpName %PSMain "PSMain"
               OpName %type_sampled_image "type.sampled.image"
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %in_var_COLOR0 Location 0
               OpDecorate %out_var_SV_Target0 Location 0
               OpDecorate %out_var_COLOR0 Location 1
               OpDecorate %source_tex DescriptorSet 0
               OpDecorate %source_tex Binding 0
               OpDecorate %samp DescriptorSet 0
               OpDecorate %samp Binding 1
```
`OpDecorate %out_var_COLOR0 Location 1` here is wrong. I think it's counting `OpDecorate %gl_Position BuiltIn Position` falsely as a location.
When compiled with `dxc shaders/blit.hlsl -spirv -T vs_6_6 -E VSMain` the decoration is correct:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 35
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %VSMain "VSMain" %gl_VertexIndex %gl_Position %out_var_COLOR0
               OpSource HLSL 660
               OpName %out_var_COLOR0 "out.var.COLOR0"
               OpName %VSMain "VSMain"
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %out_var_COLOR0 Location 0
```

`dxc --version`: `dxcompiler.dll: 1.7(dev;3759-8c9d92be)`

### LINKED ISSUE #6678: [SPIR-V] Unexpected location decorate conflict between library entrypoints
**Description**
Seems like combining `[[vk::location(X)]]` with multiple entrypoints shader via target `lib_6_X` can yield some problematic error that I believe to be unwanted.

**Steps to Reproduce**
Compiling
```hlsl
struct Vertex {
    [[vk::location(0)]] float3 position : Position;
    [[vk::location(1)]] float4 color : Color;
};

struct Fragment {
    [[vk::location(0)]] float4 sv_position : SV_Position;
    [[vk::location(1)]] float4 color : Color;
};

[shader("vertex")]
Fragment vsmain(in Vertex vertex) {
    Fragment o;
    
    o.sv_position = float4(vertex.position, 1);
    o.color = vertex.color;

    return o;
}

[[vk::location(0)]]
[shader("pixel")]
float4 psmain([[vk::location(0)]] in Fragment fragment) : SV_Target0 {
    return fragment.color;
}
```
using DXC's arguments
```
dxc <shader_file> -T lib_6_6 -spirv
```

**Expected Behavior**
The shader compile successfully and should be equivalent to:
```wgsl
struct Vertex {
    @location(0) position : vec3<f32>,
    @location(1) color : vec4<f32>
};

struct Fragment {
    @builtin(position) sv_position : vec4<f32>,
    @location(1) color : vec4<f32>
};

@vertex
fn vsmain(vertex : Vertex) -> Fragment {
    return Fragment(vec4<f32>(vertex.position, 1), vertex.color);
}

@fragment
fn psmain(fragment : Fragment) -> @location(0) vec4<f32> {
    return fragment.color;
}
```
in WGSL and yields to SPIR-V using Naga:
```spirv
; SPIR-V
; Version: 1.0
; Generator: Khronos; 28
; Bound: 45
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %19 "vsmain" %10 %13 %gl_Position %18
               OpEntryPoint Fragment %42 "psmain" %gl_FragCoord %39 %41
               OpExecutionMode %42 OriginUpperLeft
               OpMemberDecorate %_struct_6 0 Offset 0
               OpMemberDecorate %_struct_6 1 Offset 16
               OpMemberDecorate %_struct_7 0 Offset 0
               OpMemberDecorate %_struct_7 1 Offset 16
               OpDecorate %10 Location 0
               OpDecorate %13 Location 1
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %18 Location 1
               OpDecorate %gl_FragCoord BuiltIn FragCoord
               OpDecorate %39 Location 1
               OpDecorate %41 Location 0
       %void = OpTypeVoid
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
    %v4float = OpTypeVector %float 4
  %_struct_6 = OpTypeStruct %v3float %v4float
  %_struct_7 = OpTypeStruct %v4float %v4float
%_ptr_Input_v3float = OpTypePointer Input %v3float
         %10 = OpVariable %_ptr_Input_v3float Input
%_ptr_Input_v4float = OpTypePointer Input %v4float
         %13 = OpVariable %_ptr_Input_v4float Input
%_ptr_Output_v4float = OpTypePointer Output %v4float
%gl_Position = OpVariable %_ptr_Output_v4float Output
         %18 = OpVariable %_ptr_Output_v4float Output
         %20 = OpTypeFunction %void
    %float_1 = OpConstant %float 1
%_ptr_Output_float = OpTypePointer Output %float
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%gl_FragCoord = OpVariable %_ptr_Input_v4float Input
         %39 = OpVariable %_ptr_Input_v4float Input
         %41 = OpVariable %_ptr_Output_v4float Output
         %19 = OpFunction %void None %20
          %8 = OpLabel
         %12 = OpLoad %v3float %10
         %15 = OpLoad %v4float %13
          %9 = OpCompositeConstruct %_struct_6 %12 %15
               OpBranch %22
         %22 = OpLabel
         %23 = OpCompositeExtract %v3float %9 0
         %24 = OpCompositeConstruct %v4float %23 %float_1
         %25 = OpCompositeExtract %v4float %9 1
         %26 = OpCompositeConstruct %_struct_7 %24 %25
         %27 = OpCompositeExtract %v4float %26 0
               OpStore %gl_Position %27
         %31 = OpAccessChain %_ptr_Output_float %gl_Position %uint_1
         %32 = OpLoad %float %31
         %33 = OpFNegate %float %32
               OpStore %31 %33
         %34 = OpCompositeExtract %v4float %26 1
               OpStore %18 %34
               OpReturn
               OpFunctionEnd
         %42 = OpFunction %void None %20
         %35 = OpLabel
         %38 = OpLoad %v4float %gl_FragCoord
         %40 = OpLoad %v4float %39
         %36 = OpCompositeConstruct %_struct_7 %38 %40
               OpBranch %43
         %43 = OpLabel
         %44 = OpCompositeExtract %v4float %36 1
               OpStore %41 %44
               OpReturn
               OpFunctionEnd

```

**Actual Behavior**
Problematic and unexpected error is reported:
```
shader.hlsl:8:7: error: stage input location #1 already consumed by semantic 'Position'
    [[vk::location(1)]] float4 color : Color;
```
that complain about the `Fragment` color output. 

**Environment**
- DXC version: `dxcompiler.dll: 1.8 - 1.8.2403.37 (11e1318c3); dxil.dll: 1.8(101.8.2403.24)`
- Host Operating System:
  - OS: Windows 11 Pro
  - Version: 22H2
  - Build number: 22621.3593

### PR DESCRIPTION
**Pull request by s-perron**
The code that adds the input and output decoration in the entry points
inputs and outputs assumes that there is a single entry point in the
module. When using the `lib` profile that is not true.

This commit modifies the code so that it groups the stage variables by
entry point, and runs the current code on each group separably.

I hesitate to make this change because it will change the locations for
code that currently works, and will force users to update their
applications accordingly. Or they could modify their shaders
to use explicit locations attributes. Neither is great.

However, the advantage is that this allows the implicit locations to match what would happen if the shader were compiled individually. It also makes the locations more predictable  because change in another shader would change all shader after it. This is a better design, and worth the breakage.

Fixes #6678
Fixes #5213

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -2143,10 +2143,8 @@ bool DeclResultIdMapper::assignLocations(
   return true;
 }
 
-bool DeclResultIdMapper::finalizeStageIOLocations(bool forInput) {
-  if (!checkSemanticDuplication(forInput))
-    return false;
-
+bool DeclResultIdMapper::finalizeStageIOLocationsForASignleEntryPoint(
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2146]: nit:

```suggestion
bool DeclResultIdMapper::finalizeStageIOLocationsForASingleEntryPoint(
```

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 2]
```diff
@@ -2286,6 +2285,29 @@ bool DeclResultIdMapper::finalizeStageIOLocations(bool forInput) {
...
+  return result;
+}
+
+bool DeclResultIdMapper::finalizeStageIOLocations(bool forInput) {
+  if (!checkSemanticDuplication(forInput))
+    return false;
+
+  auto stageVarPerFunction = GetStageVarsPerFunction();
+  for (const auto &functionStageVars : stageVarPerFunction) {
+    if (!finalizeStageIOLocationsForASignleEntryPoint(
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2303]: nit:

```suggestion
    if (!finalizeStageIOLocationsForASingleEntryPoint(
```

File: tools/clang/lib/SPIRV/DeclResultIdMapper.h [hunk 3]
```diff
@@ -627,6 +627,22 @@ class DeclResultIdMapper {
...
+
+  /// \brief Decorates all stage variables in `functionStageVars` with proper
+  /// location and returns true on success.
+  ///
+  /// It is assumed that all variables in `functionStageVars` belong to the same
+  /// entry point.
+  ///
+  /// This method will write the location assignment into the module under
+  /// construction.
+  bool finalizeStageIOLocationsForASignleEntryPoint(
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.h:643]: nit:

```suggestion
  bool finalizeStageIOLocationsForASingleEntryPoint(
```

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 4]
```diff
@@ -2286,6 +2285,29 @@ bool DeclResultIdMapper::finalizeStageIOLocations(bool forInput) {
   return assignLocations(vars, nextLocs, &stageVariableLocationInfo);
 }
 
+llvm::DenseMap<const SpirvFunction *, SmallVector<StageVar, 8>>
+DeclResultIdMapper::GetStageVarsPerFunction() {
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2289]: nit: I believe member functions begin with lowercase letters (ie, `getStageVarsPerFunction`) in the rest of our codebase

**Review by cassiebeckley — APPROVED** [review]
This seems reasonable to me.

**Review by Keenuts — APPROVED** [review]
LGTM. I agree with the behavior change, would expect each stage to behave independently too.
