### PR TITLE
Set default floating-point environment at compiler boundaries

### LINKED ISSUE #1607: Constant folding and division by zero and fxc
Constant folding does not behave the same way as fxc

Hello, 

If you enable on a cpu fpu division by zero exception and compile a shader with 
pow(0) then you get it division by zero.

I do not get the same exception when compiling with fxc.

What are the rules in this case?

### PR DESCRIPTION
**Pull request by MrTrillian**
We were crashing while constant folding in `CGHLSLMS.TryEvalIntrinsic` when libc functions cause floating-point exceptions and the compiler caller had enabled floating-point exceptions.

I really wanted to use the standard `<cfenv>` header, but `feholdexceptions` and `fesetround` somehow had no impact on the floating-point environment, as seen by checking the x87/xmm registers before and after, so I had to use non-standard `_controlfp_s`, which makes this fix Windows-specific.

Fixes #1607

### CODE REVIEW

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp [hunk 1]
```diff
@@ -100,6 +101,24 @@ static void CreateOperationResultFromOutputs(
...
+  // _controlfp_s is non-standard and <cfenv>.feholdexceptions doesn't work on windows...?
+#ifdef _WIN32
+  unsigned int previousValue;
+  DefaultFPEnvScope() {
+    // No exceptions, preserve denormals & round to nearest.
+    _controlfp_s(&previousValue, _MCW_EM | _DN_SAVE | _RC_NEAR, _MCW_EM | _MCW_DN | _MCW_RC);
+  }
+  ~DefaultFPEnvScope() {
+    unsigned int newValue;
+    _controlfp_s(&newValue, previousValue, _MCW_EM | _MCW_DN | _MCW_RC);
```
Comment (vcsharma) [inline tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: what happens if `_controlfp_s` returns an error code? same comment for other usage.

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp [hunk 2]
```diff
@@ -100,6 +101,24 @@ static void CreateOperationResultFromOutputs(
...
 }
 
+struct DefaultFPEnvScope
+{
+  // _controlfp_s is non-standard and <cfenv>.feholdexceptions doesn't work on windows...?
+#ifdef _WIN32
+  unsigned int previousValue;
+  DefaultFPEnvScope() {
+    // No exceptions, preserve denormals & round to nearest.
+    _controlfp_s(&previousValue, _MCW_EM | _DN_SAVE | _RC_NEAR, _MCW_EM | _MCW_DN | _MCW_RC);
```
Comment (vcsharma) [inline tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: Why not pass 0 as mask value to get the complete fp control word as-is in `previousValue`?
`_controlfp_s(&previousValue, _MCW_EM | _DN_SAVE | _RC_NEAR, 0);`

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp (hunk 1 above)
Comment (MrTrillian) [reply tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: The destructor  case is difficult because we might already be handling another error since this is a cleanup routine. We could ignore, assert or failfast, how do we usually handle this?

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp (hunk 2 above)
Comment (MrTrillian) [reply tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: I hadn't seen that was possible. Note that with 0, the set mask is ignored, so I would need a second call to modify the state.. and presumably use UINT_MAX as the mask to restore the state? Since I'm not sure want to touch the infinity and precision control bits (x87-specific), I think my current way does what we want.

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp (hunk 1 above)
Comment (vcsharma) [reply tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: We talked offline. someway to communicate failure would be good if possible.

File: tools/clang/tools/dxcompiler/dxcompilerobj.cpp (hunk 2 above)
Comment (vcsharma) [reply tools/clang/tools/dxcompiler/dxcompilerobj.cpp]: We synced up offline, it seems ok here to only restore masks that we care about.
