### PR TITLE
[spirv] Hull shader output patch must be shared between threads

### LINKED ISSUE #2641: [spirv] Tessellation Control shader code generation appears incorrect
We have encountered what appears to be a bug in dxc that causes information communicated from HLSL's logical "hull shader" to its "patch constant shader" to not actually get communicated (except for from the first control point), when converted to Vulkan's logical "tessellation control shader".

As far as I can tell, when data is transmitted from the hull shader to the patch constant shader, SPIRV-dxc attempts to do this by writing the per-thread data into a temporary array, that has one entry for each thread. Then a barrier is inserted and thread 0 consumes the data from all threads to do the patch-constant shader work. The problem appears to be that this temporary array is just regular registers, not any kind of LDS or "groupshared" memory. So, thread 0 doesn't actually access data written by the other threads, it just consumes uninitialized data. This causes the tessellation either to not show up, or to flicker like mad and do crazy stuff.

If I modify the shader so that the patch-constant shader does not use any information from the hull-shader, then tessellation works as expected. However, for our use case, we require the ability to use information computed in the hull shader.

NOTE: We have not found a work around for this, so getting it fixed "soon" would be pretty important to us.

Here is a simple HLSL shader that demonstrates the problem.
```
#define BARYCENTRIC_INTERPOLATE(INPUTARRAY, INPUTPARAM, BARYC) ((BARYC.x * INPUTARRAY[0].INPUTPARAM) + (BARYC.y * INPUTARRAY[1].INPUTPARAM) + (BARYC.z * INPUTARRAY[2].INPUTPARAM))

static const float2 Positions[3] = {
	float2(0.0, -0.5),
	float2(0.5, 0.5),
	float2(-0.5, 0.5)
};

static const float3 Colors[3] = {
	float3(1.0, 0.0, 0.0),
	float3(0.0, 1.0, 0.0),
	float3(0.0, 0.0, 1.0)
};

float Tessellation_factor; //set by CPU

struct VS_OUTPUT
{
	float4 pos : POSITION0;
	float3 color : VERTCOLOR0;
};

struct HS_OUTPUT
{
	float4 pos : POSITION0;
	float3 color : VERTCOLOR0;
	float tess_factor : TESSFACTOR0;
};

struct DS_OUTPUT
{
	float4 pos : SV_Position;
	float3 color : VERTCOLOR0;
};


VS_OUTPUT main_vs( uint vert_index : SV_VertexID)
{
	VS_OUTPUT OUT;

	OUT.pos = float4(Positions[vert_index], 0.0, 1.0);
	OUT.color = Colors[vert_index];

	return OUT;
}

struct HS_PATCH_OUTPUT
{
	float tess_factor[3] : SV_TessFactor; //tessellation factor per edge
	float inside_tess_factor : SV_InsideTessFactor; //tessellation factor of triangle interior
};

[domain("tri")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[patchconstantfunc("main_hs_patch")]
[outputcontrolpoints(3)]
HS_OUTPUT main_hs(InputPatch<VS_OUTPUT, 3> inputpoints, uint i : SV_OutputControlPointID)
{
	HS_OUTPUT OUT;
	OUT.pos = inputpoints[i].pos;
	OUT.color = inputpoints[i].color;
	OUT.tess_factor = Tessellation_factor;
	
	return OUT;
}

HS_PATCH_OUTPUT main_hs_patch(const OutputPatch<HS_OUTPUT, 3> patch)
{
	HS_PATCH_OUTPUT OUT;
	OUT.tess_factor[0] = patch[0].tess_factor;
	OUT.tess_factor[1] = patch[1].tess_factor;
	OUT.tess_factor[2] = patch[2].tess_factor;
	OUT.inside_tess_factor = (patch[0].tess_factor + patch[1].tess_factor + patch[2].tess_factor) / 3;

	return OUT;
}

[domain("tri")]
DS_OUTPUT main_ds(HS_PATCH_OUTPUT constants, float3 BarycentricCoords : SV_DomainLocation, const OutputPatch<HS_OUTPUT, 3> orig_triangle)
{
	DS_OUTPUT OUT;
	OUT.pos = BARYCENTRIC_INTERPOLATE(orig_triangle, pos, BarycentricCoords);
	OUT.color = BARYCENTRIC_INTERPOLATE(orig_triangle, color, BarycentricCoords);

	return OUT;
}

float4 main_ps( DS_OUTPUT data) : SV_Target0
{
	return float4(data.color, 1.0);
}
```

This generates SPIR-V like this for the Tessellation Control stage:

```
; SPIR-V
; Version: 1.3
; Generator: Google spiregg; 0
; Bound: 103
; Schema: 0
               OpCapability Tessellation
               OpExtension "SPV_GOOGLE_hlsl_functionality1"
               OpMemoryModel Logical GLSL450
               OpEntryPoint TessellationControl %main_hs "main_hs" %in_var_POSITION0 %in_var_VERTCOLOR0 %gl_InvocationID %out_var_POSITION0 %out_var_VERTCOLOR0 %out_var_TESSFACTOR0 %gl_TessLevelOuter %gl_TessLevelInner
               OpExecutionMode %main_hs Triangles
               OpExecutionMode %main_hs SpacingFractionalOdd
               OpExecutionMode %main_hs VertexOrderCw
               OpExecutionMode %main_hs OutputVertices 3
               OpSource HLSL 600
               OpName %type__Globals "type.$Globals"
               OpMemberName %type__Globals 0 "Tessellation_factor"
               OpName %_Globals "$Globals"
               OpName %in_var_POSITION0 "in.var.POSITION0"
               OpName %in_var_VERTCOLOR0 "in.var.VERTCOLOR0"
               OpName %out_var_POSITION0 "out.var.POSITION0"
               OpName %out_var_VERTCOLOR0 "out.var.VERTCOLOR0"
               OpName %out_var_TESSFACTOR0 "out.var.TESSFACTOR0"
               OpName %main_hs "main_hs"
               OpName %VS_OUTPUT "VS_OUTPUT"
               OpMemberName %VS_OUTPUT 0 "pos"
               OpMemberName %VS_OUTPUT 1 "color"
               OpName %param_var_inputpoints "param.var.inputpoints"
               OpName %HS_OUTPUT "HS_OUTPUT"
               OpMemberName %HS_OUTPUT 0 "pos"
               OpMemberName %HS_OUTPUT 1 "color"
               OpMemberName %HS_OUTPUT 2 "tess_factor"
               OpName %temp_var_hullMainRetVal "temp.var.hullMainRetVal"
               OpName %if_merge "if.merge"
               OpDecorateString %in_var_POSITION0 UserSemantic "POSITION0"
               OpDecorateString %in_var_VERTCOLOR0 UserSemantic "VERTCOLOR0"
               OpDecorate %gl_InvocationID BuiltIn InvocationId
               OpDecorateString %gl_InvocationID UserSemantic "SV_OutputControlPointID"
               OpDecorateString %out_var_POSITION0 UserSemantic "POSITION0"
               OpDecorateString %out_var_VERTCOLOR0 UserSemantic "VERTCOLOR0"
               OpDecorateString %out_var_TESSFACTOR0 UserSemantic "TESSFACTOR0"
               OpDecorate %gl_TessLevelOuter BuiltIn TessLevelOuter
               OpDecorateString %gl_TessLevelOuter UserSemantic "SV_TessFactor"
               OpDecorate %gl_TessLevelOuter Patch
               OpDecorate %gl_TessLevelInner BuiltIn TessLevelInner
               OpDecorateString %gl_TessLevelInner UserSemantic "SV_InsideTessFactor"
               OpDecorate %gl_TessLevelInner Patch
               OpDecorate %in_var_POSITION0 Location 0
               OpDecorate %in_var_VERTCOLOR0 Location 1
               OpDecorate %out_var_POSITION0 Location 0
               OpDecorate %out_var_TESSFACTOR0 Location 1
               OpDecorate %out_var_VERTCOLOR0 Location 2
               OpDecorate %_Globals DescriptorSet 0
               OpDecorate %_Globals Binding 0
               OpMemberDecorate %type__Globals 0 Offset 0
               OpDecorate %type__Globals Block
      %float = OpTypeFloat 32
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
     %uint_1 = OpConstant %uint 1
     %uint_2 = OpConstant %uint 2
        %int = OpTypeInt 32 1
      %int_2 = OpConstant %int 2
      %int_0 = OpConstant %int 0
      %int_1 = OpConstant %int 1
     %uint_3 = OpConstant %uint 3
    %v3float = OpTypeVector %float 3
%_arr_v3float_uint_3 = OpTypeArray %v3float %uint_3
%type__Globals = OpTypeStruct %float
%_ptr_Uniform_type__Globals = OpTypePointer Uniform %type__Globals
    %v4float = OpTypeVector %float 4
%_arr_v4float_uint_3 = OpTypeArray %v4float %uint_3
%_ptr_Input__arr_v4float_uint_3 = OpTypePointer Input %_arr_v4float_uint_3
%_ptr_Input__arr_v3float_uint_3 = OpTypePointer Input %_arr_v3float_uint_3
%_ptr_Input_uint = OpTypePointer Input %uint
%_ptr_Output__arr_v4float_uint_3 = OpTypePointer Output %_arr_v4float_uint_3
%_ptr_Output__arr_v3float_uint_3 = OpTypePointer Output %_arr_v3float_uint_3
%_arr_float_uint_3 = OpTypeArray %float %uint_3
%_ptr_Output__arr_float_uint_3 = OpTypePointer Output %_arr_float_uint_3
     %uint_4 = OpConstant %uint 4
%_arr_float_uint_4 = OpTypeArray %float %uint_4
%_ptr_Output__arr_float_uint_4 = OpTypePointer Output %_arr_float_uint_4
%_arr_float_uint_2 = OpTypeArray %float %uint_2
%_ptr_Output__arr_float_uint_2 = OpTypePointer Output %_arr_float_uint_2
       %void = OpTypeVoid
         %45 = OpTypeFunction %void
  %VS_OUTPUT = OpTypeStruct %v4float %v3float
%_arr_VS_OUTPUT_uint_3 = OpTypeArray %VS_OUTPUT %uint_3
%_ptr_Function__arr_VS_OUTPUT_uint_3 = OpTypePointer Function %_arr_VS_OUTPUT_uint_3
  %HS_OUTPUT = OpTypeStruct %v4float %v3float %float
%_arr_HS_OUTPUT_uint_3 = OpTypeArray %HS_OUTPUT %uint_3
%_ptr_Function__arr_HS_OUTPUT_uint_3 = OpTypePointer Function %_arr_HS_OUTPUT_uint_3
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v3float = OpTypePointer Output %v3float
%_ptr_Output_float = OpTypePointer Output %float
%_ptr_Function_HS_OUTPUT = OpTypePointer Function %HS_OUTPUT
       %bool = OpTypeBool
%_ptr_Function_float = OpTypePointer Function %float
%_ptr_Function_v4float = OpTypePointer Function %v4float
%_ptr_Function_v3float = OpTypePointer Function %v3float
%_ptr_Uniform_float = OpTypePointer Uniform %float
   %_Globals = OpVariable %_ptr_Uniform_type__Globals Uniform
%in_var_POSITION0 = OpVariable %_ptr_Input__arr_v4float_uint_3 Input
%in_var_VERTCOLOR0 = OpVariable %_ptr_Input__arr_v3float_uint_3 Input
%gl_InvocationID = OpVariable %_ptr_Input_uint Input
%out_var_POSITION0 = OpVariable %_ptr_Output__arr_v4float_uint_3 Output
%out_var_VERTCOLOR0 = OpVariable %_ptr_Output__arr_v3float_uint_3 Output
%out_var_TESSFACTOR0 = OpVariable %_ptr_Output__arr_float_uint_3 Output
%gl_TessLevelOuter = OpVariable %_ptr_Output__arr_float_uint_4 Output
%gl_TessLevelInner = OpVariable %_ptr_Output__arr_float_uint_2 Output
%float_0_333333343 = OpConstant %float 0.333333343
    %main_hs = OpFunction %void None %45
         %60 = OpLabel
%param_var_inputpoints = OpVariable %_ptr_Function__arr_VS_OUTPUT_uint_3 Function
%temp_var_hullMainRetVal = OpVariable %_ptr_Function__arr_HS_OUTPUT_uint_3 Function
         %61 = OpLoad %_arr_v4float_uint_3 %in_var_POSITION0
         %62 = OpLoad %_arr_v3float_uint_3 %in_var_VERTCOLOR0
         %63 = OpCompositeExtract %v4float %61 0
         %64 = OpCompositeExtract %v3float %62 0
         %65 = OpCompositeConstruct %VS_OUTPUT %63 %64
         %66 = OpCompositeExtract %v4float %61 1
         %67 = OpCompositeExtract %v3float %62 1
         %68 = OpCompositeConstruct %VS_OUTPUT %66 %67
         %69 = OpCompositeExtract %v4float %61 2
         %70 = OpCompositeExtract %v3float %62 2
         %71 = OpCompositeConstruct %VS_OUTPUT %69 %70
         %72 = OpCompositeConstruct %_arr_VS_OUTPUT_uint_3 %65 %68 %71
               OpStore %param_var_inputpoints %72
         %73 = OpLoad %uint %gl_InvocationID
         %74 = OpAccessChain %_ptr_Function_v4float %param_var_inputpoints %73 %int_0
         %75 = OpLoad %v4float %74
         %76 = OpAccessChain %_ptr_Function_v3float %param_var_inputpoints %73 %int_1
         %77 = OpLoad %v3float %76
         %78 = OpAccessChain %_ptr_Uniform_float %_Globals %int_0
         %79 = OpLoad %float %78
         %80 = OpCompositeConstruct %HS_OUTPUT %75 %77 %79
         %81 = OpAccessChain %_ptr_Output_v4float %out_var_POSITION0 %73
               OpStore %81 %75
         %82 = OpAccessChain %_ptr_Output_v3float %out_var_VERTCOLOR0 %73
               OpStore %82 %77
         %83 = OpAccessChain %_ptr_Output_float %out_var_TESSFACTOR0 %73
               OpStore %83 %79
         %84 = OpAccessChain %_ptr_Function_HS_OUTPUT %temp_var_hullMainRetVal %73
               OpStore %84 %80
               OpControlBarrier %uint_2 %uint_4 %uint_0
         %85 = OpIEqual %bool %73 %uint_0
               OpSelectionMerge %if_merge None
               OpBranchConditional %85 %86 %if_merge
         %86 = OpLabel
         %87 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_0 %int_2
         %88 = OpLoad %float %87
         %89 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_1 %int_2
         %90 = OpLoad %float %89
         %91 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_2 %int_2
         %92 = OpLoad %float %91
         %93 = OpLoad %float %87
         %94 = OpLoad %float %89
         %95 = OpFAdd %float %93 %94
         %96 = OpLoad %float %91
         %97 = OpFAdd %float %95 %96
         %98 = OpFMul %float %97 %float_0_333333343
         %99 = OpAccessChain %_ptr_Output_float %gl_TessLevelOuter %uint_0
               OpStore %99 %88
        %100 = OpAccessChain %_ptr_Output_float %gl_TessLevelOuter %uint_1
               OpStore %100 %90
        %101 = OpAccessChain %_ptr_Output_float %gl_TessLevelOuter %uint_2
               OpStore %101 %92
        %102 = OpAccessChain %_ptr_Output_float %gl_TessLevelInner %uint_0
               OpStore %102 %98
               OpBranch %if_merge
   %if_merge = OpLabel
               OpReturn
               OpFunctionEnd
```

To make it easier to understand the issue, I've decompiled the SPIR-V into GLSL using SPIRV-Cross, also:
```
#version 450
layout(vertices = 3) out;

struct VS_OUTPUT
{
    vec4 pos;
    vec3 color;
};

struct HS_OUTPUT
{
    vec4 pos;
    vec3 color;
    float tess_factor;
};

layout(set = 0, binding = 0, std140) uniform type_Globals
{
    float Tessellation_factor;
} _Globals;

layout(location = 0) in vec4 in_var_POSITION0[];
layout(location = 1) in vec3 in_var_VERTCOLOR0[];
layout(location = 0) out vec4 out_var_POSITION0[3];
layout(location = 2) out vec3 out_var_VERTCOLOR0[3];
layout(location = 1) out float out_var_TESSFACTOR0[3];

void main()
{
    vec4 _61_unrolled[3];
    for (int i = 0; i < int(3); i++)
    {
        _61_unrolled[i] = in_var_POSITION0[i];
    }
    vec3 _62_unrolled[3];
    for (int i = 0; i < int(3); i++)
    {
        _62_unrolled[i] = in_var_VERTCOLOR0[i];
    }
    VS_OUTPUT param_var_inputpoints[3] = VS_OUTPUT[](VS_OUTPUT(_61_unrolled[0], _62_unrolled[0]), VS_OUTPUT(_61_unrolled[1], _62_unrolled[1]), VS_OUTPUT(_61_unrolled[2], _62_unrolled[2]));
    out_var_POSITION0[gl_InvocationID] = param_var_inputpoints[gl_InvocationID].pos;
    out_var_VERTCOLOR0[gl_InvocationID] = param_var_inputpoints[gl_InvocationID].color;
    out_var_TESSFACTOR0[gl_InvocationID] = _Globals.Tessellation_factor;
    HS_OUTPUT temp_var_hullMainRetVal[3];
    temp_var_hullMainRetVal[gl_InvocationID] = HS_OUTPUT(param_var_inputpoints[gl_InvocationID].pos, param_var_inputpoints[gl_InvocationID].color, _Globals.Tessellation_factor);
    barrier();
    if (gl_InvocationID == 0u)
    {
        gl_TessLevelOuter[0u] = temp_var_hullMainRetVal[0u].tess_factor;
        gl_TessLevelOuter[1u] = temp_var_hullMainRetVal[1u].tess_factor;
        gl_TessLevelOuter[2u] = temp_var_hullMainRetVal[2u].tess_factor;
        gl_TessLevelInner[0u] = ((temp_var_hullMainRetVal[0u].tess_factor + temp_var_hullMainRetVal[1u].tess_factor) + temp_var_hullMainRetVal[2u].tess_factor) * 0.3333333432674407958984375;
    }
}

```

As you can see, the temp_var_hullMainRetVal variable appears to just be a regular local array, and not cross-thread shared memory of any kind.

Thank you! Dxc with SPIR-V is pretty awesome, and we appreciate all the work that has gone into it. We'd love to get this tessellation issue fixed as soon as possible.

### PR DESCRIPTION
**Pull request by jaebaek**
The existing code uses the Function storage class for the output patch
of a hull shader that will be used by the patch constant function.
DirectX automatically transmits the output patch to the all threads,
which are identical between threads. Even though Vulkan does not have
the patch constant function, we can simulate it using the execution
barrier and the variable with WorkGroup storage class.

Fixes #2641

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -977,6 +977,10 @@ void SpirvEmitter::doFunctionDecl(const FunctionDecl *decl) {
   // Create all parameters.
   for (uint32_t i = 0; i < decl->getNumParams(); ++i) {
     const ParmVarDecl *paramDecl = decl->getParamDecl(i);
+    if (spvContext.isHS() && decl == patchConstFunc &&
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:980]: Please add a comment about why this parameter should be skipped. e.g.
```cpp
// Since the output patch used in hull shaders is translated to a variable with Workgroup storage
// class, there is no need to pass the variable as function parameter in SPIR-V.
```

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 2]
```diff
@@ -10956,7 +10957,7 @@ bool SpirvEmitter::processHSEntryPointOutputAndPCF(
     if (hlsl::IsHLSLInputPatchType(param->getType())) {
       pcfParams.push_back(hullMainInputPatch);
     } else if (hlsl::IsHLSLOutputPatchType(param->getType())) {
-      pcfParams.push_back(hullMainOutputPatch);
+      continue;
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:10960]: Similarly, add a comment here about why this param is being skipped. e.g.
Please add a comment about why this parameter should be skipped. e.g.
```cpp
// Since the output patch used in hull shaders is translated to a variable with Workgroup storage
// class, there is no need to pass the variable as function parameter in SPIR-V.
```

**Comment by ehsannas** [comment]
in SPIR-V we manually insert an if-clause into the code and only get 1 invocation to call the patchconstantfunction.

Maybe that's the issue, and not the storage class?

**Comment by ehsannas** [comment]
See how we check the invocation ID after the execution barrier and only invoke the PCF from the first invocation:

https://github.com/microsoft/DirectXShaderCompiler/blob/3dfed824463bbc7992df2a70a893f624002988a0/tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv#L221-L226

**Comment by jaebaek** [comment]
Thank you for your comment.

As far as I understand, the author of issue #2641 also expects that only the first thread has to call the PCF.

The issue claims that the value of output patches is wrong in the first thread.
I think it makes sense in the code example the issue provides:

```
[domain("tri")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[patchconstantfunc("main_hs_patch")]
[outputcontrolpoints(3)]
HS_OUTPUT main_hs(InputPatch<VS_OUTPUT, 3> inputpoints, uint i : SV_OutputControlPointID)
{
	HS_OUTPUT OUT;
	OUT.pos = inputpoints[i].pos;
	OUT.color = inputpoints[i].color;
	OUT.tess_factor = Tessellation_factor;
	
	return OUT;
}

HS_PATCH_OUTPUT main_hs_patch(const OutputPatch<HS_OUTPUT, 3> patch)
{
	HS_PATCH_OUTPUT OUT;
	OUT.tess_factor[0] = patch[0].tess_factor;
	OUT.tess_factor[1] = patch[1].tess_factor;
	OUT.tess_factor[2] = patch[2].tess_factor;
	OUT.inside_tess_factor = (patch[0].tess_factor + patch[1].tess_factor + patch[2].tess_factor) / 3;

	return OUT;
}
```

`main_hs` outputs only a single `HS_OUTPUT` i.e., `OUT` but `main_hs_patch` receives three output patches i.e., `const OutputPatch<HS_OUTPUT, 3> patch`.
The first thread has to access the outputs from the second and the third threads in addition to the first thread's output.

The existing DXC generates
```
%temp_var_hullMainRetVal = OpVariable %_ptr_Function__arr_HS_OUTPUT_uint_3 Function
...
         %73 = OpLoad %uint %gl_InvocationID
...
         %84 = OpAccessChain %_ptr_Function_HS_OUTPUT %temp_var_hullMainRetVal %73
               OpStore %84 %80
               OpControlBarrier %uint_2 %uint_4 %uint_0
         %85 = OpIEqual %bool %73 %uint_0
               OpSelectionMerge %if_merge None
               OpBranchConditional %85 %86 %if_merge
         %86 = OpLabel
         %87 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_0 %int_2
         %88 = OpLoad %float %87
         %89 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_1 %int_2
         %90 = OpLoad %float %89
         %91 = OpAccessChain %_ptr_Function_float %temp_var_hullMainRetVal %uint_2 %int_2
...
```

If I interpret it in high level language:
```
temp_var_hullMainRetVal[gl_InvocationID] = %80
ExecutionBarrier()
if (gl_InvocationID == 0) {
  %88 = temp_var_hullMainRetVal[0]
  %90 = temp_var_hullMainRetVal[1]     // wrong value
  %92 = temp_var_hullMainRetVal[2]     // wrong value
...
}
```

In my opinion, the Workgroup storage class for the output patch looks correct, but I do not have an experience of the hull shader and I want to doublecheck it. What do you think?

**Comment by ehsannas** [comment]
Yeah changing the storage class to Workgroup makes sense to me

File: tools/clang/lib/SPIRV/DeclResultIdMapper.h [hunk 3]
```diff
@@ -402,6 +402,13 @@ class DeclResultIdMapper {
   /// VarDecls (such as some ray tracing enums).
   void tryToCreateImplicitConstVar(const ValueDecl *);
 
+  /// \brief Creates a variable for hull shader output patch with WorkGroup
```
[the remark this answers is not in the document]
Comment (jaebaek) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.h]: done

File: tools/clang/lib/SPIRV/DeclResultIdMapper.h [hunk 4]
```diff
@@ -402,6 +402,13 @@ class DeclResultIdMapper {
...
+  /// storage class.
```
[the remark this answers is not in the document]
Comment (jaebaek) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.h]: done

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 1 above)
Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:980]: done
