### PR TITLE
[SPIR-V] Fix push_constant and shader_record_ext to work with LowerTypeVisitor

### LINKED ISSUE #5808: [SPIR-V] Validation error when push constant is passed into a function
**Description**
Getting a compiler error (thrown by SPIR-V validation) when a push constant is passed straight into a function. This error is thrown on trunk but not on DXC 1.7. ~~Please note that the SPIR-V generated between trunk and 1.7 is identical so either the problem was always there and the updated spirv-val caught it or newer spir-val is broken~~ (scratch that, seems I was wrong).

**Steps to Reproduce**
Simple repro case
```
struct Foo
{
    float m_x;
};
 
[[vk::push_constant]] ConstantBuffer<Foo> g_pc;
RWStructuredBuffer<float> g_buff;

float mul1(Foo m, float4 v)
{
	return m.m_x + v.x;
}
 
[numthreads(1, 1, 1)] void main()
{
    g_buff[0] = mul1(g_pc, float4(1, 0, 0, 1));
}
```

And the error is:
```
fatal error: generated SPIR-V is invalid: OpLoad Result Type <id> '7[%type_ConstantBuffer_Foo]' does not match Pointer <id> '4[%g_pc]'s type.
  %21 = OpLoad %type_ConstantBuffer_Foo %g_pc

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Actual Behavior**
There shouldn't be an error.

**Environment**
- DXC version: Trunk (6b4b0eb5)
- Host Operating System: Linux

### PR DESCRIPTION
**Pull request by cassiebeckley**
Since `ConstantBuffer` is now lowered in `LowerTypeVisitor`, lower `push_constant` and `shader_record_*` with `ConstantBuffer` types there as well.

Fixes #5808.

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -1441,18 +1438,30 @@ SpirvVariable *DeclResultIdMapper::createPushConstant(const VarDecl *decl) {
   const QualType type = decl->getType();
   const auto *recordType = type->getAs<RecordType>();
 
+  SpirvVariable *var;
```
Comment (Keenuts) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1441]:
```suggestion
  SpirvVariable *var = nullptr;
```

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 2]
```diff
@@ -1466,22 +1475,44 @@ SpirvVariable *DeclResultIdMapper::createPushConstant(const VarDecl *decl) {
...
+      hlsl::GetHLSLResourceResultType(type)->getAs<RecordType>();
   assert(recordType);
 
   assert(kind == ContextUsageKind::ShaderRecordBufferEXT ||
          kind == ContextUsageKind::ShaderRecordBufferNV);
 
-  const auto typeName = kind == ContextUsageKind::ShaderRecordBufferEXT
-                            ? "type.ShaderRecordBufferEXT."
-                            : "type.ShaderRecordBufferNV.";
+  SpirvVariable *var;
```
Comment (Keenuts) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1486]:
```suggestion
  SpirvVariable *var = nullptr;
```

File: tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl [hunk 3]
```diff
@@ -44,7 +44,7 @@ struct S {
 [[vk::shader_record_ext]]
 ConstantBuffer<S> cbuf;
 
-// CHECK: OpDecorate %type_ShaderRecordBufferEXT_S Block
```
Comment (Keenuts) [inline tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl:47]: Maybe I'm paranoid, but shouldn't we check those decoration do apply to the type used for the cbuf variable declaration?
Since we are in fcgl, a bug could make us generate this type correctly, but not use it for the cbuf variable.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 4]
```diff
@@ -1466,22 +1475,44 @@ SpirvVariable *DeclResultIdMapper::createPushConstant(const VarDecl *decl) {
...
-  const std::string structName =
-      typeName + recordType->getDecl()->getName().str();
-  SpirvVariable *var = createStructOrStructArrayVarOfExplicitLayout(
-      recordType->getDecl(), /*arraySize*/ 0, kind, structName,
-      decl->getName());
+    var->setHlslUserType("");
+    var->setLayoutRule(layoutRule);
+  } else {
+    const auto typeName = kind == ContextUsageKind::ShaderRecordBufferEXT
+                              ? "type.ShaderRecordBufferEXT."
```
Comment (Keenuts) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1507]: nit: name is EXT, but storage class is now KHR

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 5]
```diff
@@ -1466,22 +1475,44 @@ SpirvVariable *DeclResultIdMapper::createPushConstant(const VarDecl *decl) {
...
-                            ? "type.ShaderRecordBufferEXT."
-                            : "type.ShaderRecordBufferNV.";
+  SpirvVariable *var;
+  if (isConstantBuffer(type)) {
+    // Constant buffers already have Block decoration. The variable will need
+    // the appropriate storage class.
+
+    const auto sc = kind == ContextUsageKind::ShaderRecordBufferNV
+                        ? spv::StorageClass::ShaderRecordBufferNV
+                        : spv::StorageClass::ShaderRecordBufferKHR;
```
Comment (Keenuts) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1493]: I don't see any test checking we do add the required capabilities/extensions. Shall this be added?
I do believe changing EXT into KHR is a good change, but maybe we should now check it.

**Review by s-perron — APPROVED** [review]
Nothing beyond what Nathan already suggested.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 5 above)
Comment (cassiebeckley) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:1493]: It looks like there are tests that the ray tracing capability and extension are added for the `RaytracingAccelerationStructure` type, but not for the `vk::shader_record_ext` attribute. I'll add them into the new tests.

File: tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl (hunk 3 above)
Comment (cassiebeckley) [reply tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl:47]: Sure, added.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 4 above)
Comment (cassiebeckley) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: I've changed the typename and the enum identifier.

**Comment by cassiebeckley** [comment]
@Keenuts did you want any other changes?

File: tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl [hunk 6]
```diff
@@ -44,7 +44,7 @@ struct S {
 [[vk::shader_record_ext]]
 ConstantBuffer<S> cbuf;
```
Comment (Keenuts) [inline tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl:45]: I'm a bit confused, this test is supposed to only use the KHR variant of the ShaderRecordBuffer extensions?
Building this test with the DXC at this PR ends up generating this kind of lines:
```
 %_ptr_ShaderRecordBufferNV_type_ShaderRecordBufferKHR_block = OpTypePointer ShaderRecordBufferNV %type_ShaderRecordBufferKHR_block

...

%block = OpVariable %_ptr_ShaderRecordBufferNV_type_ShaderRecordBufferKHR_block ShaderRecordBufferNV
```

Aren't the NV version not supposed to be used?

**Comment by Keenuts** [comment]
> @Keenuts did you want any other changes?

Sorry missed this PR. Just a question about observed generated code, otherwise nothing specific.

File: tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl (hunk 6 above)
Comment (cassiebeckley) [reply tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl:45]: The NV and KHR constants have the same value; the SPIRV-Tools disassembler is defaulting to using the NV string for that constant.

**Review by Keenuts — APPROVED** [review]
