### PR TITLE
Fix CB vector to scalar array translation generating invalid IR (#6777)

### LINKED ISSUE #6510: Accessing "aggressively packed" array elements in a constant buffer via static cast results in ICE
As per https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules#more-aggressive-packing

```glsl
#define MAX_TEXTURES 4
#define MAX_BUFFERS 4

cbuffer CResourceIndexRootConstants : register(b2)
{
    uint4 iTexs[MAX_TEXTURES / 4];
    uint4 iBufs[MAX_BUFFERS / 4];
}

float4 main(CPSInLighting pin) : SV_Target0
{
    static const uint iTexsArray[MAX_TEXTURES] = (uint[MAX_TEXTURES])iTexs;
    static const uint iBufsArray[MAX_BUFFERS] = (uint[MAX_BUFFERS])iBufs;

    uint iAlbedoTexture = iTexsArray[0];
    uint iNormalTexture = iTexsArray[1];
```

This results in:
```Internal compiler error: access violation. Attempted to read from address 0x0000000000000048```

`CResourceIndexRootConstants` is mapped via root constants.

Version: dxcompiler.dll: 1.8 - 1.8.0.14496 (main, 37c0487e9); dxil.dll: 1.8(101.8.2403.21)

### PR DESCRIPTION
**Pull request by python3kgae**
In the special code to handle the memcpy pattern where a constant buffer contains a vector array that initializes a local (or static global) scalar array for use by the shader, an invalid assumption was made that if the memcpy dest was global, that the src is global as well.

This was not the case, and when expecting to generate constant expressions to index the src, these generated orphaned instructions instead, leading to invalid IR.

This fixes the issue by leveraging ReplaceConstantWithInst, and setting the insertion point for the Builder. Now, replacement *could* fail, if src instructions don't dominate replacement uses, so bool for replaced all is returned from replaceScalarArrayWithVectorArray.

Another issue was that it would replace the dest for the original memcpy with src along the way. Now, if we don't replace all uses, this turns the memcpy into a no-op and any remaining uses are no longer coming from src, but an undef dest instead. This was also fixed to skip this replacement, then clean up this use if all other uses have been successfully replaced.

Fixes #6510

(cherry picked from commit 5cfefc7d0b2d4d5af93d5668dcd5c11a003ac666)

### CODE REVIEW

**Review by damyanp — APPROVED** [review]

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp [hunk 1]
```diff
@@ -3474,38 +3493,52 @@ void replaceScalarArrayWithVectorArray(Value *ScalarArray, Value *VectorArray,
     if (U->user_empty())
       continue;
     if (BitCastInst *BCI = dyn_cast<BitCastInst>(U)) {
-      BCI->setOperand(0, VectorArray);
+      // Avoid replacing the dest of the memcpy to support partial replacement.
+      if (MC->getArgOperand(0) != BCI)
```
Comment (bob80905) [inline lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp:3497]: Should there be a nullptr check for `MC` ?

**Comment by bob80905** [comment]
Is there a way to shrink the sizes of the 3 tests?

File: lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp (hunk 1 above)
Comment (python3kgae) [reply lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp:3497]: No.
The MC is from lowerMemcpy which start when have memcpy.

**Comment by python3kgae** [comment]
> Is there a way to shrink the sizes of the 3 tests?

We could remove the debug info.
But this is a cherry-pick PR, we should need to change in main and then cherry-pick the test update to release branch.

**Review by bob80905 — APPROVED** [review]
