### PR TITLE
[SPIR-V] Handle storage buffer interfaces in structs

### LINKED ISSUE #4185: [SPIR-V] Using a StructuredBuffer stored in a local struct causes a compiler crash
Repro shader:
```
// dxc -T cs_6_3 -spirv -fspv-target-env=vulkan1.2 shader.hlsl
StructuredBuffer<uint> g_stuff_buffer;
RWStructuredBuffer<uint> g_output;

struct Struct
{
  StructuredBuffer<uint> buffer;
};

[numthreads(1, 1, 1)]
void main()
{
  Struct s;
  s.buffer = g_stuff_buffer;
  g_output[0] = s.buffer[0]; // <-- crash
  //g_output[0] = g_stuff_buffer[0]; // <-- works
}
```

The compiler simply crashes with a null-ish pointer access when built in release config. However, running a debug build gets us some clue for where to start digging into the bug. We hit an assert in SPIRV-Tools pass.cpp `Pass::GenerateCopy`:
```
// If we do not have an aggregate type, then we have a problem.  Either we
// found multiple instances of the same type, or we are copying to an
// incompatible type.  Either way the code is illegal.
assert(false &&
       "Don't know how to copy this type.  Code is likely illegal.");
```

Relevant part of the call stack:
```
 	dxcompiler.dll!spvtools::opt::Pass::GenerateCopy(spvtools::opt::Instruction * object_to_copy, unsigned int new_type_id, spvtools::opt::Instruction * insertion_position) Line 148	C++
>	dxcompiler.dll!spvtools::opt::FixStorageClass::PropagateType(spvtools::opt::Instruction * inst, unsigned int type_id, unsigned int op_idx, std::set<unsigned int,std::less<unsigned int>,std::allocator<unsigned int>> * seen) Line 235	C++
 	dxcompiler.dll!spvtools::opt::FixStorageClass::PropagateType(spvtools::opt::Instruction * inst, unsigned int type_id, unsigned int op_idx, std::set<unsigned int,std::less<unsigned int>,std::allocator<unsigned int>> * seen) Line 279	C++
 	dxcompiler.dll!spvtools::opt::FixStorageClass::Process::__l2::<lambda>(spvtools::opt::Instruction * inst) Line 43	C++
 	dxcompiler.dll!std::invoke<void <lambda>(spvtools::opt::Instruction *) &,spvtools::opt::Instruction *>(spvtools::opt::FixStorageClass::Process::__l2::void <lambda>(spvtools::opt::Instruction *) & _Obj, spvtools::opt::Instruction * && _Arg1) Line 1610	C++
 	dxcompiler.dll!std::_Invoker_ret<void,1>::_Call<void <lambda>(spvtools::opt::Instruction *) &,spvtools::opt::Instruction *>(spvtools::opt::FixStorageClass::Process::__l2::void <lambda>(spvtools::opt::Instruction *) & _Func, spvtools::opt::Instruction * && <_Vals_0>) Line 745	C++
 	dxcompiler.dll!std::_Func_impl_no_alloc<void <lambda>(spvtools::opt::Instruction *),void,spvtools::opt::Instruction *>::_Do_call(spvtools::opt::Instruction * && <_Args_0>) Line 921	C++
 	dxcompiler.dll!std::_Func_class<void,spvtools::opt::Instruction *>::operator()(spvtools::opt::Instruction * <_Args_0>) Line 969	C++
 	dxcompiler.dll!spvtools::opt::Function::ForEachInst::__l2::<lambda>(spvtools::opt::Instruction * inst) Line 64	C++
 	dxcompiler.dll!std::invoke<bool <lambda>(spvtools::opt::Instruction *) &,spvtools::opt::Instruction *>(spvtools::opt::Function::ForEachInst::__l2::bool <lambda>(spvtools::opt::Instruction *) & _Obj, spvtools::opt::Instruction * && _Arg1) Line 1610	C++
 	dxcompiler.dll!std::_Invoker_ret<bool,0>::_Call<bool <lambda>(spvtools::opt::Instruction *) &,spvtools::opt::Instruction *>(spvtools::opt::Function::ForEachInst::__l2::bool <lambda>(spvtools::opt::Instruction *) & _Func, spvtools::opt::Instruction * && <_Vals_0>) Line 754	C++
 	dxcompiler.dll!std::_Func_impl_no_alloc<bool <lambda>(spvtools::opt::Instruction *),bool,spvtools::opt::Instruction *>::_Do_call(spvtools::opt::Instruction * && <_Args_0>) Line 921	C++
 	dxcompiler.dll!std::_Func_class<bool,spvtools::opt::Instruction *>::operator()(spvtools::opt::Instruction * <_Args_0>) Line 969	C++
 	dxcompiler.dll!spvtools::opt::Instruction::WhileEachInst(const std::function<bool __cdecl(spvtools::opt::Instruction *)> & f, bool run_on_debug_line_insts) Line 743	C++
 	dxcompiler.dll!spvtools::opt::BasicBlock::WhileEachInst(const std::function<bool __cdecl(spvtools::opt::Instruction *)> & f, bool run_on_debug_line_insts) Line 270	C++
 	dxcompiler.dll!spvtools::opt::Function::WhileEachInst(const std::function<bool __cdecl(spvtools::opt::Instruction *)> & f, bool run_on_debug_line_insts, bool run_on_non_semantic_insts) Line 105	C++
 	dxcompiler.dll!spvtools::opt::Function::ForEachInst(const std::function<void __cdecl(spvtools::opt::Instruction *)> & f, bool run_on_debug_line_insts, bool run_on_non_semantic_insts) Line 61	C++
 	dxcompiler.dll!spvtools::opt::Module::ForEachInst(const std::function<void __cdecl(spvtools::opt::Instruction *)> & f, bool run_on_debug_line_insts) Line 104	C++
 	dxcompiler.dll!spvtools::opt::FixStorageClass::Process() Line 28	C++
 	dxcompiler.dll!spvtools::opt::Pass::Run(spvtools::opt::IRContext * ctx) Line 40	C++
 	dxcompiler.dll!spvtools::opt::PassManager::Run(spvtools::opt::IRContext * context) Line 50	C++
 	dxcompiler.dll!spvtools::Optimizer::Run(const unsigned int * original_binary, const unsigned __int64 original_binary_size, std::vector<unsigned int,std::allocator<unsigned int>> * optimized_binary, spv_optimizer_options_t * const opt_options) Line 597	C++
 	dxcompiler.dll!clang::spirv::SpirvEmitter::spirvToolsLegalize(std::vector<unsigned int,std::allocator<unsigned int>> * mod, std::string * messages, const std::vector<spvtools::opt::DescriptorSetAndBinding,std::allocator<spvtools::opt::DescriptorSetAndBinding>> * dsetbindingsToCombineImageSampler) Line 12984	C++
 	dxcompiler.dll!clang::spirv::SpirvEmitter::HandleTranslationUnit(clang::ASTContext & context) Line 758	C++
```

_Side note:_ while it's not part of DXC as such, it's very unfortunate that SPIRV-Tools uses regular `assert` for error reporting like this. The error check does not run in regular release config, the error message does not report source location (which it happens to have in `inst->dbg_line_insts_`, which is how I tracked down the problematic code in our huge production shader).

### PR DESCRIPTION
**Pull request by sudonatalie**
This change modifies the RemoveBufferBlockVisitor to recurse through nested pointers to transform the storage class of inner pointers where required, as well as the fields of structs. Some uses arrays are handled by hasStorageBufferInterfaceType, but this PR leaves as a TODO further verification of the handling of of other composite types.

Fixes #4185, #4187

### CODE REVIEW

**Comment by sudonatalie** [comment]
@yuriy-odonnell-epic If this patch satisfies your use case, then it is probably a worthwhile stopgap, but ack that a more robust solution is still needed long-term (tracking Issue #4187).

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp [hunk 1]
```diff
@@ -116,6 +116,32 @@ bool RemoveBufferBlockVisitor::updateStorageClass(
...
+    for (size_t i = 0; i < fields.size(); i++) {
+      if (const auto *innerPtrType =
+              dyn_cast<SpirvPointerType>(fields[i].type)) {
+        if (hasStorageBufferInterfaceType(innerPtrType->getPointeeType()) &&
+            innerPtrType->getStorageClass() !=
+                spv::StorageClass::StorageBuffer) {
+          auto *newInnerType = context.getPointerType(
+              innerPtrType->getPointeeType(), spv::StorageClass::StorageBuffer);
+          newFields[i] = newInnerType;
+          *newType = context.getPointerType(
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp:133]: When there are multiple such members in the struct, we have to handle them as well.
Could you please move lines 133~139 out of this for-loop to handle multiple members (I mean fields)?

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp [hunk 2]
```diff
@@ -116,6 +116,32 @@ bool RemoveBufferBlockVisitor::updateStorageClass(
     }
   }
 
+  // For pointer-to-struct cases, we may need to update the storage class for
+  // the inner struct fields.
+  if (const auto *innerStructType = dyn_cast<StructType>(innerType)) {
+    auto fields = innerStructType->getFields();
+    std::vector<StructType::FieldInfo> newFields(fields.begin(), fields.end());
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp:123]: nit: Personally, I prefer
```
llvm::SmallVector<StructType::FieldInfo, 2> newFields;
for (auto field : fields) {
  if (!<condition>) {
    newFields.push_back(field);
    continue;
  }
  ...
  newFields.push_back(newInnerType);
  ...
}
```

Maybe some developer can consider the following code can make dangling pointers.
(I understand this is not the case)
```
std::vector<StructType::FieldInfo> newFields(fields.begin(), fields.end());
...
newFields[i] = newInnerType;
...
```

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp [hunk 3]
```diff
@@ -116,6 +116,32 @@ bool RemoveBufferBlockVisitor::updateStorageClass(
     }
   }
 
+  // For pointer-to-struct cases, we may need to update the storage class for
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp:119]: I know DXC code base is not clean now .. as I mentioned in https://github.com/microsoft/DirectXShaderCompiler/issues/4173, we need refactoring .. It will take us longer and longer time for the maintenance.

Could you please split your code into a separate one?
e.g.,
```
bool RemoveBufferBlockVisitor::updateStorageClass(
    const SpirvType *type, const SpirvType **newType,
    spv::StorageClass *newStorageClass) {
...
if (const auto *innerStructType = dyn_cast<StructType>(innerType)) {
  return updateStorageClassForStruct(...);
}
return false;
}

bool RemoveBufferBlockVisitor::updateStorageClassForStruct(...) {
// Do the same here.
}
```

File: tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl [hunk 4]
```diff
@@ -0,0 +1,33 @@
+// RUN: %dxc -T cs_6_3 -fspv-target-env=vulkan1.2 -E main
+
+// CHECK: %Struct = OpTypeStruct %v3float %_ptr_StorageBuffer_type_StructuredBuffer_uint
+struct Struct
+{
+  float3 foo;
+  StructuredBuffer<uint> buffer;
```
Comment (jaebaek) [inline tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl:7]: Please create another struct and add two `StructuredBuffer<uint>` to the struct.
We want to check whether it correct handles both multiple fields and a single field.

**Review by jaebaek — COMMENTED** [review]
This PR looks good to me and your solution is not a hacky one but it looks correct.
I have just a few comments.

File: tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl [hunk 5]
```diff
@@ -0,0 +1,33 @@
+// RUN: %dxc -T cs_6_3 -fspv-target-env=vulkan1.2 -E main
```
Comment (jaebaek) [inline tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl:1]: Please rename this file as "tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1p2.hlsl"

**Comment by yuriy-odonnell-epic** [comment]
> @yuriy-odonnell-epic If this patch satisfies your use case, then it is probably a worthwhile stopgap, but ack that a more robust solution is still needed long-term (tracking Issue #4187).

I've applied the patch locally and tested our full production shader that originally prompted the bug report. Unfortunately, it appears that the patch does not fix the problem even though the minimal repro shader I provided does compile now. I will see if I can distill the the new repro and potentially can share the full shader privately.

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp (hunk 1 above)
Comment (sudonatalie) [reply tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp]: Oops, that was why I introduced a separate newFields and then apparently didn't finish the fix. Fixed now, thanks!

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp (hunk 2 above)
Comment (sudonatalie) [reply tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp]: Done

File: tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp (hunk 3 above)
Comment (sudonatalie) [reply tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp]: Ended up reusing updateStorageClass for recursing through nested types.

File: tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl (hunk 5 above)
Comment (sudonatalie) [reply tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl]: Done

**Comment by sudonatalie** [comment]
This latest patchset has been tested locally against @yuriy-odonnell-epic's full shader as well.

**Review by jaebaek — APPROVED** [review]
