### PR TITLE
Fix invalid CmpEQ(%bool,0) for converting bools

### LINKED ISSUE #1740: Incorrect DXC codegen for constant buffer bool vector access
This code:

```
bool2 b2;
float main() : SV_TARGET
{
  uint x = b2[1];
  return x;
}
```

Compiles into:
```
define void @main() {
  %"$Globals_cbuffer" = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 2, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %1 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %"$Globals_cbuffer", i32 0)  ; CBufferLoadLegacy(handle,regIndex)
  %2 = extractvalue %dx.types.CBufRet.i32 %1, 1
  %.i1 = icmp eq i32 %2, 0 ; <------------ !!!
  %3 = uitofp i1 %.i1 to float
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %3)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

This is incorrect, it should be `icmp ne`, not `icmp eq`.

### PR DESCRIPTION
**Pull request by MrTrillian**
The matrix lowering code special-cased bools and converted from i32s using `CmpEQ(%bool,0)` instead of `CmpNE(%bool,0)` in a few places. This change fixes it, where possible by leveraging `MemToReg` to remove the special cases.

Fixes #1740

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -4970,18 +4970,13 @@ unsigned GetEltTypeByteSizeForConstBuf(Type *EltType, const DataLayout &DL) {
 Value *GenerateCBLoad(Value *handle, Value *offset, Type *EltTy, OP *hlslOP,
                       IRBuilder<> &Builder) {
   Constant *OpArg = hlslOP->GetU32Const((unsigned)OP::OpCode::CBufferLoad);
+
+  DXASSERT(!EltTy->isIntegerTy(1), "Bools should not be loaded as their register representation.");
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: Callers are already properly requesting the mem representation of bools so removing the code below is fine.

File: lib/HLSL/HLOperationLower.cpp [hunk 2]
```diff
@@ -5424,7 +5400,7 @@ Value *TranslateConstBufMatLdLegacy(Type *matType, Value *handle,
                                     IRBuilder<> &Builder) {
   unsigned col, row;
   HLMatrixLower::GetMatrixInfo(matType, col, row);
-  Type *EltTy = HLMatrixLower::LowerMatrixType(matType, /*forMem*/memElemRepr)->getVectorElementType();
+  Type *EltTy = HLMatrixLower::LowerMatrixType(matType, /*forMem*/true)->getVectorElementType();
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: We should always load using the mem representation, but the epilogue will convert to the register representation if that's what the caller wants.

File: lib/HLSL/HLMatrixLowerPass.cpp [hunk 3]
```diff
@@ -412,26 +412,14 @@ INITIALIZE_PASS(HLMatrixLowerPass, "hlmatrixlower", "HLSL High-Level Matrix Lowe
...
     Type *fromTy = src->getType();
+    Constant *zero = llvm::Constant::getNullValue(src->getType());
     bool isFloat = fromTy->getScalarType()->isFloatingPointTy();
-    Constant *zero;
-    if (isFloat)
-      zero = llvm::ConstantFP::get(fromTy->getScalarType(), 0);
-    else
-      zero = llvm::ConstantInt::get(fromTy->getScalarType(), 0);
-
-    if (toTy->getScalarType() != toTy) {
```
[the remark this answers is not in the document]
Comment (MrTrillian) [reply lib/HLSL/HLMatrixLowerPass.cpp]: Yup, it does this:
```
  case Type::VectorTyID:
    return ConstantAggregateZero::get(Ty);
```
