### PR TITLE
Fix row_major being lost through typedefs.

### LINKED ISSUE #1647: FXC vs DXC padding issue
Hi,

I'm currently experiencing some FXC vs DXC differences in the padding when compiling some of our shaders. Shouldn't FXC and DXC padding behavior be the same when packing elements in the structure? 

Here is an example (.asm) produced by FXC:
```
struct MatTest
{   
    float4x4 mat0;                 // Offset:    0
    row_major float4x3 mat1;       // Offset:   64
    row_major float3x4 mat2;       // Offset:  128
    float3x4 mat3;                 // Offset:  176
    row_major float3x4 mat4;       // Offset:  240
    float4 someParam;              // Offset:  288
} matTest;                         // Offset:    0 Size:   304
```
vs DXC

```
; cbuffer $Globals
; {
;
;   struct dx.alignment.legacy.$Globals
;   {
;
;       struct dx.alignment.legacy.struct.MatTest
;       {
;
;           column_major float4x4 mat0;               ; Offset:    0
;           row_major float4x3 mat1;                  ; Offset:   64
;           row_major float3x4 mat2;                  ; Offset:  128
;           column_major float3x4 mat3;               ; Offset:  192
;           row_major float3x4 mat4;                  ; Offset:  256
;           float4 someParam;                         ; Offset:  304
;       
;       } matTest                                     ; Offset:    0
;
;   
;   } $Globals                                        ; Offset:    0 Size:   320
;
; }

```

### PR DESCRIPTION
**Pull request by MrTrillian**
The code attempted to cast a `QualType` to an `AttributedType`, which would fail if it was in fact a `TypedefType`. Better use the existing helper function we have.

Fixes #1647

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 1]
```diff
@@ -572,26 +572,15 @@ static unsigned AlignBaseOffset(unsigned baseOffset, unsigned size,
   bool needNewAlign = Ty->isArrayType();
 
   if (IsHLSLMatType(Ty)) {
-    bool bColMajor = !bDefaultRowMajor;
-    if (const AttributedType *AT = dyn_cast<AttributedType>(Ty)) {
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I fixed this but filed #1721 as this code apparently supports inheriting from matrices??

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 2]
```diff
@@ -2692,25 +2670,11 @@ bool CGMSHLSLRuntime::SetUAVSRV(SourceLocation loc,
...
-        break;
-      case AttributedType::Kind::attr_hlsl_unorm:
-        bUNorm = true;
-        break;
-      default:
-        // Do nothing
-        break;
-      }
-    }
+    bool bHasNormAttribute = hlsl::HasHLSLUNormSNorm(Ty, &bSNorm);
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I fixed this even though I couldn't repro it, hence I filed #1722
