### PR TITLE
Fix array operator access to a buffer resource vector member

### LINKED ISSUE #1353: using the array operator to access a buffer resource vector member.
When accessing a vector member with the array operator from a Buffer resource:
```
Buffer< uint4 > Elements;
uint v2 = Elements[0][0];
```
the output is:
DX: 
```
dxc failed : error code 0x80aa0018.
```
spirv:
```
fatal error: generated SPIR-V is invalid: OpAccessChain reached non-composite type while indexes still remain to be traversed.
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

It can be worked around with:
```
Buffer< uint4 > Elements;
uint4 temp = Elements[0];
uint v2 = temp[0];
```

You can repro the issue with the following VS:
```
struct SMeshVertex
{
    float4 position                 : ATTR0;
};

Buffer< uint4 > Elements;

struct SVertexToPixel
{
    float projectedPosition : POSITION0;
};

SVertexToPixel main( in SMeshVertex inputRaw )
{
    SVertexToPixel output = (SVertexToPixel)0;

    output.projectedPosition.x = Elements[0][0];

    return output;
}
```

Thanks
Mike

### PR DESCRIPTION
**Pull request by hekota**
Fixes #1353

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGExprCXX.cpp [hunk 1]
```diff
@@ -219,7 +219,7 @@ RValue CodeGenFunction::EmitCXXMemberOrOperatorMemberCallExpr(
       if (Base->getValueKind() != ExprValueKind::VK_RValue) {
         LValue LV = EmitLValue(Base);
         if (LV.isSimple()) {
-          This = EmitLValue(Base).getAddress();
+          This = LV.getAddress();
```
Comment (hekota) [inline tools/clang/lib/CodeGen/CGExprCXX.cpp]: This was creating a duplicate call to load the value (which was later optimized away).
