### PR TITLE
[SPIR-V] countbit on 16+64 bit types

### LINKED ISSUE #7494: [SPIR-V] Incorrect SPIR-V generated for `countbits` for non-32 bit type integers
**Description**

Saw this error:
```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-Base-04781] Expected 32-bit int type for Base operand: BitCount
   %43 = OpBitCount %v4uint %42
```

when compiling this code:

```
StructuredBuffer<int16_t4> In : register(t0);
RWStructuredBuffer<uint4> Out : register(u2);

[numthreads(1,1,1)]
void main() {
  Out[0] = countbits(In[0]);
}
```

The same error occurs when using `int64_t` as well.

**Steps to Reproduce**
https://godbolt.org/z/65fKP583e

**Actual Behavior**

From the [validator specs](https://vulkan.lunarg.com/doc/view/1.4.313.1/windows/antora/spec/latest/appendices/spirvenv.html#VUID-StandaloneSpirv-Base-04781), the validator doesn't allow OpBitCount to have non-32 bit integer types

Note: This is in contrast to the spir-v OpBitCount specification that denotes the Result and Base type can be a scalar or vector of integer type.

This will most likely require emulation of the non-32 bit types.

**Environment**
DXC version 1.8.2403.2
Host Operating System N/A

### PR DESCRIPTION
**Pull request by Keenuts**
The SPIR-V instruction can work on non-32 bit components, but only with VK maintenance 9, which seems to be hidden behing a feature bit.
Implementing countbit on such types by converting to a 32-bit integer first. Should be ok.

Fixes #7494

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -9907,6 +9910,85 @@ SpirvInstruction *SpirvEmitter::processDerivativeIntrinsic(
...
+      spvBuilder.getConstantInt(astContext.UnsignedIntTy, llvm::APInt(32, 32));
+  if (isVector) {
+    SmallVector<SpirvConstant *, 4> Components;
+    for (unsigned I = 0; I < count; ++I)
+      Components.push_back(shiftAmount);
+    shiftAmount = spvBuilder.getConstantComposite(uintType, Components);
+  }
+
+  SpirvInstruction *rhs = spvBuilder.createBinaryOp(
+      spv::Op::OpShiftLeftLogical, argType, loadInst, shiftAmount, srcLoc);
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp]: As you have mentioned, this should be right.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 2]
```diff
@@ -9907,6 +9910,85 @@ SpirvInstruction *SpirvEmitter::processDerivativeIntrinsic(
...
+  auto *rhs32 =
+      spvBuilder.createUnaryOp(spv::Op::OpUConvert, uintType, rhs, srcLoc);
+  auto *rhs_count =
+      spvBuilder.createUnaryOp(spv::Op::OpBitCount, uintType, rhs32, srcLoc);
+
+  return spvBuilder.createBinaryOp(spv::Op::OpIAdd, uintType, rhs_count,
+                                   lhs_count, srcLoc);
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:9995]: What is the return type is is always uint or will it be 64-bits with a 64-bit input?

Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9995]: Looks like it's not defined for uint16/uint64, might be an DXIL overlook to accept those?
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/countbits---sm5---asm-
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/countbits

Since the SPIR-V instruction is 32 anyway, I'd say keeping it 32 should be fine.

Comment (s-perron) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9995]: Right. OpBitCount requires 32-bit integers. Doing the add as a 32-bit integer is fine. We should check the return type of `callExpr`. If it is not 32-bit integer, we should cast it to the correct type. The type of the instruction we return should match the type of the AST node.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 3]
```diff
@@ -9907,6 +9910,85 @@ SpirvInstruction *SpirvEmitter::processDerivativeIntrinsic(
...
+  bool isVector = isVectorType(argType);
+  uint32_t count = isVector ? hlsl::GetHLSLVecSize(argType) : 1;
+  QualType uintType =
+      isVector ? astContext.getExtVectorType(astContext.UnsignedIntTy, count)
+               : astContext.UnsignedIntTy;
+
+  auto *extended =
+      spvBuilder.createUnaryOp(spv::Op::OpUConvert, uintType, loadInst, srcLoc);
+  return spvBuilder.createUnaryOp(spv::Op::OpBitCount, uintType, extended,
+                                  srcLoc);
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:9958]: We might need a cast here too if the type of the callExpr is not a 32-bit integer.

Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9958]: There is already an implicit cast, but I should add those in the test file so we don't add a regression later.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp (hunk 2 above)
Comment (s-perron) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp:9995]: Looking at the AST, it seems like the result type is always uint32. See https://godbolt.org/z/8rvGsa1xx. Maybe we can just assert that is result type of the callExpr. We should look at the result type fo the callExpr at some point.

**Comment by Keenuts** [comment]
failure in the CI seems to be related to a macos machine failure.
