### PR TITLE
Close #75 - Pack prefix-stable by default

### LINKED ISSUE #75: dxc from dxil-1.0 branch has incorrect input register mapping
For a pixel shader that reads two texture coordinates:

```c++
void ps_main
(
  noperspective float2 tex0 : TEXCOORD0,
  noperspective float4 tex1 : TEXCOORD1,
  out float4 color : SV_Target
)
{
  color = tex0.xxyy + tex1;
}
```

I am seeing the following input signature in DXIL when using `dxc` from `dxil-1.0`:

```
;
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 1   xyzw        0     NONE   float       
; TEXCOORD                 0   xy          1     NONE   float       
;
```

Notice how index 1 maps to register 0, and index 0 maps to register 1.

If I compile the same shader using the DXIL 0.7 front-end, I see:

```
;
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 0   xy          0     NONE   float       
; TEXCOORD                 1   xyzw        1     NONE   float       
;
```

which is what I would expect.

### PR DESCRIPTION
**Pull request by tex3d**
Closes #75 

Add options:
- "-pack_prefix_stable" - (default) packs signature elements maintaining prefix-stable property that appended elements do not affect the packing of prior elements.
- "-pack_optimized" - pack with whole signature optimization, requiring all signature elements to be defined in the same way for placement of any individual elements to be identical.

### CODE REVIEW

File: include/dxc/HLSL/HLModule.h [hunk 1]
```diff
@@ -281,6 +283,7 @@ class HLModule {
   HLOptions m_Options;
   std::unique_ptr<OP> m_pOP;
   size_t m_pUnused;
+  DXIL::PackingStrategy m_PackingStrategy;
```
Comment (tex3d) [inline include/dxc/HLSL/HLModule.h]: getting rid of this unused member.
