### PR TITLE
Fix issues with -Qstrip_reflect and -Qstrip_debug

### LINKED ISSUE #2162: -Qstrip_reflect re-emits root signature metadata when present, causing validation to fail
Recently added support for -Qstrip_reflect will re-emit the metadata after root signature metadata was deleted, but stored serialized root signature is still present (so it may be serialized out later).  This leads to a validation error.

One way to fix this would be to strip reflection earlier.  But that leaves the problem that re-emitting the metadata will emit something that's not valid in final DXIL, making it more likely this bug could be introduced again.  Perhaps a flag on EmitDxilMetadata, or on the DxilModule signifying that it is final metadata would be useful, as it would avoid emitting metadata that shouldn't be in final DXIL in the first place.  For information required to emit to other container parts that live in metadata during intermediate stages, care would have to be taken that a live DxilModule carries this information independently from the metadata between the final emit and the SerializeDxilContainerForModule(), otherwise it could be lost.

### PR DESCRIPTION
**Pull request by tex3d**
-Qstrip_reflect would reserialize the root signature, leading to
validation failure #2162.  Fixed by moving root sig to writer to clear
from module and prevent re-serialization to metadata.

Fixed -Qstrip_debug with -Zi and no output location still embeding
debug module.

Fixes #2162.

### CODE REVIEW

File: lib/DxilContainer/DxilContainerAssembler.cpp [hunk 1]
```diff
@@ -1527,7 +1527,8 @@ void hlsl::SerializeDxilContainerForModule(DxilModule *pModule,
   std::unique_ptr<DxilPSVWriter> pPSVWriter = nullptr;
   unsigned int major, minor;
   pModule->GetDxilVersion(major, minor);
-  RootSignatureWriter rootSigWriter(pModule->GetSerializedRootSignature());
+  RootSignatureWriter rootSigWriter(std::move(pModule->GetSerializedRootSignature())); // Grab RS here
```
Comment (MrTrillian) [inline lib/DxilContainer/DxilContainerAssembler.cpp]: Per standard, the only valid thing to do on a moved-out object is to destroy it. Even your empty() below is undefined, as well as anything else we might try to do with that vector. It'd have been better to `std::swap` it with your empty one.

Also I'd have liked a comment explaining why we are leaving the module without a root signature.
