### PR TITLE
LongVectors tests: Fix device leak and improve logging

### LINKED ISSUE #7949: Long Vectors tests: add better logging around FailIfRequirementsNotMet
It took a long to figure out that when running in environments where `_HLK_CONF` is defined the LongVectors tests will, by default, fail if the device doesn't support SM 6.9.

The log output does not make this clear.  For example:

```
The selected device does not support shader model 6.9
Error: Verify: IsTrue(createDevice(&D3DDevice, D3D_SHADER_MODEL_6_9, false)) [File: D:\a\_work\1\s\packages\OSS\dxil\test\hlk\LongVectors.cpp, Function: DxilConf_SM69_Vectorized::methodSetup, Line: 1791]
Error: TAEF: Setup fixture 'DxilConf_SM69_Vectorized::methodSetup' for the scope 'DxilConf_SM69_Vectorized::Abs_HLSLHalf_t' failed.

StartGroup: DxilConf_SM69_Vectorized::Abs_HLSLHalf_t
EndGroup: DxilConf_SM69_Vectorized::Abs_HLSLHalf_t [Failed]
```

It would be really good if this made it clear why the default behavior is different.

### PR DESCRIPTION
**Pull request by damyanp**
Previously, if a device is removed then the code that recreates it wouldn't release the old device pointer, resulting in the device leaking. This actually prevents removed device recovery entirely, since all references to a removed device need to be released before a new one can be created.  This change fixes that.

Also:

* improve logging in situations where requirements aren't met (eg trying to create a SM 6.9 device on a system that doesn't support SM 6.9)
* return false from class setup if we couldn't create a device - this will cause all the tests in the class to be skipped or failed (depending on the FailIfRequirementsNotMet setting) - reducing log noise, and saving the time that would be taken to run tests that we know are going to fail
* improve logging when recreating a device so we can tell the difference between "device was removed" and "there wasn't a device set"
* add a warning log if createDevice is called with something that looks like it already has a value set

Fixes #7949

### CODE REVIEW

File: tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp [hunk 1]
```diff
@@ -69,6 +69,11 @@ static UINT getD3D12SDKVersion(std::wstring SDKPath) {
 
 bool createDevice(ID3D12Device **D3DDevice, D3D_SHADER_MODEL TestModel,
                   bool SkipUnsupported) {
+
+  if (*D3DDevice)
+    hlsl_test::LogWarningFmt(L"createDevice called with non-null *D3DDevice - "
```
Comment (tex3d) [inline tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp:74]: Could this be a failure instead of a warning? It seems bad to allow this with just a warning.

**Review by tex3d — APPROVED** [review]
Looks good, but it feels like we should fail if we would overwrite a device pointer (creating a leak) rather than just issue a warning.

File: tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp (hunk 1 above)
Comment (damyanp) [reply tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp:74]: I'm maybe being overly cautious here, and partly this is because of the distance between this code and it running in its final location, I wanted to find out places where this might be happening without taking everything down with it - hence the warning.

Comment (tex3d) [reply tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp:74]: If it caused failures in current runs, I think we'd want to know and fix those anyway. Is now just a particularly bad time to potentially disrupt the tests? Maybe we can follow up with a change to turn this into a failure instead of doing it here.

Comment (damyanp) [reply tools/clang/unittests/HLSLExec/HlslExecTestUtils.cpp:74]: Agreed, yes, and agreed :)

**Review by inbelic — APPROVED** [review]
LGTM, other than a simple reminder that I don't see a follow-up issue/pr linked to convert to an error message.

**Comment by damyanp** [comment]
#7958 tracks the follow-up task.
