### PR TITLE
[spirv] Add needed capabilities for Raytracing AccelerationStructure.

### LINKED ISSUE #3070: [SPIR-V] Declaring RayTracingAccelerationStruct in compute shader crashes the compiler
This file (test.hlsl):

```
RaytracingAccelerationStructure test_bvh;

[numthreads(1, 1, 1)]
void main()
{
}
```

compiled with:

```
dxc.exe -spirv -T cs_6_4 -Ges -WX -fvk-use-dx-position-w -fvk-use-scalar-layout -fspv-target-env=vulkan1.2 "test.hlsl" -Fo test.spv -O0
```

Result in : 

```
1>DXC : fatal error : generated SPIR-V is invalid: Opcode TypeAccelerationStructureKHR requires one of these capabilities: RayQueryProvisionalKHR RayTracingNV RayTracingProvisionalKHR
1>  %accelerationStructureNV = OpTypeAccelerationStructureKHR
1>
1>note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### PR DESCRIPTION
**Pull request by ehsannas**
Fixes #3070

### CODE REVIEW

File: tools/clang/lib/SPIRV/CapabilityVisitor.cpp [hunk 1]
```diff
@@ -195,9 +195,20 @@ void CapabilityVisitor::addCapabilityForType(const SpirvType *type,
...
       addCapabilityForType(field.type, loc, sc);
   }
-  //
-  else if (const auto *rayQueryType =
-               dyn_cast<RayQueryProvisionalTypeKHR>(type)) {
+  // AccelerationStructureTypeNV type
+  else if (isa<AccelerationStructureTypeNV>(type)) {
+    if (featureManager.isExtensionEnabled(Extension::NV_ray_tracing)) {
+      addCapability(spv::Capability::RayTracingNV);
+      addExtension(Extension::NV_ray_tracing, "SPV_NV_ray_tracing", {});
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/CapabilityVisitor.cpp:202]: Nit: I am curious we have an unit test that checks this case.

Comment (ehsannas) [reply tools/clang/lib/SPIRV/CapabilityVisitor.cpp:202]: Done
