### PR TITLE
[Validation] Make validator reject unsupported llvm integer sizes

### LINKED ISSUE #6563: DxilValidation should reject unsupported llvm integer sizes
**Description**
Some locations in Clang CodeGen or llvm optimizations will result in odd-sized int value types, such as `i25`.  The DXIL Validator should catch and reject such unsupported sizes when found in the IR, and we should fix the sources of these to prevent them from appearing in the first place.

**Steps to Reproduce**
```hlsl
uint param;

bool fn()
{
    switch (param)
    {
    case 0:
    case 20:
    case 24:
        return false;
    }
    return true;
}

float4 main() : SV_Target
{
    float4 ret = float4(0, 0, 0, 0);
    if (fn())
    {
        ret = float4(1, 1, 1, 1);
    }
    return ret;
}
```

**Actual Behavior**
Results in IR containing `i25`:
```llvm
  %6 = trunc i32 %3 to i25
  %7 = lshr i25 15728638, %6
  %8 = and i25 %7, 1
  %9 = icmp ne i25 %8, 0
  %10 = select i1 %9, float 1.000000e+00, float 0.000000e+00
```

This `i25` type should never be produced or accepted by DxilValidation.  In this case, an optimization produces the value (which is usually the case).

This bug is about preventing this from passing validation.  See #6564 for tracking the optimization producing the value in the first place.

**Environment**
- DXC version: latest main, not a regression
- Host Operating System: any

### PR DESCRIPTION
**Pull request by damyanp**
There are a limited number of supported integer sizes in DXIL. This change updates the validator to reject shaders that use unsupported integer sizes.

Fixes #6563

### CODE REVIEW

**Review by tex3d — APPROVED** [review]
LGTM.

File: lib/DxilValidation/DxilValidation.cpp [hunk 1]
```diff
@@ -3388,10 +3400,17 @@ static void ValidateFunctionBody(Function *F, ValidationContext &ValCtx) {
           }
         }
         if (IntegerType *IT = dyn_cast<IntegerType>(op->getType())) {
-          if (IT->getBitWidth() == 8) {
+          unsigned BW = IT->getBitWidth();
+          if (BW == 8) {
             // We always fail if we see i8 as operand type of a non-lifetime
             // instruction.
             ValCtx.EmitInstrError(&I, ValidationRule::TypesI8);
+          } else if (!IsValidIntBitWidth(BW)) {
```
Comment (bob80905) [inline lib/DxilValidation/DxilValidation.cpp]: ValidateFunctionBody will call ValidateType in certain scenarios. I wonder if your test will pass without these two else ifs?
If it is possible, it is better to designate one location for validating types, and that function and your changes to it seem like the perfect fix. 
And if not, then maybe calling ValidateType instead of the else if would be better?
For example, I wonder if calling ValidateType once at 3377 will do the same as these two else ifs.

Comment (damyanp) [reply lib/DxilValidation/DxilValidation.cpp]: Nice catch, I think that works out nicer!
