### PR TITLE
[SPIRV] Emit Offset decoration for PhysicalStorage structs

### LINKED ISSUE #5327: [SPIR-V] DXC generates invalid SPIR-V when using RawBufferLoad with a struct.
From the SPIR-V spec:

> [Composite](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#CompositeType) objects in the StorageBuffer, PhysicalStorageBuffer, Uniform, and PushConstant [Storage Classes](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Storage_Class) must be explicitly laid out. The following apply to all the aggregate and matrix types describing such an object, recursively through their nested types:
>
> - Each structure-type member must have an Offset [decoration](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration).

SPIRV-Tools started to validate this rule, meaning DXC now fails hard.
Seems like we simply don't generate the `Offset` member decoration when the offset is not explicit.

Looking at the code, I see 2 places to handle that:
 - LowerTypeVisitor.cpp: only add the offset decoration when required.
 - EmitVisitor.cpp: always add the offset decoration.
 

Method 1:
To fix this in the LowerTypeVisitor.cpp, we should not only pass the layout, but also the storage class where the type is used (which here is what's changing the offsets/decorations).
Then, depending on the storage class, the offset will be set in the type or not, the the rest of the code should handle it.
This seems to be the clean method, but requires some larger changes to the lowerTypeVisitor.

Method 2:
The second method is a bit more basic: always add the decoration.
I don't think the spec is against always specifying the Offset member decoration.
This would allow us to have a simple fix.
 - Bitfields should be handled correctly since the fields are already squashed.
 - Specific offsets (layout rule by ex), the offset is pre-computed, so we don't have to compute it. Otherwise we have the full-type, so we should always have the correct size.
 
 Repro steps:
 
 
 ```hlsl
 struct S {
  uint f1;
};

uint64_t Address;

[numthreads(64, 1, 1)]
void main(uint3 id : SV_DispatchThreadID) {
  uint tmp = vk::RawBufferLoad<S>(Address).f1;
}
 ```
 
 ```bash
 dxc -spirv -T cs_6_0 -E main -HV 2021 repro.hlsl
 ```

### PR DESCRIPTION
**Pull request by Keenuts**
When the SPV_EXT_physical_storage_buffer extensions is used, vulkan can load raw addresses. For structs loaded through this mecanism, the offsets must be explicit.

This commit fixes decoration emission by attaching the correct layout when a struct is loaded using this extensions.
(Specifying a layout different than void forces explicit offsets).

Fixes #5327

### CODE REVIEW

**Comment by Keenuts** [comment]
This PR fails tests right now (requires fixes in #5390)

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp [hunk 1]
```diff
@@ -369,19 +369,25 @@ SpirvUnaryOp *SpirvBuilder::createUnaryOp(spv::Op op, QualType resultType,
                                           SpirvInstruction *operand,
                                           SourceLocation loc,
                                           SourceRange range) {
+  if (!operand)
+    return nullptr;
```
Comment (s-perron) [inline tools/clang/lib/SPIRV/SpirvBuilder.cpp:373]: How does this happen? This is a change in behaviour, so I want to understand why.

**Review by s-perron — CHANGES_REQUESTED** [review]
I think this looks good. I just want to understand how we get a null operand. That seems like an error on the part of the caller.

File: tools/clang/lib/SPIRV/SpirvBuilder.cpp (hunk 1 above)
Comment (Keenuts) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:373]: So when we have an error, we call emittError and then return null.
Example: when handling an non-implemented intrinsic function, if the function is not implemented, we emit, and return null.

But the expression is still getting parsed. The code usually is fine with that, the null moves around, and in the end, we return nullptr and show the error.

But this means functions like that can get called with nullptr.
The exact chain for this bug is:
 - castToInt(loadIfGL(subExpr)).

The loadIfGL is done on a subExpr using a non-implemented intrinsic (dot4), and returns nullptr. castToInt calls doUnaryOp, because it's a cast, but with a null operand.

Initially, I thought I should fix this call-site, but the pattern is a bit everywhere.

What I think should be good is:
 - in the SpirvBuilder, assert for null parameters.
 - in the emitter, allow null params, but check for validity before doing ptr->toRValue() but also when calling spirvBuilder functions like this one.

Comment (s-perron) [reply tools/clang/lib/SPIRV/SpirvBuilder.cpp:373]: The ideal solution is to emit and error before we start translating the AST into spir-v, but making the code more robust is good too.

**Review by s-perron — APPROVED** [review]

**Review by cassiebeckley — APPROVED** [review]
