### PR TITLE
Fix issues with structured buffer load lowering

### LINKED ISSUE #2219: Crash on StructuredBuffer<T>.Load with matrices of more than 4 elements
Repro:
```
StructuredBuffer<int2x3> sbuf;
int2x3 main() : OUT { return sbuf.Load(0); }
```
The same applies to `ByteAddressBuffer.Load<int2x3>(0)`. `StructuredBuffer<int2x3>::operator[]` does however work.

### PR DESCRIPTION
**Pull request by vcsharma**
Fixes three issues related to lowering of structured buffer load. 

The first one is a crash in templated structured buffer load on matrices of size > 4 when using `.Load()` method. The same worked fine for subscript-based loads. For the case of subscript-based loads, the matrix type is not lowered to vector type in `HLMatrixLower`. This allows special handling of matrix type in `HLOperationLower` as the type information is preserved. For the `.Load()` method case, the matrix type is lowered to vector type in `HLMatrixLower` itself. Therefore in the `HLOperationLower` pass, the lowering of matrix-load using the `.Load` method was getting treated as just another load of vector type and was causing a crash when the component count of vector exceeds 4 (in case of matrices).  This PR refactors the lowering code used for the subscript-based matrix load into a new function `TranslateStructBufVecLd` which can lower load for any size vectors (including scalar). The same method (`TranslateStructBufVecLd`) is now also used for lowering loads involving the `.Load()` method.

The second issue is related to not handling bool types correctly for the `.Load()` case. `Boolean` type is represented as `i32` in memory, but we were not converting `i1` to `i32` before lowering which was causing an assert in debug mode and also validation errors as `i1` overload for dxil op `rawBufferLoad` is not supported.

The third issue is that for subscript-based load, we were hardcoding the component count to 3 in some cases leading to mask getting wrongly set as 7. It works fine for the `.Load()` case.

Fixes #2219, #3448, #3449

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -3607,12 +3611,36 @@ void TranslateLoad(ResLoadHelper &helper, HLResource::Kind RK,
...
+    // We always get a vector from TranslateStructBufVecLd(). For vec1 case,
+    // convert it to scalar if needed to match the target type.
+    // Ex 1: For stbuf.Load<float1x1>(i), both the new value type and
+    // the target type is <1 x float>. No conversion needed here.
+    //
+    // Ex 2: For stbuf.Load<float>(i), the new value type is <1 x float>, but
+    // the target type is float, so we need a conversion here.
+    Type* NewValTy = retValNew->getType();
+    if (NewValTy->isVectorTy() && NewValTy->getVectorNumElements() == 1 &&
+       helper.retVal->getType() == NewValTy->getVectorElementType()) {
```
Comment (pow2clk) [inline lib/HLSL/HLOperationLower.cpp:3640]: Is the only way the `helper.retVal->getType()` and `NewValTy->getVectorElementType()` differ is by one being a vector and the other not? If so, is this really just checking if helper.retVal is a scalar?

I don't see how they could be different component types

File: lib/HLSL/HLOperationLower.cpp [hunk 2]
```diff
@@ -3607,12 +3611,36 @@ void TranslateLoad(ResLoadHelper &helper, HLResource::Kind RK,
...
+    unsigned ElemCount = RetTy->isVectorTy() ? RetTy->getVectorNumElements() : 1;
+    std::vector<Value*> bufLds;
+    const bool isBool = EltTy->isIntegerTy(1);
+
+    // Bool are represented as i32 in memory
+    Type* MemReprTy = isBool ? Builder.getInt32Ty() : EltTy;
+    Value* retValNew = TranslateStructBufVecLd(MemReprTy, ElemCount, Builder, helper.handle, OP, helper.status,
+      helper.addr, OP->GetU32Const(0), DL, bufLds);
+    DXASSERT_NOMSG(!bufLds.empty());
+    dxilutil::MigrateDebugValue(helper.retVal, bufLds.front());
```
Comment (pow2clk) [inline lib/HLSL/HLOperationLower.cpp:3624]: If only one element of bufLds is ever used, does it need to be a vector of all the loads?

File: tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint2x2 %s | FileCheck %s -check-prefix=CHK_MAT2x2
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=float16_t2x3 %s | FileCheck %s -check-prefix=CHK_MAT2x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint16_t3x2 %s | FileCheck %s -check-prefix=CHK_MAT3x2
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=float3x3 %s | FileCheck %s -check-prefix=CHK_MAT3x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=int3x4 %s | FileCheck %s -check-prefix=CHK_MAT3x4
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=bool4x3 %s | FileCheck %s -check-prefix=CHK_MAT4x3
+// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types -DTY=uint4x4 %s | FileCheck %s -check-prefix=CHK_MAT4x4
+
+
+// CHK_MAT1x1: call %dx.types.ResRet.f32 @dx.op.rawBufferLoad.f32(i32 139, %dx.types.Handle %{{.*}}, i32 %{{.*}}, i32 0, i8 1, i32 4)
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl:13]: You call out the assignment of a 1x1 matrix to a scalar in the code above, are there tests already that verify that functionality?

**Review by pow2clk — COMMENTED** [review]
I'm delighted to see this issue resolved at last!

I have just a few queries

File: lib/HLSL/HLOperationLower.cpp [hunk 4]
```diff
@@ -3607,12 +3611,36 @@ void TranslateLoad(ResLoadHelper &helper, HLResource::Kind RK,
...
 
   if (DXIL::IsStructuredBuffer(RK)) {
-    // Basic type case for StructuredBuffer::Load()
-    Value *ResultElts[4];
-    Value *StructBufLoad = GenerateStructBufLd(helper.handle, helper.addr, OP->GetU32Const(0),
-      helper.status, EltTy, ResultElts, OP, Builder, numComponents, Alignment);
-    dxilutil::MigrateDebugValue(helper.retVal, StructBufLoad);
-    Value *retValNew = ScalarizeElements(Ty, ResultElts, Builder);
+    Type* RetTy = helper.retVal->getType();
+    unsigned ElemCount = RetTy->isVectorTy() ? RetTy->getVectorNumElements() : 1;
```
[the remark this answers is not in the document]
Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: That's right, updated.

File: lib/HLSL/HLOperationLower.cpp (hunk 1 above)
Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: I cleaned it up a bit to make it less confusing. I am now passing a boolean flag to indicate in `TranslateStructBufVecLd` to indicate when building vector can be skipped in the first place.  

`TranslateStructBufMatLd` -> `TranslateStructBufVecLd`  // Can only have vector types 
`TranslateLoad` -> `TranslateStructBufVecLd` // Can have both scalar and vector types

File: lib/HLSL/HLOperationLower.cpp (hunk 2 above)
Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp:3623]: cleaned it up.

File: tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl (hunk 3 above)
Comment (vcsharma) [reply tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl:19]: There should be tests already to check for the scalar case like (struct_buf2.hlsl), but I added here a couple of tests to cover scalar and vec1 cases for completeness sake.

**Review by pow2clk — APPROVED** [review]
Looks good!  I like the skipped vector creation! I hadn't thought of that.

**Review by tex3d — APPROVED** [review]
LGTM

File: lib/HLSL/HLOperationLower.cpp [hunk 5]
```diff
@@ -6856,34 +6870,32 @@ void GenerateStructBufSt(Value *handle, Value *bufIdx, Value *offset,
...
-  std::vector<Value *> elts(matSize);
-
-  unsigned rest = (matSize % 4);
+  std::vector<Value*> elts(ElemCount);
+  unsigned rest = (ElemCount % 4);
   if (rest) {
-    Value *ResultElts[4];
-    GenerateStructBufLd(handle, bufIdx, offset, status, EltTy, ResultElts, OP, Builder, 3, alignment);
+    Value* ResultElts[4];
+    Value *bufLd = GenerateStructBufLd(handle, bufIdx, offset, status, VecEltTy, ResultElts, OP, Builder, rest, alignment);
```
Comment (tex3d) [inline lib/HLSL/HLOperationLower.cpp:6888]: Just realized, and this was already present in the refactored code:
While the code produces correct results, when rest is non-zero, it will produce 4-vector loads that aren't aligned in an expected way to the beginning of the vector/matrix, leading to possible performance implications.  We should fix this in a subsequent change, since It may be a pattern used elsewhere as well.

Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp:6888]: Given that the noted codegen behavior existed before this change, I have another work item to track this #3457 so that we can introduce this as a separate change.
