### PR TITLE
Execution Tests:  Long Vector - Loading and storing of buffers

### LINKED ISSUE #7543: Long Vector Execution Tests: Add test cases for loading/storing from a resources sourced in all possible ways
There was a bug caught during SM 6.9 preview resulting in a crash while loading a LongVector<half, 16> from a ResourceDescriptorHeap. 

Filing an issue to ensure we add coverage for loading from a ResourceDescriptorHeap.

The most recent Long Vector test plan document should be referenced when implementing: [Long Vector Test Plan](https://github.com/microsoft/hlsl-specs/blob/b9922ed215ac7e078bc7f45a831d1d8d0df525c8/proposals/infra/INF-0005-Long-Vector-ExecutionTest-Plan.md)

### PR DESCRIPTION
**Pull request by alsepkow**
This PR adds test cases for loading and storing of Byte Address Buffers and Structured Buffers using Root Descriptors, Descriptor Tables, and Root Descriptor Heaps. Reading is test using both SRV and UAV resources. Writing is only valid on UAV resources.

Resolves #7543

### CODE REVIEW

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 1]
```diff
@@ -1042,6 +1117,27 @@ template <typename T> struct ExpectedBuilder<OpType::ShuffleVector, T> {
...
 };
 
+//
+// Loading and Storing of buffers
+//
+// #define CAST_OP(OP, TYPE, IMPL)
+//  template <typename T> struct Op<OP, T, 1> : StrictValidation {
+//    TYPE operator()(T A) { return IMPL; }
+//  };
+// TODO: Should swap these and initialize to strict validation
```
Comment (alsepkow) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]: Whoops, Will do this.

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 2]
```diff
@@ -318,7 +332,10 @@ void fillShaderBufferFromLongVectorData(std::vector<BYTE> &ShaderBuffer,
   // enough space.
   const size_t NumElements = TestData.size();
   const size_t DataSize = sizeof(T) * NumElements;
-  ShaderBuffer.resize(DataSize);
+
+  // Ensure the shader buffer is large enough. It should be pre-sized based on
+  // the D3D12_RESOURCE_DESC for the associated D3D12_RESOURCE.
```
Comment (alsepkow) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp:337]: I should update this comment to be a little more specific about what part of the desc are important

File: tools/clang/unittests/HLSLExec/LongVectorOps.def [hunk 3]
```diff
@@ -129,28 +134,58 @@ OP_DEFAULT(BinaryComparison, NotEqual, 2, "", "!=")
...
 
+
+#define OP_LOAD_AND_STORE(SYMBOL, SHADER_NAME)                                 \
+   OP(UNARY, SYMBOL, 1, "", "", "", "LongVectorOp_" SHADER_NAME,               \
+       Default1, Default2, Default3)
+#define OP_LOAD_AND_STORE_SB(SYMBOL, SHADER_NAME)                              \
+   OP(UNARY, SYMBOL, 1, "", "", " -DUSE_STRUCTURED_BUFFER=1",                  \
+      "LongVectorOp_" SHADER_NAME, Default1, Default2, Default3)
+
+// BAB == Byte Address Buffer
```
Comment (alsepkow) [inline tools/clang/unittests/HLSLExec/LongVectorOps.def:169]: Really wasn't sure about naming on these. I hated the even longer verbose names. These don't feel great either. But I dislike them less.

File: tools/clang/unittests/HLSLExec/ShaderOpArith.xml [hunk 4]
```diff
@@ -3717,15 +3717,301 @@ void MSMain(uint GID : SV_GroupIndex,
     </Shader>
   </ShaderOp>
 
+  <ShaderOp Name="LongVectorOp_RootDescriptor_UAV" CS="CS">
+    <RootSignature>RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),
```
Comment (inbelic) [inline tools/clang/unittests/HLSLExec/ShaderOpArith.xml]:
```suggestion
    <RootSignature>
```

I don't think this flag is applicable to compute shaders. Is there a reason it is being used?

File: tools/clang/unittests/HLSLExec/ShaderOpArith.xml [hunk 5]
```diff
@@ -3717,15 +3717,301 @@ void MSMain(uint GID : SV_GroupIndex,
...
+          #endif
+        };
+      ]]>
+    </Shader>
+  </ShaderOp>
+
   <ShaderOp Name="LongVectorOp" CS="CS">
-    <RootSignature>RootFlags(0), UAV(u0), UAV(u1), UAV(u2),
-    UAV(u3)</RootSignature>
+    <RootSignature>RootFlags(0), UAV(u0),
```
Comment (inbelic) [inline tools/clang/unittests/HLSLExec/ShaderOpArith.xml]:
```suggestion
    <RootSignature>UAV(u0),
```
nit: This is equivalent to the default of not specifying

File: tools/clang/unittests/HLSLExec/ShaderOpArith.xml (hunk 4 above)
Comment (alsepkow) [reply tools/clang/unittests/HLSLExec/ShaderOpArith.xml]: I had just copied from others. Will remove!

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 6]
```diff
@@ -370,22 +387,21 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
...
-
-  // The name of the shader we want to use in ShaderOpArith.xml. Could also
-  // add logic to set this name in ShaderOpArithTable.xml so we can use
-  // different shaders for different tests.
-  LPCSTR ShaderName = "LongVectorOp";
-  // ShaderOpArith.xml defines the input/output resources and the shader
-  // source.
   CComPtr<IStream> TestXML;
   readHlslDataIntoNewStream(L"ShaderOpArith.xml", &TestXML, DxilDllLoader);
+  auto ShaderOpSet = std::make_shared<st::ShaderOpSet>();
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp:392]: Does this really have shared ownership?

Oh, maybe this is stuck trying to fit in with some of the pre-existing questionable uses of shared pointers that we're not going to fix up now.  Never mind!

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 7]
```diff
@@ -431,6 +450,62 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
   return OutData;
 }
 
+// LoadAndStore operations dynamically configure sizes on the underlying
+// resources based on the vector size and data type size.
+void configureLoadAndStoreShaderOp(
+    const Operation &Operation, const DataType &OpDataType, size_t VectorSize,
+    size_t ElementSize, std::shared_ptr<st::ShaderOpSet> &ShaderOpSet) {
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]: It doesn't look like this function actually takes ownership of ShaderOpSet does it? I'm pretty sure it isn't going to reassign it to something else?

```suggestion
    size_t ElementSize, st::ShaderOpSet *ShaderOpSet) {
```

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 8]
```diff
@@ -370,22 +387,21 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
...
+    configureLoadAndStoreShaderOp(Operation, OpDataType, Inputs[0].size(),
+                                  sizeof(T), ShaderOpSet);
 
   // RunShaderOpTest is a helper function that handles resource creation
   // and setup. It also handles the shader compilation and execution. It takes
   // a callback that is called when the shader is compiled, but before it is
   // executed.
-  std::shared_ptr<st::ShaderOpTestResult> TestResult = st::RunShaderOpTest(
-      D3DDevice, DxilDllLoader, TestXML, ShaderName,
+  auto TestResult = st::RunShaderOpTestAfterParse(
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]: I think it was better to be explicit about the typename here.  I can't tell from just reading the code here what the return type of `RunShaderOpTestAfterParse` is.

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 9]
```diff
@@ -418,11 +434,14 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
 
         LOG_ERROR_FMT_THROW(
             L"RunShaderOpTest CallBack. Unexpected Resource Name: %S", Name);
-      });
+      },
+      ShaderOpSet);
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]:
```suggestion
      std::move(ShaderOpSet));
```

This would have helped me understand that the intent here is to transfer ownership to this function.

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 10]
```diff
@@ -431,6 +450,62 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
...
 
+// LoadAndStore operations dynamically configure sizes on the underlying
+// resources based on the vector size and data type size.
+void configureLoadAndStoreShaderOp(
+    const Operation &Operation, const DataType &OpDataType, size_t VectorSize,
+    size_t ElementSize, std::shared_ptr<st::ShaderOpSet> &ShaderOpSet) {
+
+  DXASSERT_NOMSG(LoadAndStoreOpTypes.count(Operation.Type) > 0);
+
+  auto ShaderOp = ShaderOpSet->GetShaderOp(Operation.ShaderName);
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]: What's the type of `ShaderOp`?  It'd be better to be explicit here.

(this is the guidance driving my comments about the auto's: https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable)

File: tools/clang/unittests/HLSLExec/LongVectors.cpp [hunk 11]
```diff
@@ -431,6 +450,62 @@ runTest(ID3D12Device *D3DDevice, bool VerboseLogging,
...
+  DXASSERT(ShaderOp, "Invalid ShaderOp name");
+
+  // When using DXGI_FORMAT_R32_TYPELESS, we need to compute the number of
+  // 32-bit elements required to hold the vector.
+  const UINT Num32BitElements = static_cast<UINT>(
+      std::ceil(VectorSize * (OpDataType.HLSLSizeInBytes / 4.0f)));
```
Comment (damyanp) [inline tools/clang/unittests/HLSLExec/LongVectors.cpp]: Surprised to see floating point math here.

Should this be `VectorSize * (OpDataType.HlslSizeInBytes + 3) / 4`?

**Review by damyanp — CHANGES_REQUESTED** [review]
Mostly looks good, but probably should bottom out on my comments before merging :)

**Review by damyanp — APPROVED** [review]
