### PR TITLE
Fix downlevel validator compatibility with DXR 1.1 flag

### LINKED ISSUE #6321: RaytracingTier1_1 flag should not be set in module based on subobject
**Description**
DxilModule checks `StateObjectConfig` in subobjects for `AllowStateObjectAdditions`, then sets the module flag `RaytracingTier1_1` based on this, if not already set for some other reason.

This is incorrect, as the runtime will enforce feature requirement based on the subobjects used, and the module flag will prevent a library containing the subobject from being created, even if this Tier 1.1 subobject is not used.

On top of this, since subobjects are removed from the module during container serialization, recomputation of flags for validation will not see the requirement.  This doesn't fail right now because flag validation is disabled for libraries (which it shouldn't be).  This validation will be enabled for 1.8, so it's necessary to fix this issue before DXIL 1.8 release.

**Steps to Reproduce**
```hlsl
// dxc -T lib_6_5
StateObjectConfig soc = { STATE_OBJECT_FLAGS_ALLOW_LOCAL_DEPENDENCIES_ON_EXTERNAL_DEFINITONS | STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS };
```
"Raytracing tier 1.1 features" should not be a required feature for this module.

**Actual Behavior**
Disassembly output states that "Raytracing tier 1.1 features" is required.

**Environment**
- DXC version: any
- Host Operating System: any

### PR DESCRIPTION
**Pull request by tex3d**
It turns out that in the prior validator version, if a subobject required DXR 1.1, the DXR 1.1 flag would be set on each function in RDAT output, as well as the global flags. It didn't appear this was the case through a D3DReflect test because that goes through disassembly to assembly step, where subobjects are lost because they aren't in the llvm IR. The previous change assumed this was not the case when the subobjects were removed, but this removal occurs after the RDATWriter constructor, which does the full RDAT serialization since size if required right away.

This restores the detection code and hooks it into DxilModule::ComputeShaderCompatInfo when validator version is in range [1.5, 1.7]. DXR 1.1 was introduced in 1.5, and we no longer tag every function as requiring DXR 1.1 based on subobjects in 1.8.

At the moment, there is no way to CHECK the subobject RDAT in D3DReflect because they get stripped from the module (even reflection and debug modules) before serialization, and the test path for D3DReflect goes through a disassemble/re-assemble step between the prior stage and the D3DReflect stage.

Fixes #6321 (really).

### CODE REVIEW

File: lib/HLSL/DxilValidation.cpp [hunk 1]
```diff
@@ -4487,6 +4487,19 @@ static void ValidateResources(ValidationContext &ValCtx) {
...
   ShaderFlags calcFlags;
   ValCtx.DxilMod.CollectShaderFlagsForModule(calcFlags);
+
+  // Special case for validator version prior to 1.8.
+  // If DXR 1.1 flag is set, but our computed flags do not have this set, then
+  // this is due to prior versions setting the flag based on DXR 1.1 subobjects,
+  // which are gone by this point.  Set the flag and the rest should match.
+  unsigned valMajor, valMinor;
+  ValCtx.DxilMod.GetValidatorVersion(valMajor, valMinor);
+  if (DXIL::CompareVersions(valMajor, valMinor, 1, 8) < 0 &&
```
Comment (bob80905) [inline lib/HLSL/DxilValidation.cpp:4497]: Do we also need to check that the validator version is >1.5 here?

Comment (tex3d) [reply lib/HLSL/DxilValidation.cpp:4497]: Sure, we could, thanks.

**Review by bob80905 — APPROVED** [review]

**Review by hekota — APPROVED** [review]
LGTM!
