### PR TITLE
[SER] Fix HitObject in/out codegen (and make in the default)

### LINKED ISSUE #7745: [SM6.9] SER HitObjects are always passed by reference
**Description**
The SER HitObjects are supposed to have value semantics, but when passed as function parameter they are always passed by reference, even when specifying the `in` parameter modifier. No modifier should also behave like `in`.

**Steps to Reproduce**

```hlsl
RWBuffer<uint> output : register(u0, space0);

// in, out, inout and no modifier all have the same behaviour
void MakeNop(dx::HitObject obj) {
  obj = dx::HitObject::MakeNop();
}

[shader("raygeneration")]
void RayGen()
{
  RayDesc ray;
  dx::HitObject obj = dx::HitObject::MakeMiss(0, 0, ray);

  MakeNop(obj);
  output[0] = obj.IsNop();
}
```

`-T lib_6_9`
See https://godbolt.org/z/jn4EEMn77

**Actual Behavior**

The HitObject is currently always passed by reference (as if specifying `inout`)

This can be observed in the DXIL, since `HitObject::MakeMiss` call in raygen was optimized away (replaced by `MakeNop` from the function call). 

**Environment**
- DXC version: dxcompiler.dll: 1.9 - 1.8.2505.32 (b106a961d); dxil.dll: 1.9(1.8.2505.32)

### PR DESCRIPTION
**Pull request by simoll**
Closes #7745

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 1]
```diff
@@ -6148,6 +6148,13 @@ void CGMSHLSLRuntime::EmitHLSLRootSignature(HLSLRootSignatureAttr *RSA,
   }
 }
 
+// Helper to determine HLSL object types that should be treated as pass-by-value
+// at HLSL source level by creating a local copy and passing its address.
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp:6152]: Actually, the behavior for objects is *also wrong*!

The reasons are complicated, but I think they involve attempts to eliminate extra copies that the compiler was unable to clean up later in certain real-world use cases. The `HLLegalizeParameter` pass is also involved in an attempt to fix things up when copies were necessary due to writing to an `in` param, but it's not the right approach generally, and it appears to get things wrong for HLSL objects by skipping them entirely (I don't know why).

I'm not suggesting you make a broader change to fix other objects, however, maybe the comments could clarify that the concept of "ByValueObject" is an approach to fix the issue for HitObject without disrupting the current incorrect behavior for other objects, to avoid regression risk in this change. Right now, the comments assume the behavior is correct for other objects and HitObject is supposed to be treated differently, when I think it should be copying other objects as well.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 2]
```diff
@@ -6387,8 +6403,8 @@ void CGMSHLSLRuntime::EmitHLSLOutParamConversionInit(
 
     // cast before the call
     if (Param->isModifierIn() &&
-        // Don't copy object
-        !isObject) {
+        // Copy-in for non-objects, and also for by-value objects
+        (!isObject || IsByValueObject(ParamTy))) {
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: I think the change is unnecessary because `isObject` will be false here for ByValueObject, due to earlier initialization code:

```
    bool isObject = !IsByValueObject(ParamTy) &&
                    dxilutil::IsHLSLObjectType(CGF.ConvertTypeForMem(ParamTy));
```

File: tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject-array-byval.hlsl [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+[shader("raygeneration")]
+void RayGen()
+{
+  RayDesc ray;
+  dx::HitObject obj[2] = {dx::HitObject::MakeMiss(0, 0, ray), dx::HitObject::MakeMiss(0, 0, ray)};
+
+  MakeNop(obj);
+  output[0] = obj[0].IsNop();
+  output[1] = obj[1].IsNop();
+}
```
Comment (tex3d) [inline tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject-array-byval.hlsl]: Nit: I think we generally want a newline at the end of each file.

Comment (simoll) [reply tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject-array-byval.hlsl]: added newline

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 2 above)
Comment (simoll) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: turned out it was unnecessary, removed

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 1 above)
Comment (simoll) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp:6152]: Added a comment, leaving this as unresolved until confirmed that the new 'FIXME' clarifies this sufficiently
