### PR TITLE
Fix implementation of d3dcolortoubyte4

### LINKED ISSUE #2343: [DXIL] D3DCOLORtoUBYTE4 implementation incorrect
Hi, we just seen invalid results when using D3DCOLORtoUBYTE4.
The expected implementation would look like `int4((var.zyxw) * 255.001953)` but the translation is
`int4(round_ne(var.zyxw * 255)) `which yields different results.
We temporarily fixed this by adding a macro with the suggested implementation it fixed our results.

### PR DESCRIPTION
**Pull request by vcsharma**
Fixes #2343

Fix below differences in the implementation of `D3DCOLORtoUBYTE4` when compared to FXC:

- FXC doesn't use any rounding, but DXC does.
- FXC swizzles the input to `D3DCOLORtoUBYTE4`, but DXC doesn't.
- FXC uses `255.001953` as a multiplier instead of `255`. There is an existing [stackoverflow thread](https://stackoverflow.com/questions/52103720/why-does-d3dcolortoubyte4-multiplies-components-by-255-001953f) discussing the reason behind using `255.001953` (Thanks to @MrTrillian for finding this thread).

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -600,18 +600,30 @@ Value *TrivialBarrier(CallInst *CI, IntrinsicOp IOP, OP::OpCode opcode,
...
   Type *Ty = val->getType();
 
-  Constant *toByteConst = ConstantFP::get(Ty->getScalarType(), 255);
-  if (Ty != Ty->getScalarType()) {
-    toByteConst =
-        ConstantVector::getSplat(Ty->getVectorNumElements(), toByteConst);
+  bool isFXCCompatMode = CI->getModule()->GetHLModule().GetHLOptions().bFXCCompatMode;
+  // Use literal 255.001953 for scaling when FXC compat mode is enabled as
+  // FXC uses this value instead of 255 for some uknown reason.
+  static const float scalingVal = isFXCCompatMode ? 255.001953 : 255.0;
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: Can we just use the FXC magic number everywhere? Every time we have a conditional on a compilation option, we increase the test surface and interplay between slightly different behaviors. I think this one is not worth the complexity.

Also won't this complain about implicit double-to-float conversions?

File: tools/clang/test/CodeGenHLSL/d3dcolortoubyte4/d3dcolortoubyte4-const-input-fxc-compat.hlsl [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// RUN: %dxc -HV 2016 -E main -T vs_6_0 %s | FileCheck %s
```
Comment (MrTrillian) [inline tools/clang/test/CodeGenHLSL/d3dcolortoubyte4/d3dcolortoubyte4-const-input-fxc-compat.hlsl]: Nothing runs this test. Can you put it in `batch/expressions/intrinsics/`? `d3dcolortoubyte4` subfolder at your taste.

File: lib/HLSL/HLOperationLower.cpp [hunk 3]
```diff
@@ -600,18 +600,30 @@ Value *TrivialBarrier(CallInst *CI, IntrinsicOp IOP, OP::OpCode opcode,
...
   Value *val = CI->getArgOperand(HLOperandIndex::kUnaryOpSrc0Idx);
   Type *Ty = val->getType();
 
-  Constant *toByteConst = ConstantFP::get(Ty->getScalarType(), 255);
-  if (Ty != Ty->getScalarType()) {
-    toByteConst =
-        ConstantVector::getSplat(Ty->getVectorNumElements(), toByteConst);
+  bool isFXCCompatMode = CI->getModule()->GetHLModule().GetHLOptions().bFXCCompatMode;
+  // Use literal 255.001953 for scaling when FXC compat mode is enabled as
+  // FXC uses this value instead of 255 for some uknown reason.
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: I'm not sure I agree with the rationale but here it is: https://stackoverflow.com/questions/52103720/why-does-d3dcolortoubyte4-multiplies-components-by-255-001953f

File: lib/HLSL/HLOperationLower.cpp (hunk 1 above)
Comment (MrTrillian) [reply lib/HLSL/HLOperationLower.cpp]: And `static` here is weird, I'm surprised it compiles!

File: lib/HLSL/HLOperationLower.cpp (hunk 3 above)
Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: Cool! didn't expect stackoverflow thread on this. :)

Comment (MrTrillian) [reply lib/HLSL/HLOperationLower.cpp]: The answer is by one of our ATG people

File: lib/HLSL/HLOperationLower.cpp (hunk 1 above)
Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: With your reference to stackoverflow thread on FXC magic number, it seems there is some reasoning behind it. So I will use it everywhere.

File: tools/clang/test/CodeGenHLSL/d3dcolortoubyte4/d3dcolortoubyte4-const-input-fxc-compat.hlsl (hunk 2 above)
Comment (vcsharma) [reply tools/clang/test/CodeGenHLSL/d3dcolortoubyte4/d3dcolortoubyte4-const-input-fxc-compat.hlsl]: done.

File: lib/HLSL/HLOperationLower.cpp [hunk 4]
```diff
@@ -604,18 +604,15 @@ Value *TranslateD3DColorToUByte4(CallInst *CI, IntrinsicOp IOP,
...
+  // Use the same scaling factor used by FXC (i.e., 255.001953)
+  Constant *toByteConst = ConstantFP::get(Ty->getScalarType(), 255.001953);
 
   if (Ty->isVectorTy()) {
     static constexpr int supportedVecElemCount = 4;
     if (Ty->getVectorNumElements() == supportedVecElemCount) {
       toByteConst = ConstantVector::getSplat(supportedVecElemCount, toByteConst);
       // Swizzle the input val -> val.zyxw
-      ArrayRef<int> mask = { 2, 1, 0, 3 };
+      std::vector<int> mask { 2, 1, 0, 3 };
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: Oh yeah nothing would have kept the values alive with ArrayRef, but you can make this `int mask[]` to avoid the dynamic allocation.

File: lib/HLSL/HLOperationLower.cpp [hunk 5]
```diff
@@ -604,18 +604,15 @@ Value *TranslateD3DColorToUByte4(CallInst *CI, IntrinsicOp IOP,
   Value *val = CI->getArgOperand(HLOperandIndex::kUnaryOpSrc0Idx);
   Type *Ty = val->getType();
 
-  bool isFXCCompatMode = CI->getModule()->GetHLModule().GetHLOptions().bFXCCompatMode;
-  // Use literal 255.001953 for scaling when FXC compat mode is enabled as
-  // FXC uses this value instead of 255 for some uknown reason.
-  static const float scalingVal = isFXCCompatMode ? 255.001953 : 255.0;
-  Constant *toByteConst = ConstantFP::get(Ty->getScalarType(), scalingVal);
+  // Use the same scaling factor used by FXC (i.e., 255.001953)
```
Comment (MrTrillian) [inline lib/HLSL/HLOperationLower.cpp]: I'd put the rationale from stacko, maybe this quote is the clearest: `Built-in rounding, necessary because of truncation. 0.001953 * 256 = 0.5`

Comment (vcsharma) [reply lib/HLSL/HLOperationLower.cpp]: Added. Also updated PR description.
