### PR TITLE
Do not try to use EvalBinaryIntrinsic for min/max with integer type arguments.

### LINKED ISSUE #1822: Compile time evaluation of integer min/max crashes when compiling for DXIL
Compiling this shader

```hlsl
int main() : SV_TARGET
{
	return min(1, 2);
}
```

Causes an assert/crash with the following callstack:
```
 	KernelBase.dll!00007ffd29325299()	Unknown
 	dxcompiler.dll!llvm_assert(const char * _Message, const char * _File, unsigned int _Line, const char * _Function) Line 23	C++
 	dxcompiler.dll!llvm::cast<llvm::ConstantFP,llvm::Constant>(llvm::Constant * Val) Line 238	C++
 	dxcompiler.dll!EvalBinaryIntrinsic(llvm::CallInst * CI, float(*)(float, float) floatEvalFunc, double(*)(double, double) doubleEvalFunc) Line 4128	C++
 	dxcompiler.dll!TryEvalIntrinsic(llvm::CallInst * CI, hlsl::IntrinsicOp intriOp) Line 4231	C++
 	dxcompiler.dll!`anonymous namespace'::CGMSHLSLRuntime::EmitHLSLBuiltinCallExpr(clang::CodeGen::CodeGenFunction & CGF, const clang::FunctionDecl * FD, const clang::CallExpr * E, clang::CodeGen::ReturnValueSlot ReturnValue) Line 5086	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitHLSLBuiltinCallExpr(const clang::FunctionDecl * FD, const clang::CallExpr * E, clang::CodeGen::ReturnValueSlot ReturnValue) Line 507	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitCallExpr(const clang::CallExpr * E, clang::CodeGen::ReturnValueSlot ReturnValue) Line 3569	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitCallExpr(const clang::CallExpr * E) Line 363	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 305	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitCastExpr(clang::CastExpr * CE) Line 1797	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::VisitImplicitCastExpr(clang::ImplicitCastExpr * S) Line 399	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 399	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::EmitBinOps(const clang::BinaryOperator * E) Line 2350	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitBinAdd(const clang::BinaryOperator * E) Line 563	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 51	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::EmitBinOps(const clang::BinaryOperator * E) Line 2349	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitBinAdd(const clang::BinaryOperator * E) Line 563	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 51	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::EmitBinOps(const clang::BinaryOperator * E) Line 2349	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitBinAdd(const clang::BinaryOperator * E) Line 563	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 51	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::EmitBinOps(const clang::BinaryOperator * E) Line 2349	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::VisitBinAdd(const clang::BinaryOperator * E) Line 563	C++
 	dxcompiler.dll!clang::StmtVisitorBase<clang::make_ptr,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit(clang::Stmt * S) Line 51	C++
 	dxcompiler.dll!`anonymous namespace'::ScalarExprEmitter::Visit(clang::Expr * E) Line 228	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitScalarExpr(const clang::Expr * E, bool IgnoreResultAssign) Line 3859	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitReturnStmt(const clang::ReturnStmt & S) Line 1128	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitStmt(const clang::Stmt * S) Line 137	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(const clang::CompoundStmt & S, bool GetLast, clang::CodeGen::AggValueSlot AggSlot) Line 304	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList & Args, const clang::Stmt * Body) Line 807	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl GD, llvm::Function * Fn, const clang::CodeGen::CGFunctionInfo & FnInfo) Line 934	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl GD, llvm::GlobalValue * GV) Line 2613	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl GD, llvm::GlobalValue * GV) Line 1591	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl GD) Line 1448	C++
 	dxcompiler.dll!clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl * D) Line 3388	C++
 	dxcompiler.dll!`anonymous namespace'::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef DG) Line 131	C++
 	dxcompiler.dll!clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef D) Line 121	C++
 	dxcompiler.dll!clang::ParseAST(clang::Sema & S, bool PrintStats, bool SkipFunctionBodies) Line 144	C++
 	dxcompiler.dll!clang::ASTFrontendAction::ExecuteAction() Line 556	C++
 	dxcompiler.dll!clang::CodeGenAction::ExecuteAction() Line 755	C++
 	dxcompiler.dll!clang::FrontendAction::Execute() Line 468	C++
 	dxcompiler.dll!DxcCompiler::CompileWithDebug(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult, wchar_t * * ppDebugBlobName, IDxcBlob * * ppDebugBlob) Line 552	C++
 	dxcompiler.dll!DxcCompiler::Compile(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult) Line 300	C++

```

### PR DESCRIPTION
**Pull request by tafuri**
`EvalBinaryIntrinsic` does not support functions with integer arguments, and since min/max do support ints this causes a crash.
The min/max expressions are still evaluated at compile time before optimization even when not handled in `TryEvalIntrinsic`, the same is true for other functions, such as sign(int), which do not appear at all here.

Fixes #1822

### CODE REVIEW

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 1]
```diff
@@ -4228,12 +4228,16 @@ static Value * TryEvalIntrinsic(CallInst *CI, IntrinsicOp intriOp) {
   case IntrinsicOp::IOP_max: {
     auto maxF = [](float a, float b) -> float { return a > b ? a:b; };
     auto maxD = [](double a, double b) -> double { return a > b ? a:b; };
+    if (CI->getArgOperand(0)->getType()->getScalarType()->isIntegerTy())
+      return nullptr;
```
Comment (MrTrillian) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp]: Could you just add a comment like // Handled in DXIL constant folding

**Comment by MrTrillian** [comment]
Merged, thanks! :D
