### PR TITLE
Fix dxa/dxv options, crashes, support signing

### LINKED ISSUE #1500: Support for signing DXIL post-compilation
Is there an update on dxil validation in dxc, and allowing for validation/signing post-compile?

Right now you only get signed dxil if you happen to have dxil.dll in your compiler path, otherwise you just get unsigned dxil code.
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/tools/dxcompiler/dxcutil.cpp#L143
https://blogs.msdn.microsoft.com/marcelolr/2018/03/06/using-the-github-dxcompiler-dll/

Post-compile would be nice to keep shader compile toolchains flexible on Windows, but also allow us to leverage dxc running on linux machines (i.e. cloud/cluster), and the results could signed on demand (or by some other Windows environment) prior to usage on a machine without experimental features enabled. This is a pretty huge request from us (we are doing tons of linux-based cloud scaling of our pipelines, etc.. which includes shader compilation).

A linux binary that supports signing/validation would be superior, but I understand if that needs to remain as-is. However, since the compiler itself is open source, and the dxil.dll binary is loaded during compilation, it seems reasonable allow this decoupling. This way unsigned dxil could be produced on linux or windows, and then some windows-based approach can ensure dxil is properly signed when appropriate.

### PR DESCRIPTION
**Pull request by tex3d**
- Set up missing thread malloc and MSFileSystemForDisk causing crashes.
- Removed default "-" input since it doesn't even work to select stdin.
- dxv: Support loading/signing full shader binary, -o for output file if signed.

Fixes #1500.

### CODE REVIEW

**Comment by pow2clk** [comment]
Just a note that I think this satisfies #1500

File: tools/clang/tools/dxa/dxa.cpp [hunk 1]
```diff
@@ -281,16 +286,32 @@ void DxaContext::ListParts() {
 using namespace hlsl::options;
 
 int __cdecl main(int argc, _In_reads_z_(argc) char **argv) {
+  if (llvm::sys::fs::SetupPerThreadFileSystem())
+    return 1;
```
Comment (pow2clk) [inline tools/clang/tools/dxa/dxa.cpp:290]: should there be an error message here?

File: tools/clang/tools/dxa/dxa.cpp [hunk 2]
```diff
@@ -281,16 +286,32 @@ void DxaContext::ListParts() {
...
+  llvm::sys::fs::AutoCleanupPerThreadFileSystem auto_cleanup_fs;
+  if (FAILED(DxcInitThreadMalloc())) return 1;
```
Comment (pow2clk) [inline tools/clang/tools/dxa/dxa.cpp:292]: maybe here too? though this rarely fails. Maybe true of the above as well?

File: tools/clang/tools/dxv/dxv.cpp [hunk 3]
```diff
@@ -80,19 +106,50 @@ void DxvContext::Validate() {
...
     } else {
+      // Source was unsigned DxilContainer, write signed container if it's now signed:
+      if (bSourceIsDxilContainer && bSourceIsUnsigned) {
+        const hlsl::DxilContainerHeader *pHeader = hlsl::IsDxilContainerLike(
+            pSource->GetBufferPointer(), pSource->GetBufferSize());
+        hlsl::DxilContainerHash blankHash = {};
+        if (memcmp(&pHeader->Hash, &blankHash,
+                   sizeof(hlsl::DxilContainerHash)) != 0) {
+          if (OutputFilename.empty()) {
+            OutputFilename.assign(InputFilename);
```
Comment (pow2clk) [inline tools/clang/tools/dxv/dxv.cpp:117]: So this rewrites the input container with a signature if you don't specify an output? That might come as a surprise. Probably fine if the file is writable. If not, it might fail when someone only wants to know if the dxil is valid.

File: tools/clang/tools/dxv/dxv.cpp [hunk 4]
```diff
@@ -80,19 +106,50 @@ void DxvContext::Validate() {
...
+          }
+          WriteBlobToFile(pSource, StringRefUtf16(OutputFilename), CP_ACP);
```
Comment (pow2clk) [inline tools/clang/tools/dxv/dxv.cpp:119]: I don't see any check that the validation is from dxil.dll and not the internal validator. Did I miss it?

**Review by pow2clk — COMMENTED** [review]
Mostly minor comments. Really wondering about the internal validator question though

File: tools/clang/tools/dxa/dxa.cpp (hunk 1 above)
Comment (tex3d) [reply tools/clang/tools/dxa/dxa.cpp:290]: The way stdout/stderr is hooked in, if this fails, we will crash if we try to print anything.  This really should not ever fail.

File: tools/clang/tools/dxa/dxa.cpp (hunk 2 above)
Comment (tex3d) [reply tools/clang/tools/dxa/dxa.cpp:292]: Something seriously wrong if this fails, again might crash if we try to print.

File: tools/clang/tools/dxv/dxv.cpp (hunk 3 above)
Comment (tex3d) [reply tools/clang/tools/dxv/dxv.cpp:117]: True, perhaps we only output if `-o` specified, and allow -o to point to input file to overwrite it.

File: tools/clang/tools/dxv/dxv.cpp (hunk 4 above)
Comment (tex3d) [reply tools/clang/tools/dxv/dxv.cpp:119]: We check that it was unsigned before, and now it's signed, which only happens with DXIL.dll.  That's really all we can know.  We will be arriving at DXIL.dll through DxCompiler.dll here.  That means it's up to DxCompiler.dll to pass things through to DXIL.dll, and there's basically no other indication that we used DXIL.dll from this code.  This also means if you run dxv.exe without dxcompiler.dll present, it won't work, even though it will only call through to DXIL.dll.  It uses DxCompiler.dll for assembler as well.  So if we want it to work with only DXIL.dll, we would have to modify the code somewhat to attempt to initialize from DxCompiler.dll, then failing that set a flag and initialize from DXIL.dll.  If the flag is set, we would only support the full container validation, since we wouldn't have the assembler and can't use DXIL.dll for bitcode validation.

**Review by pow2clk — APPROVED** [review]
I like it!
