### PR TITLE
[spirv] Make sure asuint() argument is r-value

### LINKED ISSUE #3717: [SPIR-V] Compile error when using asuint on StructuredBuffer's Load function
### Title
[SPIR-V] Compile error when using asuint on StructuredBuffer's Load function

### Functional impact
When using asuint on StructuredBuffer<float4> Load's result, the dxc fails to compile the shader.
The same example works fine when StructuredBuffer<float4> is replaced with Buffer<float4>.
When generating DXIL instead of SPIR-V, there is no issue.

### Minimal repro steps
```
StructuredBuffer<float4> input;
[numthreads(64,1,1)]
void main(uint3 dtID : SV_DispatchThreadID)
{
	uint4 val = asuint(input.Load(dtID.x));
}
```
### Expected result
The shader should compile and bits should be reinterpreted to uint4, similarly to how it works for Buffer<float4>

### Actual result
_fatal error: generated SPIR-V is invalid: Pointer can only be converted to another pointer or int scalar: Bitcast
  %34 = OpBitcast %v4uint %33_

_note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible_

### Further technical details
http://shader-playground.timjones.io/8567033107b88276c94b2e7bd05f6662

### PR DESCRIPTION
**Pull request by jaebaek**
Fixes #3717

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -9465,7 +9465,7 @@ SpirvEmitter::processIntrinsicAsType(const CallExpr *callExpr) {
   switch (numArgs) {
   case 1: {
     // Handling Method 1, 2, and 3.
-    auto *argInstr = doExpr(arg0);
+    auto *argInstr = loadIfGLValue(arg0);
```
Comment (jaebaek) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:9468]: Without this change, it directly uses `doExpr(arg0)` that is a pointer to argument. We have to make sure the argument is a r-value not a pointer.

**Review by sudonatalie — APPROVED** [review]
