### PR TITLE
Allow native vector intrinsics with fixed component types

### LINKED ISSUE #7342: [SM6.9] Vectorize non-trivial elementwise operations
**Description**
DXIL vectorization should extend to elementwise operations where the return type and element types are not the same.

**Additional Context**
Draft implementation: https://github.com/pow2clk/DirectXShaderCompiler/commit/0a9cb89e97d2fecc0d737f712a5449e47ea8e609

### PR DESCRIPTION
**Pull request by pow2clk**
Several intrinsics that support native vectors return the same element type regardless of overload. For native vectors, these need to return a vector of size matching the overload with the fixed element type. This provides the source generation to allow it and the changes to the related lowering operations to generate the correct DXIL.

This includes some queries that return boolean information about the vector components in a boolean vector output and also the unary bit operations which operate on integers and return integers containing information about the component bits.

Incidentally moves some intrinsics that have long since not been scalarized out of the scalarized test. They were updated to expect the new output, but were in the wrong location and not tested as thoroughly as their native vector counterparts.

Fixes #7342

### CODE REVIEW

File: lib/HLSL/HLOperationLower.cpp [hunk 1]
```diff
@@ -2083,42 +2083,58 @@ Value *TranslateFirstbitHi(CallInst *CI, IntrinsicOp IOP, OP::OpCode opcode,
...
-    }
-    return result;
+  if (NumElements > 0) {
+    Neg1 = ConstantVector::getSplat(NumElements, Neg1);
+    BitWidth = ConstantVector::getSplat(NumElements, BitWidth);
   }
+
+  Value *Sub = Builder.CreateSub(BitWidth, FirstbitHi);
+  Value *Cond = Builder.CreateICmpEQ(Neg1, FirstbitHi);
+  return Builder.CreateSelect(Cond, Neg1, Sub);
```
Comment (llvm-beanz) [inline lib/HLSL/HLOperationLower.cpp:2115]: For a vector shouldn't this be per-element? If so we should have a shufflevector instead of a select.

File: tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.hlsl [hunk 2]
```diff
@@ -111,6 +111,15 @@ void main() {
 
   vector<uint, NUM> uRes = signs;
 
+  // CHECK: call <13 x i32> @dx.op.unaryBits.v13i32(i32 31, <13 x i32> [[uvec2]])  ; Countbits(value)
+  uRes += countbits(uVec2);
+
+  // CHECK: call <13 x i32> @dx.op.unaryBits.v13i64(i32 32, <13 x i64> [[lvec2]])  ; FirstbitLo(value)
+  uRes += firstbitlow(lVec2);
+
+  // CHECK: call <13 x i32> @dx.op.unaryBits.v13i32(i32 33, <13 x i32> [[uvec1]])  ; FirstbitHi(value)
```
Comment (llvm-beanz) [inline tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.hlsl]: This isn't testing the full expansion.

File: lib/HLSL/HLOperationLower.cpp (hunk 1 above)
Comment (llvm-beanz) [reply lib/HLSL/HLOperationLower.cpp:2115]: Sorry. I don't know what I was thinking... this is fine. My brain clearly is off today.

File: utils/hct/hctdb.py [hunk 3]
```diff
@@ -1406,6 +1406,7 @@ def populate_dxil_operations(self):
         # $o in a parameter type means the overload type
         # $r in a parameter type means the resource type
         # $cb in a parameter type means cbuffer legacy load return type
+        # $otpl{component} in a return type means the overload template shape with the specified component type
```
Comment (tex3d) [inline utils/hct/hctdb.py]: I have a hard time reading overloads with this name.  What about just `$o_{component}` for overload, but with fixed component type?  I think it would be easier to read.

If necessary, this pattern could be extended to the `$x0` and `$x1` pattern, with `$x0_{component}`.

**Review by tex3d — APPROVED** [review]
I just have a minor issue with the `otpl` prefix.

**Comment by pow2clk** [comment]
Thanks for the reviews @tex3d and @llvm-beanz. I have responded to the feedback and rebased with main.

**Comment by pow2clk** [comment]
I see changes are invalidating earlier approvals again, so I'll need another green checkmark.

**Review by llvm-beanz — APPROVED** [review]
