### PR TITLE
Report error for unsupported types of SV semantics

### LINKED ISSUE #2299: DXC crashes on float input with SV_DispatchThreadID semantic
Repro:
```
[numthreads(1, 1, 1)]
void main(float3 tid : SV_DispatchThreadID) {}
```

We should also validate bools and structs, any non-int types.

### LINKED ISSUE #2954: Silent crash or validation error when SV_InnerCoverage semantic is assigned to a float parameter instead of uint
### Title
Silent crash or validation error (DXIL and SPIR-V backends respectively) when SV_InnerCoverage semantic is assigned to a float parameter instead of uint

### Functional impact
Compiler crashes, no result gets printed to stdout for the DXIL backend. SPIR-V backend prints validation error and asks to report a bug.

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746311/repro_shader.txt) with `dxc.exe -E frag -T ps_6_1 repro_shader.txt`
```
float4 frag (uint viewID : SV_ViewID, float innerCoverage : SV_InnerCoverage) : SV_Target
{
  return float4(1, float(viewID), innerCoverage, 0);
}
```

### Expected result
The compiler prints out an informative error message.

### Actual result
Compiler crashes, no result gets printed to stdout for the DXIL backend.

### Further technical details
Running the snippet through the SPIR-V backend with `dxc.exe -E frag -T ps_6_1 repro_shader.txt -spirv` produces the following validation error:
`fatal error: generated SPIR-V is invalid: Expected Constituents to be scalars or vectors of the same type as Result Type components                                                %23 = OpCompositeConstruct %v4float %float_1 %22 %21 %float_0                                                                                                                                                                                                                                                                                                   note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible`
DXC bult from changeset 5ebc67c618d7061407cca039573108078f601ee6.

### LINKED ISSUE #3444: [DXIL] Decorating CS float argument with SV_DispatchThreadID semantic crashes the compiler (float2, float3 and float4 works)
### Title
[DXIL] Decorating CS float argument with SV_DispatchThreadID semantic crashes the compiler (float2, float3 and float4 works)

### Functional impact
Compiler crashes

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T cs_6_0 -E CSMain issue_shader.txt`:
```
RWStructuredBuffer<float4> rwTexture;

[numthreads(1, 1, 1)]
void CSMain(float id : SV_DispatchThreadID)
{
	rwTexture[3] = id.xxxx;
}
```
### Expected result
Shader compiles correctly, as it does for vector float arguments: `float2`, `float3`, `float4`

### Actual result
Compiler crashes

### Further technical details
Ran test on [shader playground](http://shader-playground.timjones.io/fabe1b8db0f4b2e668dbf311d7ae6620) with DXC from 2020 12 16
The SPIR-V backend produces validation errors (reported here https://github.com/microsoft/DirectXShaderCompiler/issues/3443 )

### PR DESCRIPTION
**Pull request by vcsharma**
FXC reports error, but DXC only asserts.

Fixes #2299
Fixes #2954
Fixes #3444

### CODE REVIEW

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -9720,6 +9720,69 @@ void hlsl::DiagnosePackingOffset(
   }
 }
 
+static bool IsIntegerTypeCSInputSemantic(const hlsl::SemanticDecl *sd) {
+  return
+    sd->SemanticName.equals("SV_DispatchThreadID") ||
+    sd->SemanticName.equals("SV_GroupIndex") ||
+    sd->SemanticName.equals("SV_GroupID") ||
+    sd->SemanticName.equals("SV_GroupThreadID");
+}
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:9729]: You might consider using something like: 
```c++
  const Semantic *pSemantic = Semantic::GetByName(semanticStr);
  switch(pSemantic->getKind()) {
     case Semantic::Kind::GroupID: ...

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 2]
```diff
@@ -9720,6 +9720,69 @@ void hlsl::DiagnosePackingOffset(
...
+  if (!IsIntegerTypeCSInputSemantic(semanticDecl))
+    return true;
+
+  QualType qty = ty.getCanonicalType();
+
+  const clang::Type *qtyPtr = qty.getTypePtrOrNull();
+  if (qtyPtr && qtyPtr->isScalarType() &&
+    qtyPtr->getScalarTypeKind() != Type::ScalarTypeKind::STK_Integral) {
+    return false;
+  }
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:9748]: The code might be more self-documenting and less repetitive if this common check were parceled off into a small subfunction.

File: tools/clang/lib/Sema/SemaHLSL.cpp [hunk 3]
```diff
@@ -9720,6 +9720,69 @@ void hlsl::DiagnosePackingOffset(
...
+}
+
+void hlsl::DiagnoseSemanticType(clang::Sema *self, clang::QualType &type,
+                                hlsl::SemanticDecl *semanticDecl,
+                                bool isTypeDef, bool isLocalVar,
+                                const char *declarationType) {
+
+  if (isTypeDef || isLocalVar) {
+    self->Diag(semanticDecl->Loc, diag::err_hlsl_varmodifierna)
+        << "semantic" << declarationType;
```
Comment (pow2clk) [inline tools/clang/lib/Sema/SemaHLSL.cpp:9776]: This is pre-existing of course, but I'm not sure it's consistent with our documentation as I read it here:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-variable-syntax#Semantic

which says that "The compiler ignores semantics unless they are declared on a global variable, or a parameter passed into a shader."

File: tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_type_cs_input_semantic.hlsl [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=float -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_GID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=bool -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_GID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=min16float -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_GID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=float3 %s | FileCheck %s -check-prefix=CHK_GTID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=float1x1 %s | FileCheck %s -check-prefix=CHK_GTID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=float %s | FileCheck %s -check-prefix=CHK_GTID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=bool %s | FileCheck %s -check-prefix=CHK_GTID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=min16float %s | FileCheck %s -check-prefix=CHK_GTID_TY_ERR
```
Comment (pow2clk) [inline tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_type_cs_input_semantic.hlsl:21]: Very thorough! 👍

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 5]
```diff
@@ -467,9 +618,12 @@ void CGMSHLSLRuntime::CheckParameterAnnotation(
   if (pSemantic->IsInvalid()) {
     DiagnosticsEngine &Diags = CGM.getDiags();
     unsigned DiagID =
-      Diags.getCustomDiagID(DiagnosticsEngine::Error, "invalid semantic '%0' for %1 %2.%3");
+    Diags.getCustomDiagID(DiagnosticsEngine::Error, "invalid semantic '%0' for %1 %2.%3");
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp:621]: I find this new indenting harder to read. Is it something that was automated?

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 6]
```diff
@@ -434,25 +443,167 @@ void CGMSHLSLRuntime::AddHLSLIntrinsicOpcodeToFunction(Function *F,
...
+  return qTy->getScalarTypeKind();
+}
+
+static unsigned GetCompSize(QualType qty) {
+  if (qty->isArrayType())
+    return GetCompSize(GetArrayElementType(qty));
+  if (qty->isScalarType())
+    return 1;
+  assert(IsHLSLVecType(qty));
+  return GetHLSLVecSize(qty);
```
Comment (pow2clk) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp:466]: `GetScalarElementType` is set up to handle matrices, but this is not. It seems both are ultimately invoked from the same place. I would expect both or neither to expect matrices.

Comment (vcsharma) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp:468]: good catch!

File: tools/clang/lib/AST/HlslTypes.cpp [hunk 7]
```diff
@@ -274,7 +274,7 @@ uint32_t GetElementCount(clang::QualType type) {
 /// type.</summary>
 QualType GetArrayElementType(clang::QualType type) {
   QualType qTy = type.getCanonicalType().getNonReferenceType();
-  assert(qTy->isArrayType() && "otherwise caller shouldn't be invoking this");
+  DXASSERT_NOMSG(qTy->isArrayType() && "otherwise caller shouldn't be invoking this");
```
Comment (pow2clk) [inline tools/clang/lib/AST/HlslTypes.cpp:277]: heh. well, you kind of do have a message, but it ends up being the same anyway. 😄

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp [hunk 8]
```diff
@@ -470,6 +623,9 @@ void CGMSHLSLRuntime::CheckParameterAnnotation(
       Diags.getCustomDiagID(DiagnosticsEngine::Error, "invalid semantic '%0' for %1 %2.%3");
     Diags.Report(SLoc, DiagID) << semName << SM->GetKindName() << SM->GetMajor() << SM->GetMinor();
   }
+
+  if (pSemantic->GetName())
+    DiagnoseSemanticType(SLoc, pSemantic, paramTy, semIndex);
```
Comment (tex3d) [inline tools/clang/lib/CodeGen/CGHLSLMS.cpp:628]: I just realized a serious limitation of placing all this validation under this codepath.  It only deals with top-level parameter declarations, so it only provides some early rough error checking for a limited set of cases.  To actually check these correctly, you need to generate the final signature shapes.  For that, you have to drill into certain things (vertex arrays, patches, streams), flatten the structures, and apply the semantic inheritance as you do.
This is already done later in the pipeline, but original source locations and clang diagnostics are no longer available at that point.
This is why most semantic validation is performed in HLSignatureLower, where it has the knowledge it needs to do so. 
 I actually think this additional validation needs to be moved there.  Ideally, we could better preserve source locations to improve the diagnostics at that point as well.

File: tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_type_cs_input_semantic.hlsl [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+
+// CHK_NO_ERR: define void @main
+// CHK_TID_TY_ERR: error: invalid type used for 'SV_DispatchThreadID' input semantics
+// CHK_GI_TY_ERR: error: invalid type used for 'SV_GroupIndex' input semantics
+// CHK_GID_TY_ERR: error: invalid type used for 'SV_GroupID' input semantics
+// CHK_GTID_TY_ERR: error: invalid type used for 'SV_GroupThreadID' input semantics
+
+
+[numthreads(1, 1, 1)]
+void main(TID_TY tid : SV_DispatchThreadID,
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_type_cs_input_semantic.hlsl:33]: I know the original issue was about adding a friendlier error for invalid component type on these semantics, but it grew to reveal additional checks that were needed.  Unfortunately, this test case only covers a very narrow slice of the space that needs covering based on the added error checking.

Comment (vcsharma) [reply tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_type_cs_input_semantic.hlsl]: Extended coverage to include type checking for all semantics.

File: tools/clang/lib/CodeGen/CGHLSLMS.cpp (hunk 8 above)
Comment (vcsharma) [reply tools/clang/lib/CodeGen/CGHLSLMS.cpp]: Moved the type checking logic to `HLSignatureLower`.

File: lib/HLSL/HLSignatureLower.cpp [hunk 10]
```diff
@@ -1715,6 +1759,12 @@ void HLSignatureLower::GenerateGetMeshPayloadOperation() {
 }
 // Lower signatures.
 void HLSignatureLower::Run() {
+
+  // Generate error and exit if semantic type
+  // is not one of the allowed types
+  if (!ValidateSemanticType(Entry))
+    return;
```
Comment (pow2clk) [inline lib/HLSL/HLSignatureLower.cpp:1766]: This provides no indication of failure to the subsequent passes, I worry this will bail out of the rest of this pass and potentially cause weird followup errors on subsequent passes that expect these operations to have been performed.

**Review by pow2clk — COMMENTED** [review]
It looks really good!

This was a pretty big hole in error reporting and I think this will resolve it definitively.

I just have a couple concerns on specific interpretation and error propagating where I might well be confused

File: lib/DXIL/DxilSemantic.cpp [hunk 11]
```diff
@@ -113,41 +120,156 @@ bool Semantic::IsInvalid() const {
...
+        // TessFactor or InsideTessFactor must either be float[2] or float
+        if ((m_Kind == Kind::TessFactor ||
+             m_Kind == Kind::InsideTessFactor) &&
+          !dxilutil::IsIntegerOrFloatingPointType(semTy)) {
+          return false;
+        }
+        // Clip/Cull can be array of scalar or vector
+        if ((m_Kind == Kind::ClipDistance ||
+          m_Kind == Kind::CullDistance) &&
+          !IsScalarOrVectorTy(semTy)) {
```
[the remark this answers is not in the document]
Comment (tex3d) [reply lib/DXIL/DxilSemantic.cpp:212]: These ones are special.  All components must total in up to two vectors, with a max of 8 components total.  One could use all 8, or the other, or any mixture totaling 8 or few components in one or two packed vectors.  So yes, they support different sized types here.

File: lib/HLSL/HLSignatureLower.cpp (hunk 10 above)
Comment (tex3d) [reply lib/HLSL/HLSignatureLower.cpp:1766]: That's true, and I have a feeling that continuing with this pass will result in fewer weird cascading errors from this than returning here.  Currently, it seems the only way to abort the pipeline is with a report_fatal_error, which currently raises a structured exception - which is way too harsh for something like this, and we should likely change report_fatal_error to throw a C++ exception, since we still have a chance of emitting a useful error message then.

File: tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/semantics_type_checking/unsupported_types_cs_input_semantics.hlsl [hunk 12]
```diff
@@ -0,0 +1,36 @@
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=uint3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_NO_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=float3 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_TID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=float1x1 -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_TID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=float -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_TID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=bool -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_TID_TY_ERR
+// RUN: %dxc -E main -T cs_6_0 -DTID_TY=min16float -DGI_TY=uint -DGID_TY=uint3 -DGTID_TY=uint3 %s | FileCheck %s -check-prefix=CHK_TID_TY_ERR
```
Comment (tex3d) [inline tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/semantics_type_checking/unsupported_types_cs_input_semantics.hlsl:6]: I see you tried min16float, but not min16uint.  What does min-precision of valid type (uint) do?  It should succeed but use i32 intrinsic overload, I believe.  Also, what does native 16-bit type uint16_t do?  I think it should succeed, using i32 intrinsic, like the min-precision case does.

File: lib/HLSL/HLSignatureLower.cpp [hunk 13]
```diff
@@ -1204,6 +1204,50 @@ void HLSignatureLower::GenerateDxilInputsOutputs(DXIL::SignatureKind SK) {
...
+    if (argTy->isArrayTy()) {
+      // Array type for arguments with specific qualifiers are expected.
+      // In this case, we do validation on array's element type.
+      DxilParamInputQual inputQual = paramAnnotation.GetParamInputQual();
+      if (inputQual == DxilParamInputQual::InputPatch ||
+        inputQual == DxilParamInputQual::InputPrimitive ||
+        inputQual == DxilParamInputQual::OutIndices ||
+        inputQual == DxilParamInputQual::OutPrimitives ||
+        inputQual == DxilParamInputQual::OutputPatch ||
+        inputQual == DxilParamInputQual::OutVertices) {
```
Comment (tex3d) [inline lib/HLSL/HLSignatureLower.cpp:1238]: Wish there was a better place to associate the input qualifier property with the expected array parameter shape (though this is a bit of an internal HL IR detail).  Even if it was in its own function somewhere.

**Review by tex3d — APPROVED** [review]

File: tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/semantics_type_checking/unsupported_types_cs_input_semantics.hlsl (hunk 12 above)
Comment (vcsharma) [reply tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/semantics_type_checking/unsupported_types_cs_input_semantics.hlsl:8]: That's right. Both `min16uint` and `uint16_t` are valid types for these semantics. I updated the test.

File: lib/HLSL/HLSignatureLower.cpp (hunk 10 above)
Comment (vcsharma) [reply lib/HLSL/HLSignatureLower.cpp:1772]: > I have a feeling that continuing with this pass will result in fewer weird cascading errors from this than returning here

Actually bailing out early avoids crashes at least in some cases. Like for CS SV semantics, if we pass an invalid type like `float` and let it continue with the lowering then it crashes in  `HLSignatureLower::GenerateDxilCSInputs()` in the below line.

```
    // If the argument is of non-i32 type, convert here
    if (newArg->getType() != NumTy)
      newArg = Builder.CreateZExtOrTrunc(newArg, NumTy);
```

Based on the comments here, I agree we need a mechanism to stop further compilation when we generate errors. I suspect we would need that mechanism not just in this change, but probably at other places too where we generate errors. Therefore I created an issue #3496 to track this as a future enhancement that we would like to implement.

Comment (pow2clk) [reply lib/HLSL/HLSignatureLower.cpp:1772]: That's consistent with my later investigations. I approve of solving the larger problem right later.

File: include/dxc/DXIL/DxilSemantic.h [hunk 14]
```diff
@@ -25,24 +25,26 @@ class Semantic {
...
+    FloatOrInt32Ty     = FloatTy | Int32Ty,
+    Int16Or32Ty        = Int16Ty | Int32Ty,
+    AnyIntTy           = BoolTy | Int16Ty | Int32Ty | Int64Ty,
+    AnyFloatTy         = HalfTy | FloatTy | DoubleTy,
+    AnyTy              = AnyIntTy | AnyFloatTy,
   };
 
   enum class SizeClass {
     Scalar,
+    Vec1,
```
Comment (tex3d) [inline include/dxc/DXIL/DxilSemantic.h:47]: Can't we treat Vec1 as Scalar?  I think either one should be legal for all scalar system values, right?  I see some that still only go up to Scalar, so does that mean those won't accept vec1?  Why not?

Also, it would be nice to make the 0 enum value something like Invalid, or the Unknown.  If Scalar aliased Vec1, then vector size would align with the enum values (always easier when looking at raw values, such as in debugger).

File: lib/DXIL/DxilSemantic.cpp [hunk 15]
```diff
@@ -126,7 +126,10 @@ Semantic::SizeClass Semantic::GetCompCount(llvm::Type* ty) const {
     return SizeClass::Unknown;
 
   if (ty->isVectorTy()) {
-    if (ty->getVectorNumElements() == 2) {
+    if (ty->getVectorNumElements() == 1) {
+      return SizeClass::Vec1;
```
Comment (tex3d) [inline lib/DXIL/DxilSemantic.cpp:130]: Here is where we could simply return Scalar, right?

**Review by tex3d — APPROVED** [review]
LGTM!

**Comment by pow2clk** [comment]
Just to throw this into the mix, #5768 is related to this cadre of errors as well.

We could use the means of defining what types go with what semantics here, but we wouldn't want to place it in the DxilSignature pass as this did. Rather, we should put it in Sema, possibly SemaHLSL DiagnoseEntry function.
