### PR TITLE
Skip inserting redundant phi nodes on struct type

### LINKED ISSUE #1745: Generated dxil has phi on struct type
**Shader**
```
// dxc.exe /Emain /Tps_5_0 /Zi /Zpr /O3 shader.hlsl

cbuffer cb
{
 int cb_a;
 int cb_b;
 bool cb_c[1];
}

static const struct
{
 int a;
 int b;
 bool c[1];
} cbstruct = { cb_a, cb_b, cb_c };


bool IsPos( float3 pos )
{
 float maxpos = max(pos.x, max(pos.y, pos.z) );
 float minpos = min(pos.x, min(pos.y, pos.z) );
 return ( maxpos < 32 && minpos > 0 );
}

float3 GetPos()
{
 [branch]
 if(cbstruct.c[cbstruct.b])
 {
  return float3(0,0,0);
 }
 else
 {
  return float3(1,1,1);
 }
}

int GetIdx( )
{
 for( int i=0; i< 4 ; i++ )
 {
  if( i == cbstruct.b )
  {
   return -1;
  }
  float3 pos = GetPos();
  if( IsPos(pos) )
  {
   return i;
  }
 }

 return -1;
}

float GetColor()
{
 int idx = GetIdx(); 
 if( idx == cbstruct.a )
 {
   return 1.0;
 }
 return 0.0;
}


void main(out float4 OutColor : SV_Target0)
{
 float x = GetColor();
 [branch]
 if ( x < 0.0001f )
 {
  OutColor = 0.0f;
 }
}

```
**Issue:** Generated dxil has phi on struct type. PHI on struct type is not a valid dxil. Apart from fixing this bug, we would also likely need to update the validator to fail the validation in case such as these.

`%.lcssa = phi %dx.types.CBufRet.i32 [ %0, %"\01?GetPos@@YA?AV?$vector@M$02@@XZ.exit.i.i" ], [ %0, %for.body.i.i ], [ %6, %for.inc.i.i ], [ %6, %"\01?GetPos@@YA?AV?$vector@M$02@@XZ.exit.i.i.1" ], [ %13, %for.inc.i.i.1 ], [ %13, %"\01?GetPos@@YA?AV?$vector@M$02@@XZ.exit.i.i.2" ], [ %19, %for.inc.i.i.2 ], [ %19, %"\01?GetPos@@YA?AV?$vector@M$02@@XZ.exit.i.i.3" ], [ %19, %for.inc.i.i.3 ]`

### PR DESCRIPTION
**Pull request by vcsharma**
Fixes #1745.

### CODE REVIEW

File: lib/Transforms/Utils/LCSSA.cpp [hunk 1]
```diff
@@ -245,6 +246,15 @@ bool llvm::formLCSSA(Loop &L, DominatorTree &DT, LoopInfo *LI,
            !isa<PHINode>(I->user_back())))
         continue;
 
+      // HLSL changes begin
+      // Skip inserting redundant PHI nodes on instruction of struct type
+      // as the resultant IR is not considered a valid DXIL.
```
Comment (MrTrillian) [inline lib/Transforms/Utils/LCSSA.cpp]: Isn't it a problem that a function that claim to produce LCSSA form may not actually do so? What happens if struct-producing instructions from in the loop are referenced outside of it?

File: lib/Transforms/Utils/LCSSA.cpp [hunk 2]
```diff
@@ -255,7 +265,8 @@ bool llvm::formLCSSA(Loop &L, DominatorTree &DT, LoopInfo *LI,
   if (SE && Changed)
     SE->forgetLoop(&L);
 
-  assert(L.isLCSSAForm(DT));
+  if(shouldExpectLCSSAform)
+    assert(L.isLCSSAForm(DT));
```
Comment (MrTrillian) [inline lib/Transforms/Utils/LCSSA.cpp]: prefer `assert(shouldExpectLCSSAform && L.isLCSSAForm(DT));`

File: lib/Transforms/Utils/LCSSA.cpp (hunk 1 above)
Comment (vcsharma) [reply lib/Transforms/Utils/LCSSA.cpp]: Note that the phi node inserted by LCSSA is **redundant** one and is only inserted to have a loop-closed SSA which makes the code shape amenable to other loop optimizations. In other words, even if we don't insert the redundant phi node, it would still be a valid SSA.

Comment (MrTrillian) [reply lib/Transforms/Utils/LCSSA.cpp]: Valid SSA, yes, but going from its name one could assume that after calling this method you have a valid LCSSA form. The phi node is redundant for SSA but is it required to be valid LCSSA?

Comment (MrTrillian) [reply lib/Transforms/Utils/LCSSA.cpp]: All right, we talked and I understand why this is ok, though it'd be good if the comment could be say why DXIL doesn't like phis of structs in this case.
