### PR TITLE
[spirv] handle texture swizzling used in interlocked op

### LINKED ISSUE #2409: [spirv] Interlock operation error on unnecessary swizzle
With the command-line ` -E main -T vs_6_0 -spirv` and this short repro:
```
RWTexture3D<uint> target			: register(u1);

struct VS_OUTPUT
{ 
    float4	Pos				: SV_Position;
};

void main(VS_OUTPUT input)
{
	uint3 index = uint3(0,0,0);
	InterlockedAdd(target[index].r, 1);   <<< ERROR
}
```

I receive the error 
> error: using static variable or function scope variable in interlocked operation is not allowed

Given that the type of `target` is already `uint`, the swizzle is unnecessary but also harmless. Removing the swizzle fixes the error.

(To me it appears that the `.r` swizzle on `target[index].r` is generating a temporary which is passed to the InterlockedAdd.)

Version: `dxcompiler.dll: 1.5 - 1.4.0.2338 (master, f8d0271d)`

### PR DESCRIPTION
**Pull request by jaebaek**
1. Report an error if interlocked op has a texture argument whose
result type is non-scalar. This is not allowed in SPIR-V.
2. If the argument for interlocked op is a vector swizzling of a
texture, we should use the texture instead of the swizzling.

Fixes #2409

### CODE REVIEW

**Comment by jaebaek** [comment]
Sorry. I forgot to add unittests. Please do not review it yet.

**Comment by jaebaek** [comment]
I think it is ready to review.

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -7265,13 +7265,33 @@ SpirvEmitter::processIntrinsicInterlockedMethod(const CallExpr *expr,
     spvBuilder.createStore(doExpr(outputArg), toWrite, callExpr->getExprLoc());
   };
 
+  // Set up cxxOpCall if dest is CXXOperatorCallExpr or vector swizzling
+  // of CXXOperatorCallExpr to handle texture buffer correctly.
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp]: You should replace this comment with a much more informative comment. You are matching a very particular pattern. So you should write what that pattern is. Otherwise it's very confusing why you are doing all the casts and why you are getting the castExpr base expression. e.g:

```
// If a vector swizzling of a texture is done as an argument of an interlocked method,
// we need to handle the access to the texture buffer element correctly. For example:
//
//  InterlockedAdd(myRWTexture[index].r, 1);
//
// `-CallExpr
//  |-ImplicitCastExpr
//  | `-DeclRefExpr Function 'InterlockedAdd' 'void (unsigned int &, unsigned int)'
//  |-HLSLVectorElementExpr 'unsigned int' lvalue vectorcomponent r
//  | `-ImplicitCastExpr 'vector<uint, 1>':'vector<unsigned int, 1>' <HLSLVectorSplat>
//  |   `-CXXOperatorCallExpr 'unsigned int' lvalue
```

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp]: Thanks. Updated.
