### PR TITLE
[SPIRV] Implement out variables in patch constant functions

### LINKED ISSUE #3743: [SPIR-V] Patch constant function does not support out parameters (works with DXIL backend)
### Title
[SPIR-V] Patch constant function does not support `out` parameters  (works with DXIL backend)

### Functional impact
Can't use the `out` modifier on any of the `patchconstantfunc`'s arguments to write outputs with the SPIR-V backend. This, however, works with the DXIL backend and with the regular (non-patch) Hull stage function

### Minimal repro steps
1. Compile the following shader with `dxc.exe -T hs_6_0 -E Hull -spirv repro_shader.txt`:
[repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6419768/repro_shader.txt)

### Expected result
Compilation succeeds and the out parameters are allowed as they are with the DXIL backend

### Actual result
Compilation fails with the following errors:
```
repro_shader.txt:3:28: error: patch constant function parameter 'edge' unknown
void HullConst (out  float edge [3] : SV_TessFactor, out float inside : SV_InsideTessFactor, out float myFloat : MY_FLOAT)
                           ^
repro_shader.txt:3:64: error: patch constant function parameter 'inside' unknown
void HullConst (out  float edge [3] : SV_TessFactor, out float inside : SV_InsideTessFactor, out float myFloat : MY_FLOAT)
                                                               ^
repro_shader.txt:3:104: error: patch constant function parameter 'myFloat' unknown
void HullConst (out  float edge [3] : SV_TessFactor, out float inside : SV_InsideTessFactor, out float myFloat : MY_FLOAT)
                                                                                                       ^
```

### Further technical details
Used DXC release v1.6.2104 (e09a454)

### PR DESCRIPTION
**Pull request by s-perron**
The documentation for the patch constant functions only mention

> The outputs are usually defined by a structure and is
identified by HS_CONSTANT_DATA_OUTPUT in this example; the structure
depends on the domain type and would be different for triangle or
isoline domains.

This is why we did not realize that we needed to implement out variables
as well. This commit implement the alternate method of having an output.

Fixes #3743

### CODE REVIEW

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -13459,6 +13445,18 @@ bool SpirvEmitter::processHSEntryPointOutputAndPCF(
                                          /*forPCF*/ true))
     return false;
 
+  // Traverall all of the parameters for the PCF and copy out all of the output
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:13448]: nit: Typo (Traverse?)

File: tools/clang/lib/SPIRV/SpirvEmitter.h [hunk 2]
```diff
@@ -1241,6 +1238,15 @@ class SpirvEmitter : public ASTConsumer {
   ///  https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Derivatives.html.
   void addDerivativeGroupExecutionMode();
 
+  /// Creates an input variable for `param` that will be used by the PCF. The
```
Comment (sudonatalie) [inline tools/clang/lib/SPIRV/SpirvEmitter.h:1241]: nit: Expand PCF acronym in the comments here?

**Review by sudonatalie — APPROVED** [review]
LGTM % nits

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 3]
```diff
@@ -14419,6 +14417,34 @@ void SpirvEmitter::addDerivativeGroupExecutionMode() {
...
+SpirvEmitter::createFunctionScopeTempFromParameter(const ParmVarDecl *param) {
+  const QualType type = param->getType();
+  std::string tempVarName = "param.var." + param->getNameAsString();
+  auto paramLoc = param->getLocation();
+  auto *tempVar = spvBuilder.addFnVar(
+      type, paramLoc, tempVarName, param->hasAttr<HLSLPreciseAttr>(),
+      param->hasAttr<HLSLNoInterpolationAttr>());
+  // SpirvInstruction *loadedValue =
+  // spvBuilder.createLoad(tempVar->getAstResultType(), tempVar, paramLoc);
+  // declIdMapper.createStageOutputVar(param, nullptr, /*forPCF*/ true);
```
Comment (cassiebeckley) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:14444]: Is there a reason you left in the above lines that have been commented out?

**Review by cassiebeckley — CHANGES_REQUESTED** [review]

**Review by cassiebeckley — APPROVED** [review]
