### PR TITLE
[linux-port] Support full IID comparison on GCC

### LINKED ISSUE #2680: Runtime loading dxcompiler on mac/linux
Hi, I'm wondering if there's currently a supported way to dlopen dxcompiler on mac/linux without linking against the lib. There doesn't seem to be a way to grab the REFIID for types without having access to the static `Interface::Interface_ID` symbol which will be name mangled.

Would adding an exported C function that can do a lookup be a viable option, or is there some existing workaround that I've missed?

### LINKED ISSUE #3097: Linux: E_NOINTERFACE when using dynamic library
I compiled `dxc` successfully on Linux, using master branch.
I wrote a simple c++ code that loads `libdxcompiler.so.3.7` using `dlopen`, obtains `DxcCreateInstanceProc` using `dlsym` and attempts to create instance of `IDxcUtils` interface:

```cpp
        const GUID CLSID_DxcLibrary = make_guid(0x6245d6af, 0x66e0, 0x48fd, 0x80, 0xb4, 0x4d, 0x27, 0x17, 0x96, 0x74, 0x8c);
        const IID IID_IDxcUtils = make_guid(0x4605C4CB, 0x2019, 0x492A, 0xAD, 0xA4, 0x65, 0xF2, 0x0B, 0xB7, 0xD6, 0x7F);

        DxcCreateInstanceProc pfn = (DxcCreateInstanceProc)fptr;
        void *pif = nullptr;
        HRESULT hr = pfn(CLSID_DxcLibrary, IID_IDxcUtils, &pif);

        printf("hr = %08x\n", hr);
```

The returned HRESULT is 0x80004002 (E_NOINTERFACE	No such interface supported).

Interestingly, if instead I load dynamic library from build artifacts, the return code is 0 (SUCCESS).
Why would it not work anymore with the latest locally built version?
Any help appreciated.

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes #2680, fixes #3097 

@ehsannas As per request, my patches to support IIDs on all compilers without `__declspec(uuid("...))` support like GCC. For reference most of the implementation details have been elaborated [here](https://github.com/microsoft/DirectXShaderCompiler/issues/2680#issuecomment-635499459).

In the current form external applications and wrappers using `DxcCreateInstance` (on an `__EMULATE_UUID`-enabled `dxcompiler`) get an `E_NOINTERFACE` because they cannot pass in the same pointer (or hash since #2796), nor know whether the (dynamically loaded) library is compiled with a compiler that supports `__uuidof()` (msvc, clang). To solve this all objects "simply" need to expose the full `IID` when they are emulated.
While relatively straightforward to implement (see initial commits) this requires duplication of the IID and an extra macro to be added to every structure (the latter already existing).

To counter this all `struct __declspec(uuid("...")) ISomething` are replaced with a macro that emits a similar struct header on supported compilers, but a template specialization wrapping the IID on all other compilers. This ensures the `IID` is not duplicated within the code nor the compatibility macro forgotten about, though is less readable than a normal stringified uuid.

One major downside of this method, further elaborated in https://github.com/microsoft/DirectXShaderCompiler/issues/2680#issuecomment-635499459, is `__uuidof()` not working on an interface implementation (subclass). That might be solved by consuming the inheritance chain and `{` bracket in the macro and emitting the static `uuidof()` method again.

This PR picks two small warning fixes from LLVM, but needs more to fully cover all warnings currently spewed out by the compilers. Or are there plans to update LLVM in larger swaths?
In addition `CMakeSettings.json` is updated to support VS2019, though I am unable to test backwards compatibility with VS2017 and below.

### Things that have yet to be done:
- Autoformat the changed class definitions (unfortunately autoformatting the entire file results in too many changes);
- Squash unnecessary commits after individual idea/implementation review;
- deal with `TODO`/`WIP`/`HACK` markings in commits and comments, ie.:
  - Make sure all classes have the new `INTERFACE_STRUCT_HEADER`, then remove the empty check in `IsEqualIID` (I think all are covered now?);
  - Move `INTERFACE_STRUCT_HEADER` to a single place accessible by everything (ie. the defines in `WinAdapter.h` are not available to `dxcapi.h` when not compiling under `WIN32`);
- Finally we have to discuss a binary incompatibility issue on vtable layout when `WinAdapter` is used, but that is irrelevant for this PR.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Looks like we get a `-Wmissing-braces` warning on Apple because clang doesn't like the UUID emulation macro, even though it is supported natively through `-fms-extensions`. How about applying the same `ifndef __clang__` [here](https://github.com/microsoft/DirectXShaderCompiler/pull/2404/files#diff-2a329b1b3f386f4254d99c942e2f1c12R61) to Apple?

Despite that I've fixed the macro which still compiles fine on GCC. `clang-format` makes it more readable, too :slightly_smiling_face:

Btw I was hoping [`__has_declspec_attribute`](https://clang.llvm.org/docs/LanguageExtensions.html#has-declspec-attribute) to return false when `-fms-extensions` is not enabled, but it always seems to return true :shrug:

**Comment by MarijnS95** [comment]
Looks like AppVeyor got stuck at version generation :thinking:

```
-- Build files have been written to: /home/appveyor/projects/DirectXShaderCompiler/build
ninja
[563/1283] Generating dxcversion.inc.gen
Generating version
```

**Comment by rellensb** [comment]
> Looks like we get a `-Wmissing-braces` warning on Apple because clang doesn't like the UUID emulation macro, even though it is supported natively through `-fms-extensions`. How about applying the same `ifndef __clang__` [here](https://github.com/microsoft/DirectXShaderCompiler/pull/2404/files#diff-2a329b1b3f386f4254d99c942e2f1c12R61) to Apple?
> 
> Despite that I've fixed the macro which still compiles fine on GCC. `clang-format` makes it more readable, too 🙂
> 
> Btw I was hoping [`__has_declspec_attribute`](https://clang.llvm.org/docs/LanguageExtensions.html#has-declspec-attribute) to return false when `-fms-extensions` is not enabled, but it always seems to return true 🤷
> 

I think (I haven't yet tested it) that clang defines `_MSC_VER` when `-fms-extensions` is enabled. This might be the safer check since I think it's only enabled by default with clang on windows anyhow.

On a related note, maybe we should give `__EMULATE_UUID` a public name? We ran into issues where if we had a GCC prebuilt dxc library and used it with a clang built project, we'd end up with a mismatch unless we manually defined `__EMULATE_UUID` to override the default assumptions.

**Comment by MarijnS95** [comment]
> I think (I haven't yet tested it) that clang defines `_MSC_VER` when `-fms-extensions` is enabled. This might be the safer check since I think it's only enabled by default with clang on windows anyhow.

It doesn't seem to be defined when compiling on Linux with `-fms-extensions`, unfortunately.

> On a related note, maybe we should give `__EMULATE_UUID` a public name? We ran into issues where if we had a GCC prebuilt dxc library and used it with a clang built project, we'd end up with a mismatch unless we manually defined `__EMULATE_UUID` to override the default assumptions.

The goal of this PR is to get rid of that mismatch all together. The API should be the same regardless of compiler or platform, especially when FFI wrappers in other languages (ie. Rust) are concerned.

**Comment by ehsannas** [comment]
Thanks for your contribution @MarijnS95. I'll review soon.

File: include/dxc/Support/WinAdapter.h [hunk 1]
```diff
@@ -563,27 +566,65 @@ enum tagSTATFLAG {
...
+// TODO: We can also eat the open bracket and emit members containing the UUID.
+// Advantage:
+//    One can define subclasses on guid types, and __uuidof() still works
+//    normally on them (as TInterfaceIids won't have a specialization for that
+//    type - or is that impossible in Windows too?)
+// Disadvantage:
+//    public/private inheritance has to run through the struct
+//
+// This seems like a cakewalk tradeoff IF __uuidof() works on non-guid
+// subtypes in Windows
```
Comment (pow2clk) [inline include/dxc/Support/WinAdapter.h:604]: I find these comments confusing. Can you elaborate?

File: include/dxc/dxctools.h [hunk 2]
```diff
@@ -63,21 +61,19 @@ CLSID_SCOPE const CLSID
                          0x40b3,
                          {0x96, 0x8d, 0x93, 0xe1, 0x24, 0x73, 0x4d, 0xa4}};
 
-struct __declspec(uuid("261afca1-0609-4ec6-a77f-d98c7035194e"))
-IDxcRewriter2 : public IDxcRewriter {
+INTERFACE_STRUCT_HEADER(IDxcRewriter2, 261afca1,0609,4ec6, a7,7f, d9,8c,70,35,19,4e)
```
Comment (pow2clk) [inline include/dxc/dxctools.h:64]: For any reviewer considering verifying that the new sequences match the old, I have already done so and convinced myself they are correct. Feel free to review them anyway if you don't trust me. 😆

File: CMakeSettings.json [hunk 3]
```diff
@@ -1,365 +1,468 @@
...
+          "type": "BOOL"
         }
-    ]
-}
\ No newline at end of file
+      ],
+      "inheritEnvironments": [ "msvc_x64_x64" ]
+    }
+  ]
+}
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply CMakeSettings.json:468]: > I'm really uncomfortable with the json change. Why was it included?

Because I have 2019 installed and cannot permit myself to install 2017 side-by-side.

I asked [before](https://github.com/microsoft/DirectXShaderCompiler/issues/2680#issuecomment-635499459) whether this change was okay:

> , as well as the necessary updates to CMakeSettings.json to get it to work properly under VS 2019. Let me know if these you want these upstreamed too.

Without explicit answer I opted to leave this in rather than make a separate PR straight away. That can - _obviously_ - easily be done at any point.

As for compatibility, that was mentioned in the PR description:

> In addition CMakeSettings.json is updated to support VS2019, though I am unable to test backwards compatibility with VS2017 and below.

Would you mind validating this? I'd be _very_ disappointed if Microsoft/Visual Studio break backwards compatibility this way, with no easy way out (such as a simple `version` field).
That said the documentation for VS 2017 and VS 2019 on variable layout is identical:
https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2017
https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2019
This leaves me rather surprised; how's the current config working in 2017?

File: include/dxc/Support/WinAdapter.h [hunk 4]
```diff
@@ -54,15 +54,11 @@
 #define _countof(a) (sizeof(a) / sizeof(*(a)))
 
 // If it is GCC, there is no UUID support and we must emulate it.
-#ifdef __APPLE__
-#define __EMULATE_UUID 1
-#else // __APPLE__
-#ifdef __GNUC__
 #ifndef __clang__
+#if defined(__APPLE__) || defined(__GNUC__)
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:58]: It is intended, as mentioned above. Indeed, the extra if statement becomes superfluous that way - I'll drop it.

As for your `__has_declspec_attribute`, please see my prior comment on this:

https://github.com/microsoft/DirectXShaderCompiler/pull/3062#issuecomment-668002691

File: include/dxc/Support/WinAdapter.h [hunk 5]
```diff
@@ -233,7 +229,7 @@
 
 #define E_ABORT (HRESULT)0x80004004
 #define E_ACCESSDENIED (HRESULT)0x80070005
-#define E_BOUNDS (HRESULT)0x8000000B
+#define E_BOUNDS  (HRESULT)0x8000000B
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:232]: That's part of [reverting](https://github.com/microsoft/DirectXShaderCompiler/pull/3062/commits/e6298ed4818d0030b8a031d6c7fe7ae00a9ba83d) an earlier commit introducing hashes in place of IIDs. I can undo and amend this, or squash the revert into my commits to make it seem like an incremental change.

[This implementation was made before the hash solution was merged. Upon rebasing it was easier to revert than fix all the conflicts, even if I might squash to hide this local defect]

File: include/dxc/Support/WinAdapter.h [hunk 6]
```diff
@@ -477,13 +468,25 @@ inline bool operator!=(REFGUID guidOne, REFGUID guidOther) {
...
 inline bool IsEqualIID(REFIID riid1, REFIID riid2) {
+  // Use reference compare like the previous implementation
+  if (&riid1 == &riid2)
+    return true;
+
+  // HACK: Many IIDs are currently initialized to {},
+  // which are obviously identical to eachother. Disallow
+  // this case, those are handled by reference compare only.
+  // This can be removed when all interfaces have a proper
+  // IID specified.
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:479]: > Make sure all classes have the new INTERFACE_STRUCT_HEADER, then remove the empty check in IsEqualIID (I think all are covered now?);

This is, indeed, superfluous now. I'll remove it.

File: include/llvm/ADT/ArrayRef.h [hunk 7]
```diff
@@ -84,9 +84,19 @@ namespace llvm {
...
+// it does not do lifetime extension.
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Winit-list-lifetime"
+#endif
     /*implicit*/ ArrayRef(const std::initializer_list<T> &Vec)
     : Data(Vec.begin() == Vec.end() ? (T*)0 : Vec.begin()),
       Length(Vec.size()) {}
+#if LLVM_GNUC_PREREQ(9, 0, 0)
+#pragma GCC diagnostic pop
+#endif
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/llvm/ADT/ArrayRef.h:99]: I can't seem to find an [open pr](https://github.com/microsoft/DirectXShaderCompiler/pulls/pow2clk) for this, would you mind pointing me to it?

Same applies here, I've asked about this in the PR description:

> This PR picks two small warning fixes from LLVM, but needs more to fully cover all warnings currently spewed out by the compilers. Or are there plans to update LLVM in larger swaths?

In particular this commit addresses massive warning spam that makes it impossible to validate the rest of the compilation on GCC. I don't mind setting up a separate PR if you agree.

File: include/llvm/ADT/SmallVector.h [hunk 8]
```diff
@@ -330,7 +330,7 @@ class SmallVectorTemplateBase<T, true> : public SmallVectorTemplateCommon<T> {
   void push_back(const T &Elt) {
     if (LLVM_UNLIKELY(this->EndX >= this->CapacityX))
       this->grow();
-    memcpy(this->end(), &Elt, sizeof(T));
+    memcpy(reinterpret_cast<void *>(this->end()), &Elt, sizeof(T));
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/llvm/ADT/SmallVector.h:333]: Let's move this to a separate PR then.

File: include/dxc/dxcapi.h [hunk 9]
```diff
@@ -132,23 +129,38 @@ typedef struct DxcShaderHash {
...
+#define INTERFACE_STRUCT_HEADER(interface_name, uuid0, uuid1, uuid2, uuid3_0,  \
+                                uuid3_1, uuid3_2, uuid3_3, uuid3_4, uuid3_5,   \
+                                uuid3_6, uuid3_7)                              \
+  struct __declspec(uuid(INTERFACE_STRUCT_HEADER_str(                          \
+    uuid0-uuid1-uuid2-uuid3_0##uuid3_1-uuid3_2                                 \
+    ##uuid3_3##uuid3_4##uuid3_5##uuid3_6##uuid3_7                              \
+  ))) interface_name
+// clang-format on
+#endif
+
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/dxcapi.h:148]: The problem being that we need this macro in `WinAdapter` for `clang`, too. I don't like defining it twice and `WinAdapter.h` is included in more places besides `dxcapi.h`. Where do you recommend to place it?

File: include/dxc/Support/WinAdapter.h (hunk 1 above)
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:604]: The tradeoffs are more clearly elaborated in the PR description and linked comment:

> > One major downside of this method, further elaborated in [#2680 (comment)](https://github.com/microsoft/DirectXShaderCompiler/issues/2680#issuecomment-635499459), is `__uuidof()` not working on an interface implementation (subclass). That might be solved by consuming the inheritance chain and `{` bracket in the macro and emitting the static `uuidof()` method again.

File: include/dxc/dxctools.h (hunk 2 above)
Comment (MarijnS95) [reply include/dxc/dxctools.h:64]: Be aware I have yet to fix the formatting (most notably mixed spacing) on these though. Unfortunately I can't format the entire file, leading to manually selecting every header and pressing the autoformat hotkey... :no_mouth:

File: include/dxc/Support/WinAdapter.h [hunk 10]
```diff
@@ -563,27 +566,65 @@ enum tagSTATFLAG {
...
+
+#define DECLARE_CROSS_PLATFORM_UUIDOF_VALUE(interface_name, ...)               \
+  template <> struct TInterfaceIids<interface_name> {                          \
+    static REFIID uuidof() {                                                   \
+      static IID _IID = __VA_ARGS__;                                           \
+      return _IID;                                                             \
+    }                                                                          \
+  };
+
+// TODO: Move DECLARE_CROSS_PLATFORM_UUIDOF_VALUE into INTERFACE_STRUCT_HEADER
```
[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h]: The macro in question (`DECLARE_CROSS_PLATFORM_UUIDOF_VALUE`) doesn't use the token paste operator at all and is, in fact, [trivial to merge](https://github.com/microsoft/DirectXShaderCompiler/pull/3062/commits/62fbe719b499024e0f89c3623f819b5f9c2130f2).

File: include/llvm/ADT/ArrayRef.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (pow2clk) [reply include/llvm/ADT/ArrayRef.h]: There is no PR for this. It's a side project I contribute to on my linux box while I'm waiting for builds. If you create a separate PR, I'll be happy to fast track it.

[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/llvm/ADT/ArrayRef.h]: Found it: https://github.com/pow2clk/DirectXShaderCompiler/commits/user/grroth/gcc_warnings

Most of those seem to be manual changes though? I'm in favor of picking from LLVM to retain history and prevent any unnecessary divergence, they fixed the same issues after all. This is not my project though, any preference?

> while I'm waiting for builds

[Shameless boasting] (un)fortunately that's not a problem on a ThreadRipper...
In all seriousness I may be able to tackle this issue much quicker for that reason. I'll see what I can pick and apply your changes on top. Will make sure it's more complete than the measly two picks previously in this PR though.

[the remark this answers is not in the document]
Comment (pow2clk) [reply include/llvm/ADT/ArrayRef.h]: I've not bothered to pull directly from the LLVM project when I've cribbed from them in the past. I'm not sure exactly how you'd do that given how long ago we forked. I've just copied the substance as you've done here.

[the remark this answers is not in the document]
Comment (MarijnS95) [reply include/llvm/ADT/ArrayRef.h]: The two patches applied here were as simple as `curl <raw patch url> | git am`, no manual copying involved. But that requires finding the appropriate patch in the first place...

I'll see what works best :slightly_smiling_face:

**Comment by MarijnS95** [comment]
@tex3d It was brought to my attention that `__declspec(uuid)` after defining the class is invalid, at least on Clang 5.0 according to Travis-CI:

https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/719950719

I get no issues on Clang 10 whatsoever. Moving the macro as a forward declaration before the definition seems to be a valid alternative - this fits more naturally with the original attribute location too. Let's see if Clang 5 accepts this :)

**Comment by pow2clk** [comment]
Lest it be missed because, sadly, Travis is still giving Github the silent treatment, this PR didn't compile successfully on GCC: https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/722178516

**Comment by MarijnS95** [comment]
@pow2clk:
> Lest it be missed because, sadly, Travis is still giving Github the silent treatment

How about moving to Github Actions? Looks like Travis has no logs of notifying Github to look into this from the public side.

> this PR didn't compile successfully on GCC: https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/722178516

My bad, that's something I could have foreseen and compile-tested locally with GCC. Should be fixed now.

(Also, would you mind replying to review comments? There's no hurry to get this PR in but I'm curious about your opinion)

**Comment by MarijnS95** [comment]
@ehsannas @pow2clk @tex3d It has been over a month since the last feedback; is there any update to the comments above to make this ready to go in? I understand it might not be the most important PR but I'd like to prevent running into conflicts when new interfaces are added or existing code is modified.

**Review by ehsannas — APPROVED** [review]
This looks good to me. I'll wait for approval from @pow2clk or @tex3d before merging.

File: include/dxc/Support/WinAdapter.h [hunk 11]
```diff
@@ -563,27 +555,73 @@ enum tagSTATFLAG {
...
+
 #define IID_PPV_ARGS(ppType)                                                   \
-  (**(ppType)).uuidof(), reinterpret_cast<void **>(ppType)
+  __uuidof(decltype(**(ppType))), reinterpret_cast<void **>(ppType)
 
 #else // __EMULATE_UUID
 
-#define DECLARE_CROSS_PLATFORM_UUIDOF(T)
-#define DEFINE_CROSS_PLATFORM_UUIDOF(T)
+#define CROSS_PLATFORM_UUIDOF(interface, spec)                                 \
```
Comment (pow2clk) [inline include/dxc/Support/WinAdapter.h:623]: Tex suggested an `#ifndef CROSS_PLATFORM_UUIDOF ` protection around this define. I didn't see any response to it. It seems a reasonable request to me.

File: lib/HLSL/DxilContainerReflection.cpp [hunk 12]
```diff
@@ -2566,9 +2566,9 @@ HRESULT CFunctionReflection::GetDesc(D3D12_FUNCTION_DESC *pDesc) {
   pDesc->BoundResources = (UINT)m_UsedResources.size();
 
   //Unset:  UINT                    InstructionCount;            // Number of emitted instructions
-  //Unset:  UINT                    TempRegisterCount;           // Number of temporary registers used 
+  //Unset:  UINT                    TempRegisterCount;           // Number of temporary registers used
   //Unset:  UINT                    TempArrayCount;              // Number of temporary arrays used
-  //Unset:  UINT                    DefCount;                    // Number of constant defines 
+  //Unset:  UINT                    DefCount;                    // Number of constant defines
```
Comment (pow2clk) [inline lib/HLSL/DxilContainerReflection.cpp:2571]: For future reference, these unnecessary, albeit stylistically desirable whitespace changes really disrupt and slow the review process. I'm not opposed to them, but if you want to make them, please put them in their own change. It's really easy to review a change that only alters whitespace.

**Review by pow2clk — COMMENTED** [review]
It looks fine apart from the lack of response to @tex3d's comment from August that I highlighted. I'd like to get that resolved before approving.

File: include/dxc/Support/WinAdapter.h (hunk 11 above)
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:623]: > I didn't see any response to it

Tex specifically requested to add it to the `dxcapi` variant, though he might have meant `WinAdapter` instead. That's indeed reasonable, and perhaps even required:

You requested to move this macro (in `dxcapi.h`) back up to where `DECLARE_CROSS_PLATFORM_UUIDOF` was previously defined:

```diff
-#ifdef _WIN32
-#define DECLARE_CROSS_PLATFORM_UUIDOF(T)
-#define DEFINE_CROSS_PLATFORM_UUIDOF(T)
-#else
+#ifndef _WIN32
 #include <dlfcn.h>
 #include "dxc/Support/WinAdapter.h"
 #endif
```

I'll make both changes :ok_hand: 

Note that I won't add protection around the `__EMULATE_UUID` variant: if `CROSS_PLATFORM_UUIDOF` gets defined prior it's probably the Windows (+msvc extensions) -only variant, an error that must be caught.

Comment (pow2clk) [reply include/dxc/Support/WinAdapter.h:623]: Perhaps the comment references an old version of the code. It looks like you did a force push at some point so I can't go back and see what state the code was in when Tex made the comment. I took it to mean adding it to WinAdapter.h too, but that was in the context of the current state of the code. Maybe he was just asking for the ifndef that is now there. I really can't tell because the history was lost.

File: lib/HLSL/DxilContainerReflection.cpp (hunk 12 above)
Comment (MarijnS95) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: These are made automatically by my editor to ensure _I_ don't submit unnecessary whitespace. While I understand it's hard to reject introductions of these during review it makes the code noisy to work with, both during development and as you correctly point out, review. It adds an extra barrier: I have to revert these changes, submit them separately, or turn off "trim trailing whitespace" altogether and doublecheck everything I submit.

Opened https://github.com/microsoft/DirectXShaderCompiler/pull/3272 for that, as soon as this is rebased and that's merged the changes should disappear from the diff.

On a related note it's similarly disruptive to have `.clang-format` while very few files (outside imported files from external projects/libraries) adhere to it. Only `WinAdapter` can be autoformatted without creating tons of unnecessary noise. Fixing that makes git history and blaming useless, though.

File: include/dxc/Support/WinAdapter.h (hunk 11 above)
Comment (MarijnS95) [reply include/dxc/Support/WinAdapter.h:623]: I don't understand where it went either: GitHub used to be pretty good at showing "outdated" changes on the right line, even if commits are amended or force-pushed (it'll simply record the exact commit hash the review comment applies to). It must have been `WinAdapter.h`.

**Comment by MarijnS95** [comment]
> It looks fine apart from the lack of response

There are quite a few questions open from my side too (as replies on review comments). Are those worth replying and investigating or can you otherwise mark your threads as resolved? That way everyone knows the state of this PR and remaining issues to be worked on.

**Review by pow2clk — APPROVED** [review]
Looks fine. Another note for future reference, force pushing, as you just did, also makes reviewing only the new parts difficult because it repushes all of the changes so they all look new.

File: lib/HLSL/DxilContainerReflection.cpp (hunk 12 above)
Comment (pow2clk) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: I don't know how most people avoid these kind of incidental changes, but they do. Personally, I use emacs which lets me write what I want and doesn't do anything I don't tell it to, I find that enormously preferable. While I'm indifferent to clang formatting, I'm not a fan of clang-format. I recommend finding a way to bypass it as well.

Barring all that, we could have one enormous git blame ruining change that brings all these files into alignment with these requirements and silence this issue forever. I'm not inclined to do that myself, but I wouldn't object to it.

**Review by tex3d — APPROVED** [review]
This looks good!

File: lib/HLSL/DxilContainerReflection.cpp (hunk 12 above)
Comment (MarijnS95) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: > I don't know how most people avoid these kind of incidental changes, but they do.

Seems like they don't, how else did trailing whitespace end up in these files?

The point is I can easily turn it off, but it helps _me personally_ write code without ever worrying about formatting, indentation or trailing whitespace: one press of a button and it's tidy.

I don't like `clang-format`s judgement on many things either, but at least it introduces a certain form of consistency to a codebase. Still waiting for `rustfmt` to be ported to C++ :wink:.

In addition to ruining git blame, all open PRs and sidetracked branches can be thrown away, unless the user knows how to rewrite their branch efficiently in git.

Comment (pow2clk) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: You misunderstand. I mean that people manage to avoid changes that "fix" these flaws in their PRs even though they are pervasive in the codebase.

**Comment by MarijnS95** [comment]
> Another note for future reference, force pushing, as you just did, also makes reviewing only the new parts difficult because it repushes all of the changes so they all look new.

Having had a preliminary ack from you this is intended: rebase the branch on top of master to make sure everything is fine, and squash all `fixup` commits into the relevant base commit to make things tidy. Though that might not be completely necessary with the squash-merge strategy used here. The resulting diff is small enough that this is not too big of an issue?

Despite the acks received here there's still some dead/commented code in the diff. Anything I should do with that?

**Comment by pow2clk** [comment]
I didn't mean to imply that you should remove the whitespace changes in a separate change so much as suggest that they be excluded in any future changes you make here. So those that linger are fine.

Incidentally, force pushes have also obliterated the link in the hassl-rs readme: https://github.com/Traverse-Research/hassle-rs/blob/master/README.md

Force pushing is occasionally necessary, but pretty widely frowned upon. The only effect it would have here is creating an ugly commit message, which is unfortunate, but I edit squashed messages when I merge them.

File: lib/HLSL/DxilContainerReflection.cpp (hunk 12 above)
Comment (MarijnS95) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: We both misunderstand. It is my _intention_ to leave these changes in. Usually maintainers are ever so slightly embarrassed when minor flaws like these pop up and are happy they are fixed "under the radar" rather than creating extra noise with separate commits/PRs that subsequently have to be tested (valuable CI time), approved and merged. Or left to linger around. Unless they are large enough to warrant an entry in an `ignore-revs-file`.

Comment (pow2clk) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: I'm sorry you disapprove of how I do my job. Nevertheless, I stand by my previous statements.

**Comment by MarijnS95** [comment]
@pow2clk We have very different approaches to using git. Mine is more kernel-oriented, where I intentionally structure commits and their diffs in a linear way, provide relevant commit messages and titles for each and make them bisectable. Fair point to be made, I've slacked on that here because all the effort is squashed away anyway. 

The squash-merge strategy applied here is focused at a wider audience and aims to prevent endless chains of merges, "fix typo"/"apply review comment" commits and the like that are not relevant when looking at the history as a whole. 

Force pushes being frowned upon turned out to be a myth ever since I was first told about it. Indeed, don't ever do that to master/ main or any other branch that is shared between more than one developer. Apart that it's a really powerful tool when used with care, and specifically suited to a distributed vcs like git.

As for that particular example in the hassle-rs readme, I doubt that link was intended to end up there. Instead it should have linked to this PR as a whole, or to https://github.com/microsoft/DirectXShaderCompiler/commit/9527fe6346391ac9a31799d730c7744b482e2386 directly which is still valid. I anticipated this PR to be merged sooner, allowing it to be removed quickly again. Or rather, I should have submitted that change separately as it has little to do with IID support on GCC. My bad.

File: lib/HLSL/DxilContainerReflection.cpp (hunk 12 above)
Comment (MarijnS95) [reply lib/HLSL/DxilContainerReflection.cpp:2571]: Don't get me wrong, I don't disapprove of your job at all. If anything I'm frowning upon myself for going on this tangent for this long. My sole intent is to get across _why_ I sneak such changes into a PR in the first place.

How can I best resolve this unfortunate situation? Close the whitespace PR as it's _just_ noise, and revert (as opposed to force-push off) the matching commit at the beginning of this PR?

**Comment by pow2clk** [comment]
@MarijnS95, I have no interest in changing your approach to git outside of contributing to this repo. When contributing to this repo if you avoid spurious whitespace changes and don't use force pushes and you will facilitate reviews.

**Comment by MarijnS95** [comment]
> @MarijnS95, I have no interest in changing your approach to git outside of contributing to this repo.

I am not expecting this to change anything, merely explaining myself, why I'm doing this a certain way. If dxc has a contributor guide specifying how to supply additional fixups to a PR or it is requested in-person to do it a certain way I can adjust to that.

> When contributing to this repo if you avoid spurious whitespace changes

Ack. Though be more clear about that next time instead of suggesting to "please put them in their own change".

> and don't use force pushes

Ack

> and you will facilitate reviews.

I don't understand what you are trying to say with that. Keep in mind we're discussing whether or not to obliterate _trailing whitespace_ while at the same time relevant review questions were still open at the top of this PR (have since been marked "resolved"), nor have I received any comments about commented-out (dead) code, whether I should seek to implement static assertions and such.

**Comment by pow2clk** [comment]
You have alluded to unresolved questions that I did not see in the source. Force pushes sometimes removes these comments if the system is unable to match up line numbers. If you add them to the source now, I will address them.

It isn't strictly necessary that you understand why littering a change with irrelevant detritus slows and discourages reviews so long as you avoid it.
