### PR TITLE
[spirv] do not use WorkGroup storage class for hull shader output patch

### LINKED ISSUE #3248: [SPIR-V] Workgroup memory not allowed in tessellation-control shader
According to the SPIR-V specification, workgroup memory (`shared` in GLSL) is only allowed in the compute shader stage (as well as the new mesh and task shader stages). However, DXC generates this to communicate patch constant data in a tessellation control shader as intermediate storage. The SPIRV-Tools validation does not catch this error and causes a triangle soup on NVIDIA hardware and a crash in the Vulkan implementation on AMD hardware.

The solution presented in [PR3059](https://github.com/microsoft/DirectXShaderCompiler/pull/3059) doesn't work in UE4 with most of our tessellation shaders. Our old shader compiler pipeline used the output attribute slots that were already allocated. I submitted a workaround in our P4V repository that creates another output attribute slot as intermediate storage. The problem with that is it allocates a lot of output slots when large structures are involved and easily exceeds the Vulkan limits with certain configurations in our material system.

This is the line where I hook in another output variable with a custom `createStageOutputVar` function:
https://github.com/microsoft/DirectXShaderCompiler/blob/6008113f6023f3ffd955855a6a9aae50480ea1a9/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp#L3668

### PR DESCRIPTION
**Pull request by jaebaek**
This CL lets DXC create a immediate variable with `Output` storage class
for the constant output patch of a hull shader instead of using `Workgroup`
storage class because a variable with `Workgroup` storage class is not
allowed in a Vulkan tessllation shader.

Fixes #3248

### CODE REVIEW

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 1]
```diff
@@ -2943,6 +2944,40 @@ SpirvVariable *DeclResultIdMapper::getBuiltinVar(spv::BuiltIn builtIn,
   return var;
 }
 
+SpirvVariable *DeclResultIdMapper::createSpirvIntermediateOutputStageVar(
+    const NamedDecl *decl, const llvm::StringRef name, QualType type,
+    uint32_t arraySize) {
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2949]: `arraySize` is not used in the function. Is it not needed? Why not?

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp [hunk 2]
```diff
@@ -2264,7 +2264,8 @@ bool DeclResultIdMapper::createStageVars(
     // Decorate with interpolation modes for pixel shader input variables
     // or vertex shader output variables.
     if (((spvContext.isPS() && sigPoint->IsInput()) ||
-         (spvContext.isVS() && sigPoint->IsOutput())) &&
+         (spvContext.isVS() && sigPoint->IsOutput()) ||
+         (spvContext.isHS() || spvContext.isDS())) &&
```
Comment (ehsannas) [inline tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2268]: I'm curious why this is needed? (why `Flat` should be applied)

**Review by ehsannas — CHANGES_REQUESTED** [review]
Looks good overall. Just a couple of nits.

The comment here also needs to be updated (s/Workgroup/Output)
https://github.com/microsoft/DirectXShaderCompiler/blob/af14220b45d3ce46e0bad51ce79655e41d07c478/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L1123-L1125

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 2 above)
Comment (jaebaek) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: This code is from the UnrealEngine's code, but I do not think this is needed.
I removed it.

**Review by jaebaek — COMMENTED** [review]
Thank you for the code review. I updated it based on the feedback. PTAL.

File: tools/clang/lib/SPIRV/DeclResultIdMapper.cpp (hunk 2 above)
Comment (ehsannas) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: @LukasBanana Do you know why this change was made in the UE fork? it results in 

```
OpDecorate %gl_InvocationID Flat
OpDecorate %gl_PrimitiveID Flat 
```
being added to hull shaders and domain shaders.

Comment (LukasBanana) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: I added that change myself as I was assuming all integer types need the flat interpolation specifier for stage variables in SPIRV, except of vertex input and fragment output attributes of course. Now that I think about it, it's probably only required for the variables that are in fact interpolated, i.e. for the fragment shader. But if that's the case, why would it be required in the vertex shader (i.e. `spvContext.isVS() && sigPoint->IsOutput()`) if a geometry shader for instance is hooked into the pipeline? In this scenario, the vertex shader wouldn't interpolate its vertices, the geometry shader would do that.

Comment (ehsannas) [reply tools/clang/lib/SPIRV/DeclResultIdMapper.cpp]: Thanks 👍

**Review by ehsannas — APPROVED** [review]
