### PR TITLE
[spirv] report error for invalid tex2d multiplication

### LINKED ISSUE #3166: [SPIR-V] Crash when compiling faulty shader to SPIRV
Compiling this shader to SPIRV causes a crash, instead of outputting an error:
```
sampler Sampler;

float4 PS(float2 texCoord : TEXCOORD0) : SV_TARGET0
{
    return tex2D(Sampler, texCoord) * 1;
}
``` 
Removing the *1 at the end of the return statement will prevent the crash, and generate the appropriate error message (tex2D not supported).

Command line:
```
dxc.exe -spirv -T ps_4_0 -E PS shader.hlsl -Fo spirv.txt
```

### PR DESCRIPTION
**Pull request by jaebaek**
Calling tex2D must report an error but the multiplication using it
crashes instead of an error report.

Fixes #3166

### CODE REVIEW

**Review by ehsannas — APPROVED** [review]

File: tools/clang/lib/SPIRV/SpirvEmitter.cpp [hunk 1]
```diff
@@ -5556,6 +5556,8 @@ SpirvInstruction *SpirvEmitter::processBinaryOp(
   } else {
     // Evalute lhs before rhs
     lhsPtr = doExpr(lhs);
+    if (lhsPtr == nullptr)
```
Comment (kuhar) [inline tools/clang/lib/SPIRV/SpirvEmitter.cpp:5559]: nit:
```suggestion
    if (!lhsPtr)
```

Comment (jaebaek) [reply tools/clang/lib/SPIRV/SpirvEmitter.cpp]: done

**Review by jaebaek — COMMENTED** [review]
Thank you for your code review. I updated it!

**Review by kuhar — APPROVED** [review]
