### PR TITLE
[Validator] Add validation for createHandleFromBinding

### LINKED ISSUE #7019: DXIL Validator doesn't notice obviously bad indices in the createHandleFromBinding op
**Description**
Giving the CreateHandle operation an index that is less-than the binding lower bound fails validation:
```
Function: main: error: Constant values must be in-range for operation.
note: at '%0 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 1, i32 0, i1 false)' in block 'entry' of function 'main'.
```

However, this passes the validator if we have the same error but are using DXIL 1.6+'s CreateHandleFromBinding.

**Steps to Reproduce**
Craft a resource binding with a lower bound greater than zero and then index it at 0.
```llvm
; call has binding info starting at 1 but index at 0:
call %dx.types.Handle @dx.op.createHandleFromBinding(i32 217, %dx.types.ResBind { i32 1, i32 1, i32 4, i8 1 }, i32 0, i1 false)
; metadata for the same binding:
!{i32 1, %"class.RWBuffer<vector<float, 4> >"* undef, !"", i32 4, i32 1, i32 1, i32 10, i1 false, i1 false, i1 false, !7}
```

**Environment**
- DXC version: dxcompiler.dll: 1.8 - 1.8.0.14766 (main, ac36a797d); dxil.dll: 1.8(1.8.0.14766)

### PR DESCRIPTION
**Pull request by damyanp**
Previously, the validator didn't validate the parameters to createHandleFromBinding.  This change adds validation that validates:

* Bind parameter is constant — validates the bind struct parameter is a constant
* Resource class is valid — validates resourceClass is one of CBuffer, Sampler, SRV, or UAV
* Index range — validates constant indices fall within [rangeLowerBound, rangeUpperBound]

Fixes #7019

### CODE REVIEW

**Comment by damyanp** [comment]
There doesn't seem to be any validation at all for CreateHandleFromBinding.  Maybe the right way to resolve this would be to get all the validation in place?

File: lib/DxilValidation/DxilValidationUtils.cpp [hunk 1]
```diff
@@ -229,6 +230,52 @@ void ValidationContext::BuildResMap() {
...
+      case DXIL::ResourceClass::SRV:
+      case DXIL::ResourceClass::UAV:
+        break;
+      default:
+        EmitInstrError(CI, ValidationRule::InstrOpConstRange);
+        continue;
+      }
+
+      // Validate constant index is within binding range.
+      ConstantInt *cIndex = dyn_cast<ConstantInt>(hdl.get_index());
```
Comment (bogner) [inline lib/DxilValidation/DxilValidationUtils.cpp]: I don't fully understand what the `DXIL::OpCode::CreateHandle` version of this logic is doing where it handles a case for "index must be 0 for none array resource." (sic), so I'm not sure if it's relevant here, but do we need similar logic as well?

File: lib/DxilValidation/DxilValidationUtils.cpp [hunk 2]
```diff
@@ -229,6 +230,52 @@ void ValidationContext::BuildResMap() {
...
 
+  // Scan all createHandleFromBinding for validation.
+  for (auto &it :
+       hlslOP->GetOpFuncList(DXIL::OpCode::CreateHandleFromBinding)) {
+    Function *F = it.second;
+    if (!F)
+      continue;
+    for (User *U : F->users()) {
+      CallInst *CI = cast<CallInst>(U);
+      DxilInst_CreateHandleFromBinding hdl(CI);
```
Comment (bob80905) [inline lib/DxilValidation/DxilValidationUtils.cpp]: nit: variable naming conventions in new code, ideally should be capitalized.

File: lib/DxilValidation/DxilValidationUtils.cpp [hunk 3]
```diff
@@ -229,6 +230,52 @@ void ValidationContext::BuildResMap() {
...
+
+      // Validate resourceClass is valid.
+      switch (static_cast<DXIL::ResourceClass>(B.resourceClass)) {
+      case DXIL::ResourceClass::CBuffer:
+      case DXIL::ResourceClass::Sampler:
+      case DXIL::ResourceClass::SRV:
+      case DXIL::ResourceClass::UAV:
+        break;
+      default:
+        EmitInstrError(CI, ValidationRule::InstrOpConstRange);
```
Comment (bob80905) [inline lib/DxilValidation/DxilValidationUtils.cpp:262]: You should use a different validation rule for this.
Consider adding a validation rule:
self.add_valrule(
            "Instr.ResourceClassForCreateHandleFromBinding", "The specified resource class must be CBuffer, Sampler, SRV, or UAV"
        )
To line 8544 of hctdb.py.
I wasn't able to find a decent match for what you want in any of the other rules.

File: lib/DxilValidation/DxilValidationUtils.cpp [hunk 4]
```diff
@@ -229,6 +230,52 @@ void ValidationContext::BuildResMap() {
...
+    if (!F)
+      continue;
+    for (User *U : F->users()) {
+      CallInst *CI = cast<CallInst>(U);
+      DxilInst_CreateHandleFromBinding hdl(CI);
+
+      // Validate bind parameter is constant.
+      Value *bind = hdl.get_bind();
+      if (!isa<Constant>(bind)) {
+        EmitInstrError(CI, ValidationRule::InstrOpConstRange);
```
Comment (bob80905) [inline lib/DxilValidation/DxilValidationUtils.cpp:246]: This validation rule may also be misleading. The value may be within range, but not constant. You might consider another validation rule specific to this.

File: tools/clang/test/LitDXILValidation/createHandleFromBinding_passing.ll [hunk 5]
```diff
@@ -0,0 +1,47 @@
+; REQUIRES: dxil-1-8
+; RUN: %dxv %s | FileCheck %s
+
+; CHECK: Validation succeeded.
```
Comment (bob80905) [inline tools/clang/test/LitDXILValidation/createHandleFromBinding_passing.ll:4]: I vaguely recall this being an unpreferred pattern (checking for success directly).
Though it's hard because the validator doesn't really output anything when it succeeds other than this.
It's a nit, but I imagine we have sufficient testing of validation with createhandlefrombinding that we already validate that the validator won't complain about valid use of it. I would question the utility/value of this test.

File: lib/DxilValidation/DxilValidationUtils.cpp (hunk 1 above)
Comment (damyanp) [reply lib/DxilValidation/DxilValidationUtils.cpp]: Thanks - I think we might be missing checks for non-constant indexes entirely.

I just pushed a version that handles this, but as soon as I pushed it I realized that using lower==upper to decide if something is an array or not is probably not the right thing to do.

Comment (damyanp) [reply lib/DxilValidation/DxilValidationUtils.cpp]: It doesn't look like we can safely detect array resources without the extra information about the type that CreateHandle has.  I think rejecting dynamic indexing on single element arrays would be undesireable.

File: lib/DxilValidation/DxilValidationUtils.cpp (hunk 2 above)
Comment (damyanp) [reply lib/DxilValidation/DxilValidationUtils.cpp]: I was torn on this one - I did have a version that used new conventions, but this file is pretty consistent here and it seemed even stranger to have different conventions for the same shaped code _in the same function_.

Maybe these functions are so long anyway it's not even worth thinking of them as a single unit and it's ok to have different conventions within them....will probably happily go with whatever opinion anyone feels like giving, assuming that the opinion is made based on the whole function instead of this diff...

File: lib/DxilValidation/DxilValidationUtils.cpp (hunk 3 above)
Comment (damyanp) [reply lib/DxilValidation/DxilValidationUtils.cpp:262]: This matches what we do for CreateHandle I think?

File: tools/clang/test/LitDXILValidation/createHandleFromBinding_passing.ll (hunk 5 above)
Comment (damyanp) [reply tools/clang/test/LitDXILValidation/createHandleFromBinding_passing.ll:4]: Is there an alternative pattern?  This is how a bunch of the existing tests do it.

While there is some coverage of createHandleFromBinding, I'm not sure that we'd necessarily have coverage for all the cases in here which is why I added it.

File: lib/DxilValidation/DxilValidationUtils.cpp (hunk 1 above)
Comment (damyanp) [reply lib/DxilValidation/DxilValidationUtils.cpp]: @bogner - latest iteration is what I think is the response to this.  We don't have enough information to add a new validation rule for this, but I added some _passing tests around arrays to capture some of the thinking.

File: lib/DxilValidation/DxilValidationUtils.cpp (hunk 3 above)
Comment (bob80905) [reply lib/DxilValidation/DxilValidationUtils.cpp:262]: Made an issue here:
https://github.com/microsoft/DirectXShaderCompiler/issues/8266
